### ISSUE TITLE
ZDCoreCreateRequestView's text view is partially hidden on iPad

### ISSUE THREAD

**Issue by sfwalsh** [zendesk/zendesk_sdk_ios#1]
The text view in ZDCoreCreateRequestViewController is partially hidden by the navigation bar on iPad. Please see screenshot attached.
![ios simulator screen shot 19 aug 2014 16 24 22](https://cloud.githubusercontent.com/assets/3273708/3968244/ed45902a-27b4-11e4-901a-c93ac2e630d5.png)

**Comment by BPlano** [comment]
@sfwalsh - This should be fixed as of SDK version 1.1.1.1 - could you update your SDK implementation to the latest version? You should be good to go at that point.
