### ISSUE TITLE
Xcode 7.1 breaks Swift import of framework

### ISSUE THREAD

**Issue by hermanolsson** [zendesk/zendesk_sdk_ios#102]
We are using the framework via cocoapods (the official specs repo) and since upgrading to Xcode 7.1 we are seeing this error when importing the framework with ```import ZendeskSDK```

```include of non-modular header inside framework module 'ZendeskSDK'````

Moving the import to the Objective C bridging header seems to fix the problem, but that is just a temporary solution in my opinion.

Any ideas on why this happens?

![screenshot 2015-10-22 17 33 27](https://cloud.githubusercontent.com/assets/92683/10669869/0b226c28-78e3-11e5-8cfb-d9470097fc21.png)

**Comment by tecknut** [comment]
@hermanolsson Thanks for highlighting this, we're taking a look at it now. We'll get back to you soon.

**Comment by hermanolsson** [comment]
Thanks @tecknut . We have two other issues with the SDK together with our Swift project, and since you guys were so fast on this one, I will add those as separate issues later tonight.

**Comment by Pitsko** [comment]
+1

any updates?

**Comment by adrianmacneil** [comment]
+1

**Comment by adrianmacneil** [comment]
See [my patch](ac4b75cdb317f656fc0b0be44424a8f9aff8377f) for a fix.

**Comment by RonanMcH** [comment]
Hi @hermanolsson  and @adrianmacneil, 
we've made this fix. You should see the fix in our latest release (1.5.1.1).
Thanks again for pointing it out,
Ronan.
