### ISSUE TITLE
Show use of CocoaPods Trunk in README

### ISSUE THREAD

**Issue by billinghamj** [zendesk/zendesk_sdk_ios#104]
As you're no longer updating your own CocoaPods Specs repo (latest published version is 1.4.1.3), the README should probably be updated to examples which would pull the pod from CocoaPods Trunk.

**Comment by RonanMcH** [comment]
Hi @billinghamj ,
thank you for bring this to our attention.  This was just a mistake when we did the last release, not to update the Cocoapods Specs Repo.  It is updated now to the latest release (1.4.1.4).
Thanks again,
Ronan.
