### ISSUE TITLE
Wrap up a React Native Component

### ISSUE THREAD

**Issue by cancan101** [zendesk/zendesk_sdk_ios#105]
Would be cool if this were wrapped up as a react native component.

For an similar effort see: https://github.com/auth0/Lock.ReactNative

**Comment by baz8080** [comment]
@cancan101 It looks cool. We don't have any plans to do this right now but react native is an interesting tech to us.

**Comment by cancan101** [comment]
One step that would help toward supporting React Native would be to ship an XCode project that does not have any dependencies on Cocoa Pods and that can be added along the lines of: https://facebook.github.io/react-native/docs/linking-libraries-ios.html#content.

Here are some example projects:
* https://github.com/aksonov/react-native-tableview
* https://github.com/lwansbrough/react-native-camera (supports IOS and Android)
* https://github.com/umhan35/react-native-search-bar

**Comment by pierrezen** [comment]
Hi Cancan101

I have created a FR on your behalf for our product manager to look at it .

I would also suggest that you post on https://support.zendesk.com/hc/en-us/community/topics/200132066-Product-feedback as our product manager are monitoring this community actively and it allows our customers to upvote for the feature requests.

**Comment by oarrabi** [comment]
Hello @cancan101,

This feature has been added to our backlog, we will keep an eye on. 
I will close this issue at the moment. When this is fixed we will post an update here.

Thanks,

**Comment by rturk** [comment]
I'm confused why this issue was closed?

**Comment by chirag04** [comment]
@oarrabi any update on this?

**Comment by mathewcropper** [comment]
Hi @chirag04. I'm the Product Manager for our SDKs. We have no plans to build a React Native component at present, and are instead continuing to focus on the Android and iOS SDKs for Chat and Support. Apologies if the previous updates on this issue weren't clear on how the feature request was handled.

**Comment by tmaly1980** [comment]
@mathewcropper , that's disappointing. Mobile app development is cumbersome when it needs to be written twice in two separate languages, so having a javascript-based interface via react native seems natural. A LOT of people are going that way with mobile development as it cuts dev time significantly. I am not a native iOS/Android developer, so I couldn't say how what's involved, only that I'd imagine you'd just have a thin JS wrapper to interact with your iOS and Android SDK. I'm stuck working with React Native so I will most likely interface with a REST API or create my own internal FAQ/feedback system.
