### ISSUE TITLE
Adding Chat to Project

### ISSUE THREAD

**Issue by cancan101** [zendesk/zendesk_sdk_ios#110]
This line:
```objectivec
#import <ZDCChat/ZDCChat.h>
```
is giving me:
```
/Users/alex/ZD/ios/ZD/AppDelegate.m:11:9: 'ZDCChat/ZDCChat.h' file not found
```

Right now my Podfile looks like:
```ruby
target 'ZD' do
   pod 'ZendeskSDK'
end
```

**Comment by RonanMcH** [comment]
Hi @cancan101,
this is not the correct repo for the Zendesk Chat SDK.  I believe [this ](https://github.com/zendesk/zendesk_sdk_chat_ios) is the SDK you are looking for.  Let us know if this was your problem.
Ronan.

**Comment by cancan101** [comment]
Is the entry in the Pod file `pod 'ZendeskSDK'` supposed to be the same for the [regular SDK](https://github.com/zendesk/zendesk_sdk_ios) and the chat SDK?

**Comment by RonanMcH** [comment]
Hi @cancan101 ,
thanks for bringing this to our attention, you are correct in thinking this is wrong.  The podspec for the Zendesk Chat SDK should read:

source 'https://github.com/zendesk/Specs.git'
pod 'ZDCChat'

This is what you should have in you podfile to include the Chat SDK. I have put in a pull request on the repo to change the "readme" to the correct pod link.  It should get merged very soon.
Thanks again,
Ronan.

**Comment by RonanMcH** [comment]
@cancan101  pull request is merged!
