### ISSUE TITLE
Add showRequestList that Does not Require a NavController

### ISSUE THREAD

**Issue by cancan101** [zendesk/zendesk_sdk_ios#112]
Currently a `NavController` is required to show the Request List.

The same is not true when starting chat. Why is that?
```objectivec
/**
 * Show the chat UI and begin connecting to the chat server.
 * This method will present the chat UI in a new modal.
 * @param sessionConfig block in which the session config may be used to override the 
 *        defaults for this session only, leave nil to use the default config
 */
+ (void) startChat:(ZDCSessionConfigBlock)sessionConfig;
```

Same issue with `showRequestCreationWithNavController`. 

For example:
```objectivec
/**
 *  Displays a request list view controller.
 *
 *  @param navController A navigation controller from which to push the request list view.
 */
+ (void) showRequestListWithNavController:(UINavigationController *)navController;
```

**Comment by tecknut** [comment]
Hi @cancan101, chat shows itself as a modal over your apps content. It creates it's own nav controller. `showRequestCreationWithNavController` places itself on your nav stack.

**Comment by cancan101** [comment]
Right. Any reason that there can't be a version of `showRequestList` that also creates it's own nav controller?

**Comment by tecknut** [comment]
We can certainly add this method as a convenience. 

If you would something you can work with right now you can create a request list controller and implement `ZDKCreateRequestUIDelegate` methods. 

```objective-c

- (ZDKNavBarCreateRequestUIType) navBarCreateRequestUIType {
    return <# either ZDKNavBarCreateRequestUITypeLocalizedLabel or ZDKNavBarCreateRequestUITypeImage#>
}


- (UIImage *) createRequestBarButtonImage {
    UIImage *image = [UIImage imageNamed:<#If you want an icon in the nav bar#>];
    return image;
}


- (NSString *) createRequestBarButtonLocalizedLabel {
    // This will give you our translated strings for new
    // You can return something else if you desire
    return NSLocalizedStringFromTableInBundle(@"ios.ZDKRequests.rightBarButton.title.new",
                                              [ZDKBundleUtils stringsTableName],
                                              [ZDKBundleUtils frameworkStringsBundle], nil);
}
``` 

Create a `ZDKRequestListViewController` and present it in a new nav:

```objective-c
- (void) requestList {
    ZDKRequestListViewController *requestListController = [ZDKRequestListViewController new];
    requestListController.delegate = self; // assuming you've implemented the methods in self

    UINavigationController* navController = [[UINavigationController alloc] initWithRootViewController:requestListController];
    [self presentViewController:navController animated:YES completion:nil];
}
```

Hope this helps you.

Thanks

**Comment by RonanMcH** [comment]
Hi @cancan101 ,
hope this has helped. I am going to tentatively close this issue but feel free to reopen it if you feel it has not been solved.
Ronan.

**Comment by cancan101** [comment]
@RonanMcH, [per this](https://github.com/zendesk/zendesk_sdk_ios/issues/112#issuecomment-155181957), I was hoping these methods could be added to the SDK itself.

**Comment by tecknut** [comment]
@cancan101 We have added this to our roadmap, however we can't give you an exact date when that will be released. 

We'll leave this open until we have what was [described here](https://github.com/zendesk/zendesk_sdk_ios/issues/112#issuecomment-155181957) as methods within the SDK.

**Comment by cancan101** [comment]
Also would be great to have similar for 
https://developer.zendesk.com/embeddables/docs/ios/gettingstarted#starting-with-help-center

**Comment by cancan101** [comment]
Related question: what is the `ViewController` that `showHelpCenterWithNavController` uses?

**Comment by baz8080** [comment]
Hi @cancan101 

The controller is [ZDKSupportViewController](https://github.com/zendesk/zendesk_sdk_ios/blob/master/ZendeskSDK.framework/Headers/ZDKSupportViewController.h)

**Comment by baz8080** [comment]
Hey @cancan101 I'm going to close this one for now. If you still need help on this issue please let us know.
