### ISSUE TITLE
[feature request] BITCODE support

### ISSUE THREAD

**Issue by ralph-e-boy** [zendesk/zendesk_sdk_ios#113]
Hi:

In order for apps to support bitcode app thinning in ios 9, all dependent libraries need to also be compiled with bitcode support. Could this feature be enabled in the zendesk frameworks ( chat too ) ? 

More info here:

https://developer.apple.com/library/tvos/documentation/IDEs/Conceptual/AppDistributionGuide/AppThinning/AppThinning.html

**Comment by RonanMcH** [comment]
Hi @ralph-e-boy,
Bitcode is enable for both the ZendeskSDK and the ChatSDK.  Could please provide more details if it is not working for you? 
Thanks,
Ronan.

**Comment by RonanMcH** [comment]
Hi @ralph-e-boy,
we had a minor issue enabling bitcode support on the ChatSDK, we are working to resolve this issue and will release with it fixed soon.  The regular ZendeskSDK is fine though and does have bitcode support enabled.
Ronan.

**Comment by ralph-e-boy** [comment]
@RonanMcH  thank you!
