### ISSUE TITLE
"class" is a reserved keyword

### ISSUE THREAD

**Issue by netizen01** [zendesk/zendesk_sdk_ios#119]
ZDKUIUtil.h exposes a few appearance class functions which use the word "class" as a parameter name.

This work is reserved in Swift and will throw compiler errors.

Suggest renaming the param names to "clazz" or something similar.

"+ (id) appearanceForClass:(Class)clazz selector:(SEL)selector;"
"+ (id) appearanceForClass:(Class)clazz selector:(SEL)selector defaultValue:(id)defaultValue;"

**Comment by tecknut** [comment]
@ojstewart thanks for pointing this out. Can you describe how to reproduce this? 

We have test apps in Swift and Objective-C, neither of these had any errors. We'd like to be able to test for this going forward.

**Comment by ojstewart** [comment]
Figured out the issue:
I have a Objective-C++ code in my project. "class" is a keyword in C++.

So this isn't actually a Swift error, it's a C++ issue.

To test, change any of your project .m files to a "Objective-C++ Source" file type.
Make sure this file includes the Zendesk framework header:
#import <ZendeskSDK/ZendeskSDK.h>

There will the "class" error as well as a new one (@import directives cannot be used with C++).

My issue could possibly be avoided if I can figure out how to isolate the ZendeskSDK from my C++ code (I think it's possible)...
BUT - this is an easy fix for your team to just avoid a reserved keyword.

**Comment by oarrabi** [comment]
@ojstewart We will be updating this in a later release. Thank you for raising it.

**Comment by netizen01** [comment]
Status update on this?

**Comment by tecknut** [comment]
@netizen01 This is fixed, and will be out in our next release.

**Comment by oarrabi** [comment]
Hello @netizen01. We just released 1.5.4.1 please update and check it out.
