### ISSUE TITLE
Crash in sample app

### ISSUE THREAD

**Issue by Sky** [zendesk/zendesk_sdk_ios#120]
[ZDKHelpCenterAttachmentsDataSource setCallback:]: unrecognized selector sent to instance 0x7fb281eaefb0'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010f050f45 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010e7cadeb objc_exception_throw + 48
	2   CoreFoundation                      0x000000010f05956d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x000000010efa6eea ___forwarding___ + 970
	4   CoreFoundation                      0x000000010efa6a98 _CF_forwarding_prep_0 + 120
	5   SDK-Sample                          0x000000010c875a4c -[ZDKHelpCenterDataSource init] + 193
	6   SDK-Sample                          0x000000010c857edd -[ZDKHelpCenterAttachmentsDataSource initWithArticleId:] + 57
	7   SDK-Sample                          0x000000010c86aba6 -[ZDKArticleViewController initWithArticle:] + 302

iOS9 simulator
Same crash if you click Support in sample app main menu.

**Comment by tecknut** [comment]
@Sky Thanks for raising this with us, we've identified the problem and should have a patch out soon.

**Comment by tecknut** [comment]
@Sky We just put out a patch. Can you try this and verify it's working for you?

**Comment by Sky** [comment]
Works now. Thank you!

**Comment by tecknut** [comment]
No problem, please let us know if you have any further issues. 

Thanks again for raising this.
