### ISSUE TITLE
Not possible to compile project with version 1.5.2.1

### ISSUE THREAD

**Issue by Pitsko** [zendesk/zendesk_sdk_ios#123]
xcode 7.1.1
cocoapods - pod 'ZendeskSDK', '~> 1.5.2.1'
issue:
![screenshot 2015-12-02 10 33 05](https://cloud.githubusercontent.com/assets/172434/11540244/7c8a41c0-98e0-11e5-8b00-8b8bd2df6eb8.png)

but it works with branch:
pod 'ZendeskSDK', :git => 'https://github.com/adrianmacneil/zendesk_sdk_ios.git', :branch => 'fix-modulemap'

**Comment by StevenDiviney** [comment]
Hi @Pitsko,

Thanks for bringing this to our attention, we are working on a fix. The branch you linked is out of date so we can't just pull it in.

Thanks

**Comment by StevenDiviney** [comment]
Hi @Pitsko,

We just did a release to fix this. Unfortunately the person registered with Cocoapods trunk won't be in until Monday so we can't update the spec. In the mean time you can use the SDKs repo on github by changing your the ZendeskSDK line in your podfile to the one below.

pod 'ZendeskSDK', :git => 'https://github.com/zendesk/zendesk_sdk_ios.git'

We will push the new release up to the main cocoapods trunk on Monday.

**Comment by tecknut** [comment]
Hey guys, I just pushed to cocoapods from home. It's up to date with the latest release so no need to change your Podfile.

**Comment by RonanMcH** [comment]
Thanks @tecknut and @Pitsko,
the problem has been fixed so I'm to close the issue.
