### ISSUE TITLE
ZDKHelpCenterSearch

### ISSUE THREAD

**Issue by Sky** [zendesk/zendesk_sdk_ios#124]
Hi,

ZDKHelpCenterSearch.sectionId type is NSNumber but ZDKHelpCenterSection.sid is NSString, strange
Same for categoryId.

**Comment by tecknut** [comment]
Hi @Sky thanks for pointing this out. Not sure why these were created with this discrepancy. 

I'm going to open an internal issue with this. 

Is this blocking you in any way?

**Comment by Sky** [comment]
Nope, I convert Number to String, it's confusing but not a problem :)

**Comment by oarrabi** [comment]
Hello @Sky,

We added this to our backlog. I will be closing this issue for now, when fixed we will update this issue to inform you.

Thanks.
