### ISSUE TITLE
like/dislike

### ISSUE THREAD

**Issue by Sky** [zendesk/zendesk_sdk_ios#127]
Hi,

ZDKHelpCenterProvider* provider = [ZDKHelpCenterProvider new];
[provider upvoteArticleWithId: article.sid withCallback: ^(NSArray* items, NSError* error) {
}];

Error Domain=ZDDispatcher Code=3 "The operation couldn’t be completed. (ZDDispatcher error 3.)" UserInfo=0x7fed00974280 {zd_dispatcher_err=HTTP Error: 403}

Same for downvote.

**Comment by tecknut** [comment]
Hey @Sky, Can you give us some context around what you're doing? 

Have you initialised the SDK successfully before calling these methods?

**Comment by Sky** [comment]
Yes,
I can fetch Sections and Articles, create Requests and Comments but can't Vote for Article :(

**Comment by Sky** [comment]
Actually I notices that errors are quite scrooge :)

**Comment by Sky** [comment]
Also small question:
if "ZDKConfig.initializeWithAppId:zendeskUrl:ClientId" fails first time due to network problems, should I call it next time I want to fetch Categories/Sections/Articles or do something with Requests? Eg. should I check state of ZDKConfig before calling another requests?

**Comment by pierrezen** [comment]
We have a version of the initialize method that has completion blocks. Using this version should allow to capture any initialisation issue. 

```
- (void) initializeWithAppId:(NSString *)applicationId
                  zendeskUrl:(NSString *)zendeskUrl
                    ClientId:(NSString *)oAuthClientId
                   onSuccess:(ZDKInitializeSuccess)successBlock
                     onError:(ZDKAPIError)errorBlock
```

**Comment by Sky** [comment]
I am already using this version but the suggestion was about automatic resending this call when needed.

What about my initial like/dislike issue?

**Comment by pierrezen** [comment]
On the automatic resend, I understand and I will mark this as a feature request. 

On the initial like/dislike issue, you are receiving a 403 which I think is why @tecknut ask for the initialisation details. You will need a valid identity to be able to call the voting providers. Identity is different from authentication and is required. Can you confirm that this is what you do (identity set prior to voting) ?

**Comment by Sky** [comment]
I have set [ZDKConfig instance].userIdentity to ZDKAnonymousIdentity instance if you asking about this, in other case I will not be able send Requests and Comments which I mention in my second comment.

**Comment by pierrezen** [comment]
I have tried with the sample application shipped with the SDK, ZDKAnonymousIdentity and the code snippet you have shared and I can not reproduce the issue 

```
ZDKHelpCenterProvider* provider = [ZDKHelpCenterProvider new];
[provider upvoteArticleWithId: article.sid withCallback: ^(NSArray* items, NSError* error) {
}];
```
As we will need more information regarding your account that can not be shared publicly, please contact us at support.zendesk.com and will be happy to help resolving your integrations issues.
