### ISSUE TITLE
Enable pull to refresh on issue chat view

### ISSUE THREAD

**Issue by dyermd** [zendesk/zendesk_sdk_ios#130]
Currently you can see a list of your current issues and if you click on one see the specific chat log for the issue, but if an agent updates the ticket while a customer is viewing the chat log there is no way for them to get the update without first going back in the navigation view and then reentering the issue. It would be great if chat view enabled the pull down to refresh action or if that view would poll for updates so it is much more interactive like the Messages application in iOS.

**Comment by pierrezen** [comment]
Hi dyermd,

We currently don't have a pull to refresh feature in that screen, but you can achieve a similar experience by enabling push notification in the SDK. In this case, if the agent updates the ticket, the chat view will automatically be refreshed.

**Comment by dyermd** [comment]
Thank you. Do you have documentation on how to do that?

On Tuesday, December 8, 2015, Pierre-Alain Bouchard <
notifications@github.com> wrote:

> Hi dyermd,
>
> We currently don't have a pull to refresh feature in that screen, but you
> can achieve a similar experience by enabling push notification in the SDK.
> In this case, if the agent updates the ticket, the chat view will
> automatically be refreshed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zendesk/zendesk_sdk_ios/issues/130#issuecomment-163059949>
> .
>


-- 
Sent from Gmail Mobile

**Comment by pierrezen** [comment]
A good starting point is our developer documentation
https://developer.zendesk.com/embeddables/docs/ios/push_notifications

**Comment by baz8080** [comment]
@dyermd I'm going to close this issue for now. If you need any more help please let us know.
