### ISSUE TITLE
Article labels

### ISSUE THREAD

**Issue by Sky** [zendesk/zendesk_sdk_ios#132]
There is no way to get list of article labels with ProviderSDK :(

**Comment by schlan** [comment]
Hi @Sky 
I added your feature request to our backlog. We'll notify you, as soon as we have any updates on it.
Sebastian

**Comment by Sky** [comment]
I swizzled ZDKHelpCenterArticle.parseArticle to get this field from JSON payload which already has labels data from API and added another property to ZDKHelpCenterArticle.

**Comment by schlan** [comment]
Thank you for clarification. We'll look into that.

**Comment by rickyngan** [comment]
Could we use the API, without the mobile SDK?

https://developer.zendesk.com/rest_api/docs/help_center/labels

List All Labels
GET /api/v2/help_center/articles/labels.json

Lists all the labels in all the articles in Help Center.

curl https://{subdomain}.zendesk.com/api/v2/help_center/articles/labels.json \
  -v -u {email_address}:{password}

**Comment by baz8080** [comment]
@rickyngan You could, but that core API is for agents only. The SDK operates on an end-user access level.

**Comment by StevenDiviney** [comment]
@rickyngan @Sky We have released a new version of the SDK. Labels are now part of the article model.

**Comment by baz8080** [comment]
@rickyngan @Sky I'm going to close this issue. You can find our release notes here: https://developer.zendesk.com/embeddables/docs/ios/release_notes
