### ISSUE TITLE
SampleApp can not be compiled, duplicate symbol _llvm.embedded.module

### ISSUE THREAD

**Issue by ronaldjhp** [zendesk/zendesk_sdk_ios#133]
I am trying to test the current SampleApp under xCode 6,4. It does not compile, show this kind of error message 

clang: error: linker command failed with exit code 1 (use -v to see invocation) 
...
duplicate symbol _llvm.embedded.module in:
/SampleApp/SampleApp/Frameworks/ZendeskSDK.framework/ZendeskSDK(ZDKRequestCommentTableCell.o)
...

**Comment by baz8080** [comment]
@ronaldjhp Is upgrading to xcode 7.x an option for you? This could be related to our latest releases having support for bitcode.

**Comment by ronaldjhp** [comment]
I can not upgrade to xCode 7.x these days because it does not allow to compile under iOS 8.4.

**Comment by tecknut** [comment]
@ronaldjhp It should be possible for you to upgrade and keep your old installation. There are ways to get the older simulators to work with newer versions of Xcode.

**Comment by baz8080** [comment]
I'm going to close this issue as there is a workaround.
