### ISSUE TITLE
Support specifying multiple category+section IDs

### ISSUE THREAD

**Issue by js** [zendesk/zendesk_sdk_ios#134]
#46 talks about supporting limiting the in-app KB to selected categories and/or sections, but it's only currently possible to specify a single category or section not multiple categories or sections.

I'd very much like support for specifying multiple categories with something like a `+[ZDKHelpCenter presentHelpCenterWithNavController:filterByCategoryIDs:]` methods

**Comment by baz8080** [comment]
@js thanks for the feature request. I'm going to add it to our backlog so that we can get it to be seen by our product manager. If you had any more ideas about how you would like this to work, please let us know.

**Comment by mathewcropper** [comment]
Hi @js. I'm the new Product Manager for our SDKs and I thought I'd drop you a line to let you know that in our upcoming release (next month or so) it will be possible to specify multiple category IDs or section IDs when filtering your Help Center. It's been a long time coming, but hopefully this update finds you well.

I'll leave this issue open, and will update the thread when the release goes out.

**Comment by RonanMcH** [comment]
Hi @js,
In our new Help Center, you can now specify to open it with multiple categories or multiple sections by specifying their particular IDs in the entry methods. The new Help Center was part of our latest release of the Support SDK and is available now from the repo.
Thanks,
Ronan.
