### ISSUE TITLE
Option to restrict landscape in the  'Contact Us' screen

### ISSUE THREAD

**Issue by ronaldjhp** [zendesk/zendesk_sdk_ios#135]
I am working in an app that allows the orientation according the screen. I reliazed that  the 'Contact Us' screen allows the landspace orientation, but I want to restrict landspace in this in screen. Normally the restriction are set overriding the method 'shouldAutorotateToInterfaceOrientation', but in this case I can not modify the code. 

So I think there should be an option (in a method parameter) that allows manage the orientation.

**Comment by tecknut** [comment]
Hey @ronaldjhp, can you clarify something for us please? You do not want your app to allow 'Contact Us' to rotate to landscape?

Thanks

**Comment by ronaldjhp** [comment]
@tecknut exactly, I want 'Contact Us' only in portrait.

**Comment by tecknut** [comment]
So this should be possible. We have done this in one of our demo apps which can be found here. 

https://github.com/zendesk/sdk_demo_app_ios/tree/master/Remember%20The%20Date

**Comment by baz8080** [comment]
I'm going to close this as we haven't heard back from you in a while. Please reply if you're still having issues with this issue.
