### ISSUE TITLE
Carthage support?

### ISSUE THREAD

**Issue by mikemee** [zendesk/zendesk_sdk_ios#137]
Is there any interest in adding Carthage support?  

E.g. if I did a PR for it, would you accept it?  (Many CocoaPod projects are adding it).

**Comment by oarrabi** [comment]
Hello @mikemee.
Sure, we were discussing adding it and have it under planning. 
However a PR would be great. please feel free to submit one :)

**Comment by hgale** [comment]
@mikemee did you manage to get this working with Carthage?

**Comment by mikemee** [comment]
Haven't gone back and tried to be honest. This was one of several projects that didn't have a Carthage install, so we bit the bullet and added Cocopods to the build so we could keep moving...  We'll use it when it appears though :)

**Comment by hgale** [comment]
@oarrabi any plans to support this? Right now I am trying to build a dynamic library from scratch in order to support the zendesk sdk in our app.

**Comment by oarrabi** [comment]
Hello @hgale,

Yep, we do have a plan to support this. However, at the moment, we can't since the SDK is distributed as a static library its not possible to distribute it using Carthage.
We do plan to distribute the library as a dynamic framework in the future. When we have that we will support carthage.
Sorry for the inconvenience :)

**Comment by hgale** [comment]
Okay, here is how I worked around this issue:

I created an internal github repo that just included the framework files.  I then added this repo to our Cartfile and just had our internal scripts checkout the carthage frameworks. I then just included those in our project.

**Comment by oarrabi** [comment]
@hgale Do you have the repo that you used for this? If you do that would be easier to refer.

**Comment by marbetschar** [comment]
@oarrabi any progress on this? I would love to use the SDK together with Carthage! :)

**Comment by oarrabi** [comment]
Hello @marbetschar, we’re aware of it and would like to provide Carthage support, but I am afraid that it’s not something we are planning to actively work on for some time.

**Comment by mathewcropper** [comment]
Hi. I'm Mat, the Product Manager for our SDKs. The best place for SDK feature requests is the [Zendesk SDK community](https://support.zendesk.com/hc/en-us/community/topics/200488257-Zendesk-SDKs), or the [Product Feedback community](https://support.zendesk.com/hc/en-us/community/topics/200132066-Product-feedback) for broader Zendesk ideas. This allows your idea to have a broader reach and discussion. We don't manage feature requests via Github, I'm afraid.

I looked, and there isn't anything in there at the moment for this particular idea. If you'd like to add it, I'm sure the community would be interested in your thoughts.

**Comment by Antoine4011** [comment]
I created the ideas on the Zendesk Community 
https://support.zendesk.com/hc/en-us/community/posts/221982207-Carthage-support-for-iOS

**Comment by mxcl** [comment]
You can add the URL anyway, then include the bundled frameworks from the `Checkouts` entry that Carthage clones. However I then get “Unable to install app” when trying to use the resulting app.

Not sure what I'm missing. This seems like a work around while we wait 3 years for them to do the two minutes of work supporting Carthage requires.

**Comment by txaiwieser** [comment]
This is not an acceptable "alternative" to not supporting Carthage the right way. How are we suppoused to implement in our CI if it fails and you should "ignore the error"... 🙄 
At least give us a .json with precompiled links for each version.

https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework

Zendesk really can't have a developer to implement that, in a day?

**Comment by mxcl** [comment]
Well, it's not an error, it's a warning. So is CI safe unless Carthage returns non-zero for warnings.

**Comment by mxcl** [comment]
And yes, in my experience Carthage is much easier to support than CocoaPods and takes about 30 minutes to implement. I've put Carthage in about 40 projects.

**Comment by kevnm67** [comment]
@mathewcropper As previously mentioned, implementing carthage support is ~trivial.  Further, the community is willing to do the work.  Are ya'll open to Carthage support if someone opens a PR?

**Comment by satindar** [comment]
@kevnm67 Have you tried using the `binary` command in the Cartfile? I've done it for a different framework that only released a binary and it worked. 

You would create a .json file in the same dir as your Cartfile that looks like this:

```
// Zendesk.json
{
    "2.3.1": "https://github.com/zendesk/zendesk_sdk_ios/archive/2.3.1.zip"
}
```

and then add this line to the Cartfile:

`binary "Zendesk.json"`

That should work. I haven't tried it yet. Was just looking through the docs here to see if Zendesk supports Carthage yet.
