### ISSUE TITLE
Expose labels?

### ISSUE THREAD

**Issue by jimmaye** [zendesk/zendesk_sdk_ios#138]
Hi

I'm really a fan of the getFlatArticlesWithCallback: which the ZDKHelpCenterProvider class provides. 
Is it possible to provide specific labels in the same way that getArticlesByLabels:withCallback: can somehow?
If not, can I access the labels directly on the articles? The labes are included in the JSON response according to my ssl proxy.

Thanks in advance!

**Comment by schlan** [comment]
Hi @jimmaye, 
At the moment we don't support filtering articles by labels, on the `getFlatArticlesWithCallback` call.
We're planning to add a field for labels to articles. It's already in our backlog we keep you updated on this.

**Comment by jimmaye** [comment]
Hi @schlan 
Nice to know. Thanks again!

**Comment by StevenDiviney** [comment]
@jimmaye We have released a new version of the SDK. Labels are now part of the article model.
