### ISSUE TITLE
Dynamically switching between JWT and Anonymous identities

### ISSUE THREAD

**Issue by billinghamj** [zendesk/zendesk_sdk_ios#139]
I'm trying to use the following code to dynamically switch between authenticating users anonymously or with JWTs (as we want our users to be able to send us messages while they're logged out).

I've tried five different arrangements of code to try and make this work, and nothing seems to change the outcome - extraordinarily frustrating!

```objc
if (_credentials)
{
  // works
  [[ZDKConfig instance] initializeWithAppId:kCUVZendeskJwtAppId zendeskUrl:kCUVZendeskURL andClientId:kCUVZendeskJwtClientId];

  [ZDKConfig instance].userIdentity = [[ZDKJwtIdentity alloc] initWithJwtUserIdentifier:_credentials.zendeskToken];
}
else
{
  // fails
  [[ZDKConfig instance] initializeWithAppId:kCUVZendeskAnonClientId zendeskUrl:kCUVZendeskURL andClientId:kCUVZendeskAnonClientId];

  ZDKAnonymousIdentity *anon = [ZDKAnonymousIdentity new];
  anon.name = @"Anonymous";
  anon.email = @"anonymous-user@example.com";
  anon.externalId = @"anonymous-user@example.com";
  [ZDKConfig instance].userIdentity = anon;
}
```

This is the error I get when trying to submit a ticket:

```
Error Domain=ZDDispatcher Code=-1013 "(null)" UserInfo={zd_dispatcher_err=JWT identity is nil or has a nil user token. Have you set an identity?}
```

Worth noting:

- we're using a different client ID and app ID, depending on whether we're using anonymous/JWT, as I understand that an app set up on the Zendesk admin site only allows one type of authentication
- the subdomain is https://cuvva.zendesk.com
- the above code is called a while before the Zendesk ticket UI is presented - the UI is only presented after the user taps a button, so there is a gap of at least half a second before the config might be used
- the code above runs each time the user's login state changes, and once when the app loads

I'm at my wits' end with this issue. So confused as to why none of the methods I've tried aren't working :(

**Comment by billinghamj** [comment]
Actually, specifically the anonymous set of code doesn't work. The JWT code is working fine.

**Comment by RonanMcH** [comment]
Hi @billinghamj ,
This is not something we support.  Switching one application between two applications within Zendesk with two different authentication types will cause errors from the server.  Anonymous authentication does allow the user to add an email so maybe this best suits your use-case.
Ronan.

**Comment by billinghamj** [comment]
Hi Ronan,

Why wouldn't this work? They're two completely different OAuth clients, and your own sample app shows this behavior also:

https://github.com/zendesk/zendesk_sdk_ios/blob/master/SampleApp/SampleApp/ZDSampleAppConfigurationViewController.m#L322-L336

Also see: 
![screenshot of Zendesk admin configuration](https://cloud.githubusercontent.com/assets/905772/12423969/e64cbd94-bec5-11e5-8af5-63a976dc1316.png)

**Comment by RonanMcH** [comment]
While our [documentation](https://developer.zendesk.com/embeddables/docs/ios/authentication) never explicitly states that only one type of authentication type can be used in your app at one time, this is in fact the case. The documentation describes the caveats between JWT vs Anonymous authentication. 

It's not clear from earlier comments whether you want to support a transition on one device from one user, authenticated with Anonymous authentication, to the same user authenticated with JWT.

Is this something you are trying to achieve?

**Comment by billinghamj** [comment]
So how does your sample app work? It appears to allow the Zendesk client to be reconfigured without killing the app.

Transitioning a single user from Anonymous to JWT authentication would be nice. In this case, I do not need to make any connection between the two users though - it is acceptable for them to be entirely unlinked.

We'd also want to be able to disassociate the user and go back to Anonymous with a new ID - if the user signed out of the app.

**Comment by baz8080** [comment]
Hi,

Our sample app works, but only when we [clear the persistent state](https://github.com/zendesk/zendesk_sdk_ios/blob/master/SampleApp/SampleApp/ZDSampleAppConfigurationViewController.m#L285) and restart the app before we switch authentication types. ZDKConfig is a singleton and doesn't completely reinitialise when you call `initializeWithAppId`. You may find that the clearing of the data might work, but you will experience other issues before we have a valid solution in place.

You are detailing a valid use-case but it isn't one that isn't going to work at the moment. It is in our backlog but it isn't scheduled to be worked on imminently.

**Comment by billinghamj** [comment]
Thanks for that clarification.

I think you should consider looking at that fairly soon. For now though, I think we've had enough of Zendesk and will probably switch to Intercom. :+1:

**Comment by baz8080** [comment]
Thanks for the feedback, James. I've passed it on to our product manager. What I said in the last comment stands for now.

**Comment by shfishburn** [comment]
We are having the issue: JWT identity is nil or has a nil user token. Have you set an identity JUST with using JWT. Help!

**Comment by baz8080** [comment]
@shfishburn This happens when either `userIdentity`  in `[ZDKConfig instance]` is nil, or when the user token in `[ZDKJwtIdentity]` is nil.  Here are some snippets which show the setting of an identity and the user token that the identity contains.

```
ZDKJwtIdentity jwtUserIdentity = [[ZDKJwtIdentity alloc] initWithJwtUserIdentifier:@"JWT User Identifier"];
[ZDKConfig instance].userIdentity = jwtUserIdentity;
```

or

```
let jwtUserIdentity = ZDKJwtIdentity(jwtUserIdentifier:"JWT User Identifier")
ZDKConfig.instance().userIdentity = jwtUserIdentity
```

**Comment by shfishburn** [comment]
This is exactly the code we’ve implemented in our iOS app and we still consistently see this error.
 


On April 7, 2016 at 2:00:28 AM, Barry Carroll (notifications@github.com) wrote:

@shfishburn This happens when either userIdentity in [ZDKConfig instance] is nil, or when the user token in [ZDKJwtIdentity] is nil. Here are some snippets which show the setting of an identity and the user token that the identity contains.

ZDKJwtIdentity jwtUserIdentity = [[ZDKJwtIdentity alloc] initWithJwtUserIdentifier:@"JWT User Identifier"];
[ZDKConfig instance].userIdentity = jwtUserIdentity;

or

let jwtUserIdentity = ZDKJwtIdentity(jwtUserIdentifier:"JWT User Identifier")
ZDKConfig.instance().userIdentity = jwtUserIdentity

**Comment by baz8080** [comment]
@shfishburn The local identity can be erased when an authentication failure happens. If you send us a test JWT token we can try to debug that part.  We would need an example of what you replace `JWT User Identifier` with.

**Comment by sunilhts** [comment]
hi.. could you please tell me that "jwt user identifier" is the string that will be with "10 digit alpha numeric value"

**Comment by ndobri** [comment]
@sunilhts if I may suggest, read our docs about [setting an identity](https://developer.zendesk.com/embeddables/docs/ios/set_an_identity#must-do-set-an-identity-authentication) to get familiarized with both JWT and ANONYMOUS identities in Zendesk. That page should provide extensive information to you, but if you still have further questions please leave us a message by clicking the help button at the bottom-right of the docs page and you'll get further assistance.
