### ISSUE TITLE
Title not centered

### ISSUE THREAD

**Issue by kiliannet** [zendesk/zendesk_sdk_ios#140]
Hi! 

I have a problem with **ZDKRequests** object.
Whether "Contact Support" or "My tickets", the screen are showing with title not centered.

I'm using this code:
````
- (void)zendeskContact {
    [ZDKRequests showRequestCreationWithNavController:self.navigationController];
}
- (void)zendeskTickets {
    [ZDKRequests showRequestListWithNavController:self.navigationController
                                      layoutGuide:ZDKLayoutRespectAll];
}
````
Also, I attached you two screenshots so you can see the problem. 

![screenshot at jan 21 09-15-54](https://cloud.githubusercontent.com/assets/796971/12476500/99ee1670-c021-11e5-92fc-0deb57b9e3f3.png)
![screenshot at jan 21 09-17-24](https://cloud.githubusercontent.com/assets/796971/12476501/99f4c2fe-c021-11e5-9945-ce20d0c7ea38.png)

Thanks in advance!

**Comment by tecknut** [comment]
Hey @kiliannet, I've just attempted to replicate this and I'm not able to. 

<img width="312" alt="screen shot 2016-01-21 at 10 26 27" src="https://cloud.githubusercontent.com/assets/2079547/12477837/c6001eae-c029-11e5-9ade-66c8055d40fa.png">

Is there anything in your setup which could help us replicate this issue?

Also does this happen on all your test devices?

Thanks

**Comment by kiliannet** [comment]
Sorry, I was my mistake.

In my code legacy I found a category of UINavigationItem that override setTitle methods.

Thanks and apology.
