### ISSUE TITLE
Ability to Hide the Set Attachment Button on Create Request

### ISSUE THREAD

**Issue by cancan101** [zendesk/zendesk_sdk_ios#142]
Is there any way to hide the Set Attachment button on the "Create Request" view? I am looking at [`ZDKRequestCreationConfig`](https://github.com/zendesk/zendesk_sdk_ios/blob/de13c2aea1be24adc3a7331eefd67dc121616693/ZendeskSDK.framework/Headers/ZDKRequests.h#L40-L46) but I don't see any setting to do so.

[These docs](https://developer.zendesk.com/embeddables/docs/ios/customization#create-ticket) indicate the button may be customized but don't specify how to hide.

**Comment by tecknut** [comment]
Hey @cancan101 you can disable attachments in your [Zendesk admin settings](https://support.zendesk.com/hc/en-us/articles/203927716-Attachments-in-Zendesk#sec1).

**Comment by cancan101** [comment]
That seems to be a global change. Is there no way to disable it from the client (ie only under certain circumstance)?

**Comment by RonanMcH** [comment]
Hi @cancan101 ,
I'm afraid this functionality is not available at the moment.  We will treat this as a feature request and I will create a story for it so that our product manager can have a look at it.  It will be in a future release but unfortunately I can't give a timeline for it.
Thanks,
Ronan.

**Comment by mathewcropper** [comment]
Hi. I'm Mat, the Product Manager for our SDKs. The best place for SDK feature requests is the [Zendesk SDK community](https://support.zendesk.com/hc/en-us/community/topics/200488257-Zendesk-SDKs), or the [Product Feedback community](https://support.zendesk.com/hc/en-us/community/topics/200132066-Product-feedback) for broader Zendesk ideas. This allows your idea to have a broader reach and discussion. We don't manage feature requests via Github, I'm afraid.

I looked, and there isn't anything in there at the moment for this particular idea. If you'd like to add it, I'm sure the community would be interested in your thoughts.
