### ISSUE TITLE
search results in Help Center return all categories, even if Help Center is show with filterByCategoryId:

### ISSUE THREAD

**Issue by andrewljohnson** [zendesk/zendesk_sdk_ios#145]
The use case is to have categories for iOS and Android versions of an app. Only the iOS articles should show when the user searches.

**Comment by brendan-fahy** [comment]
Hi @andrewljohnson 

This issue has already been fixed, and will be included in our next release (1.5.4) - which will be going out in the next two weeks. 

Thanks and best regards,

Brendan

**Comment by oarrabi** [comment]
Hello @andrewljohnson. We just released 1.5.4.1 please update and check it out.
