### ISSUE TITLE
Cocoapods subspecs always include the file "ZendeskSDKStrings.bundle"

### ISSUE THREAD

**Issue by lbasile** [zendesk/zendesk_sdk_ios#146]
Our project is using Zendesk's built-in "Rate the App" UI. We've changed the copy by including a `ZendeskSDKStrings.bundle` as per these instructions: https://developer.zendesk.com/embeddables/docs/ios/customization#customizing-strings-and-localization

We use Cocoapods to include the ZendeskSDK's `Core` subspec. We're upgrading from 1.4.1.4 -> 1.5.3.1 and see these two issues:

1. The `Core` subspec depends on `Providers` in order to build. Without importing `Providers`, building the library gives the error: `Module 'ZendeskProviderSDK' not found` on Line 80 of `ZendeskSDK.h`. This should be added as a dependency to the `Core` subspec (`ss.dependency 'ZendeskSDK/Providers'`).

2. `Providers` includes the resource `ZendeskSDKStrings.bundle`. I suspect it should not do this, since the `Localization` subspec is intended to include this resource.

Because of this, we can't install 1.5.3.1 via Cocoapods and keep the copy changes we made because we can't get around `ZendeskSDKStrings.bundle` being included in its pods folder.

**Comment by StevenDiviney** [comment]
@lbasile, thanks for bringing this to our attention. We are in the middle of a release right now and don't want to commit anymore changes but we will fix the podspec next week and update you.

**Comment by lbasile** [comment]
Great. Thanks for the quick response.

**Comment by marcferna** [comment]
I'm also having this issue

**Comment by tecknut** [comment]
@marcferna We are preparing something for a patch release for this at the moment. We will respond on this issue when it's live.

**Comment by marcferna** [comment]
@tecknut Any update on this? 

Thanks!

**Comment by baz8080** [comment]
@marcferna @lbasile Sorry for the late update. We are preparing a chat sdk release in this sprint, so this issue will be handled soon, but it won't be available in the next 2 weeks.

**Comment by StevenDiviney** [comment]
@marcferna @lbasile We have released a new version of the SDK that fixes this issue.

Have a look at [ZDKLocalization](https://developer.zendesk.com/embeddables/docs/ios/customization#customizing-strings-and-localization) to add your own strings while keeping the defaults in place.

**Comment by tecknut** [comment]
I'm closing this for now since we have release an update that solves the issue. Feel free to re-open or create a new issue if you have further problems.
