### ISSUE TITLE
64-bit architecture missing in 1.5.4.1

### ISSUE THREAD

**Issue by rickyngan** [zendesk/zendesk_sdk_ios#148]
Have to rollback to 1.5.3.1 to workaround with this

**Comment by pierrezen** [comment]
Hi @rickyngan,

Would you be able to share the error you are seeing and how you have upgraded? (manually vs cocoapods)

When running lipo on the framework files, it does show both 64 bits architectures (x86_64 arm64) so I am wondering if there is something that I am missing to reproduce your issue.

**Comment by rickyngan** [comment]
I used cocoapods (pod 'ZendeskSDK/Providers') when compile , it gives the following error:

Undefined symbols for architecture arm64:
  "_OBJC_METACLASS_$_ZDKDispatcher", referenced from:
      _OBJC_METACLASS_$_ZDKAPIDispatcher in ZendeskProviderSDK(ZDKAPIDispatcher.o)
     (maybe you meant: _OBJC_METACLASS_$_ZDKDispatcherResponse)
  "_OBJC_CLASS_$_ZDKDispatcher", referenced from:
      _OBJC_CLASS_$_ZDKAPIDispatcher in ZendeskProviderSDK(ZDKAPIDispatcher.o)
     (maybe you meant: _OBJC_CLASS_$_ZDKDispatcherResponse)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

<img width="589" alt="untitled" src="https://cloud.githubusercontent.com/assets/988470/13002846/9a4a15fa-d1ac-11e5-8cc6-15b1cc7c99c3.png">

**Comment by tecknut** [comment]
Hey @rickyngan, can you try clean your workspace and delete the derived data for your project. 

We have tried replicating this and were unable to do so. 

Thanks, 
Alan

**Comment by rickyngan** [comment]
I tried to clean the derived data folder, it still the same error message.

After that, I tried to include both in pod file 

pod 'ZendeskSDK/Providers'
pod 'ZendeskSDK'

the complie get zero error message.

**Comment by schlan** [comment]
Hi @rickyngan, I'm going to tentatively close this issue but feel free to reopen it if the issue has not been solved for you.

**Comment by rbobbins** [comment]
Hi @schlan, I tried updating the `ZendeskSDK/Providers` pod from v1.5.4.1. I'm having the same issue as @rickyngan.
