### ISSUE TITLE
Possibility to present a single knowledge base article?

### ISSUE THREAD

**Issue by js** [zendesk/zendesk_sdk_ios#151]
We have some cases where it would be useful to link to a specific KB article (eg presenting it modally). Does such a thing exist in the SDK today?

**Comment by tecknut** [comment]
Hey @js this should be possible. 

https://github.com/zendesk/zendesk_sdk_ios/blob/master/ZendeskProviderSDK.framework/Headers/ZDKHelpCenterProvider.h#L116

If you know the Id of the article you can fetch it with the provider method above. You should get a ZDKHelpCenterArticle model back. You can then init and push the view controller bellow.

https://github.com/zendesk/zendesk_sdk_ios/blob/master/ZendeskSDK.framework/Headers/ZDKArticleViewController.h#L47

That should work. If it doesn't let us know and we'll try work something out.

**Comment by baz8080** [comment]
Going to close this one as we haven't heard back from you in a while. Feel free to reopen in if you still want help.
