### ISSUE TITLE
Crash creating request

### ISSUE THREAD

**Issue by kielgillard** [zendesk/zendesk_sdk_ios#152]
Here is a crash report from a framework binary downloaded about a week ago.
[dismiss.log.zip](https://github.com/zendesk/zendesk_sdk_ios/files/133660/dismiss.log.zip)

**Comment by tecknut** [comment]
@kielgillard Can you confirm the version of the SDK in your app at the time of the crash?

Thanks

**Comment by kielgillard** [comment]
`1.5.3.1`

**Comment by oarrabi** [comment]
@kielgillard Thanks for the quick reply, We just released a new version of the SDK `1.5.4.1`. Can you check if it solves your crash.

Also, could you share the code you're using that is causing this issue?

**Comment by oarrabi** [comment]
Hello @kielgillard, 

I will close this issue for the moment. however, please feel free to reopen if the issue persists.

**Comment by kielgillard** [comment]
Thanks. The crash seems pretty obscure and the changes including the updated SDK hasn't gotten out to our users yet.
