### ISSUE TITLE
Change color of status bar

### ISSUE THREAD

**Issue by crisgarner** [zendesk/zendesk_sdk_ios#153]
I'm trying to change the color on the status bar on the showRequestListWithNavController, but I get stuck with a weird animation and a black status bar.

showRequestCreationWithNavController Is not having that problem

Here is my code 

```
 UINavigationBar.appearance().barTintColor =  UIColor(red: 26, green: 188, blue: 156)
 UINavigationBar.appearance().tintColor =  UIColor.whiteColor()
 let titleDict: NSDictionary = [NSForegroundColorAttributeName: UIColor.whiteColor()]
 UINavigationBar.appearance().titleTextAttributes = titleDict as? [String : AnyObject]
                
   ZDKCreateRequestView.appearance().backgroundColor = UIColor(red: 26, green: 188, blue: 156)
   
ZDKRequests.showRequestListWithNavController(self.navigationController)
```

![simulator screen shot feb 18 2016 10 05 48 am](https://cloud.githubusercontent.com/assets/578688/13149670/edac1ff2-d627-11e5-9b5b-afc00e57f8c4.png)

**Comment by StevenDiviney** [comment]
@crisgarner 
What platforms are you seeing this on? Can you post the weird animation please?

**Comment by crisgarner** [comment]
I added this line of code in the app delegate and now the animation bug is like the video attached.

`UIApplication.sharedApplication().delegate?.window??.backgroundColor = UIColor(red: 26, green: 188, blue: 156)`

![ezgif-768205410 1](https://cloud.githubusercontent.com/assets/578688/13183811/2a108f38-d6fe-11e5-893f-ae65f68105b2.gif)

**Comment by RonanMcH** [comment]
Hi @crisgarner ,
Try adding the following code snippet to your appDelegate:
```
UINavigationBar.appearance().translucent = false
```
The bug is being caused by a difference in translucency between our SDK and your app.  This code should override both so you set it to `true` or `false` I believe. Hope this works.
Thanks,
Ronan.

**Comment by crisgarner** [comment]
Thanks @RonanMcH, that did solve the issue.
