### ISSUE TITLE
ZDKRequestProvider - query/search function Request

### ISSUE THREAD

**Issue by rickyngan** [zendesk/zendesk_sdk_ios#154]
https://github.com/zendesk/zendesk_sdk_ios/blob/master/ZendeskProviderSDK.framework/Headers/ZDKRequestProvider.h

Currently, there is no query/search with the subject,

It will be nice if this is included in the future, as the Activity of User in Web Portal.

Thanks

**Comment by tecknut** [comment]
@rickyngan We currently have a way to set the subject for new requests. Can you expand on this please? If you can provide an example of what you want to set in the subject that would be great.

**Comment by rickyngan** [comment]
I would like to know is there any way in mobile SDK to "search requests" as the red eclipse marked below:

![searchrequests](https://cloud.githubusercontent.com/assets/988470/13307951/1d4e83e4-dbaa-11e5-8662-d36286eadc95.png)

**Comment by oarrabi** [comment]
Hello @rickyngan,

At the moment, we don't have this functionality. Searching for tickets by subject is more of an agent feature. 

Could you please tell us what is your particular use case?

**Comment by rickyngan** [comment]
hi @oarrabi ,

We consider to let the end-user/customer to search the ticket requested in the Mobile app.

Currently, filter by status is using:
`- (void) getRequestsByStatus:(NSString *) status withCallback:(ZDKRequestListCallback) callback`

We just want to know if there any "Search Ticket" function for that, as similar to the web portal.

**Comment by oarrabi** [comment]
Hello @rickyngan,

Thank you for reporting this feature. We added this to our backlog to be tracked.
I will keep this issue opened and update you once it's solved.

**Comment by mathewcropper** [comment]
Hi there. I'm Mat, the Product Manager for our SDKs. I'd like to give you an update.

I've reviewed the request, and it's an interesting idea. It's not something I'm planning to push to build at the moment, for a couple of reasons. 

The first is that for most use cases (but not all), an end-user will have few open tickets that appear in their request list on mobile. Anything fewer than ten open tickets is easy to flick through. The feature would have limited use compared to other features we would also like to build. 

The second is that building a request list UI using the SDK's API providers is fairly straightforward. With that, you could implement a search feature of your own with minimal effort.

I'll close this issue on that basis, with thanks for sharing your feedback. If you would like to share other ideas in future, the best place is in one of our Zendesk communities, where it will have a broader reach and discussion. I'd suggest either the [Zendesk SDKs community](https://support.zendesk.com/hc/en-us/community/topics/200488257-Zendesk-SDKs) for feature requests specific to the SDK, or the [Product feedback community](https://support.zendesk.com/hc/en-us/community/topics/200132066-Product-feedback) for more general ideas.
