### ISSUE TITLE
No email when creating tickets.

### ISSUE THREAD

**Issue by markst** [zendesk/zendesk_sdk_ios#155]
Currently we don't have push notification web hook service integrated. 
So we'd like to reply to open tickets using email. 

The ticket submission view controller suggests the user can input their email. 
![](https://zen-marketing-documentation.s3.amazonaws.com/docs/en/mobile_sdk_submit_ticket.png
)

We have since figured that your documentation says:
```
/**
 * Text field for email input. Only shown if using anonymous and conversations disabled.
 *
 *  @since 1.4.0.1
 */
```

So we've disabled conversations from within the admin panel. 
However the create ticket vc is still not providing the user with the option to enter their email, despite also providing email:

```objc
- (void)updateZendeskWithPatientInfo:(Patient *)patient
{
    id <ZDKIdentity> userIdentity = nil;
    /*
    if (patient) {
        userIdentity = [[ZDKJwtIdentity alloc] initWithJwtUserIdentifier:patient.patientID.stringValue];
    } else 
     */
     {
        ZDKAnonymousIdentity * identity = [ZDKAnonymousIdentity new];
         if (patient) {
             identity.name  = [NSString stringWithFormat:@"%@ %@",patient.firstName ?: @"",patient.lastName ?: @""];
             identity.email = patient.email;
             identity.externalId = patient.patientID.stringValue;
         }
         userIdentity = identity;
     }
    
    ZDKConfig.instance.userIdentity = userIdentity;
}
```

![pasted_image_at_2016_02_26_03_26_pm](https://cloud.githubusercontent.com/assets/274318/13343505/455f7dc8-dca1-11e5-885f-3a0ddd814d19.png)

Is there some confusion?
Perhaps you can provide some advice.

**Comment by baz8080** [comment]
Hi @markst 

We don't show the email field when it has already been supplied in the identity like:

`identity.email = patient.email;`

The settings are also cached for up to one hour, so you might have to clear the data on the simulator if you want to pick them up immedately.

**Comment by markst** [comment]
Understood. Regardless `patient.email` can be nil, so we'd like the display the option to enter an email if we have no email for a patient. 

What you mention about the caching of settings appears to be the issue. The email field is not presented to the user. 

Thanks @baz8080.

**Comment by nikita-leonov** [comment]
@baz8080 how to reset a cache?
