### ISSUE TITLE
Request List description label text

### ISSUE THREAD

**Issue by marcoscurvello** [zendesk/zendesk_sdk_ios#157]
My Request List currently looks like the following image. Is there a way to customize the data displayed in that list? These tickets/requests are automatically generated once a live chat starts using the ZopimSDK. 

![simulator screen shot mar 1 2016 4 46 26 pm](https://cloud.githubusercontent.com/assets/745227/13440097/27b2f0e4-dfcf-11e5-9b08-cc1fa68c3ae3.png)

**Comment by StevenDiviney** [comment]
@marcoscurvello This cannot be changed in the provided UI. The only solution would be to create your own UI using [providers](https://developer.zendesk.com/embeddables/docs/ios/providers) and filter the text there.

**Comment by marcoscurvello** [comment]
Thanks, Steven. :)
