### ISSUE TITLE
ZDKCreateRequestView placeholder only allows a single line.

### ISSUE THREAD

**Issue by meekapps** [zendesk/zendesk_sdk_ios#159]
When customizing the placeholder string for a ZDKCreateRequestView, you can only use a string that fits on a single line before it is truncated. Unfortunately UITextView does not have a built in placeholder property, but it looks like you have your own internal ZDKTextView that does. However, the private placeholder UILabel seems to be restricted to being a single line of text by numberOfLines being set to 1. It would be nice if we could customize the placeholder text that wraps to multiple lines as we can with the Android SDK.

**Comment by RonanMcH** [comment]
HI @meekapps ,
Could you tell us the string key of the string you are referring to in ZDKCreateRequestViewController and we can have a look at it? 
Thanks, 
Ronan.

**Comment by meekapps** [comment]
The string we are customizing is:

> ios.ZDKRequests.createRequest.description.placeholder

Thanks!

**Comment by RonanMcH** [comment]
Hi @meekapps ,
I have managed to recreated this and added a story to fix it. We will leave this issue open and keep you updated on its progress.
Regards,
Ronan.

**Comment by RonanMcH** [comment]
Hi @meekapps ,
This issue has been fixed in our latest release (1.7.0.1) which is available from the repo.
Thanks for bringing it to our attention,
Ronan.
