### ISSUE TITLE
Very ugly notice if user has no tickets

### ISSUE THREAD

**Issue by brstgt** [zendesk/zendesk_sdk_ios#16]
See this: http://cl.ly/image/142E0q2f2k2v

Uieeeek - this is really plain!

**Comment by baz8080** [comment]
@brstgt Apologies for the glacial pace of my response. We're aware of the issue and we're hoping to make it look better soon.

**Comment by RonanMcH** [comment]
Hi @brstgt ,
this has been improved to look better as of release 1.5.0.1.

**Comment by RonanMcH** [comment]
This issue has been fixed so I am going to close it off.
Thanks again for bringing to our attention,
Ronan.
