### ISSUE TITLE
Sample iOS App not getting compiled in Xcode 6.4

### ISSUE THREAD

**Issue by rbseraphic** [zendesk/zendesk_sdk_ios#160]
I tried to integrate Zendesk in my app. I have added Security and MobileCoreServices frameworks, but still getting linker errors. I tried running the sample app and it was also not getting compiled. I ran the sample app on Xcode 7.2, it worked.

**Comment by brendan-fahy** [comment]
Hi @rbseraphic,

Can you give us some more detail about the errors you're getting on 6.4? What are the error messages, and so on?

Thanks.

**Comment by baz8080** [comment]
@rbseraphic I'm going to close this one as we haven't heard back from you. Feel free to reopen it if you would like help.
