### ISSUE TITLE
Failure to initialize due to network connection error

### ISSUE THREAD

**Issue by platedbay** [zendesk/zendesk_sdk_ios#162]
Hello,

We've integrated recently with the most recent version of the SDK. Things are working great; however, we're receiving a lot of reports from users where they're unable to access any of our Zendesk content. I looked into our error logs and it looks like the `initializeWithAppId` is failing at an alarming frequency. The `errorBlock` is coming back with the following error:

```
Zendesk: Error Domain=ZDDispatcher Code=1 "(null)" UserInfo={zd_dispatcher_err=Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." 
UserInfo={NSUnderlyingError=0x15d736a80 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "The network connection was lost." UserInfo={NSErrorFailingURLStringKey=https://{ourdomain}.zendesk.com/api/mobile/sdk/settings/{tokenremoved}.json,
NSErrorFailingURLKey=https://{ourdomain}.zendesk.com/api/mobile/sdk/settings/{tokenremoved}.json, _kCFStreamErrorCodeKey=57, _kCFStreamErrorDomainKey=1, NSLocalizedDescription=The network connection was lost.}}, 
NSErrorFailingURLStringKey=https://{ourdomain}.zendesk.com/api/mobile/sdk/settings/{tokenremoved}.json, NSErrorFailingURLKey=https://{ourdomain}.zendesk.com/api/mobile/sdk/settings/{tokenremoved}, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=57, NSLocalizedDescription=The network connection was lost.}}:
```
We don't believe our users are having connectivity issues anywhere else in the application. Is there a known issue with connecting to the mobile API? Would anyone recommend some sort of strategy to attempt to initialize the `ZDKConfig` several times until success? Thanks!

**Comment by tecknut** [comment]
Hey @platedbay, we're going to look into this. 

Are there more logs before these lines? Something which should probably look like:

```
Response code [null]: 0
```

This could end up requiring us to request more logs with more details. The issue might be better served in a ticket with us on support.zendesk.com

**Comment by platedbay** [comment]
Hi @tecknut , we don't have any more logs from the failures. We were merely logging the returned `ZDKAPIError` in the failure block. I haven't been able to create this locally; however, this has happened ~125 times over the past five days amongst 50+ different users.

I just took a look at more of the logs, and I'm also seeing this error:

```
initialized Zendesk: Error Domain=ZDDispatcher Code=3 "The operation couldn’t be completed. (ZDDispatcher error 3.)" UserInfo=0x17047bd80 {zd_dispatcher_err=Error Domain=NSURLErrorDomain Code=-1003 "A server with the specified hostname could not be found." UserInfo=0x1702e2500 {NSUnderlyingError=0x17044be50 "A server with the specified hostname could not be found.", 
```

I don't believe our user's internet connections are failing them this frequently. Thanks.

**Comment by tecknut** [comment]
Could you create a ticket with us on https://support.zendesk.com? 

We may need to look at our systems logs to investigate further, so we'll need some account details. 

Thanks

**Comment by platedbay** [comment]
Done and done @tecknut . Thanks!

**Comment by ndobri** [comment]
@platedbay closing the github issue as it is now tracked within Zendesk support.

**Comment by luky1984** [comment]
closed and tracked within zendesk support? very helpful for others. i have same problem, dont know what the hell what is the problem. simple thing as calling this

[[ZDKConfig instance] initializeWithAppId:@"1e41a096a8cd8e009ea4fa"
    zendeskUrl: @"https://omniwear.zendesk.com"
    clientId: @"mobile_sdk_client_e1c4e6262f1d02f43496"];

then this

    [ZDKRequests presentRequestCreationWithViewController:self];

and it doesnt work.

**Comment by tecknut** [comment]
@luky1984 I removed some details from your last comment. If you think you're having an issue which requires giving us your account details please file a ticket with us at support.zendesk.com
