### ISSUE TITLE
NavigatonBar disappears.

### ISSUE THREAD

**Issue by RanjitKadam** [zendesk/zendesk_sdk_ios#164]
When I add a comment on the request list and click on send, my top navigationBar disappears.
Can i know the completion handler for it. So that i can show my navigationBar again

**Comment by StevenDiviney** [comment]
@RanjitKadam I am unable to replicate this, can you provide a bit more detail? Does it happen every time you send a comment? Do you change the orientation of the device at any stage?

We hide the nav bar in the comments screen when the device is rotated to landscape to provide more space for content. Is this the behavior you are seeing?

**Comment by RanjitKadam** [comment]
@StevenDiviney . I am not rotating the device, in portrait mode only, it happens . my navigationController is a subClass of ENSideMenu'NavigationController.
https://github.com/evnaz/ENSwiftSideMenu/blob/master/README.md

**Comment by RanjitKadam** [comment]
@StevenDiviney  I tried using "ZDKRequests.presentRequestListWithNavController(self)" and now after i comment, the navBar doesnt disappear. But there is another issue, the backbutton color doesnt change to white.

![img_0003](https://cloud.githubusercontent.com/assets/16592090/14201146/97deb140-f80d-11e5-80b7-e92b6a5bff5d.PNG)
![img_0004](https://cloud.githubusercontent.com/assets/16592090/14201148/99a64ed4-f80d-11e5-954e-4b2d2466703c.PNG)

**Comment by oarrabi** [comment]
Hello @RanjitKadam,

To change the color of the back button you need to set the appearance selector `tintColor` of the `UINavigationBar`

```swift
UINavigationBar.appearance().tintColor = UIColor.greenColor()
```

Please let me know if this solves your issue.

**Comment by RanjitKadam** [comment]
hey @oarrabi it works. thanks a lot

**Comment by oarrabi** [comment]
That's great to hear @RanjitKadam :) I will close this now, feel free to contact us for any other query/issue!
