### ISSUE TITLE
Article labels are not available in iOS SDK.

### ISSUE THREAD

**Issue by Voley** [zendesk/zendesk_sdk_ios#165]
We need to use advanced filtering for articles and we wanted to do that using labels. But for some reason ZDKHelpCenterArticle or ZDKHelpCenterFlatArticle do not have properties for labels.

Could you please add that?

**Comment by RonanMcH** [comment]
Hi @Voley ,
we have already added the property `articleLabels` to the `ZDKHelpCenterArticle`. Unfortunately, we have not released with the property added yet.  It will be in our next release which will be in the next few weeks. We will keep this issue open and update you when we have released.
Thanks,
Ronan.

**Comment by StevenDiviney** [comment]
@Voley We have released a new version of the SDK with label names now part of the article model.

**Comment by baz8080** [comment]
@Voley  I'm going to close this issue. You can find our release notes here: https://developer.zendesk.com/embeddables/docs/ios/release_notes
