### ISSUE TITLE
1.5.4.1 get inexplicable requester(Email)

### ISSUE THREAD

**Issue by VincentSit** [zendesk/zendesk_sdk_ios#166]
Today, our operations staff feedback to us with a problem. The email of all new feedback on Zendesk is `elifdesimone@yahoo.com`.

I was very surprised, because Zendesk previous work fine. I did not find this email in our code or db, through debugging and found that we did not pass this email to zendesk server. I do not know where it came from, I guess probably zendesk internal problems.

I suspect that the new version of Zendesk SDK caused this problem, so I downgraded to 1.5.3.1 via CocoaPods,  feedback's email get the correct display.

I'm not sure if this is your problem, but it has been resolved after the downgrade.

P.S.  Zendesk SDK for iOS.

**Comment by RonanMcH** [comment]
Hi @VincentSit ,
This is an issue that is better handled internally and we can check the logs on the server-side to debug this issue. I am gonna open a ticket for you with us so that we can obtain some of your account details confidentially. 
Thanks,
Ronan.

**Comment by VincentSit** [comment]
Hi @RonanMcH ,
Thanks for reply.

Do you need me to provide any information to you?
For example, company's URL.

**Comment by RonanMcH** [comment]
Hi @VincentSit ,
Yes but via the ticket I just created for you with your email address.
Thanks.

**Comment by VincentSit** [comment]
Hi, @RonanMcH ,

Thanks, I have registered success. Where do I provide the information to you?

**Comment by VincentSit** [comment]
[Submit a request](https://support.zendesk.com/hc/en-us/requests/new)?

**Comment by VincentSit** [comment]
Ok, I received your mail.

**Comment by RonanMcH** [comment]
I am going to close this issue, now that we are handling it internally.
