### ISSUE TITLE
Crash on iOS below 8

### ISSUE THREAD

**Issue by atsokolov** [zendesk/zendesk_sdk_ios#167]
Hi! It crashes on iOs below 8 while trying to make a call from unity wrapper:
`[[ZDKConfig instance] addUserAgentHeaderSuffixWithKey:UnityHeaderName value:UnityPluginVersionNumber];`

And there's the error:

> Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFConstantString containsString:]: unrecognized selector sent to instance

Is there anything we could do about it?

**Comment by RonanMcH** [comment]
Hi @atsokolov ,
Thanks for bringing this crash to our attention. We going to release a patch on the plugin to fix this crash very soon. Unfortunately, there is nothing you can do at the moment as the code lives in the Zendesk SDK which is precompiled. I will keep this issue open and update you as soon as the patch has been released.
Thanks again,
Ronan.

**Comment by RonanMcH** [comment]
Hi @atsokolov ,
We did a soft release today so there's no documentation but the ios 8 issue is fixed. [Here](https://zen-marketing-product.s3.amazonaws.com/product/unityplugin1_4_1.zip) is the zip).
Thanks again,
Ronan.

**Comment by atsokolov** [comment]
Hi, thanks! :)

**Comment by RonanMcH** [comment]
I am going to close this issue since it has been resolved. Thanks again.
