### ISSUE TITLE
typo Feeback -> Feedback 

### ISSUE THREAD

**Issue by sspitzer** [zendesk/zendesk_sdk_ios#168]
After submitting feedback, the thank you screen has a typo.

![screen shot 2016-04-06 at 1 06 33 pm](https://cloud.githubusercontent.com/assets/538054/14331041/61c4126e-fbf8-11e5-8bd5-23e23810a2c7.png)

**Comment by sspitzer** [comment]
this is ios.RMA.request.success.title

**Comment by baz8080** [comment]
@sspitzer Thanks for letting us know. We'll get this fixed.

**Comment by StevenDiviney** [comment]
@sspitzer Again, thanks for bringing this to our attention. We have released a new version of the SDK with the correct spelling.

**Comment by baz8080** [comment]
@sspitzer I'm going to close this issue. Thanks for letting us know about it. You can find our release notes here: https://developer.zendesk.com/embeddables/docs/ios/release_notes
