### ISSUE TITLE
Bugs in "My tickets"

### ISSUE THREAD

**Issue by brstgt** [zendesk/zendesk_sdk_ios#17]
1. If i add a new ticket from within "My tickets" the view does not update. It still shows "No tickets blabla"
2. Tickets in "My tickets" cannot be opened. Tap on ticket does just nothing.

**Comment by grabbou** [comment]
I can confirm this bug still happens.

**Comment by BPlano** [comment]
Hey @brstgt (and @grabbou) -

If you are still experiencing this issue, I recommend first updating to the latest version of our SDK (1.1.0.1), and then - if the issue still persists - please send a ticket to support@zendesk.com. 

Happy to help if we can!

**Comment by tecknut** [comment]
The current version refreshes itself now.
