### ISSUE TITLE
Add additional information that is not visible to the user.

### ISSUE THREAD

**Issue by VincentSit** [zendesk/zendesk_sdk_ios#170]
Hi, I want to add some additional information to the ticket such as memory usage, disk space to help us help users solve problems faster.

Because the information is not meaningful to the user, we do not want visible to the user.

What should I do?

**Comment by RonanMcH** [comment]
Hi @VincentSit ,
There are many different ways to attach additional information to a ticket. This article [here](https://developer.zendesk.com/blog/adding-metadata-to-tickets-created-by-the-mobile-sdk) details how to add additional information to a ticket. `ZDKCustomFields` could be a good way to send additional info without the end-user seeing it. They are detailed in the article.
Let us know if you need anymore help,
Ronan.

**Comment by VincentSit** [comment]
Thank you, I did not notice that ZDKCustomFields also need to be configured in the control panel in our web site. I will  try later.

**Comment by VincentSit** [comment]
Hi @RonanMcH , I have create a custom ticket field and get it's ID, but where can I find the data I submit through the `ZDKCustomField`? I can not find it in my control panel.

![qq20160420-0](https://cloud.githubusercontent.com/assets/4084679/14662175/427f6ee6-06e6-11e6-813c-652ea6d6a9d2.png)


The following is my code:   

```
ZDKAnonymousIdentity *identity = [ZDKAnonymousIdentity new];
  identity.name = self.name;
  identity.email = self.name;
  identity.externalId = [IBLUser currentUser].identifier;
  
  [ZDKConfig instance].userIdentity = identity;
  [ZDKConfig instance].customTicketFields = @[[[ZDKCustomField alloc] initWithFieldId:@31910347 andValue:description]
                                              ];
  
  ZDKCreateRequest *request = [ZDKCreateRequest new];
  request.subject = self.subject;
  request.requestDescription = self.message;
  request.tags = @[@"xxx", @"xxx"];
  
  ZDKRequestProvider *provider = [ZDKRequestProvider new];
  [provider createRequest:request withCallback:^(id result, NSError *error) {
    sender.enabled = YES;
    
    if (error) {
      [SVProgressHUD showErrorWithStatus:[error localizedDescription]];
    }
    else {
      [SVProgressHUD showSuccessWithStatus:IBLLocalizedString(@"IBLSupportAndFeedbackViewController.hud.submitSuccess")];
    }
  }];
```

**Comment by RonanMcH** [comment]
Hi @VincentSit ,
![screen shot 2016-04-20 at 13 30 53](https://cloud.githubusercontent.com/assets/12997923/14674511/42a59c9a-06fc-11e6-84bf-3711832263d1.png)
The custom fields appear in the left handside tool They're called "Custom Ticket Testing" and "Promo Code" here in this instance. Can you see them? They should be configured from the admin tab on the Zendesk dashboard! They should be set to visible.
Hope this helps,
Ronan.

**Comment by VincentSit** [comment]
Hi @RonanMcH , sorry, I still can't find it, is there anything wrong with my configuration?

![qq20160421-0](https://cloud.githubusercontent.com/assets/4084679/14707818/4084eea4-07f9-11e6-9aa1-706e2a47777a.png)
![qq20160421-1](https://cloud.githubusercontent.com/assets/4084679/14707819/40b4b1b6-07f9-11e6-83e2-941b1a148f7a.png)

**Comment by oarrabi** [comment]
Hello @VincentSit 

The second screenshot shows that the DeviceInformation is not Visible nor Editable.
Make sure to make the field visible and editable

The settings should look like this:
<img width="933" alt="screen shot 2016-04-26 at 15 42 46" src="https://cloud.githubusercontent.com/assets/1461052/14822208/a99815cc-0bc5-11e6-9fba-32bebe2ba1e2.png">

After updating the ticket, the DeviceInformation row should havev "editable*" on it. Similar to Subject row in your screenshot.

Thanks.

**Comment by VincentSit** [comment]
@oarrabi Thank you.
