### ISSUE TITLE
Unable to create request

### ISSUE THREAD

**Issue by pradeepb28** [zendesk/zendesk_sdk_ios#172]
```
let identity = ZDKAnonymousIdentity()             
  identity.email =  "xxx"
  identity.name = "xxx"
  ZDKConfig.instance().userIdentity = identity
let request = ZDKCreateRequest()
         request.subject = "xxxx"       
        let provider = ZDKRequestProvider()        
        provider.createRequest(request) { (req: AnyObject?, error:NSError?) in            
            if error != nil {
                print(error.debugDescription)
            }            
        }
```

result: not showing up on the portal

**Comment by RonanMcH** [comment]
Hi @pradeepb28 ,
If you are creating a request using the provider API, the request's property `requestDiscription` must not be `nil`. I will make a story to include this information in our docs.
I tested your code and including this code snippet should make it work:
```
request.requestDescription = "This is a test"
```
Thanks,
Ronan.

**Comment by pradeepb28** [comment]
Thank you so much but I am facing another issue while after adding the above line, now I am able to submit request but it's showing up duplicate requests on the portal.

**Comment by StevenDiviney** [comment]
@pradeepb28 Where in your code are you creating the request? It sounds like it's getting called multiple times.

**Comment by tecknut** [comment]
Hey @pradeepb28 are you still having an the same issue?

**Comment by pradeepb28** [comment]
No

Get Outlook for iOS




On Tue, May 24, 2016 at 7:43 AM -0700, "Alan Egan" <notifications@github.com> wrote:












Hey @pradeepb28 are you still having an the same issue?

**Comment by tecknut** [comment]
Ok, I'm going to close this. 

Get in touch if you have any more issues.
