### ISSUE TITLE
RateMyApp dialog hides navigationBar

### ISSUE THREAD

**Issue by RanjitKadam** [zendesk/zendesk_sdk_ios#176]
I am using Rate my app dialog. I am using this code to show the dialog

 ZDKRMA.configure { _, config in
            config.dialogActions =
                [ZDKRMAAction.RateApp.rawValue,
                    ZDKRMAAction.SendFeedback.rawValue,
                    ZDKRMAAction.DontAskAgain.rawValue]
        }

ZDKRMA.showAlwaysInView(self.view)

Now the dialog is show, and when I click on send feedback, keyboard appears and my navigation bar disappears. So I want to know what is going wrong. Secondly I want to know whether there is a completion handler which can be accessed when the feed back is sent, where i can unhide my naivigationbar.

**Comment by StevenDiviney** [comment]
@RanjitKadam I am unable to replicate this. Can you give some more information please? Are you seeing this on specific iOS versions or platforms?

RMA doesn't modify the nav bar as far as I can see. It tries to find the top most view controller and present using it. Can you provide some information about your view hierarchy? We do try and work out what the top most controller is and present as appropriate. (Example, if it's a nav controller we use visibleViewController, for tab bar controller we use selectedViewController)

Unfortunately we do not surface a completion handler for RMA feedback.

**Comment by tecknut** [comment]
@RanjitKadam Just to give you an update on this. 

We still can't replicate this. 

As @StevenDiviney said there is no completion handler. However there is an `NSNotification` you can observe for [dismissal](https://github.com/zendesk/zendesk_sdk_ios/blob/master/ZendeskProviderSDK.framework/Headers/ZendeskSDKConstants.h#L551), [successes](https://github.com/zendesk/zendesk_sdk_ios/blob/master/ZendeskProviderSDK.framework/Headers/ZendeskSDKConstants.h#L557) and [errors](https://github.com/zendesk/zendesk_sdk_ios/blob/master/ZendeskProviderSDK.framework/Headers/ZendeskSDKConstants.h#L560).

Hopefully these help you work around the issue. 

Let us know if this works for you !

**Comment by ndobri** [comment]
Hi @RanjitKadam, 

I am tentatively going to close this issue due to inactivity. If you still need help around it feel free to reopen it.
