### ISSUE TITLE
Missing localisation 

### ISSUE THREAD

**Issue by fwal** [zendesk/zendesk_sdk_ios#177]
The SDK is missing localisation for the key `ios.ZDKRequests.leftBarButton.title_cancel_` for several languages, including swedish.

This string serves as the close/cancel button for the default request list created with `ZDKRequests.presentRequestListWithViewController` and will instead display the key all over the screen.

**Comment by RonanMcH** [comment]
Hi @fwal ,
this issue has been fixed in release 1.6.1.1. 
Thanks for bringing it to our attention,
Ronan.
