### ISSUE TITLE
Missing enumeration values in ZDKUIUtil.h

### ISSUE THREAD

**Issue by ibsh** [zendesk/zendesk_sdk_ios#179]
ZDKUIOriginInWindow lacks explicit cases for UIInterfaceOrientationUnknown, UIInterfaceOrientationPortrait.
This causes an error in our build process at Scribd.

**Comment by RonanMcH** [comment]
Hi @ibsh ,
what is the error you are experiencing in your build process? Could you please send us the build logs containing the error?
Thanks,
Ronan.

**Comment by ibsh** [comment]
We have -Wswitch-enum enabled.
.../ZendeskSDK.framework/Headers/ZDKUIUtil.h:265:13: error: enumeration values 'UIInterfaceOrientationUnknown' and 'UIInterfaceOrientationPortrait' not explicitly handled in switch [-Werror,-Wswitch-enum]

**Comment by baz8080** [comment]
Thanks for the clarification @ibsh. We're going to discuss your issue with the team this morning.

**Comment by RonanMcH** [comment]
This was handled internally and has been fixed.
