### ISSUE TITLE
Number of layout bugs

### ISSUE THREAD

**Issue by rroy1590** [zendesk/zendesk_sdk_ios#18]
ZDKEndUserCommentTableCell - when presented modally as a formsheet, the comments cell text is cut off.
![image](http://i.imgur.com/CtUAxFp.png)

ZDKCommentEntryView - does not respect the bottom layout guide, and renders behind/underneath a tabbar.
![image](http://i.imgur.com/61bSMU0.png)

and when presented modally, the whole request comments table layout is completely off. note how the table extends much farther below the content. and the comments button is again drawn at the bottom off screen.
![image](http://i.imgur.com/AI0D4XG.png)

seems to be a number of problems when the different table views are presented as formsheets, this is the help center, both the table cells and the final article page have incorrect sizing larger than the formsheet size.
![image](http://i.imgur.com/8EIthV5.png)

I believe the root issue is that layouts/constraints are getting set in `viewDidLoad` instead of `viewDidLayoutSubviews` and so there is a mismatch of original view sizing and the final presented sizing depending on modality.

**Comment by BPlano** [comment]
@rroy1590 - We just released version 1.1.0.1 of our SDK, which should fix these issues. Could you update to the latest version and get back to me if you're still having trouble? Thanks!

**Comment by rroy1590** [comment]
@BPlano none of these seem to be fixed.

![screen shot 2015-03-04 at 5 09 30 pm](https://cloud.githubusercontent.com/assets/906694/6497198/4502804e-c291-11e4-9df8-ffedefba4b1d.png)

![screen shot 2015-03-04 at 5 09 17 pm](https://cloud.githubusercontent.com/assets/906694/6497200/4d8135c6-c291-11e4-867f-ba7e34aaa5b1.png)

![screen shot 2015-03-04 at 5 08 23 pm](https://cloud.githubusercontent.com/assets/906694/6497201/54ca3dfa-c291-11e4-8714-3dfd60f23e8e.png)
![screen shot 2015-03-04 at 5 08 16 pm](https://cloud.githubusercontent.com/assets/906694/6497204/5af1bd8e-c291-11e4-924f-9c7f0b3d2a82.png)

**Comment by rroy1590** [comment]
@BPlano so I updated to 1.0.0.1 and none of the ^ ui bugs were fixed:

![screen shot 2015-03-04 at 5 09 30 pm](https://cloud.githubusercontent.com/assets/906694/6497198/4502804e-c291-11e4-9df8-ffedefba4b1d.png)

![screen shot 2015-03-04 at 5 09 17 pm](https://cloud.githubusercontent.com/assets/906694/6497200/4d8135c6-c291-11e4-867f-ba7e34aaa5b1.png)

![screen shot 2015-03-04 at 5 08 23 pm](https://cloud.githubusercontent.com/assets/906694/6497201/54ca3dfa-c291-11e4-8714-3dfd60f23e8e.png)
![screen shot 2015-03-04 at 5 08 16 pm](https://cloud.githubusercontent.com/assets/906694/6497204/5af1bd8e-c291-11e4-924f-9c7f0b3d2a82.png)

I then updated to 1.1.1.1 and... nothing seems to work at all.

I cannot launch the help center at all and get these errors:
![screen shot 2015-03-04 at 5 16 39 pm](https://cloud.githubusercontent.com/assets/906694/6497274/446820f2-c292-11e4-8899-c3d6eaab74f3.png)
![screen shot 2015-03-04 at 5 16 27 pm](https://cloud.githubusercontent.com/assets/906694/6497273/4467f79e-c292-11e4-90d7-cc8082c7023f.png)

further, the my tickets view shows nothing ever:
![zendesk](https://cloud.githubusercontent.com/assets/906694/6497301/83b6ccc2-c292-11e4-8a3b-b9b2b3b28137.gif)
![screen shot 2015-03-04 at 5 18 56 pm](https://cloud.githubusercontent.com/assets/906694/6497305/957f4eac-c292-11e4-89c3-50dc507e729b.png)

**Comment by BPlano** [comment]
Hey @rroy1590 -

I think the best step we can take now is to get you in touch with our Developers - would you mind sending a ticket (via email or support.zendesk.com) into support@zendesk.com and mention me (Bryant Plano) in the ticket?

When you submit the ticket, could you in include the following info:
- Confirm that you're using 1.1.0.1 (or 1.1.1.1)
- Specify the method by which you're installing the SDK (Pods or framework)
- Logs to go with your screenshots & code snippets

Much appreciated - thanks!

:: BP
