### ISSUE TITLE
ZDKRMA dialog blocks Xcode UI Inspector

### ISSUE THREAD

**Issue by INRIX-Patrick-Winchell** [zendesk/zendesk_sdk_ios#181]
Xcode 7.3.1
iOS 9.3
SDK 1.6.1.1

REPRO STEPS:
1. Activate ZDKRMA with showAlwaysInView: .
2. Activate the Xcode UI Inspector/debugger. Menu -> Debug -> View Debugging -> Capture View Hierarchy

EXPECTED RESULT:
UI Inspector loads.

ACTUAL RESULT:
UI Inspector shows a completely blank screen. Debug console shows the message "**\* Assertion failure in -[ZDKUITextView _firstBaselineOffsetFromTop], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3512.60.7/UITextView.m:1683"

**Comment by RonanMcH** [comment]
Hi @INRIX-Patrick-Winchell ,
I have been able to reproduce this. Apparently, it may be caused by UIKit's UITextView which ZDKUITextView inherits from, has assertions if not used with auto layout but I will continue to try get to the root of it. 
Thanks,
Ronan

**Comment by RonanMcH** [comment]
Hi @INRIX-Patrick-Winchell ,
We deprecated the RMA feature in the SDK and it will be removed in the next release. We have built an open source alternative, available [here](https://github.com/zendesk/rate_my_app_ios) that works in conjunction with the SDK. 
Thanks,
Ronan.
