### ISSUE TITLE
Is it possible to limit ZDKSupportViewController to particular sectionId?

### ISSUE THREAD

**Issue by nikita-leonov** [zendesk/zendesk_sdk_ios#182]
I am currently building ZDKSupportViewController in code, and embed it into my view hierarchy. It works well, except it starting from categories list, while I want to limit the scope of search after presentation to particular section. ZDKHelpCenterSearch search property is not initialized right after init, also if I provide ZDKHelpCenterSearch created manually right after initialization with all section & category ids that I am interested in, it is disregarded. I have an assumption that it is actually set-over again. Any recommendations how to limit ZDKSupportViewController to a particular sectionId without using ZDKHelpCenter presentation methods?

**Comment by tecknut** [comment]
@nikita-leonov What exactly are you trying to achieve? What aspects are you trying to limit, browsing and searching?

Are you looking to have `ZDKSupportViewController` start with a list of Sections, not Categories?

**Comment by nikita-leonov** [comment]
Actually to start with list of articles but not categories.

**Comment by tecknut** [comment]
This should work for you then. You'll need to edit certain bits to obviously 😄 

Let us know if this works out for you.

```
    ZDKHelpCenterSection *section = [[ZDKHelpCenterSection alloc] init];
    section.sid = <the-section-id-you-want-to-use>;
    
    ZDKSupportViewController *support = [[ZDKSupportViewController alloc] initWithSection:section];
    support.title = sectionName;
    support.delegate = // Set this if you want to control how the contact nav bar button looks, see ZDKHelpCenterConversationsUIDelegate

    ZDKHelpCenterSearch *search = [[ZDKHelpCenterSearch alloc] init];
    search.sectionId = @(<the-section-id-you-want-to-use>);

    support.search = search;

    [navController pushViewController:support animated:YES];
```

**Comment by nikita-leonov** [comment]
Thanks, I will try it! Looks like it should work :)

**Comment by nikita-leonov** [comment]
I tried your suggestion, everything works fine. Thanks.

**Comment by tecknut** [comment]
Good to hear, thanks for confirming.
