### ISSUE TITLE
JWT fails when ios app killed and relaunched, unable to fetch tickets, comments and create tickets

### ISSUE THREAD

**Issue by basawarajh-cuelogic** [zendesk/zendesk_sdk_ios#184]
We are working on ios app using zendesk ios sdk, using request, provider classes for creating and fetching tickets and comments. Authentication mode is JWT. When ever we kill app or when ever we logout user from app and relogin with JWT authentication then it fails and we are unable to retrive tickets and comments. If we try after 5 minutes then we get login sucess. Please let me know the issue ASAP and how can we fix this issue. Any help will be appreciated. 

This is very urgent, have to upload app to appstore.

**Comment by brendan-fahy** [comment]
Hi @basawarajh-cuelogic,

As we're already in discussion about this on the Zendesk support ticket you opened with us, I'm going to close this issue so we can keep the communication on one channel. Thanks.
