### ISSUE TITLE
error from cocoapods pod install 

### ISSUE THREAD

**Issue by charliepixegon** [zendesk/zendesk_sdk_ios#192]
Hello, 

After including ZendeskSDK as a dependency in our pod we get the following error. 

To reproduce create a new lib with (Swift, create example app options)

: pod lib create

then in your podspec file add: 

s.dependency 'ZendeskSDK'

goto the Example app created with your lib and run pod install

[charlie@charliembp2015 Example]$ pod install
Analyzing dependencies
Fetching podspec for `DigitalBibleToolkit` from `~/Documents/Libraries/DigitalBibleToolkit`
Fetching podspec for `PartnerBibleCore` from `../`
Fetching podspec for `PartnerUserServices` from `~/Documents/Libraries/PartnerUserServices`
Downloading dependencies
Using Alamofire (3.4.0)
Using DigitalBibleToolkit (0.2.0)
Using KAProgressLabel (3.3.0)
Using Kingfisher (2.4.1)
Using MBProgressHUD (0.9.2)
Installing PartnerBibleCore 0.1.0 (was 0.1.0)
Using PartnerUserServices (0.1.0)
Using Realm (1.0.0)
Using RealmSwift (1.0.0)
Installing ZendeskSDK (1.6.2.1)

# **[!] The 'Pods-PartnerBibleCore_Example' target has transitive dependencies that include static binaries: (/Users/charlie/Documents/Libraries/PartnerBibleCore/Example/Pods/ZendeskSDK/ZendeskProviderSDK.framework and /Users/charlie/Documents/Libraries/PartnerBibleCore/Example/Pods/ZendeskSDK/ZendeskSDK.framework)
[charlie@charliembp2015 Example]$**

**Comment by charliepixegon** [comment]
just a note, I also tried adding the following to our pod spec: 

s.frameworks = 'MobileCoreServices', 'SystemConfiguration', 'Security', 'MessageUI'

and got the same error.

**Comment by StevenDiviney** [comment]
@charliepixegon this is an issue with cocoapods. The SDK is currently only offered as a static library. Cocoapods does not support mixing dynamic and static libraries, more information can be found [on the cocoapods repo](https://github.com/CocoaPods/CocoaPods/issues/3839).

We plan on releasing the SDK as a dynamic library but I am unable to say when. It won't be in the near future.

**Comment by mathewcropper** [comment]
Hi there. I'm reviewing our open issues, and as this is expected based on how Cocoapods works and given that we are only offering static libraries at the moment, I'll close the thread.
