### ISSUE TITLE
ZendeskSDK.h uses wrong flag for importing the ZendeskProviderSDK

### ISSUE THREAD

**Issue by HSchultjan** [zendesk/zendesk_sdk_ios#198]
The flag MODULES_DISABLED is not a valid clang flag.
The proper flag to check would be CLANG_ENABLE_MODULES.
But all #import and #include directives are mapped to use @import automatically, so there is no need to check this flag.

**Comment by tecknut** [comment]
Hi @HSchultjan (this flag)[https://github.com/zendesk/zendesk_sdk_ios/blob/master/ZendeskSDK.framework/Headers/ZendeskSDK.h#L78] is our own flag which we use internally during development. It is not intended to be `CLANG_ENABLE_MODULES`.

Thanks

**Comment by HSchultjan** [comment]
Then the header will cause a compile error when CLANG_ENABLE_MODULES is disabled. You should fix that.

**Comment by tecknut** [comment]
if you have `CLANG_ENABLE_MODULES` set to `NO` you should define `MODULES_DISABLED` in `Preprocessor Macros` in your Xcode build settings and set it to `1`.

**Comment by HSchultjan** [comment]
Why should i have to do that?

**Comment by tecknut** [comment]
`CLANG_ENABLE_MODULES` set to `YES` is required for our frameworks reference each other with `@import` when being used in apps using swift. We need to support this.

`CLANG_ENABLE_MODULES` defaults to `YES` in all new projects for some time now. This being the default, we have set up the imports in this way so as to support the majority of those integrating the SDK. 

In the case that `CLANG_ENABLE_MODULES` is required to be set to `NO`, we have the preprocessor macro to facilitate this.

**Comment by HSchultjan** [comment]
I know why you use this preprocessor macro, but why should i be forced to do this as well?
There is no technical requirement for me to create the macro. If you only use this macro for internal development it should not be in the header anyways.

**Comment by tecknut** [comment]
I understand where you’re coming from. 

We use this internally to test with apps which have `CLANG_ENABLED_MODULES` set to `NO`, something which is non standard, but supported through this macro. 

Without the `@import`, swift apps integrating our SDK cannot compile. We feel that it's important to support as many use cases as we can, and in doing this we need to make choices like this. In this case we decided that the default case,  `CLANG_ENABLED_MODULES` set to `YES`,  should require no extra configuration in order work out of the box and a small amount of configuration is required for the less common case. 

Unfortunately, for the reasons above, this isn’t something we’re looking to change. We appreciate the feedback, though. Please do continue to share your thoughts with us.
