### ISSUE TITLE
Attachment image overlaps text view while user enters text.

### ISSUE THREAD

**Issue by nikita-leonov** [zendesk/zendesk_sdk_ios#199]
For a ZDKCreateRequestViewController if user enters text and does not press return during entry attachment position is not adjusted and overlaps text view.
![img_0247](https://cloud.githubusercontent.com/assets/991541/16603152/ce815ae8-42ce-11e6-9249-48a37da4ebce.PNG)

**Comment by ndobri** [comment]
@nikita-leonov tracking both issues under #200 issue as it will likely be fixed at the same time.
