### ISSUE TITLE
When no results found in FAQ, Contact Support button does not work

### ISSUE THREAD

**Issue by grabbou** [zendesk/zendesk_sdk_ios#20]
As above.

**Comment by BPlano** [comment]
@grabbou -

Would you mind sending in a ticket to Zendesk Support on this one? Would like to look into it further if possible.

Sorry for the delay in getting back to you.

**Comment by grabbou** [comment]
Hey, I moved to something else for now so I can't help you with this issue this time :(

**Comment by BPlano** [comment]
No worries :) Thanks for responding anyway!

**Comment by dsica** [comment]
I still see this in the latest version, 1.3.0.1.  Is there a workaround or reason this was closed?

**Comment by pierrezen** [comment]
@dsica , 

When using the Sample Application that comes with the SDK (with the latest 1.3.0.1), the contact button is presenting the Contact screen. If you are still facing that issue with the control within your application, can you create a ticket to Zendesk Support and we will be happy to help ...

**Comment by dsica** [comment]
Thanks, it's not working for me with the latest SDK.  I have created a ticket, https://support.zendesk.com/hc/en-us/requests/1133943
