### ISSUE TITLE
Attachment image overlaps text view after user attached an image.

### ISSUE THREAD

**Issue by nikita-leonov** [zendesk/zendesk_sdk_ios#200]
For a ZDKCreateRequestViewController if user entered a big portion of text and attaches an image afterward attachment will overlap an entered text, so only small portion of text will be visible, more over user will not be able to scroll entered text content to see it fully.

![img_0247](https://cloud.githubusercontent.com/assets/991541/16603191/1082654a-42cf-11e6-9593-0a9a9043f7b0.PNG)

**Comment by ndobri** [comment]
@nikita-leonov, 

Thanks for pointing this out to us. I've added it as an issue internally so we can track the progress. This github issue will be updated once the fix is released.

**Comment by tecknut** [comment]
Hi @nikita-leonov we've just released version 2 of the SDK. We've reworked the request creation UI and commenting UI.  

This issue is no longer present in the SDK.

Thanks,
Alan
