### ISSUE TITLE
Set scrollEnabled = YES on ZDKUITextView in ZDKRequestViewController

### ISSUE THREAD

**Issue by mindgraffiti** [zendesk/zendesk_sdk_ios#201]
1. Set up and present a ZDKCreateRequestViewController with the attachment button.

```
ZDKCreateRequestViewController *requestListVC = [ZDKCreateRequestViewController new];
UINavigationController *navController = [[UINavigationController alloc] initWithRootViewController:requestListVC];
    
[self.parentViewController presentViewController:navController animated:YES completion:nil];
```

2. Launch the simulator (iPh6 9.3)
3. Type 2-3 paragraphs of text, until the text extends past the attachment button.

*Actual Result*
A white toolbar with the attach button blocks the view and the UITextView has scrolling disabled.

*Expected Result*
The UITextView scrolls so the user can see the rest of the text they are typing.

**Comment by StevenDiviney** [comment]
@mindgraffiti I am unable to replicate this. Is your project using any other frameworks that might be modifying the the behaviour of UITextView? A quick way to check is integrate the Zendesk SDK into a new project.

Also why are you presenting the request view controller in this way? Our API provides `[ZDKRequests presentRequestCreationWithViewController:<UIViewController>];`. Do you have a requirement that this does not meet?

**Comment by mindgraffiti** [comment]
@StevenDiviney thanks for looking at this. I have used: `[ZDKRequests presentRequestCreationWithViewController:<UIViewController>];` previously and thought they were interchangeable. Both result in the UITextView with scrolling disabled.

I'll create a sample app and see if it reproduces there. If not, I'll return and close this issue.
