### ISSUE TITLE
ZDKCommentsViewController missing?

### ISSUE THREAD

**Issue by ted-ah** [zendesk/zendesk_sdk_ios#204]
I'm interested in displaying an individual request within an application.

Under the **Individual View Request component** section at the following link (https://developer.zendesk.com/embeddables/docs/ios/advancedtopics#adding-ui-components), it references the `ZDKCommentsViewController` class.

This class seems to have been removed after v1.5.4.1 of the SDK. Was this intentional? Is there another way to perform the task with the latest SDK?

**Comment by ndobri** [comment]
@ted-ah thank you for pointing this out. It will be added back in our next release that is coming out soon. We will update this issue to let you know once the release is out.

**Comment by RonanMcH** [comment]
hi @ted-ah ,
We made the `ZDKCommentsViewController` public again in our latest release of the Support SDK (1.7.0.1) which is available from the repo. 
Thanks again for bringing it to our attention,
Ronan.
