### ISSUE TITLE
Rate My App option not working

### ISSUE THREAD

**Issue by pguptamedocity** [zendesk/zendesk_sdk_ios#205]
I have configured RMA and provided this link https://itunes.apple.com/us/app/icancerhealth-cancer-care/id723088265?mt=8 in my iOS app link field. When I tried to use your's Rate our app option using iOS sdk it redirects to app store with an error i.e "Your request produced an error.[newNullResponse]."
Please find the attached screen for reference.
Please look into this asap, eagerly waiting for your response.

![img_0188](https://cloud.githubusercontent.com/assets/20553767/16979668/ed61c184-4e7f-11e6-9b7a-6014e93427ca.PNG)

**Comment by brendan-fahy** [comment]
Hi @pguptamedocity,

Note than in [our documentation](https://developer.zendesk.com/embeddables/docs/ios/rate_my_app), we state:

```
...be sure to enter the shorter version of the Apple App Store URL. Example: 
https://itunes.apple.com/ie/app/id368796007 not 
https://itunes.apple.com/ie/app/zendesk/id368796007?mt=8.
```

It looks like you're using RMA with the longer form of the App Store URL. Can you try with the shorter version?

**Comment by pguptamedocity** [comment]
Hi Brendan 

I tried that shorter url and found not working but actually it was a copy paste error. Now I manually write that shorter url then it worked perfectly.

Thanks 
Superman Brendan
