### ISSUE TITLE
Show a Single Help Center Article

### ISSUE THREAD

**Issue by andrewljohnson** [zendesk/zendesk_sdk_ios#206]
I'd like to show a single Help Center article in my iOS app, when a user clicks a certain button.

I couldn't find a way to do this in the docs.

Is it possible to do so? Is it documented if so? or is this a feature request?

**Comment by StevenDiviney** [comment]
@andrewljohnson Yes this can be done. First you have to fetch the article using `- (void) getArticleById:withCallback:;` in `ZDKHelpCenterProvider` and then display it using `[[ZDKArticleViewController alloc] initWithArticle:]

**Comment by andrewljohnson** [comment]
Thanks!

When I Google that, it doesn't seem documented, maybe worth adding something... not sure how I would discover it without knowing the classname.
