### ISSUE TITLE
ZDKHelpCenterProvider initWithLocale confusion

### ISSUE THREAD

**Issue by Voley** [zendesk/zendesk_sdk_ios#209]
It takes locale parameter, that is nsstring. But there are no variants anywhere of what it can take.
It warns if I use [NSLocale currentLocale].

What should be used in that field?

**Comment by baz8080** [comment]
Hi @Voley The locale is an NSString and will match what locale you want to retrieve in Help Center. `@"en-us"` is an example. We'll update the docs to make this clearer.

**Comment by baz8080** [comment]
@Voley I'm going to close this issue. Please feel free to reopen if you need to.
