### ISSUE TITLE
ZDKHelpCenterCategoryViewModel object not exposed 

### ISSUE THREAD

**Issue by jaz-ah** [zendesk/zendesk_sdk_ios#211]
I am trying to call the new method on ZDKHelpCenterProvider : getHelpCenterOverviewWithHelpCenterOverviewModel -- it returns an array of ZDKHelpCenterCategoryViewModel - but this object isn't declared anywhere for me to use in code... could you expose this along with ZDKHelpCenterSectionViewModel and ZDKHelpCenterArticleViewModel?  or do I have to go through the other methods on ZDKHelpCenterProvider of:
getCategoriesWithCallback, getSectionsForCategoryId, etc...

**Comment by baz8080** [comment]
Hi @jaz-ah. You are correct in that you have to use the other methods like `getCategoriesWithCallback`.

The new HelpCenterOverview models, and ancillary code are intended to be private. You can post a feature request in our [SDK forum](https://support.zendesk.com/hc/en-us/community/topics/200488257-Zendesk-SDKs) if you wish.
