### ISSUE TITLE
confusion with ZDKHelpCenterCategoriesDataSource

### ISSUE THREAD

**Issue by jaz-ah** [zendesk/zendesk_sdk_ios#212]
I was trying to use this class as the datasource to a new table view I created, but I'm not sure exactly what the right usage pattern is - am I supposed to call reloadData() on it?  how does the tableView know to reload itself when the data comes in?

**Comment by baz8080** [comment]
Hi @jaz-ah. 
ZDKHelpCenterCategoriesDataSource is intended to be private. You can post a feature request in our [SDK forum](https://support.zendesk.com/hc/en-us/community/topics/200488257-Zendesk-SDKs) if you wish.
