### ISSUE TITLE
Theme not applying to Ticket Creation

### ISSUE THREAD

**Issue by timbroder** [zendesk/zendesk_sdk_ios#218]
I've set up Zendesk like this:

```swift
        ZDKConfig.instance()
            .initializeWithAppId(
                "########",
                zendeskUrl: "#####",
                clientId: "#######")
        let identity = ZDKAnonymousIdentity()
        ZDKConfig.instance().userIdentity = identity
```

Then styled:

```swift
        let theme = ZDKTheme.baseTheme()
        
        theme.primaryTextColor = UIColor.kidPrimaryColor()
        theme.secondaryTextColor = UIColor.kidSecondaryRedColor()
        theme.primaryBackgroundColor = UIColor.kidWhiteColor()
        theme.secondaryBackgroundColor = UIColor.kidLightGrayColor()
        theme.emptyBackgroundColor = UIColor.whiteColor()
        theme.separatorColor = UIColor.grayColor()
        
        theme.fontName = "Sofia Pro Light"
        theme.boldFontName = "Sofia Pro Regular"
        
        theme.apply()
```

Then called:

```swift
ZDKRequests.presentRequestCreationWithViewController(self)
```

But, I still see the stock UI:

![image](https://cloud.githubusercontent.com/assets/121503/18034383/2a87744e-6d09-11e6-884c-15a828a3e027.png)

**Comment by RonanMcH** [comment]
Hi @timbroder ,
The code you using is correct for applying style to the SDK. The problem is that you aren't using the correct styling properties on the `ZDKTheme`.  The `metaTextColor` will style the text placeholder in the text view and the `inputTextColor` property will style the text inputted into the text view.  
The background of the text view is styled using `primaryBackgroundColor`, so I believe that is the color you set in your code. 
Hope this helps,
Ronan.

**Comment by timbroder** [comment]
Thanks @RonanMcH 

Do I have access to modify the colors of these?

![image](https://cloud.githubusercontent.com/assets/121503/18099979/07096f04-6eb7-11e6-9035-f2357bedb065.png)

**Comment by RonanMcH** [comment]
Hi @timbroder ,
You can modify the color of the navigation bar title and buttons using the global appearance selectors for these objects.  The code looks like this:
```
[UIBarButtonItem appearance].tintColor = [UIColor redColor];
[UINavigationBar appearance].titleTextAttributes = @{NSForegroundColorAttributeName:[UIColor yellowColor]};
```
Hope this helps,
Ronan.

**Comment by tecknut** [comment]
@timbroder Just following up on this issue. Have you been able to style your integration?

**Comment by RonanMcH** [comment]
Hi @timbroder ,
Since we haven't heard back from you, I am going to close this issue. Feel free to reopen it if your issue hasn't been resolved.
Thanks,
Ronan.

**Comment by timbroder** [comment]
Thank you @RonanMcH 

I'm all set! Apologies for the delay
