### ISSUE TITLE
Failed to update SDK settings: The operation couldn’t be completed. (ZDDispatcher error 4.)

### ISSUE THREAD

**Issue by luky1984** [zendesk/zendesk_sdk_ios#220]
I am using this code (with my own appId and zendeskUrl and client)

[[ZDKConfig instance] initializeWithAppId:@"xxxx"
zendeskUrl: @"xxxx"
clientId: @"xxxx"];

[ZDKRequests presentRequestCreationWithViewController:self];

expecting it could work, but in the contact form i see black field with text "there was an error, pleas try again"

and in xcode console:

[DEBUG]: No SDK configuration file found in local storage, sending request to fetch configuration file.
[DEBUG]: Reachability Flag Status: -R ------- networkStatusForFlags
[DEBUG]: Dispatcher failed to validate account : Zendesk URL => (null), OAuthClientId => (null)
[ERROR]: Failed to update SDK settings: The operation couldn’t be completed. (ZDDispatcher error 4.)

**Comment by tecknut** [comment]
@luky1984 please open a ticket with us at support.zendesk.com
