### ISSUE TITLE
Deprecated designated initializer = cannot subclass

### ISSUE THREAD

**Issue by MaximusMcCann** [zendesk/zendesk_sdk_ios#221]
I see `init!(success: ZDKCreateRequestSuccess!, andError error: ZDKCreateRequestError!)` is deprecated.  Fair enough, however it is, apparently, still the designated initializer.

trying to subclass `ZDKCreateRequestViewController` and override `init()` yields:

![image](https://cloud.githubusercontent.com/assets/1643285/18356213/70123c46-75b1-11e6-9e6a-31d0a676317a.png)

Trying to make it a `convenience init`:
```
  override init!(success: ZDKCreateRequestSuccess!, andError error: ZDKCreateRequestError!) {
    super.init(success: success, andError: error)
  }

  convenience init() {
    self.init(success: { _ in
      }) { _ in
    }
    delegate = self
  }
```
The above compiles, but yields `fatal error: use of unimplemented initializer 'init(nibName:bundle:)' for class 'project.ChildZendeskTicketVC` as the init calls the "designated" initializer.

Also tried:
![image](https://cloud.githubusercontent.com/assets/1643285/18356588/ef46bbf8-75b2-11e6-9e6d-b586e55742bd.png)

Help would be greatly appreciated.

Cheers

Copy and paste-able start:
```
import Foundation
import ZendeskSDK

final class ChildZendeskTicketVC: ZDKCreateRequestViewController, ZDKCreateRequestViewControllerDelegate {
  override init!(success: ZDKCreateRequestSuccess!, andError error: ZDKCreateRequestError!) {
    super.init(success: success, andError: error)
  }
  
  convenience init() {
    self.init(success: { _ in
    }) { _ in
    }
    delegate = self
  }
  
  required init?(coder aDecoder: NSCoder) {
    fatalError("init(coder:) has not been implemented")
  }
  
  // MARK: ZDKCreateRequestViewControllerDelegate
  final func createRequestViewController(viewController: ZDKCreateRequestViewController!, didCreateTicketWithSuccess result: AnyObject!) {
    // Perform standard action here
  }
  final func createRequestViewController(viewController: ZDKCreateRequestViewController!, didFailCreateTicketWithError error: NSError!) {
    // Perform standard action here
  }
}
```

Podfile.lock contents:
```
  - ZendeskSDK (1.7.1.1):
    - ZendeskSDK/Providers (= 1.7.1.1)
    - ZendeskSDK/UI (= 1.7.1.1)
  - ZendeskSDK/Providers (1.7.1.1)
  - ZendeskSDK/UI (1.7.1.1):
    - ZendeskSDK/Providers
```

**Comment by RonanMcH** [comment]
Hi @MaximusMcCann ,
Thanks for the code snippet. Unfortunately, this class was written in objective-c a while ago and is not set up to be subclassed in Swift. We currently have no intention of updating it to do so. You can post a feature request in our [SDK forum](https://support.zendesk.com/hc/en-us/community/topics/200488257-Zendesk-SDKs) if you wish.
Thanks,
Ronan.
