### ISSUE TITLE
Camera and Photo Library usage could cause iOS 10 app rejection

### ISSUE THREAD

**Issue by lightbow** [zendesk/zendesk_sdk_ios#223]
When submitting apps to the App Store Review process, inclusion of Zendesk will trigger the following rejection email:

> To process your delivery, the following issues must be corrected:
> 
> This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an **NSPhotoLibraryUsageDescription** key with a string value explaining to the user how the app uses this data.
> 
> This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an **NSCameraUsageDescription** key with a string value explaining to the user how the app uses this data.

This is caused by Apple's [new rules](https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/ExpectedAppBehaviors/ExpectedAppBehaviors.html#//apple_ref/doc/uid/TP40007072-CH3-SW4) about informing users of app features that impact their privacy. Even if the rest of the app has no interaction with the camera or the photo library, it will still be called out for these violations. Users can work around this roadblock by just putting in the suggested Info.plist key/value pairs, but ideally Zendesk would offer a framework option that does not include the dependency on the camera/media library.

HockeyApp faces [the same issue](https://github.com/bitstadium/HockeySDK-iOS/commit/4bc00fd96076d86b3271cef28de2582c9b8752df), and is dealing with it by splitting things out into into a separate framework. I realize you already have the separate Providers framework, but it would be great to have a solution for folks that would like to use your UI for the Help Center, but not get flagged for the privacy-access plist description requirement.

**Comment by mathewcropper** [comment]
Hi @lightbow. Thanks for posting.

We're updating our documentation to make it clear that the SDK requires this permission, and to flag the requirement to update *info.plist* with the relevant description.

At the moment, we aren't planning to offer a version of the UI without support for attachments, but I'll keep it in mind. Thank you for the idea and for sharing the HockeyApp context!

I'll mark this issue as closed, as the problem and the answer are contained in the original post. Documentation will be updated in our next release, which is planned for either today or tomorrow, at the latest.

**Comment by jdsk8r** [comment]
We got the same error today when we submitted our app for review, we added those keys on the Info.plist file but either way we are still getting the same error when submitting the app for review.

**Comment by ioskunal** [comment]
Have you fixed this issue?
Because my app asks for the camera permission but still does not ask for the permission while accessing photos.
