### ISSUE TITLE
Category names not displayed when using presentHelpCenterOverview on iOS10

### ISSUE THREAD

**Issue by coredream** [zendesk/zendesk_sdk_ios#227]
- SDK version: 1.7.3.1
- Xcode version: 8
- iOS or Simulator:  iPhone6 and Simulator
- iOS Version: 10.0
- Swift version:

Steps to Reproduce:

1. Using your provided SampleApp, tap Support button
2. Category names are missing

Section and Article names appear correctly.  Category names are displayed on iOS9, but not iOS10.

**Comment by tecknut** [comment]
@coredream Thanks for raising this, and using the new issue template 😄 we found and patched the issue https://github.com/zendesk/zendesk_sdk_ios/pull/229

Try this out and get back to us if everything working well.

**Comment by coredream** [comment]
This appears to be working now from the master branch (1.7.4.1).  Thanks!

**Comment by oarrabi** [comment]
Hello @coredream,
I will close this issue now, please feel free to reopen if it it persists :)
