### ISSUE TITLE
Getting  "zd_dispatcher_err" = "Error Domain=NSURLErrorDomain Code=-1012 \"The operation couldn\U2019t be completed. (NSURLErrorDomain error -1012.)\"

### ISSUE THREAD

**Issue by angela-** [zendesk/zendesk_sdk_ios#23]
When i try to integrate zendesk to an existing app I am getting:
```
Request error: [{
    "zd_dispatcher_err" = "Error Domain=NSURLErrorDomain Code=-1012 \"The operation couldn\U2019t be completed. (NSURLErrorDomain error -1012.)\" UserInfo=0x7fc1d84b1a30 {NSErrorFailingURLStringKey=https://x.zendesk.com/access/sdk/anonymous, NSUnderlyingError=0x7fc1d874bb00 \"The operation couldn\U2019t be completed. (kCFErrorDomainCFNetwork error -1012.)\", NSErrorFailingURLKey=https://x.zendesk.com/access/sdk/anonymous}";
}]
```

but using the same code, when i try it on a new/blank project I am able to make request succesfully

**Comment by BenjaminBriggs** [comment]
I'm getting the same issue but with the jwt authentication. Has there been any progress on this?

**Comment by angela-** [comment]
none so far, i found a temporary fix of setting a blank anonymous authentication at the first request then set the actual authentication then make the next request.

**Comment by BPlano** [comment]
@angela- and @BenjaminBriggs -

Could you submit tickets to support@zendesk.com and mention me (Bryant Plano)? I'd like to look into this issue further.

As a side note, we also recently released SDK v1.1.0.1 - it's possible this may have been fixed with that release, so I would recommend updating to the latest SDK version - but if you're still seeing the issue, let us know and we can take a closer look. Thanks!

**Comment by BPlano** [comment]
@angela / @BenjaminBriggs -

Any luck figuring this one out? Sounds like a new project made the difference? If you're still having trouble, let us know :)

**Comment by angela-** [comment]
Just upgraded the zendesk sdk and it was already working for me

**Comment by BPlano** [comment]
Awesome @angela-, glad to hear it :)

@BenjaminBriggs, if you're still having issues, shoot us an email - support@zendesk.com. Thanks!

**Comment by baz8080** [comment]
Hi All,

This error usually relates to a misconfiguration and isn't an SDK-wide issue per sé. I'm going to close this one but please create new issues if you encounter something similar and we'll help.
