### ISSUE TITLE
Switching between Zendesk environments

### ISSUE THREAD

**Issue by roelspruit** [zendesk/zendesk_sdk_ios#230]
Hi,

I am trying to build a setup with the mobile SDK that would allow us to switch between a sandbox Help Center and a production Help Center within the app (for testing purposes). I am trying to do this by re-initializing the SDK with a new appId, ClientID and zendeskUrl. This does not seem to be working correctly. If I open help center after switching environments I get various errors:

`"zd_dispatcher_err" = "HTTP Error: 404";`
or sometimes an error
`zd_dispatcher_err" = "Error Domain=NSURLErrorDomain Code=-1012`

If I startup the app from scratch and connect to either the sandbox or production help center I do not get these errors.

My questions: 
- Is this kind of switching supported? 
- Does the ZendeskSDK remember some kind of authentication even when re-initializing the SDK?

This is my complete initialization code:
```
ZDKLogger.enable(true)
ZDKLocalization.registerTableName("Zendesk")
        
ZDKConfig.instance().initializeWithAppId(appId, zendeskUrl: url, clientId: clientId)
        
let identity = ZDKAnonymousIdentity()
identity.externalId = Profile.currentProfile().userId
ZDKConfig.instance().userIdentity = identity
```

- SDK version: 1.7.3.1
- Xcode version: 8
- iOS or Simulator: iPhone 5s Simulator
- iOS Version: iOS 10
- Swift version: 2.3

Steps to Reproduce:

1. Initalize the SDK
2. Open the Help Center
3. Re-initialize the SDK with different appId, zendeskUrl and clientId
4. Open the help center again. Now you will often get an error

**Comment by tecknut** [comment]
Hi @roelspruit, this isn't something that is currently supported. There is however a workaround which you can use for development purposes. We'd recommend not using it in a production app.

If you use UserDefaults to store anything in you're app then you can use the following: 

```
UserDefaults.standard.set(0, forKey: "last_reload")
UserDefaults.standard.synchronize()
```

A better approach, which you should do if you can do it, is to blast away everything in defaults. 

```
UserDefaults.standard.removePersistentDomain(forName: <#your-bundle-id#>)
UserDefaults.standard.synchronize()
```

Again this is not something that should be done in production. 

If you'd like to make a feature request please post one [here](https://support.zendesk.com/hc/en-us/community/topics/200488257-Zendesk-SDKs).

Can you let us know if this works for you?

Thanks.

**Comment by baz8080** [comment]
Hi @roelspruit 

I'm going to close this issue for now, as the workaround should work for you.
