### ISSUE TITLE
presentHelpCenterWithViewController is deprecated

### ISSUE THREAD

**Issue by Nikiraf** [zendesk/zendesk_sdk_ios#231]
I have just update Zandesk SDK and I'm getting warning:
`zendesk presentHelpCenterWithViewController is deprecated as of 1.7.2.1`

I don't know what to use instead "presentHelpCenterWithViewController"

**Comment by RonanMcH** [comment]
Hi @Nikiraf ,
The Zendesk Support SDK has been updated with a new Help Center UI. The old UI will be removed in the next major release. This is why you are seeing this `deprecation warning`. Details of the new Help center and its implementation are [here](https://developer.zendesk.com/embeddables/docs/ios/show_help_center#show-the-help-center-in-the-navigation-controller-with-requests).
Thanks,
Ronan.

**Comment by Nikiraf** [comment]
Hi RonanMcH,
Thanks for you replay.

A have tried to fix it with:
let helpCenterContentModel = ZDKHelpCenterOverviewContentModel.defaultContent()
ZDKHelpCenter.pushHelpCenterOverview(self.navigationController, withContentModel:helpCenterContentModel)

But there is now cancel button, to go back to previous screen

**Comment by Nikiraf** [comment]
Hi RonanMcH. Thanks for replay. It's working now.

**Comment by mathewcropper** [comment]
Fantastic! Thanks for letting us know. I'll close this issue :)
