### ISSUE TITLE
Unable to change email

### ISSUE THREAD

**Issue by pszot-pgs** [zendesk/zendesk_sdk_ios#232]
- SDK version: 1.7.3.1
- Xcode version: 7.3.1
- iOS or Simulator: Simulator
- iOS Version: 9.3.1
- Swift version: 2.2

I have something like this:

```
if !initialized {
    ZDKConfig.instance().initializeWithAppId(config.appID, zendeskUrl: config.zendeskUrl, clientId: config.clientId)
}

let identity = ZDKAnonymousIdentity()
identity.email = email
identity.name = email
ZDKConfig.instance().userIdentity = identity

let provider = ZDKRequestProvider()
let request = ZDKCreateRequest()
provider.createRequest(request) { (result, error) in
    callback(error: error)
}
```

And email for ticket in dashboard is always the first one set in ZDKAnonymousIdentity. So if I logout, and login with different account, ticket is created for wrong user.

**Comment by pszot-pgs** [comment]
It seem to work if I call initializeWithAppId each time. Is this workaround ok?
The manual seem to imply that this method should be called only once.

**Comment by tecknut** [comment]
@pszot-pgs Can you have a look at these docs and let us know if what you're experiencing is different to what is expected?

https://developer.zendesk.com/embeddables/docs/ios/set_an_identity

https://support.zendesk.com/hc/en-us/articles/217914138#toc_1

**Comment by pszot-pgs** [comment]
> If you don't identify a user, a user named "Mobile App User" is created in Zendesk when the user makes his or her first support request from a device. Zendesk uses a device identifier to associate all subsequent requests from the same device with the anonymous user in Zendesk. Another user named "Mobile App User" is created for requests submitted from a different device.

This doesn't seem to be true, because if I kill the app I can create request with new email without problem. 
Could you tell me if calling `initializeWithAppId` before each request is ok? I only want to send requests, not view them. The rest of conversation will be carried by emails.

**Comment by mathewcropper** [comment]
Hi @pszot-pgs. I'm Mat, the product manager for our SDKs. I've been following this thread, and I think that it might be better served as a ticket, rather than end up with a long running thread here. 

Would you mind sending an email to support@zendesk.com? If you reference this and ask for the ticket to be assigned to Mathew Cropper in the SDK team, it'll come to me and we'll follow up there.

If you're able to include a sample project that demonstrates your issue, that'd be awesome.

**Comment by pszot-pgs** [comment]
Hi, I will preprare sample project when I have time. Current workaround seems to be working for me.
