### ISSUE TITLE
'Failed to fetch attachments' with 401 auth error

### ISSUE THREAD

**Issue by asutula** [zendesk/zendesk_sdk_ios#234]
- SDK version: 1.7.4.1
- Xcode version: 7.3.1
- iOS or Simulator: Both
- iOS Version: 9 and 10
- Swift version: 2.2

Steps to Reproduce:

1. Configure iOS Zendesk SDK with keys that point at a production Zendesk environment that is managed on the back end as a 'brand' (it uses a different sub-domain). This Zendesk account also supports multiple languages.
2. In the iOS app, present the Zendesk view controller to display a list of help articles.
3. Select an article.
4. The text of the article is displayed, but see error message 'Failed to fetch attachments' appear at the top of the article.

Looking at the network requests, I can see a possible problem:

The request for attachments is made (notice the presence of the Authorization header):
```
GET /api/v2/help_center/articles/219119268/attachments/block.json&per_page=1000 HTTP/1.1
Host: mobile-apps.zendesk.com
Client-Identifier: mobile_sdk_client_<snip!>
Content-Type: application/json
Accept-Encoding: gzip, deflate
Connection: keep-alive
Accept: application/json
User-Agent: Zendesk-SDK/1.6.1.1 iOS/9.3 Env/Development
Authorization: Bearer <bearer token is present>
Mobile-Sdk-Identity: <snip!>
Accept-Language: en-us
```
With the 302 redirect response:
```
HTTP/1.1 302 Found
Server: nginx
Date: Tue, 27 Sep 2016 18:59:08 GMT
Content-Type: text/html; charset=utf-8
Status: 302 Found
X-UA-Compatible: IE=edge
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
X-Zendesk-API-Version: v2
Location: https://mobile-apps.zendesk.com/api/v2/help_center/en-us/articles/219119268/attachments/block.json&per_page=1000?
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: X-Zendesk-API-Warn
X-Zendesk-User-Id: 
Strict-Transport-Security: max-age=86400;
X-Zendesk-Origin-Server: hcapp3.pod9.iad1.zdsys.com
X-Request-Id: <snip!>
X-Runtime: 0.056023
Cache-Control: must-revalidate, private, max-age=0
X-Content-Type-Options: no sniff
Transfer-Encoding: chunked
Connection: Keep-alive

<html><body>You are being <a href="https://mobile-apps.zendesk.com/api/v2/help_center/en-us/articles/219119268/attachments/block.json&amp;per_page=1000?">redirected</a>.</body></html>
```
The next request, to the redirect URL is made (note the absence of the Authorization header):
```
GET /api/v2/help_center/en-us/articles/219119268/attachments/block.json&per_page=1000? HTTP/1.1
Host: mobile-apps.zendesk.com
Client-Identifier: mobile_sdk_client_<snip>
Content-Type: application/json
Accept-Encoding: gzip, deflate
Connection: keep-alive
Accept: application/json
User-Agent: Zendesk-SDK/1.6.1.1 iOS/9.3 Env/Development
Mobile-Sdk-Identity: <snip!>
Accept-Language: en-us
```
With a 401 response:
```
HTTP/1.1 401 Unauthorized
Server: nginx
Date: Tue, 27 Sep 2016 18:59:09 GMT
Content-Type: application/json; charset=utf-8
Status: 401 Unauthorized
WWW-Authenticate: Zendesk realm="API"
X-Zendesk-User-Id: 
Strict-Transport-Security: max-age=86400;
X-Zendesk-Origin-Server: hcapp1.pod9.iad1.zdsys.com
X-Request-Id: <snip!>
X-Runtime: 0.057289
Transfer-Encoding: chunked
Connection: Keep-alive

{"error":"Couldn't authenticate you"}
```

So it seems that the Authorization header getting dropped during the redirect could be the problem. I compared this to the series of requests/responses made from our equivalent Android app, and the Authorization header is maintained.

**Comment by baz8080** [comment]
Hi @asutula 

I edited your comment to remove some of the more sensitive information. Thanks for the detailed report! The dev team is on Dublin time, and someone will look at the issue tomorrow.

Is your brand host-mapped by any chance?

Thanks!

**Comment by asutula** [comment]
Thanks @baz8080 I was just about to do that and you beat me to it 👍

**Comment by asutula** [comment]
@baz8080 I'm not too familiar with the back end setup for Zendesk. I'll try to find out, but maybe you can explain what 'host-mapped' means?

**Comment by baz8080** [comment]
@asutula it means that your brand's Zendesk would be available at something like support.yourbrand.example.com (as well as {yourbrand}.zendesk.com) :)

**Comment by asutula** [comment]
I don't think it is host-mapped.

**Comment by asutula** [comment]
To clarify, our primary Zendesk is host-mapped (support.example.com), but not this specific brand.

**Comment by baz8080** [comment]
Hi @asutula We think we have isolated the issue and we are going to prepare a patch for it.

**Comment by asutula** [comment]
That's great news. Looking forward to the fix.

**Comment by baz8080** [comment]
Hi @asutula We pushed out [1.7.5.1](https://developer.zendesk.com/embeddables/docs/ios/version_information#summary). Can you update and try again please?

**Comment by baz8080** [comment]
Hi @asutula 

We had reports from other customers that this fixed the issue, so I'm going to close this issue. Feel free to reopen it if your issue persists!
