### ISSUE TITLE
No pushRequestCreationWithNavigationController method

### ISSUE THREAD

**Issue by benaneesh** [zendesk/zendesk_sdk_ios#235]
In the [docs](https://developer.zendesk.com/embeddables/docs/ios/create_request) the following code is used to open the create request screen:

`ZDKRequests.pushRequestCreationWithNavigationController(self.navigationController)`

Except the `pushRequestCreationWithNavigationController` is not in the SDK. How do I open the create Request VC? Or do I have to have my own UI and use `ZDKRequestProvider` ?

- SDK version: 1.7.4.1
- Xcode version: 8.0.1
- iOS or Simulator: Both
- iOS Version: iOS 9 & 10
- Swift version: 2.3

Steps to Reproduce:

1. Install using `pod 'ZendeskSDK'`
2. Try using `ZDKRequests.pushRequestCreationWithNavigationController(self.navigationController)`

**Comment by oarrabi** [comment]
Hello @benaneesh,

Sorry for the confusion, it looks like the documentation for this method is not correct. We are going to fix it asap.

You should be using this method to present the create request

```swift
ZDKRequests.presentRequestCreationWithViewController(viewController)
```

Let me know if it works for you :)

Thanks,
Omar..

**Comment by baz8080** [comment]
@benaneesh I'm going to close this issue for now.
