### ISSUE TITLE
Have not effects settings the boolean hideContactSupport

### ISSUE THREAD

**Issue by yzhong52** [zendesk/zendesk_sdk_ios#238]
- SDK version: 1.7.5.1
- Xcode version: 7.3.1
- iOS or Simulator: 4S
- iOS Version: 9.3
- Swift version: 2.2

I am trying to hide the contact us button in the SDK. But setting the boolean `hideContactSupport`:

    let helpCenterContentModel = ZDKHelpCenterOverviewContentModel.defaultContent()
    helpCenterContentModel.hideContactSupport = true
    ZDKHelpCenter.pushHelpCenterOverview(navigationController, withContentModel:helpCenterContentModel)

However, I am able to work around this problem by calling this: 

    ZDKHelpCenter.setNavBarConversationsUIType(.None)
            
Any idea why `helpCenterContentModel.hideContactSupport = true` doesn't work for me?

**Comment by RonanMcH** [comment]
Hi @yzhong52 ,
The snippet `ZDKHelpCenter.setNavBarConversationsUIType(.None)` is the correct way to hide the `Contact us` button in the Help Center UI. The `hideContactSupport` boolean has actually been mis-documented in the `ZDKHelpCenterOverviewContentModel` header file, it is not to hide the right navigation bar button but to hide the `Contact Support` button on an empty search as shown below. 
<img width="375" alt="screen shot 2016-10-03 at 16 50 58" src="https://cloud.githubusercontent.com/assets/12997923/19043851/bbd6fa72-8989-11e6-8b85-ecdaa9ddfbc3.png">
 
I will change the header file documentation now and it will be in our next release.
Thank you for bringing it to our attention,
Ronan.

**Comment by yzhong52** [comment]
Awesome, thanks for the prompt response!

**Comment by couldhll** [comment]
+1
