### ISSUE TITLE
Arrow is being too closed to the label

### ISSUE THREAD

**Issue by yzhong52** [zendesk/zendesk_sdk_ios#239]
- SDK version: 1.7.5.1
- Xcode version: 7.3.1
- iOS or Simulator: 4S
- iOS Version: 9.3
- Swift version: 2.2

It was great the ZenDesk allow us to customize font and text colour. But could you make the space between the label "See all 8 articles" and the arrow on the right a little bit wider? They look odd that they are almost touching each other. 

Also is it possible to make the tint colour of the arrow the same as the text label "See all 8 articles", or make it configurable? 

<img src="https://cloud.githubusercontent.com/assets/3712071/19129358/129274b8-8b15-11e6-8e96-80208c360643.png" width="320">

**Comment by baz8080** [comment]
@yzhong52 The things that you want to change are not configurable There's a balance between keeping customization simple and the amount of things that we expose. There is an option to build your own UI if ours does not suit by using the API Provider SDK.

* https://developer.zendesk.com/embeddables/docs/ios/integrate_sdk#recommended-adding-the-support-sdk-with-cocoapods
* https://developer.zendesk.com/embeddables/docs/ios/api_providers

**Comment by yzhong52** [comment]
Okay, that sounds fair to me. Let's keep it simple don't change the colour then. 

But can we make the spacing of the label and arrow a little wider? It is too close, isn't it?

![screen shot 2016-10-06 at 8 17 25 am](https://cloud.githubusercontent.com/assets/3712071/19151911/55fe1e72-8b9d-11e6-8090-f3a63bd008ff.png)

**Comment by baz8080** [comment]
@yzhong52 Can I ask you to post your request in our [feedback forum](https://support.zendesk.com/hc/en-us/community/topics/200488257-Zendesk-SDKs) please? That way, our product manager will be able to see it and weigh in. It might be Monday before we can give you a definitive answer on it though.

**Comment by baz8080** [comment]
@yzhong52 A workaround might be to pad the end of the string a bit. The string in question is:

```
"ios.ZDKHelpCenter.helpCenterOverview.see_all.title" = "See all %lu articles";
```

You can then [override the string](https://developer.zendesk.com/embeddables/docs/ios/localize_text).

**Comment by yzhong52** [comment]
Thanks for the prompt response Barry and the workaround. That solves my problem.

I will post you a feedback later today thanks!
