### ISSUE TITLE
getArticlebyId 404s when locale is en-us instead of en

### ISSUE THREAD

**Issue by andrewljohnson** [zendesk/zendesk_sdk_ios#240]
- SDK version: 1.7.3.1
- Xcode version: 8.0
- iOS or Simulator: both
- iOS Version: 9 and 10
- Swift version: none

Steps to Reproduce:

This test was done on a non-localized article. [View it here](https://help.gaiagps.com/hc/en-us/articles/221252948-Import-a-Custom-Map-Source-to-gaiagps-com). 

If you try and call this code, the request will 404:

    // this ends up being the string "en" 
    NSString *language = [[[NSBundle mainBundle] preferredLocalizations] objectAtIndex:0];
    ZDKHelpCenterProvider *provider = [[ZDKHelpCenterProvider alloc] initWithLocale:language];
    NSString *tmsMapSourceFormArticleID = @"221252948";
    [provider getArticleById:tmsMapSourceFormArticleID withCallback: ^(NSArray *arrayOfOneArticle, NSError *error) {
        NSLog(@"%@",error);  // a 404 error
        NSLog(@"%@",arrayOfOneArticle);  // null
    }

To make this work, you need to hardcode the locale to be en-us. Then the code above works.

    NSString *language = @"en-us";

This seems like a bug, because:

    1. You'd expect to be able to use the locale string returned by the OS.
    2. This used to work before SDK 1.7, it was a regression.
    3. If you supply the "en" locale when first initializing the SDK, the English Help Center works (just not calling individual articles).

For #3, i.e. this works:
    
    [[ZDKConfig instance] initializeWithAppId:@"SOME_APP_ID" zendeskUrl:@"https://SOME_COMPANY.zendesk.com" clientId:@"SOME_CLIENT_ID"];
    NSString *language = [[[NSBundle mainBundle] preferredLocalizations] objectAtIndex:0];
    [ZDKConfig instance].userLocale = language;

**Comment by oarrabi** [comment]
Hello @andrewljohnson,

The help center expects the full locale (language and region). You can get that using `[NSLocale currentLocale]`

Check the updated snippet bellow:
```objc
    NSString *language = [[[NSLocale currentLocale] localeIdentifier] lowercaseString];
    ZDKHelpCenterProvider *provider = [[ZDKHelpCenterProvider alloc] initWithLocale:language];
    NSString *tmsMapSourceFormArticleID = @"221252948";
    [provider getArticleById:tmsMapSourceFormArticleID withCallback: ^(NSArray *arrayOfOneArticle, NSError *error) {
        NSLog(@"%@",error);  // a 404 error
        NSLog(@"%@",arrayOfOneArticle);  // null
    }];
```

Note: The point number 3 works, since we have a locale resolution that happens when opening the helpcenter but not when requesting a single article.

Thanks.

**Comment by andrewljohnson** [comment]
Thanks, is this documented?

**Comment by DarthMike** [comment]
@oarrabi This doesn't work for me if i.e. locale is "es_US" (which passing it to the provider would be as string "es-us". 

What exactly the initializer is expecting in that string?

**Comment by DarthMike** [comment]
To elaborate here, I think request is failing in my case because we don't have localization. Working on it (peak) here: https://peaklabs.zendesk.com/hc

For example, I assume the request fails if I try to fetch "es-us" (as in user device) but then we only have "es". So is there any way to retrieve the available localizations in zendesk so we can do the resolution you do yourself when initializing `ZDKConfig` ?

**Comment by tecknut** [comment]
@DarthMike Can you try out this? 

```
ZDKHelpCenterProvider *provider = [[ZDKHelpCenterProvider alloc] initWithLocale:@"en-us"];
[provider getCategoriesWithCallback:^(NSArray *items, NSError *error) {
        NSLog(@"%@",items);
}];
```
Does this work for you?

**Comment by DarthMike** [comment]
Hello @tecknut, thanks for reply. 

Passing @"en-us" works correctly.

**Comment by DarthMike** [comment]
Hello, any feedback? Using @"en-us" is not correct, as user might have any combination of localization/country, and we need to resolve locales.

**Comment by tecknut** [comment]
@DarthMike what is your current workflow? Are you building an integration based on our providers?

**Comment by DarthMike** [comment]
Yes we are using the providers with custom UI. Specifically only using `ZDKHelpCenterProvider`.

**Comment by tecknut** [comment]
So we have a local resolution that happens in the back end. But this is based on the locale which is set on `ZDKConfig`. 
We don't have an api which would let you list the locales for which you have articles. 
The closest thing to that would be for you to call the settings provider with the desired locale. If the local is one which your Help Center is configured with you should be able to pull out that local from the `ZDKHelpCenterSettings` model nested in the `ZDKSettings` model which is returned.
If your Help Center has no matching locale, the settings will return whatever the default local is according to your Help Center settings. 

Hopefully this helps.

**Comment by DarthMike** [comment]
Thanks @tecknut  I'll try that.
