### ISSUE TITLE
zendesk navigation bar  ui error 

### ISSUE THREAD

**Issue by sunilhts** [zendesk/zendesk_sdk_ios#241]
- SDK version: 1.6.2.1
- Xcode version:7.3.1
- iOS or Simulator: iPhone6s
- iOS Version: iOS 9.3
- Swift version:2.2

For detail description open the below link
http://stackoverflow.com/questions/39992623/zendesk-adding-help-center-issue-with-navigtion-bar

**Comment by baz8080** [comment]
@sunilhts Strings are in a different bundle. If you installed the SDK manually, and not with Cocoapods, then you will have to copy that bundle as per the [docs](https://developer.zendesk.com/embeddables/docs/ios/integrate_sdk#adding-the-support-sdk-manually)

**Comment by sunilhts** [comment]
I checked.. I have not done manually.. I am using cocoapods.. cocoapods version 0.39.0..

**Comment by ndobri** [comment]
Duplicate of #242
