### ISSUE TITLE
Setting nil value for a dictionary at ZDKAnonymousIdentity#toJson call

### ISSUE THREAD

**Issue by takkyun** [zendesk/zendesk_sdk_ios#243]
It's the same issue as https://github.com/zendesk/zendesk_sdk_ios/issues/183

- SDK version: tested on 1.5.4.1 and 1.7.5.1
- Xcode version: tested with 7.3.1 and 8.0
- iOS or Simulator: both
- iOS Version: tested on 9.3 and 10.0
- Swift version: tested with objective-c code

Steps to Reproduce:

Run the following code:

```
ZDKAnonymousIdentity *identity = [[ZDKAnonymousIdentity alloc] init];
identity.name = @"123456789";'
identity.email = @"123456789@qq.com";
identity.externalId = @"123456789";
NSDictionary *dictionary = [identity toJson];
```

It causes calling `setObject:forKey:` (`setObject:forKeyedSubscript:`) with `nil` value (`key` == `externalId`).

The return value of `toJson` is going to be if I've replaced `NSNull` instance when it happened:

```
{
    email = "123456789@qq.com";
    externalId = "<null>";
    "external_id" = "123456789";
    name = "123456789";
    "sdk_guid" = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX";
}
```

so SDK is using "external_id" instead of "externalId" but still try to set "externalId" with `nil` value.

Probably it's guarded with runtime exception inside SDK, so app won't be crashed.

**Comment by RonanMcH** [comment]
Hi @takkyun ,
Thanks for pointing this out. The `externalId` was migrated and we do guard for it. Reopen this issue if it's causing you issues.
Ronan.
