### ISSUE TITLE
Filter article by label with spaces

### ISSUE THREAD

**Issue by ernestofndz** [zendesk/zendesk_sdk_ios#247]
- SDK version: 1.7.5.1
- Xcode version: 8.0
- iOS or Simulator: Both
- iOS Version: 10
- Swift version: Obj-C

Steps to Reproduce:
1. Instantiate the model with a label that includes space

`helpCenterContentModel.labels = @[@"Label space"]`

URL won't be supported. Solution at this point is to **encode** the string. 

By the way, the example on the [page](https://developer.zendesk.com/embeddables/docs/ios/filter_help_center#filter-by-article-label) is instantiating the array like this `@{@"ios", @"ios8"}` when it should be `@[@"ios", @"ios8"]`.

**Comment by ndobri** [comment]
@ernestofndz thanks for reporting this issue. It has been added to out backlog, but we can't commit to fixing it right now. We will however, post an update here once the release with the patch is out.

**Comment by RonanMcH** [comment]
Hi @ernestofndz ,
We just released version 1.7.6.1 of the Support SDK. This issue has been fixed in this release. `labels` with spaces should now work.
Thanks,
Ronan.
