### ISSUE TITLE
ZDKRMA: showAlwaysInView ~> Indeterministic delay

### ISSUE THREAD

**Issue by vCrespoP** [zendesk/zendesk_sdk_ios#248]
- SDK version: 1.7.5.1
- Xcode version: 7.3.1
- iOS or Simulator: Simulator and device
- iOS Version: 9.3
- Swift version: 2.2

This method delays in showing the popup an undetermined amount of time. 
```
ZDKRMA.showAlwaysInView(self.view)
```

1) How to avoid having that delay?
2) Any block/closure/handler called when it's ready to display?
3) Any way to avoid this and present it in a nice and not confusing way to the user?

Thank you for your time.

**Comment by brendan-fahy** [comment]
Hi @vCrespoP,

There is a delay (in number of seconds) for RMA which is configured on your Zendesk admin page, Admin -> Mobile SDK -> [Your app] -> Rate My App tab -> Delay. `ZDRMA.showAlwaysInView` uses this delay before showing the popup. Have you checked/changed what value has been set for this in the web console?

**Comment by vCrespoP** [comment]
Hello Brendan, thanks for your response.

Yes, that's set to 1 second but it delays a lot (like 10 seconds). 

My scenario is that I want to show this right upon the tap of a button, I can show a loader for 1 second, or whatever is needed, to coordinate when the popup shows and when my loader dismisses.

Ideal thing would be not to have any delay (but I cannot set to zero), and 1 seconds seems to be taking a lot more  than intended.

I've tried some time after changing this setting, just in case the SDK needs some time to get the updated value, without success.

Any hint here?

Thanks so much!

PS: In any case it would be a very good pattern to have a completion handler so we don't have to rely on the value written in the config panel.

**Comment by brendan-fahy** [comment]
OK, can you tell us where in the lifecycle of your ViewController that you're calling `ZDKRMA.showAlwaysInView`?

**Comment by vCrespoP** [comment]
It's being called after the view has loaded, but it's the user who triggers the action. Imagine a UITableView with settings and one being "rate the app".

Mh...maybe what you pointed me at is the notification I'm looking for! I'm going to try, thanks, will get back to you soon :)

**Comment by vCrespoP** [comment]
Absolutely perfect.

Just in case somebody is on the same road I am, this is the code I used with RxSwift:

```
 _ = NSNotificationCenter.defaultCenter()
            .rx_notification(ZDKRMANotificationTriggered)
            .subscribeNext { _ in
               // Hide loader here
        }
```
_Note, in real code, add to disposeBag after subscribing._

Anyways, having a completion block maybe is a good design idea but this is 100% up to you of course. Feel free to close this issue if this is not the case.

Thanks a lot Brenand!

**Comment by tecknut** [comment]
Thanks @vCrespoP, we're going to close this issue. Don't hesitate to reach out again if you have any further issues.
