### ISSUE TITLE
Sorting of help center not matching web

### ISSUE THREAD

**Issue by vCrespoP** [zendesk/zendesk_sdk_ios#249]
- SDK version: 1.7.5.1
- Xcode version: 7.3.1
- iOS or Simulator: Simulator and device
- iOS Version: 9.3
- Swift version: 2.2

The way help articles display within the mobile app through the SDK is not the same as in the web version.

Anything to configure so it matches? It's really confusing and unpleasant to be different.

Thanks a lot.

**Comment by mathewcropper** [comment]
Hi @vCrespoP. Thanks for posting.

This is a known issue, and you can find this mentioned in the _known issues_ section of our docs here: https://developer.zendesk.com/embeddables/docs/ios/version_information

The relevant extract from the docs is below:

> Help Center articles do not appear in the same order as on the web. In v1.7.2.1 we forced the ordering to be based on article creation date (descending) to bring it closer to the web experience for most scenarios. If you have manually ordered articles, or chosen a different sort order, articles may not order correctly in the Support SDK. This is a limitation of the API that we use, and we are working on a fix.

At the moment, there's no way to work around this and we've done the best we can to make the ordering closer to web for many use cases. Until the API we consume is updated, this issue will appear. We don't have a timeline on a resolution for this problem, I'm afraid.

**Comment by vCrespoP** [comment]
Very sorry to hear that :(

Feel free to keep this issue opened or close it at will. 

Thanks for your quick response Mathew, have a good day.

**Comment by mathewcropper** [comment]
I'll leave this open, as it definitely is a problem and it's not fixed. I'd be dishonest if I closed it.

We'll keep you posted here.

**Comment by JeromeRiiot** [comment]
Hello Mathew, 
I also would like this issue to be solved. Is there any hope?

**Comment by tecknut** [comment]
Hi @JeromeRiiot, there is hope. We're currently testing a solution. This issue will be update once the solution is out in the wild.  

Thanks

**Comment by JeromeRiiot** [comment]
This is great news. I'm looking forward to the resolution. 
Thank you for your feedback.
Jérôme.

**Comment by iDurian** [comment]
@mathewcropper When will solve this issue? We found that latest SDK still has this bug.

**Comment by baz8080** [comment]
@iDurian It's a priority for us to fix this issue. There are a lot of moving parts, and we'll get it fixed as soon as we can. There is no clear ETA for this though, but we will keep you all up to date as we progress.

**Comment by JeromeRiiot** [comment]
@baz8080 Thanks for the update, Barry. Still a must have for myself.

**Comment by harrygt** [comment]
Any news on this?

**Comment by baz8080** [comment]
Hi All,

A fix for iOS is not available just yet, but it is fixed in the 2.0 beta of the Android SDK, which has been available since mid December. If you'd like to have a look at that, it's here: https://support.zendesk.com/hc/en-us/community/posts/115010033908-Start-here-Zendesk-Support-Mobile-SDK-v2-beta

We don't give exact ETAs, but the GA of 2.0 is getting quite close now.

**Comment by divo** [comment]
@JeromeRiiot At the moment there is no plan for an iOS beta but 2.0 is on the way for both platforms.

**Comment by JeromeRiiot** [comment]
Ok, Thanks.

**Comment by baz8080** [comment]
Hi All,

We have release version 2.0 of the SDK and it has a lot of improvements, including fixing the order of Help Center content. Please [check it out](https://developer.zendesk.com/embeddables/docs/ios_support_sdk/nutshell)
