### ISSUE TITLE
Translations in Help Center not displaying

### ISSUE THREAD

**Issue by vCrespoP** [zendesk/zendesk_sdk_ios#250]
- SDK version: 1.7.5.1
- Xcode version: 7.3.1
- iOS or Simulator: Simulator and device
- iOS Version: 9,3
- Swift version: 2.2

Steps to reproduce:
1) Have the device in German
2) Present the Help Center from the SDK (no problem here)
3) Everything is in English even though the device is in German as you can see (Back to "Einstelungen" / [Settings])

![captura de pantalla 2016-10-19 a las 12 59 23](https://cloud.githubusercontent.com/assets/7558064/19516384/0c49cf88-95fc-11e6-9aa2-229055c81920.png)

I know I can override them:
https://developer.zendesk.com/embeddables/docs/ios/localize_text

But German is on that list, so as far as I understand it should show texts in German, but they're not being displayed in german to me.

Anything I've missed in order to let the SDK display the correct language? 
Any hint?

Thanks for your time :D

**Comment by tecknut** [comment]
Hi @vCrespoP do you have German set up as a localised language in your app?

![screen shot 2016-10-19 at 14 26 25](https://cloud.githubusercontent.com/assets/2079547/19520410/1b74a9fe-9608-11e6-9e3a-645c508657b6.png)

If not, try adding it. Your app needs to be localised for the corresponding strings to be picked up.

**Comment by vCrespoP** [comment]
That was it, thanks.

**Comment by tecknut** [comment]
No problem. Get back to us with any further issues.
