### ISSUE TITLE
Dark background moves in behind UINavigationBar

### ISSUE THREAD

**Issue by klemensz** [zendesk/zendesk_sdk_ios#255]
- SDK version: 1.7.6.1
- Xcode version: 8.1
- iOS or Simulator: Both
- iOS Version: 10
- Swift version: - (Objective-C)

Steps to Reproduce:

1. Call `[ZDKHelpCenter pushHelpCenterOverview:navigationController withContentModel:helpCenterContentModel];` No special styling is applied.
2. Move from the start screen to the tickets screen or a help article.
3. The dark area will first cover 1/3 of the NavigationBar, and once the article is loaded, the full NavigationBar so that it basically becomes grey.

![simulator screen shot 11 11 2016 16 18 26](https://cloud.githubusercontent.com/assets/1116517/20265175/d8f8631e-aa6f-11e6-9137-c3ba8003024a.png)

Is this a known issue or is there something we can do against it?

**Comment by StevenDiviney** [comment]
@klemensz I am unable to replicate this. It looks like your App has some styling applied to the Navigation Bar, could you share the code you are using to style your own app?

**Comment by klemensz** [comment]
Basically we're using this in the ViewController that will call pushHelpCenterOverview: 
```
    UIColor* color = [Branding brandingColor];
    [[UIView appearance] setTintColor:color];
    self.navigationController.navigationBar.barStyle = UIBarStyleDefault;
    self.navigationController.navigationBar.tintColor = color;
    self.backgroundView.backgroundColor = color;
    self.controlView.backgroundColor = color;
    [[UIApplication sharedApplication] delegate].window.tintColor = color;
```

This is how it looks in the View Hierarchy.
![bildschirmfoto 2016-11-11 um 16 23 50](https://cloud.githubusercontent.com/assets/1116517/20351750/a7bb7952-ac14-11e6-9347-b12e6c01e4a1.png)

**Comment by ndobri** [comment]
Hi @klemensz in order for us to assist you better and in more detail I'd like to invite you to open a ticket with support@zendesk.com where we can work out the details. We can update this github issue afterwards.

**Comment by mathewcropper** [comment]
Hey. I noticed that @klemensz created [this post](https://support.zendesk.com/hc/en-us/community/posts/245054487-iOS-Dark-background-moves-in-behind-UINavigationBar) in the Zendesk SDKs community. I turned that into a ticket, and assigned it to us to follow up 😄

**Comment by RonanMcH** [comment]
I am going to close this issue as we are handling it internally in a ticket.
