### ISSUE TITLE
linker warning when building with XCode8.0 or greater

### ISSUE THREAD

**Issue by jaz-ah** [zendesk/zendesk_sdk_ios#256]
- SDK version:  - ZDCChat (1.3.2.1):
    - ZDCChat/API (= 1.3.2.1)
    - ZDCChat/Localization (= 1.3.2.1)
    - ZDCChat/UI (= 1.3.2.1)
  - ZDCChat/API (1.3.2.1)
  - ZDCChat/Localization (1.3.2.1)
  - ZDCChat/UI (1.3.2.1):
    - ZDCChat/API
  - ZendeskSDK (1.7.6.1):
    - ZendeskSDK/Providers (= 1.7.6.1)
    - ZendeskSDK/UI (= 1.7.6.1)
  - ZendeskSDK/Providers (1.7.6.1)
  - ZendeskSDK/UI (1.7.6.1):
    - ZendeskSDK/Providers
- Xcode version: 8.0, 8.1 or 8.2 (Beta)
- iOS or Simulator: 10.0 / 10.1 / 10.2 simulator
- iOS Version: 10.0 / 10.1 / 10.2 simulator
- Swift version: 3.0

Steps to Reproduce:

1.  Just build an application with the zendesk sdk using cocoapods with the above versions, will get the linker warning:
ld: warning: Some object files have incompatible Objective-C category definitions. Some category metadata may be lost. All files containing Objective-C categories should be built using the same compiler.

I have broken this down and limited it to a test application with just the zendesk sdk.  It looks like the zendesk sdk is probably built w/ XCode7.x and we are getting this compatibility warning.

**Comment by tecknut** [comment]
Hi @jaz-ah, we have a couple of Categories in the SDK. These are probably what this is warning is complaining about.

Are you experiencing any hard crashes when running our UI? The Categories are on some of our view controllers. 

It's not ideal, but if you're not seeing any hard crashes than it should be ok in the short term. 

We're planning an upcoming release, however this will most likely be out at some point in January.

**Comment by jaz-ah** [comment]
no crashes/obvious issues arising from it.  Will your next release be based on XCode8.1/8.2?

**Comment by StevenDiviney** [comment]
@jaz-ah We have published a new release, with XCode 8. Can you let us know if it fixes your issue?

**Comment by jaz-ah** [comment]
yes but I'm seeing this issue with the ZDCChat sdk as well - could you upgrade that too @StevenDiviney ?

**Comment by oarrabi** [comment]
Hello @jaz-ah,

We are planning to release ZDCChat SDK soon. It would help if you close this one and open it there as it will help others that have the same issue.

**Comment by jaz-ah** [comment]
ok @oarrabi I've filed: https://github.com/zendesk/zendesk_sdk_chat_ios/issues/142 for the same issue in the chat sdk. closing this one now as fixed.
