### ISSUE TITLE
Weird class/property text everywhere

### ISSUE THREAD

**Issue by MaximusMcCann** [zendesk/zendesk_sdk_ios#257]
- SDK version:1.7.6.1
- Xcode version: 8.1 (8B62)
- iOS or Simulator: Simulator iPhone 5s
- iOS Version: 10.1
- Swift version: 3.0.1

Steps to Reproduce:

1. I just open the VC
![image](https://cloud.githubusercontent.com/assets/1643285/20815644/4f84049e-b7e4-11e6-8b9a-ac43f52b9902.png)

![image](https://cloud.githubusercontent.com/assets/1643285/20815520/c9075f38-b7e3-11e6-8874-f493ba828ed8.png)

**Comment by baz8080** [comment]
@MaximusMcCann how did you import the SDK? If you used CocoaPods then the strings bundle should have been brought in and linked automatically. If not, then you have to remember to add the [strings bundle](https://developer.zendesk.com/embeddables/docs/ios/integrate_sdk#adding-the-support-sdk-manually)

**Comment by MaximusMcCann** [comment]
I did `Pod Install`

**Comment by baz8080** [comment]
This usually happens when the ZendeskSDKStrings.bundle is not linked correctly to the target from where you are launching the Zendesk SDK. Cocoapods usually does this linking. Does your podfile add the SDK and its bundles to the right target? Can you show us your podfile snippet?

**Comment by MaximusMcCann** [comment]
Quit Xcode, nuked Derived Data, nuked Pods folder and re `pod install`.  Did the trick. Cheers
