### ISSUE TITLE
ZDKRMA Rate My App dialog shown partially off screen on certain iPad modals

### ISSUE THREAD

**Issue by dangochi** [zendesk/zendesk_sdk_ios#258]
- SDK version: 1.7.6.1
- Xcode version: 8.1
- iOS or Simulator: iPad simulator/device
- iOS Version: 10.1

In our app, we have a navigation controller that we present, and from that navigation controller's view, we show the RMA dialog: ```[ZDKRMA showAlwaysInView:navigationController.view];```

This works just fine on iPhone. However, if on iPad, we configure that same UINavigationController from above slightly differently. Before we present it, we set these properties:
```
navigationController.modalPresentationStyle = UIModalPresentationFormSheet;
navigationController.modalTransitionStyle = UIModalTransitionStyleCoverVertical;
```

When trying to show the RMA dialog from a presented navigation controller with these properties set on iPad, the dialog is not quite in the correct spot. See the attached screenshots for an example.

![rate app 1](https://cloud.githubusercontent.com/assets/1784093/20819707/1125339c-b7eb-11e6-8bb0-ff307814567f.png)
![rate app 2](https://cloud.githubusercontent.com/assets/1784093/20819710/145afd9e-b7eb-11e6-9e75-f3f86ea9e346.png)

**Comment by tecknut** [comment]
Hi @dangochi, could you try to show RMA in a view controllers view? From your snippet it seems like you're presenting it from a navigation controller's view. `[ZDKRMA showAlwaysInView:navigationController.view];`

If this is a container view controller, maybe try showing it from one of the child view controllers views. 

Thanks

**Comment by dangochi** [comment]
@tecknut thanks for the quick response. I did try that as well, but I get the same result. I put similar code in Zendesk's sample "Remember The Date" app and got the same results when trying to present from various different views (see screenshot below).

When I put a symbolic breakpoint on ```[ZDKRMADialogView initWithDelegate:]```, I notice that it appears to be using some method called ```CGRectMakeCenteredInScreen```. I see an implementation of that in ```ZDKUIUtil.h```, and if that code is the same as what the SDK is using, I think I can see why the dialog is being placed where it is. 

In this case, it makes me think I should be trying to add the dialog to ```[UIApplication sharedApplication].keyWindow```, but in that case, the dialog doesn't even show up at all.

![for zendesk](https://cloud.githubusercontent.com/assets/1784093/20846322/f42ed7be-b87d-11e6-9a1e-a5dffb924d7d.png)

**Comment by StevenDiviney** [comment]
@dangochi You are correct, CGRectMakeCenteredInScreen is the problem. We are laying out the RMA view based on screen coordinates, not the view it's contained in.

I've logged an issue internally for us to track this, although I can't commit to a timeline for a fix.

Since the offending code is public, you can fix it if you want. There is no nice way to do this but a quick and dirty hack is as follows:

```
CGRect screen =  [[[[[UIApplication sharedApplication] keyWindow] rootViewController] presentedViewController] view].bounds;
```
It fixes the issue, but is, erm, questionable. 

This is the best we can do for now.

**Comment by RonanMcH** [comment]
Hi @dangochi ,
We deprecated the RMA feature in the SDK and it will be removed in the next release. We have built an open source alternative, available [here](https://github.com/zendesk/rate_my_app_ios) that works in conjunction with the SDK. 
Thanks,
Ronan.
