### ISSUE TITLE
VoiceOver Issue with Description

### ISSUE THREAD

**Issue by jacksontaylor13** [zendesk/zendesk_sdk_ios#259]
- SDK version: 1.7.6.1
- Xcode version: 8.1
- iOS or Simulator: All iOS Devices and Simulators
- iOS Version: 10.1
- Swift version: 3.0.1

Steps to Reproduce:

1. Open the Request Creation Form `ZDKRequests.presentRequestCreation(with: strongSelf)`
2. Turn on VoiceOver
3. VoiceOver works properly for Email and speaks "Email, text field" when clicked
4. Click on description

Expected: "Description, text field"

Observed: "text field"

**Comment by mathewcropper** [comment]
Hey @jacksontaylor13. Thanks for this. As it happens, this exact issue is on hit list of accessibility improvements for the Support SDK. We're planning a patch release of the Support SDK in January. Leave this with me and I'll see if this can be slotted into there.

**Comment by jacksontaylor13** [comment]
Perfect! Thanks @mathewcropper!

**Comment by mathewcropper** [comment]
Hey @jacksontaylor13. We've fixed this, and it's awaiting release. We're targeting end of Jan / start of Feb for our next release, so I'll update you here when we do that. You can also subscribe to our RSS [here](https://developer.zendesk.com/embeddables/docs/ios/follow_updates) to stay up to date on releases.

**Comment by mathewcropper** [comment]
Hi @jacksontaylor13. The fix for this has now been released in v1.8.0.1 of the Support SDK. Release notes are [here](https://developer.zendesk.com/embeddables/docs/ios/version_information).

Thanks for your patience with this. I'll close this issue now, but if you have any other questions just shout.
