### ISSUE TITLE
Crash on iOS 7

### ISSUE THREAD

**Issue by Zhulmin** [zendesk/zendesk_sdk_ios#267]
- SDK version: 1.7.6.1
- Xcode version: Xcode 8
- iOS or Simulator: iPhone 4s
- iOS Version: iOS 7.1.2
- Swift version: none

Steps to Reproduce:
dyld: Symbol not found: _OBJC_CLASS_$_NSURLQueryItem
  Referenced from: /var/mobile/Applications/1FCE6451-22CC-4073-9434-148D3A55976F/Fotor.app/Fotor
  Expected in: /System/Library/Frameworks/Foundation.framework/Foundation
 in /var/mobile/Applications/1FCE6451-22CC-4073-9434-148D3A55976F/Fotor.app/Fotor

NSURLQueryItem is available above iOS 8
but I get the crash before appDelegate call the method
- (BOOL)application:  didFinishLaunchingWithOptions:

how can I solve the problem at iOS 7?

**Comment by RonanMcH** [comment]
Hi @Zhulmin ,
We have tested on iOS 7 and have never experienced this crash. Are you sure it is the Zendesk Support SDK causing this crash? 
Thanks,
Ronan.

**Comment by Zhulmin** [comment]
Maybe not,  sorry.

**Comment by RonanMcH** [comment]
I don't believe it is a crash in the Zendesk SDK so I'm going to close this issue for now!
Feel free to reopen it if you discover else wise.
Ronan.
