### ISSUE TITLE
Some parts of the UI are not localizable

### ISSUE THREAD

**Issue by insidegui** [zendesk/zendesk_sdk_ios#274]
- SDK version: 1.7.6.1
- Xcode version: 8.2.1 (8C1002)
- iOS or Simulator: Both
- iOS Version: 10.2
- Swift version: 3.0

The `pt` localization provided by the SDK is good, but we wanted to customize some of the text. Almost all of it is customizable by creating a new `Localizable.strings` file, but two places I can't seem to find a way to localize:

![contact support](https://cloud.githubusercontent.com/assets/67184/22661801/e98bf4f6-ec8d-11e6-8ebe-0785f8b2b376.png)

![new ticket title](https://cloud.githubusercontent.com/assets/67184/22661820/f82d073e-ec8d-11e6-88fe-4c47e5ff55c0.png)

Here is my `Localizable.strings` file:

```
"ios.ZDKRequests.createRequest.error.request" = "Falha ao enviar a solicitação";
"ios.ZDKRequests.createRequest.requestSubject" = "Solicitação do aplicativo";
"ios.ZDKRequests.requestList.empty" = "Nenhuma solicitação aberta no momento";
"ios.ZDKRequests.requestList.error" = "Falha ao obter as solicitações";
"ios.ZDKRequests.requestList.title" = "Minhas Solicitações";
"ios.ZDKRequests.rightBarButton.title.new" = "Nova";
"ios.ZDKRequests.rightBarButton.title.contact" = "Nova Solicitação";
"ios.ZDKHelpCenter.support.contactSupport" = "Nova Solicitação";
```

All of the strings worked, except for `ios.ZDKRequests.rightBarButton.title.contact` and `ios.ZDKHelpCenter.support.contactSupport`. Also, that `Contact Support` button on the empty search screen doesn't seem to have a localizable key, so I can't customize its text.

**Comment by oarrabi** [comment]
Hello @insidegui 

To control the title of this screen overwrite the `ios.ZDKRequests.createRequest.title` localization key. For the right bar button please use `ios.ZDKRequests.createRequest.submit.button`.

As for the `Contact Support` button, you are correct, it looks like its a bug. I raised an internal issue in our bug tracker to track this issue.

I will keep this GitHub issue open and update you when we fix the `Contact Support` button localization. In the meantime, can you let me know if the other localization keys worked.

Thanks and sorry for the inconvenience :)

**Comment by insidegui** [comment]
Thanks! Looking forward to an update :)

**Comment by tecknut** [comment]
Hey @insidegui, have you updated to the latest version?

This issue should be solved now. 
Thanks

**Comment by insidegui** [comment]
We haven't yet, but we're going to implement our own UI for other reasons, so this will not be an issue anymore. Thanks 😃
