### ISSUE TITLE
Release notes for version 1.8.0.1

### ISSUE THREAD

**Issue by samuelleach** [zendesk/zendesk_sdk_ios#275]
Hello @RonanMcH

Thanks a lot for the work you're putting in on the iOS SDK.

One of the things we noticed about the release 1.8.0.1 was that there were no release notes to tell us how things had changed.

https://github.com/zendesk/zendesk_sdk_ios/releases/tag/1.8.0.1

Could I ask you to write some brief bullet points on that? That would be really helpful for us.

My name is Sam Leach - we're a customer of yours at Track24.com.

**Comment by baz8080** [comment]
Hi Sam,

We host the release notes on [developer.zendesk.com](https://developer.zendesk.com/embeddables/docs/ios/version_information). There's a link in the [README](https://github.com/zendesk/zendesk_sdk_ios/blob/master/README.md) if you ever forget the link/

Thanks!

**Comment by samuelleach** [comment]
Thanks for your help. The advantage of the github release notes to us is that they provide an atom feed to all the packages we need. I followed the link you provided though and found that there is an rss feed here: http://zen-marketing-product.s3.amazonaws.com/product/rss/SDKs.xml

**Comment by baz8080** [comment]
Hi Sam, 

That's a good point. We might be able to duplicate release notes here in the future, although it isn't something we're actively looking into now.

I'm glad that you found our feed!
