### ISSUE TITLE
Contact Us form email validation needs to trim whitespace

### ISSUE THREAD

**Issue by afehners** [zendesk/zendesk_sdk_ios#278]
- SDK version: 1.9.0.1
- Xcode version: 8.2.1
- iOS or Simulator: Both
- iOS Version: 10
- Swift version: 3

I've had several reports come through via my website instead of In App because they were unable to send a message via the Contact Us form. I have discovered that in all cases a space was inserted at the end of their email address, which causes the email address validation to fail and the 'Send' button is not enabled. It would be sensible for the email address to be Trimmed of white space before being used for validation and set as the from email address.

Steps to Reproduce:

1. Open Contact Us form from help center view
2. type in your email address but add a space after as if it auto completed
3. type in a message
4. 'Send' button will not enable whilst email address has whitespace at end

**Comment by StevenDiviney** [comment]
Hi @afehners,

Thanks for bringing this to our attention. I have created an issue for us to track it internally. I can't say when we will release it though, we need to decide when to work on it. We will update you when we know more.

**Comment by RonanMcH** [comment]
Hi @afehners ,
We have changing the behaviour of the UI of the Contact Us form to not allow users to enter whitespace in the email field. This fix is in our latest release (version 1.10.1.1).
Thanks,
Ronan.

**Comment by tecknut** [comment]
Closing this. Feel free to reopen if you have any further issue.
Thanks
