### ISSUE TITLE
ZDKCreateRequestViewController does not work properly after adding it as a child view controller

### ISSUE THREAD

**Issue by SiarheiBarysenka** [zendesk/zendesk_sdk_ios#279]
Our app uses some custom presentations of Zendesk Create Request page, so we ended up with the following presentation of `ZDKCreateRequestViewController` (the code is shortened to reflect the main idea):

```
override func viewDidLoad() {
    // This view controller is contained in UINavigationController stack,
    // so its navigationController property is non-nil

    let child = ZDKCreateRequestViewController()
    child.delegate = ... // Here we set up the delegate

    addChildViewController(child)
    view.addSubview(child.view)
    child.view.autoPinEdgesToSuperviewEdges()
    child.didMove(toParentViewController: self)
}
```

This approach worked perfectly up until SDK version 1.6.2.1. Starting from version 1.7.0.1, the `ZDKCreateRequestViewController` has `Send` button all the time disabled (even if text is entered), and also doesn't display the `Attachments` button.

Could you please provide any information why this approach causes misbehavior in the SDK versions >= 1.7.0.1, or maybe recommend any alternatives how `ZDKCreateRequestViewController` can be embedded into the parent?

- SDK version: 1.8.0.1
- Xcode version: 8.2.1
- iOS or Simulator: iOS
- iOS Version: 9.3.4, 10.2.1
- Swift version: 3.0.2

**Comment by oarrabi** [comment]
Hello @SiarheiBarysenka,

**Comment by oarrabi** [comment]
Hello @SiarheiBarysenka,

Try giving `ZDKCreateRequestViewController` its own navigation controller. The following code  should do it

```swift
let child = ZDKCreateRequestViewController()
child.delegate = ....

let navigation = UINavigationController(rootViewController: child)
addChildViewController(navigation)
view.addSubview(navigation.view)
navigation.view.autoPinEdgesToSuperviewEdges()
navigation.didMove(toParentViewController: self)
```

Please let me know if it solves the issue.

Thanks,
Omar...

**Comment by SiarheiBarysenka** [comment]
Thanks @oarrabi,

This approach helps!

In addition to your solution I just have to add `navigation.isNavigationBarHidden = true` line to prevent displaying two navigation bars, since in my case `parent` is also contained in `UINavigationController`, and `barButtonItem`s from `ZDKCreateRequestViewController` are set explicitly to `parent` for styling purposes.

Thanks again for the solution.

**Comment by baz8080** [comment]
@SiarheiBarysenka Thanks for letting us know that it worked 👍
