### ISSUE TITLE
Crashing on [NSNull isEqualToString:]

### ISSUE THREAD

**Issue by Enthouan** [zendesk/zendesk_sdk_ios#28]
I'm trying to use the SDK but when I run this code in the viewDidLoad of one of my view controllers :

    ZDKAnonymousIdentity *identity = [ZDKAnonymousIdentity new];
  
    # I simplified the code but the strings are always well defined
    identity.name = @"name";
    identity.email = @"email";
    identity.externalId = @"12345";
    
    [ZDKConfig instance].userIdentity = identity;
    
    [[ZDKConfig instance] initializeWithAppId:@"app_id" zendeskUrl:@"zendeskURL" andClientId:@"clientID"];

The app crashes immediately : `Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull isEqualToString:]: unrecognized selector sent to instance 0x1138ee4c0'` 

Am I doing something wrong?

**Comment by BPlano** [comment]
Hey @Enthouan,

Have you had any luck getting this fixed up? Please make sure you're using the latest version of our SDK (1.2.0.1 as of this comment).

If you're still having issues, let us know. Thanks!

**Comment by baz8080** [comment]
Hey @Enthouan 

We have shored up our nil handling in identities a lot since this was first reported. I'm going to mark this as closed, but please reopen if you're still having the issue after upgrading to the latest version
