### ISSUE TITLE
No tickets currently open

### ISSUE THREAD

**Issue by abekert** [zendesk/zendesk_sdk_ios#280]
- SDK version: 1.9.0.1
- Xcode version: 8.2 (8C38)
- iOS or Simulator: Both
- iOS Version: 10.2
- Swift version: Objective-C

Steps to Reproduce:

I am using anonymous identification. It works great if I am using static hard-coded values of email&name right in application:didFinishLaunchingWithOptions:.

    ZDKAnonymousIdentity *identity = [ZDKAnonymousIdentity new];
    identity.email = @"email@me.com";
    [ZDKConfig instance].userIdentity = identity;

But I need user to login somewhere else to know him and I want to set the identity later. But when I do it later, or with non-static data, it resets users' tickets.

I am checking **sdk_guid** field of identity to get know if there are any changes:

    NSLog(@"%@", [(NSObject *)[ZDKConfig instance].userIdentity description]);

Any time I set **[ZDKConfig instance].userIdentity**, it changes **sdk_guid**. Even if I set it twice with the same object:

    ZDKAnonymousIdentity *identity = (ZDKAnonymousIdentity *)[ZDKConfig instance].userIdentity;
    [ZDKConfig instance].userIdentity = identity;
    NSLog(@"%@", [(NSObject *)[ZDKConfig instance].userIdentity description]);    // NSLog prints one value 
    [ZDKConfig instance].userIdentity = identity;
    NSLog(@"%@", [(NSObject *)[ZDKConfig instance].userIdentity description]);    // NSLog prints other value 

Why? I didn't change anything. I think, **sdk_guid** should be based on **email** value. And if it is the same, **sdk_guid** should remain the same.

**Comment by abekert** [comment]
When I look at **userIdentity** property at **ZDKConfig.h**, I see it's marked as *strong*:

@property (nonatomic, strong, setter=setUserIdentity:, getter=userIdentity) id<ZDKIdentity> userIdentity;

But if you modifying its fields doesn't apply to stored value. So next code doesn't do anything:

    ZDKAnonymousIdentity *identity = (ZDKAnonymousIdentity *)[ZDKConfig instance].userIdentity;
    identity.email = [self userEmail];
    identity.name = [self userName];

To apply changes I need to set it again:

    [ZDKConfig instance].userIdentity = identity;

Why?

**Comment by oarrabi** [comment]
Hello @abekert,

The current implementation for `ZDKAnonymousIdentity` will create an `sdk_guid` each time an identity is created. That is the intended behaviour of the anonymous identity. Changing the `ZDKAnonymousIdentity` is considered as setting a new identity. 

Are you having an issue that preventing you from settings the user identity late when your have an identity?

Can you please elaborate a bit more on your use case.

Thanks,
Omar Abdelhafith

**Comment by abekert** [comment]
Thanks for your answer, Omar.

Yes, I can't set user's email to identity when I get it later from login.

My steps:

In **- (void)application:didFinishLaunchingWithOptions:** after initing Zendesk I set an empty identity:

    ZDKAnonymousIdentity *identity = [ZDKAnonymousIdentity new];
    [ZDKConfig instance].userIdentity = identity;

When I open Support screen in the app, I set user's information from his login:

    ZDKAnonymousIdentity *identity = (ZDKAnonymousIdentity *)[ZDKConfig instance].userIdentity;
    identity.name = [self name]; 
    identity.email = [self email];
    [ZDKConfig instance].userIdentity = identity;

Every new app start my tickets dissapear from the app, but during the same session they are here. What steps I supposed to do to set up identity correctly?

**Comment by abekert** [comment]
In my case even setting user's email on the app start, if I have it, removes tickets. Even if it is the same between sessions, **sdk_guid** differs and data become erased

If I set statically with string, it has the same **sdk_guid** between app starts, and everything fine:

ZDKAnonymousIdentity *identity = [ZDKAnonymousIdentity new];
identity.name = @"Alexander"; 
identity.email = @"me@me.com";
[ZDKConfig instance].userIdentity = identity;

**Comment by oarrabi** [comment]
Hello @abekert,

The clearing happens when the identity changes between from 

```
ZDKAnonymousIdentity *identity = [ZDKAnonymousIdentity new];
```

to 

```
ZDKAnonymousIdentity *identity = (ZDKAnonymousIdentity *)[ZDKConfig instance].userIdentity;
identity.name = [self name]; 
identity.email = [self email];
```

Can you update the logic so that if you have a login user you delay the call to `[ZDKConfig instance].userIdentity` and only call it once with the user name and email?

Thanks,
Omar...

**Comment by abekert** [comment]
Hello, Omar.

It worked. I removed creation of identity from **application:didFinishLaunchingWithOptions:** and create and assign it only when user taps "Contact Us" or "My Tickets" button on support screen.

The code:

    autotype identity = [ZDKAnonymousIdentity new];
    identity.name = self.name;
    identity.email = self.email;
    [ZDKConfig instance].userIdentity = identity;

Even if user taps several times during the same session, it doesn't shuffle **sdk_guid** if there is the same user info, as supposed.
