### ISSUE TITLE
Issue with batteryLevel == 100. iOS 10x

### ISSUE THREAD

**Issue by SergeyBulyno** [zendesk/zendesk_sdk_ios#281]
- SDK version:v(1.7.4.1) and v(1.9.0.1)
- Xcode version:8.2.1
- iOS or Simulator:iOS (iphone 5, iphone se, ipad air)
- iOS Version:10.x
use objective c.

Steps to Reproduce:

1. Hi, I use Method [ZDKDeviceInfo deviceInfoDictionary] witch launch in [ZDKRequests configure: block and deviceInfoDictionary always return battery level == 100.
I changed sdk version, initialization (via fabric and initializeWithAppId:zendeskUrl: clientId:), try launch [ZDKDeviceInfo batteryLevel] directly, but nothing help me.

**Comment by RonanMcH** [comment]
Hi @SergeyBulyno ,
Thanks for reporting this issue. We clarified it as a bug and it will be fixed in our next release of the support SDK. Unfortunately, I can't give a timeline for this but we will update you here when it has been released.
Thanks,
Ronan.

**Comment by RonanMcH** [comment]
Hi @SergeyBulyno ,
This issue has been fixed in the latest version of the SupportSDK (1.10.0.1). 
Thanks,
Ronan.
