### ISSUE TITLE
XCode 8.3, "Umbrella for module 'ZendeskSDK' already covers this directory" 

### ISSUE THREAD

**Issue by jregnauld** [zendesk/zendesk_sdk_ios#284]
Hi,

I have an issue with Zendesk SDK, cocoapods and XCode 8.3.

I use Zendesk SDK as a dependency in a podspec and it used to work very well.
Unfortunately since I install XCode 8.3, I get the error "Umbrella for module 'ZendeskSDK' already covers this directory" when I'm running "pod install" or "pod update" in my project :(

Do you know how to fix it?

Thanks a lot for your help!

**Comment by oarrabi** [comment]
Hello @jregnauld

Sorry for the inconvenience.
Can you please share parts of your Podfile and Podspec file so we can debug this?

Thanks...

**Comment by jregnauld** [comment]
Hi @oarrabi 

Sorry I made a mistaske my previous comment. :-/
In fact I didn't use Zendesk SDK as a dependency in the podspec, but I added it manually in my pod because of the static binaries issue.

It was working fine when installing or updating my pod in a project, but not anymore since XCode 8.3

Cheers and sorry again for the mistake :-/

**Comment by oarrabi** [comment]
Hey @jregnauld ,

Would it be ok if you share part of your Podfile. that would help us debug the issue.

Thanks,

**Comment by jregnauld** [comment]
yes for sure :)

`source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!


def zendesk
    pod 'my_pod_which_include_zendesk_sdk', '~> 2.0.0'
    pod 'ZDCChat', '~> 1.3.3.0'
end


def analytics_pods
    pod 'Tune', '~> 4.9.1'
    pod 'PubNub', '~> 4.5.14'
    pod 'GoogleAnalytics', '~> 3.17'
    pod 'GoogleIDFASupport', '~> 3.14'
end

def fabric_pods
    pod 'Fabric'
    pod 'Crashlytics'
end

def google_pods
    pod 'FirebaseAppIndexing', '~> 1.0.3'
    pod 'GoogleMaps', '~> 1.10.5'
    pod 'GoogleTagManager', '~> 3.15.2'
end

def service_pods
    analytics_pods
    fabric_pods
    google_pods
end

def ab_testing_pods
    pod 'Firebase/RemoteConfig', '~> 3.11.1'
    pod 'Optimizely-iOS-SDK', '~> 1.5.0'
end

def main_pods
    core_layer_domain_agnostic
    
    service_pods
    ab_testing_pods
    
    pod '1PasswordExtension', '~> 1.8.1'
    pod 'ActionSheetPicker-3.0', '~> 2.0.5'
    pod 'AFNetworking', '~> 2.5.4'
    pod 'CMMapLauncher', '~> 1.1.0'
    pod 'CRToast', '= 0.0.81'
    pod 'CocoaAsyncSocket', '~> 7.5.0'
    pod 'FBAnnotationClustering', '~> 0.2.2'
    pod 'FBSDKCoreKit', '~> 4.13.0'
    pod 'FBSDKLoginKit', '~> 4.13.0'
    pod 'FXKeychain', '~> 1.5'
    pod 'KVOController', '~> 1.0.3'
    pod 'KZPropertyMapper', '~> 2.6'
    pod 'libextobjc', '~> 0.4.1'
    pod 'INTULocationManager', '~> 4.2.0'
    pod 'IQKeyboardManager', '~> 4.0.2'
    pod 'JB4ASDK', '~> 4.4.0'
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'OHHTTPStubs', '~> 4.0.1'
    pod 'pop', '~> 1.0.9'
    pod 'SDWebImage', '~> 3.7.3'
    pod 'SMCalloutView', '~> 2.1.5'
    pod 'SZTextView', '~> 1.2.2'
end

#--------TARGETS ---------

target 'MyProject' do
    main_pods
    zendesk
    
    target 'MyProject Tests' do
        inherit! :search_paths
    end
end
`

**Comment by tecknut** [comment]
Thanks @jregnauld we'll have a look at this now and get back to you.

**Comment by tecknut** [comment]
Hey @jregnauld where is `'my_pod_which_include_zendesk_sdk'` defined?

**Comment by federicocappelli** [comment]
@tecknut answering for @jregnauld the pod is in a private repo

**Comment by federicocappelli** [comment]
Opening my_pod_which_include_zendesk_sdk i'm not able to build anymore:

```
/Users/myself/Projects/my_pod_which_include_zendesk_sdk/my_pod_which_include_zendesk_sdk/Frameworks/Zendesk/ZendeskProviderSDK.framework/Modules/module.modulemap:2:3: error: umbrella for module 'ZendeskSDK' already covers this directory
  umbrella header "ZendeskProviderSDK.h"
  ^
/Users/myself/Projects/my_pod_which_include_zendesk_sdk/my_pod_which_include_zendesk_sdk/Frameworks/Zendesk/ZendeskProviderSDK.framework/Modules/module.modulemap:5:10: error: inferred submodules require a module with an umbrella
  module * { export * }
         ^
<module-includes>:1:1: warning: umbrella header for module 'ZendeskSDK' does not include header 'my_pod_which_include_zendesk_sdk-umbrella.h'
#import "Headers/ZendeskSDK.h"
^
<module-includes>:1:1: warning: umbrella header for module 'ZendeskSDK' does not include header 'ZDKAccountAuthHelper.h'
#import "Headers/ZendeskSDK.h"
^
<module-includes>:1:1: warning: umbrella header for module 'ZendeskSDK' does not include header '/Users/myself/Projects/my_pod_which_include_zendesk_sdk/my_pod_which_include_zendesk_sdk/Frameworks/Zendesk/ZendeskSDK.framework/PrivateHeaders/ZDKAlertAction.h'
#import "Headers/ZendeskSDK.h"
^
<module-includes>:1:1: warning: umbrella header for module 'ZendeskSDK' does not include header '/Users/myself/Projects/my_pod_which_include_zendesk_sdk/my_pod_which_include_zendesk_sdk/Frameworks/Zendesk/ZendeskSDK.framework/PrivateHeaders/ZDKAlertController.h'
#import "Headers/ZendeskSDK.h"
^
<module-includes>:1:1: warning: umbrella header for module 'ZendeskSDK' does not include header 'ZDKErrorParser.h'
#import "Headers/ZendeskSDK.h"
^
<module-includes>:1:1: warning: umbrella header for module 'ZendeskSDK' does not include header 'ZDKLoginRequest.h'
#import "Headers/ZendeskSDK.h"
^
<module-includes>:1:1: warning: umbrella header for module 'ZendeskSDK' does not include header 'ZDKLoginRequestPartsFactory.h'
#import "Headers/ZendeskSDK.h"
^
<module-includes>:1:1: warning: umbrella header for module 'ZendeskSDK' does not include header 'ZDKRequestExecutor.h'
#import "Headers/ZendeskSDK.h"
^
<module-includes>:1:1: warning: umbrella header for module 'ZendeskSDK' does not include header 'ZDKRequestHelper.h'
#import "Headers/ZendeskSDK.h"
^
<module-includes>:1:1: warning: umbrella header for module 'ZendeskSDK' does not include header 'ZDKRequestManager.h'
#import "Headers/ZendeskSDK.h"
^
<module-includes>:1:1: warning: umbrella header for module 'ZendeskSDK' does not include header 'ZDKRequestQueue.h'
#import "Headers/ZendeskSDK.h"
^
<module-includes>:1:1: warning: umbrella header for module 'ZendeskSDK' does not include header 'ZDKRequestSession.h'
#import "Headers/ZendeskSDK.h"
^
<module-includes>:1:1: warning: umbrella header for module 'ZendeskSDK' does not include header 'ZDKRequestSessionFactory.h'
#import "Headers/ZendeskSDK.h"
^
<module-includes>:1:1: warning: umbrella header for module 'ZendeskSDK' does not include header 'ZDKRequestSessionLoggedIn.h'
#import "Headers/ZendeskSDK.h"
^
<module-includes>:1:1: warning: umbrella header for module 'ZendeskSDK' does not include header 'ZDKRequestSessionLoggingIn.h'
#import "Headers/ZendeskSDK.h"
^
<module-includes>:1:1: warning: umbrella header for module 'ZendeskSDK' does not include header 'ZDKRequestSessionNotLoggedIn.h'
#import "Headers/ZendeskSDK.h"
^
<module-includes>:1:1: warning: umbrella header for module 'ZendeskSDK' does not include header '/Users/myself/Projects/my_pod_which_include_zendesk_sdk/my_pod_which_include_zendesk_sdk/Frameworks/Zendesk/ZendeskSDK.framework/PrivateHeaders/ZDKUITextView.h'
#import "Headers/ZendeskSDK.h"
^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/my_pod_which_include_zendesk_sdk-umbrella.h"
        ^
/Users/myself/Projects/my_pod_which_include_zendesk_sdk/Example/Pods/Target Support Files/my_pod_which_include_zendesk_sdk/my_pod_which_include_zendesk_sdk-umbrella.h:155:9: error: could not build module 'ZendeskSDK'
#import "ZendeskSDK.h"
```

**Comment by StevenDiviney** [comment]
@federicocappelli @jregnauld I am unable to replicate this but I'm going to guess it's related to a known issue in XCode 8.3

"Known Issues
When building a framework that has module maps in both the source and the install directories that define the same module, the compiler will show a redefinition message. (28638816)

Workaround: Rename the module map file in the source directory to a non-default name (the default name is module.modulemap or module.map), and set the Module Map File build setting to the renamed module map"

https://developer.apple.com/library/content/releasenotes/DeveloperTools/RN-Xcode/Chapters/Introduction.html

**Comment by jregnauld** [comment]
Hi @StevenDiviney, thanks for your help!

I renamed the module map file and it fixed the issue. Good guess! :)

It seems to be similar to this issue http://www.openradar.me/30194818

Would it possible for you to modify the build setting for the module map file name? because if we want to get the last Zendesk SDK version, we will have to do the same workaround again.

Thanks again for your answer!

**Comment by tecknut** [comment]
@jregnauld thanks for letting us know it worked out.
