### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by Kastr** [zendesk/zendesk_sdk_ios#286]
- SDK version: 1.9.2.1
- Xcode version: 8.2.1 (8C1002)
- iOS or Simulator: iPhoneSE
- iOS Version: 10
- Swift version: 3

After I created a CocoaTouch Framework, I used CocoaPods to install Zendesk SDK using _pod 'ZendeskSDK/Providers'_ or _pod 'ZendeskSDK'_ in this Framework.
We are getting the following error after compiling the project:

Undefined symbols for architecture x86_64:
  "_UIApplicationWillEnterForegroundNotification", referenced from:
      -[ZDKConfig initializeWithAppId:zendeskUrl:clientId:] in ZendeskProviderSDK(ZDKConfig.o)
  "_OBJC_CLASS_$_UIDevice", referenced from:
      objc-class-ref in ZendeskProviderSDK(ZDKRequestHelper.o)
      objc-class-ref in ZendeskProviderSDK(ZDKDeviceInfo.o)
  "_OBJC_CLASS_$_UIImage", referenced from:
      objc-class-ref in ZendeskProviderSDK(ZDKBundleUtils.o)
      objc-class-ref in ZendeskProviderSDK(ZDKAvatarProvider.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by RonanMcH** [comment]
Hi @Kastr ,
I have been unable to reproduce this issue myself. The errors seems to be pointing at missing symbols for `UIKit` objects. Maybe try embedding `UIKit` with your framework before building it.  Can you let us know if this works?
Thanks,
Ronan.

**Comment by Kastr** [comment]
Thanks for replying @RonanMcH 
Unfortunately it didn't work.
We now decided to import the SDK directly into our app instead of modularizing to a CocoaTouch Framework. This way it works fine and there is no error.
Thank you for your time!
