### ISSUE TITLE
New ticket screen clips pasted text

### ISSUE THREAD

**Issue by Laevand** [zendesk/zendesk_sdk_ios#287]
- SDK version: 1.9.2.1
- Xcode version: 8.3
- iOS or Simulator: Both
- iOS Version: 10
- Swift version: 3.1

New ticket screen allows pasting only as much text as vertical space between keyboard and navigation bar allows.

Steps to Reproduce:

1. Copy 30 lines of text to clipboard
1. Open Contact Us form from help center view and create a new ticket
1. Paste text into a text view
1. Only first 14 lines are shown, no scrolling is allowed

![simulator screen shot 17 apr 2017 17 01 54](https://cloud.githubusercontent.com/assets/1598161/25091280/eb2c1356-2390-11e7-8cd5-148bb2cd7455.png)

**Comment by StevenDiviney** [comment]
@Laevand thanks for reporting this. It's not clipping the text, the text is below because we are not resizing the view when text is pasted in. The effect is same though :)

I have created an issue for us to track this internally.

**Comment by tecknut** [comment]
Hi @Laevand it's taken a while, but this issue is no longer present in the SDK. We've just released a big update which has completely reworked the request ui. 

Please try it out and get back to us. 

Thanks,
Alan
