### ISSUE TITLE
No option for 'Remind Me Later' or 'Dismiss' in ZDKRMAAction

### ISSUE THREAD

**Issue by juanpdelat** [zendesk/zendesk_sdk_ios#288]
- SDK version: 1.9
- Xcode version: 8.3.1
- iOS or Simulator: Both
- iOS Version: 10.3.1
- Swift version: 3.1

Steps to Reproduce:

1. Integrate through cocoapods.
2. Configure `ZDKRMA` with `ZDKRMAAction.rateApp`, `ZDKRMAAction.sendFeedback` and `ZDKRMAAction.undisplayed`
3. Present `ZDKRMA` using `showAlways(in view: UIView!)`

**Comment by StevenDiviney** [comment]
@juanpdelat 
I'm not sure what your question is, can you clarify? The four supported Rate My App actions are:
```
typedef NS_ENUM(NSInteger, ZDKRMAAction) {

    /**
     * Enumeration for rating an app.
     */
    ZDKRMARateApp        = 1,

    /**
     * Enumeration for sending feedback.
     */
    ZDKRMASendFeedback   = 2,

    /**
     * Enumeration for choosing to never be prompted for feedback again.
     */
    ZDKRMADontAskAgain   = 3,

    /**
     * Enumeration for an undisplayed option.
     */
    ZDKRMAUndisplayed    = 4
};
```

**Comment by juanpdelat** [comment]
What I mean is there is no way for the user to dismiss the popup and be asked again in the future, the only options are to rate the app, to send feedback or opening a ticket and to not ask ever again.

<img width="306" alt="screen shot 2017-05-02 at 10 22 06 am" src="https://cloud.githubusercontent.com/assets/1113309/25622123/73371b60-2f21-11e7-99d6-e8947d64c4fe.png">

Is there a way to just dismiss the popup and show it again in the future?

**Comment by tecknut** [comment]
@juanpdelat Yes there is a way to do this. 

https://github.com/zendesk/zendesk_sdk_ios/blob/master/ZendeskSDK.framework/Headers/ZDKRMAConfigObject.h#L32

https://github.com/zendesk/zendesk_sdk_ios/blob/master/ZendeskSDK.framework/Headers/ZDKRMAConfigObject.h#L124

You can add your own `shouldShowBlock`and return true when you want the popup to show. The block is passed a number of details which you can use to decide whether to show. The one that might make sense for you to check is `lastOptionSelected`. 

Also it's worth mentioning that if you use show always the should show block isn't invoked, and as it says will always show the popup.

**Comment by tecknut** [comment]
Ok so for a start what you could do is [change the strings](https://developer.zendesk.com/embeddables/docs/ios/localize_text).

This will allow you to set text as you like. I'm not sure whether your app is in more than one language, if it's only in one language this step is less hassle.

In addition to this you can use the should show block to change the semantics of don't ask again to a remind me later. 

Unfortunately though the UI is tied down to at most 3 distinct options. There were plans to open this up for more customisation which never came to fruition. 

As a last resort, It's possible to build out something similar to RMA UI and us the [requests provider](https://github.com/zendesk/zendesk_sdk_ios/blob/master/ZendeskProviderSDK.framework/Headers/ZDKRequestProvider.h#L87) to send a request.

**Comment by RonanMcH** [comment]
Hi @juanpdelat ,
We deprecated the RMA feature in the SDK and it will be removed in the next release. We have built an open source alternative, available [here](https://github.com/zendesk/rate_my_app_ios) that works in conjunction with the SDK. 
Thanks,
Ronan.
