### ISSUE TITLE
can't show Contact Form directly

### ISSUE THREAD

**Issue by andrewljohnson** [zendesk/zendesk_sdk_ios#289]
I don't see in the docs how to show the Contact Form directly, without showing Help Center.

Is this possible, and is there documentation on how to do it (in Objective C)?

- SDK version:
Any
- Xcode version:
Any
- iOS or Simulator:
Any
- iOS Version:
Any
- Swift version:
NA

Steps to Reproduce:

1. 
2.

**Comment by StevenDiviney** [comment]
@andrewljohnson 
https://developer.zendesk.com/embeddables/docs/ios/requests#create-a-new-ticket

`[ZDKRequests presentRequestCreationWithViewController:viewController];`

**Comment by andrewljohnson** [comment]
Thanks! Totally missed that.
