### ISSUE TITLE
Setting top border color on ZDKCommentInputView has no effect

### ISSUE THREAD

**Issue by baldursson** [zendesk/zendesk_sdk_ios#29]
After executing:
`[[ZDKCommentInputView appearance] setTopBorderColor:[UIColor redColor]];`

The top border is still the default gray

**Comment by BPlano** [comment]
Hey @baldursson - a colleague of mine added a PR for your issue, and this should be fixed as of SDK version 1.3.0. Please download the latest version and let us know if you continue to see any problems. Thanks! :)
