### ISSUE TITLE
Custom Back Button on ZDKHelpCenter and ZDCChat

### ISSUE THREAD

**Issue by xuaninbox** [zendesk/zendesk_sdk_ios#291]
- SDK version: 1.9.2.2
- Xcode version: 8.3.2
- iOS or Simulator: iOS
- iOS Version: 10.3.1
- Swift version:3.1

try to add my custom back button to ZDKHelpCenter and ZDCChat but it seems it always use the system default back button.

navigationItem.leftBarButtonItem = UIBarButtonItem(image: #imageLiteral(resourceName: "common_back"), style: .plain, target: self, action: #selector(btnBackPush(_:)))

but even if this works it only changes one view controller and I'm hoping to change all that follows

So, what should be the best approach to achieve this?

Thanks!

**Comment by schlan** [comment]
Hey @xuaninbox, please try to set the custum icon like this ([source](http://stackoverflow.com/questions/16254456/setting-navigation-bar-back-button-image)): 

```
[[UIBarButtonItem appearance] setBackButtonBackgroundImage:barButtonImage forState:UIControlStateNormal barMetrics:UIBarMetricsDefault];
```

**Comment by xuaninbox** [comment]
Thx!

Cause I use leftBarButtonItem, I ended up subclassing UINavigationController

	import UIKit

	class HelpNavigationController: UINavigationController {

	    override func viewDidLoad() {
	        super.viewDidLoad()
	    }

	    override func didReceiveMemoryWarning() {
	        super.didReceiveMemoryWarning()
	    }

	    override func pushViewController(_ viewController: UIViewController, animated: Bool) {
	        super.pushViewController(viewController, animated: animated)
	        viewController.navigationItem.leftBarButtonItem = UIBarButtonItem(image: #imageLiteral(resourceName: "common_back"), style: .plain, target: self, action: #selector(btnBackPush(_:)))
	    }

	    override func btnBackPush(_: Any) {
	        popViewController(animated: true)
	    }
	}
