### ISSUE TITLE
Issue with Customizing UI support  zendesk

### ISSUE THREAD

**Issue by Patrashkov** [zendesk/zendesk_sdk_ios#292]
- SDK version:1.9.2.1
- Xcode version:  8.3.2 (8E2002)
- iOS or Simulator: 
- iOS Version:
- Swift version: 3.1

First, forgive me, maybe for a stupid question.
I'm trying to hide the UITableViewHeaderFooterView in the UITableView section namely "Help and FAQs"
But I still have not coped with this problem (((( maybe someone will suggest a solution
Photo with the problem attached
![screen shot 2017-05-04 at 19 34 46](https://cloud.githubusercontent.com/assets/18269516/25714939/57076f8e-3102-11e7-9328-52017cd6ac71.png)
![screen shot 2017-05-04 at 19 18 12](https://cloud.githubusercontent.com/assets/18269516/25714950/5e65512e-3102-11e7-85d1-8df1a4932352.png)

**Comment by baz8080** [comment]
@Patrashkov Sorry that this isn't good new, but hiding the header isn't something that is supported. The only solution would be to rebuild the UI on top of our [API provider](https://developer.zendesk.com/embeddables/docs/ios/api_providers) layer.
