### ISSUE TITLE
Tickets raised through mobile SDK lack identifying information

### ISSUE THREAD

**Issue by afehners** [zendesk/zendesk_sdk_ios#293]
If a user raises an issue through the Help Center then all tickets arrive with the requester set as "Mobile App User". If tickets are raised via the web Help Center then it displays their name as entered on the web form.

It is very hard to scan through all the support tickets raised via the mobile SDK and spot ones raised by the same person without going into each and inspecting the email address.

I tried adding a name for the user in App, but this seems to get ignored
`ZDKAnonymousIdentity *identity = [ZDKAnonymousIdentity new];
        identity.name = @"Test_name";
    }
    [ZDKConfig instance].userIdentity = identity;`

Is there anyway to achieve this? Should the name being getting picked up and displayed in the ticket?

**Comment by StevenDiviney** [comment]
@afehners 

Do you have conversations disabled in your SDK settings? There is currently a bug in the SDK. If conversations are disabled and the identity has no email, the name will be lost when the user submits a ticket.

**Comment by afehners** [comment]
Hi, Yes, I have conversations turned off.

If I set a dummy identity email, will it work around this issue, and get replaced with the user inputted email, from the submission form, later on?

**Comment by tecknut** [comment]
If you change a value on an `ZDKAnonymousIdentity` it is treated as a new identity and any data from the previous identity is cleared.

https://help.zendesk.com/hc/en-us/articles/229489568#toc_1

Also if you set a dummy email, the UI won't load with the email field. 

We have a release coming out soon which should have a fix for this. 

If you can't wait for that, is there any way you can capture the name and email of users before they get to the create request screen?

**Comment by tecknut** [comment]
Hey @afehners we've put out a release which fixes this issue. 

Can you verify this is working for us? Please reopen the issue if you find it persists. 

Thanks
