### ISSUE TITLE
Localizable.string corrupted

### ISSUE THREAD

**Issue by raissetto** [zendesk/zendesk_sdk_ios#294]
- SDK version: 1.9.92
- Xcode version: 8.3.2
- iOS or Simulator: iOS
- iOS Version:  10.3
- Swift version: 3.1

Steps to Reproduce:

1. go to zendeskSDKStrings.bundle
2. open it.lproj/Localizable.strings

this is my file:

bplist00ﬂA	

 !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVVWXYZ[\]^_`abcdefghijklmnohpqrstuvwxoyz{|ko[_#ios.RMA.request.sendFeedback.button_;ios.sdk.ZDKRequests.createRequest.attachment.chooseExisting_&ios.ZDKHelpCenter.support.contactError_!ios.ZDKRequests.commentList.error_ios.RMA.request.error.title_ios.RMA.dialog.header.title_4ios.ZDKAPI.request.sendFeedback.device.freeDiskspace_3ios.ZDKAPI.request.sendFeedback.device.batteryLevel_2ios.ZDKAPI.request.sendFeedback.device.totalMemory_%ios.ZDKHelpCenter.categoriesListError_$ios.ZDKHelpCenter.searchResultsError_ios.RMA.dialog.rateApp.button_2ios.ZDKHelpCenter.helpCenterOverview.see_all.title_ios.RMA.dialog.dismiss.button_5ios.sdk.ZDKRequests.createRequest.attachment.newPhoto_/ios.ZDKRequests.createRequest.email.placeholder_4ios.sdk.ZDKRequests.createRequest.attachment.replace_*ios.ZDKHelpCenter.helpCenterOverview.title_"ios.ZDKHelpCenter.noArticles.title_ios.RMA.request.header.title_"ios.ZDKHelpCenter.toastRetryButton_,ios.RMA.request.sendFeedback.tryAgain.button_+ios.ZDKRequests.createRequest.submit.button_)ios.ZDKHelpCenter.searchField.placeholder_!ios.ZDKRequests.requestList.title_(ios.sdk.ZDKHelpCenter.flatArticles.title_)ios.RMA.request.sendFeedback.close.button_!ios.ZDKRequests.requestList.empty_$ios.ZDKHelpCenter.noCategories.title_'ios.ZDKRequests.commentSubmittion.error_#ios.ZDKHelpCenter.sectionsListError_)ios.ZDKHelpCenter.articleAttachmentsError_ios.ZDKRequests.connectionError_$ios.RMA.request.textView.placeholder_!ios.ZDKRequests.requestList.error_"ios.RMA.dialog.sendFeedback.button_(ios.ZDKRequests.rightBarButton.title.new_,ios.ZDKRequests.createRequest.requestSubject_ios.RMA.request.success.title_*ios.ZDKRequests.leftBarButton.title_cancel_"ios.ZDKHelpCenter.noSections.title_+ios.ZDKRequests.createRequest.error.request_2ios.sdk.ZDKRequests.pushNotification.dismiss.title_$ios.RMA.request.sendFeedback.subject_ios.RMA.request.back.button_"ios.RMA.request.header.description_#ios.ZDKRequests.createRequest.title_+ios.ZDKRequests.createRequest.cancel.button_5ios.ZDKRequests.createRequest.description.placeholder_/ios.sdk.ZDKRequests.pushNotification.open.title_ios.ZDKHelpCenter.support.title_#ios.RMA.request.success.description_(ios.ZDKRequests.commentEntry.placeholder_'ios.ZDKHelpCenter.noSearchResults.title_#ios.ZDKHelpCenter.articlesListError_3ios.sdk.ZDKRequests.createRequest.attachment.remove_0ios.ZDKAPI.request.sendFeedback.device.osVersion_(ios.ZDKHelpCenter.support.contactSupport_,ios.ZDKAPI.request.sendFeedback.device.model_(ios.ZDKHelpCenter.search.noResults.title_7ios.sdk.ZDKRequests.createRequest.attachment.fileTooBig_!ios.RMA.request.error.description_ios.ZDKHelpCenter.toastOkButton_,ios.ZDKRequests.rightBarButton.title.contact_-ios.sdk.ZDKRequests.leftBarButton.close.title^Invia feedback_Scegli esistente_Connessione impossibile_ Impossibile caricare i commenti.oSi Ë verificato un errore._La nostra app ti soddisfa?_Spazio libero sul disco:_Livello batteria:_Memoria totale dispositivo:_"Impossibile reperire le categorie.oSi Ë verificato un problema_Valuta la nostra app._Mostra gli altri %lu articolioNon chiedere pi˘[Scatta foto_Indirizzo email[SostituisciUAiuto_Nessun articolo trovato._Siamo spiacentiWRiprovaUInvia_Come possiamo aiutarti?]I miei ticket_Elenco articoliVChiudi_Nessun ticket aperto al momento_Nessuna categoria trovata._ Impossibile inviare il commento._ Impossibile reperire le sezioni._"Impossibile reperire gli allegati._Nessuna connessione._Descrivi il problema_Impossibile reperire i ticket._No, invia il feedbackUNuovo^Ticket via app_Feedback inviato.WAnnulla_Nessuna sezione trovata._Invio ticket non riuscito.ROK_Feedback via appXIndietro_2Vogliamo migliorare. Facci sapere se hai problemi.ZContattaci[DescrizioneTApriZAssistenza_Grazie per averci contattato.XCommento_Nessun risultato trovato._"Impossibile reperire gli articoli.WRimuovi_Versione sistema operativo:XModello:_Nessun risultato pero'Dimensione massima dell allegato: %@ MBo#Si Ë verificato un errore. Riprova.ç≥Ò>\z±ÁDkã¿‡JÅÆ”ÚFt†ƒÔ?fê∂‚+OtüŒÓ@n£ Ë
3aôÀÌ		>	h	é	ƒ	˜
"
Q
|
∂
⁄
¸+[j}ó∫Ò)=[Äπ—Ò

 
2
>
D
_
q
y

ô
ß
π
¿
‚
ˇ"EjÅòπ—◊Ê˙:=PYéô•™µ’ﬁ˙'ENe∂}ˇ

**Comment by tecknut** [comment]
This is a compiled strings file, you can select how you want to view it. 

![strings](https://cloud.githubusercontent.com/assets/2079547/26443556/d25316c8-4130-11e7-8f40-25802430c0d9.gif)
