### ISSUE TITLE
Unable to customize how the view controllers are presented

### ISSUE THREAD

**Issue by nomadplanet** [zendesk/zendesk_sdk_ios#296]
- SDK version: 1.9.2.2
- Xcode version: any
- iOS or Simulator: any
- iOS Version: any
- Swift version: any

Steps to Reproduce:

1. let helpCenter = ZDKHelpCenterOverviewController(helpCenterOverviewModel: ZDKHelpCenterOverviewContentModel.defaultContent()); helpCenter.uiDelegate = self; present(helpCenter, animated: true, completion: nil); // add additional code so that the contact form is reachable with the right bar button item
2. Launch app on iPad
3. Go to contact form
4. Click New
5. The modal form is fullscreen and we're not able to customize the tintColor and the barTintColor (could be white on white !). Same for the photo picker.

Please provide a way to customize more elements in the presented UI screens, including status bar styles.

**Comment by RonanMcH** [comment]
Hi @nomadplanet , you can present the contact form as in `formSheet`style with the following code:
```
let helpCenter = ZDKHelpCenterOverviewController(helpCenterOverviewModel: ZDKHelpCenterOverviewContentModel.defaultContent())
        let navController = UINavigationController(rootViewController: helpCenter)
        
        present(navController, animated: true, completion: nil);
        helpCenter.modalPresentationStyle = .formSheet
        navController.modalPresentationStyle = .formSheet
``` 
We don't expose the controller to actually set properties on it here when presented from Help Center. You could post [here](https://support.zendesk.com/hc/en-us/community/topics/200132066-Product-feedback) with your feature request which is monitored by our product manager. 
Thanks,
Ronan.

**Comment by morgan-legal** [comment]
Is there any update on that point ?

**Comment by divo** [comment]
@morgan-legal We don't currently plan to support this. You can [head over to the community](https://support.zendesk.com/hc/en-us/community/topics/200488257-Zendesk-SDKs) and post a feature request and we will consider it for future work.
