### ISSUE TITLE
Incorrect section order

### ISSUE THREAD

**Issue by nomadplanet** [zendesk/zendesk_sdk_ios#297]
- SDK version: 1.9.2.2
- Xcode version: any
- iOS or Simulator: any
- iOS Version: any
- Swift version: any

Steps to Reproduce:

1. On Zendesk, create several sections, for instance FOO, BAR, ZEN, DESK
2. On the web, they're displayed in the alphabetical order : BAR, DESK, FOO, ZEN  which is what's expected
3. On mobile (including Android), they are displayed in a random order (for instance BAR, FOO, DESK, ZEN)

I suspect that they're displayed in the creation order on mobile but I am not certain about this. The wrong order is consistent between iOS and Android.

![screen shot 2017-06-08 at 17 11 15](https://user-images.githubusercontent.com/592864/26936053-da5a038e-4c6d-11e7-9674-596069fc289d.png)
![simulator screen shot 8 jun 2017 17 11 02](https://user-images.githubusercontent.com/592864/26936052-da560c5c-4c6d-11e7-9c54-8fc4eb347eb4.png)

**Comment by baz8080** [comment]
Hi @nomadplanet 

We have an issue open here for sorting issues. We are making progress on the fix, and will update that issue when we have a solution: https://github.com/zendesk/zendesk_sdk_ios/issues/249

Thanks
