### ISSUE TITLE
Articles not sorted in correct order

### ISSUE THREAD

**Issue by nomadplanet** [zendesk/zendesk_sdk_ios#298]
- SDK version: 1.9.2.2
- Xcode version: any
- iOS or Simulator: any
- iOS Version: any
- Swift version: any

Steps to Reproduce:

1. Create a section
2. Create articles A, B and C
3. They're displayed in creation order on the web A, B, C
4. They're displayed in the most recent order on mobile (including Android): C, B, A

We need to be consistent on this, preferably most recent first.

**Comment by baz8080** [comment]
Hi @nomadplanet 

We have an issue open here for sorting issues. We are making progress on the fix, and will update that issue when we have a solution: https://github.com/zendesk/zendesk_sdk_ios/issues/249

Thanks
