### ISSUE TITLE
Crashing on autorelease

### ISSUE THREAD

**Issue by phaddius** [zendesk/zendesk_sdk_ios#299]
- SDK version: 1.9.2.2
- Xcode version: 8.3.2
- iOS or Simulator: iPhone Device - doesn't crash on simulator
- iOS Version: 10.3.2
- Swift version: 3

Steps to Reproduce:

1. Launch the HelpCenter - either via pushOverview or presentOveriew:
let helpCenterContentModel = ZDKHelpCenterOverviewContentModel.defaultContent()
ZDKHelpCenter.pushOverview(self.navigationController, with:helpCenterContentModel)

2a. Dismiss the Help Center, or...
2b. Tap on any article, or...
2c. Tap on Contact Us

3. Wait 100-1000ms

4. Crash
Thread 1Queue : com.apple.main-thread (serial)
#0	0x000000018893015c in objc_msgSend ()
#1	0x0000000189d9aa80 in -[__NSArrayI dealloc] ()
#2	0x000000018893a134 in (anonymous namespace)::AutoreleasePoolPage::pop(void*) ()
#3	0x000000018ffe9c3c in -[UIView dealloc] ()
#4	0x000000018893a134 in (anonymous namespace)::AutoreleasePoolPage::pop(void*) ()
#5	0x000000018ffe9c3c in -[UIView dealloc] ()
#6	0x000000018893a134 in (anonymous namespace)::AutoreleasePoolPage::pop(void*) ()
#7	0x000000018ffe9c3c in -[UIView dealloc] ()
#8	0x0000000190178614 in -[UINavigationTransitionView dealloc] ()
#9	0x000000018893a134 in (anonymous namespace)::AutoreleasePoolPage::pop(void*) ()
#10	0x000000018ffe9c3c in -[UIView dealloc] ()
#11	0x0000000190178564 in -[UILayoutContainerView dealloc] ()
#12	0x0000000189d9fea0 in -[__NSDictionaryM dealloc] ()
#13	0x000000018893a134 in (anonymous namespace)::AutoreleasePoolPage::pop(void*) ()
#14	0x0000000189d96b28 in _CFAutoreleasePoolPop ()
#15	0x0000000189e66cec in __CFRunLoopRun ()
#16	0x0000000189d96da4 in CFRunLoopRunSpecific ()
#17	0x000000018b800074 in GSEventRunModal ()
#18	0x0000000190051058 in UIApplicationMain ()
#19	0x0000000100271c94 in main at AppDelegate.swift:23
#20	0x0000000188da559c in start ()

**Comment by nsomar** [comment]
Hello @phaddius,

I just tried to reproduce the issue the information you specified. However, I was unable to get it to crash.
Does the issue happen when you run the sample app too?
Can you share a bit of more code; such as how you are initializing the SDK and a bit more context on how you are presenting `ZDKHelpCenter`?

Thanks,
Omar Abdelhafith

**Comment by phaddius** [comment]
Hi there, I haven't tried the sample app, as I'm sure it runs fine :)

As for my own code, here is how I am doing things. I'm integrating via
Fabric, my zendesk credentials are in my info.plist, as a "kit" inside the
Fabric dictionary. In my didFinishLaunchingWithOpitons, I'm calling:

Fabric.with([Crashlytics.self, AWSCognito.self, Zendesk.self])


Then whenever I want to show the help center:

let helpCenterContentModel =
ZDKHelpCenterOverviewContentModel.defaultContent()

ZDKHelpCenter.pushOverview(self.navigationController,
with:helpCenterContentModel)

OR

ZDKHelpCenter.presentOverview(g_tabBarController, with:
helpCenterContentModel)


g_tabBarController is a global reference to my TabBarController, which is
always non-nil.

**Comment by nsomar** [comment]
Hello @phaddius,

I tried to reproduce the issue using Fabric and with both a navigation controller and a tabbar controller but I can't reproduce it yet.
Do you think you can provide a sample app that reproduces the issue?

Thanks,
Omar...
