### ISSUE TITLE
[ZDKRMA showInView:] doesn't work

### ISSUE THREAD

**Issue by xareelee** [zendesk/zendesk_sdk_ios#30]
I test both one [sample apps](https://github.com/zendesk/sdk_demo_app_ios) and my own app to invoke `-[ZDKRMA showInView:]` and it doesn't work. No view shows up; even there is no any error message on my console. The only message shows on my console is:

```
Reachability Flag Status: -R ------- networkStatusForFlags
```

----

**Update**

Ok, I found [the documentation](https://developer.zendesk.com/embeddables/docs/ios/rate_my_app#prompting-customers) about this: 

> **Calling [ZDKRMA showInView:self.view] only shows the dialog if the display criteria configured in Zendesk have been met.**

**But how can I force it to show up even if the criteria hasn't been met?**

[The documentation](https://developer.zendesk.com/embeddables/docs/ios/rate_my_app#demonstration-mode) told me not to use `showAlwaysInView` in production apps.

> RMA can be configured to always be displayed by calling showAlwaysInView. When you call this method, the dialog is displayed even if the configuration forbids it. This method is provided for testing purposes and should not be used in production apps.

----

**Update**

I find I didn't save the zero delay in the admin configuration, but after setting the value, it is still takes up to 4 seconds to show up the "Rate My App" view. That's too long.

----

**Update**

I found the server can't save my settings for zero delay. After saving and refresh the web page, it still shows 3 seconds for delay. 

I recommend that it should show an animating UI indicator when waiting while using  `showAlwaysInView`.

**Comment by blakeperdue** [comment]
I have the same issue. @xareelee were you ever able to get the delay set to zero? I am manually calling the RMA code to show the prompt exactly when I want it shown (when a user clicks a button called "Rate This App"). 

There doesn't seem to be a way to override this delay. And in the Zendesk admin panel you cannot set it to zero.

**Comment by baz8080** [comment]
If you want to have complete control over rate my app you can use the `showAlwaysInView` like this:

Objective-C

```objective-c
[ZDKRMA showAlwaysInView:self.view];
```

Swift

```swift
ZDKRMA.showAlwaysInView(self.view)
```

[Source](https://developer.zendesk.com/embeddables/docs/ios/rate_my_app#show-always)
