### ISSUE TITLE
As a user I can not submit a new ticket.

### ISSUE THREAD

**Issue by AnujD7781** [zendesk/zendesk_sdk_ios#300]
- SDK version: 1.7.1.1
- Xcode version: Version 8.3.3 (8E3004b)
- iOS or Simulator: iOS
- iOS Version: 10.3
- Swift version: 3
- Anonymous access

Steps to Reproduce:

1. Tap on contact us -> opens my Ticket section
2. Click on New ticket
3. continue typing in the textview area.
4. Placeholder "**Description does not go away.**"
5. **Send button is disabled even after I wrote a ticket.**

Source code,
1. initializing ZDKConfig

    [[ZDKConfig instance] initializeWithAppId:SKZendeskAppID zendeskUrl:SKZendeskURL clientId:SKZendeskClientID];

2. Setting up Identity.
ZDKAnonymousIdentity *identity = [ZDKAnonymousIdentity new];
        if (user)
        {
            identity.name = user.name;
            identity.email = user.email;
        }
        [ZDKConfig.instance setUserIdentity:identity];

3. Opening support View controller
ZDKHelpCenter.push(with: self.navigationController, filterBySectionId: "PLACEHOLDER_TEXT", sectionName: "Support", layoutGuide: ZDKLayoutRespectBottom)

![img_4799](https://user-images.githubusercontent.com/9776703/27244500-a85b73d4-529b-11e7-9b24-167f02ab876f.PNG)

**Comment by AnujD7781** [comment]
Fixed.....

**Comment by nsomar** [comment]
Hello @AnujD7781,

I am glad that this issue was fixed :)
I'll be closing the issue now, feel free to contact us if you face any other issue.

**Comment by batjo** [comment]
I'm running into the same issue, do you remember how you fixed it?

**Comment by AnujD7781** [comment]
@batjo I had an Obj-C category for UITextView to add placeholder text, which caused this issue to occur. I believe it was interfering with Zendesks own placeholder logic. Tested after removing that call and it started working just fine.
