### ISSUE TITLE
how to send a request to specific organization ?

### ISSUE THREAD

**Issue by PatrickSCLin** [zendesk/zendesk_sdk_ios#301]
- SDK version: 1.9.2.2
- Xcode version: 8.3.3
- iOS or Simulator: iphone 6
- iOS Version: 10.3.2
- Swift version: Swift 3

How to send a request to specific organization ?
I'm only able to send a request to main dashboard for now, I can see a request from organization only when the sender as a member of organization, but I don't think that is best solution.

Is possible to send a request to specific organization by iOS SDK?

**Comment by RonanMcH** [comment]
Hi @PatrickSCLin ,
It is not possible to configure tickets from the SDK to a specific organization. It is possible to configure other aspects of the ticket from the SDK which are detailed [here](https://developer.zendesk.com/embeddables/docs/ios/requests#in-your-code).
I hope this helps,
Ronan.
