### ISSUE TITLE
new crash with 1.10.0.1 in ZDKRequestExecutor.m

### ISSUE THREAD

**Issue by jaz-ah** [zendesk/zendesk_sdk_ios#306]
- SDK version: 1.10.0.1
- Xcode version: 8.3.3
- iOS or Simulator: iOS
- iOS Version: (multiple)
- Swift version: 3

Found this crash starting to ramp up with our new release that included the sdk above:

<img width="935" alt="screen shot 2017-07-07 at 7 28 42 am" src="https://user-images.githubusercontent.com/13263369/27962185-f1c02d8a-62e5-11e7-8b3f-db7ad4643507.png">

We will probably have to revert to an older sdk unless you have a fix shortly - thanks.

**Comment by brendan-fahy** [comment]
Hey @jaz-ah, thanks for reporting this, we'll check into it and get back to you.

**Comment by tecknut** [comment]
@jaz-ah can you provide us with the code you've written to integrate the SDK? 

It might help us figure out what's happening. 

Additionally, have you managed to reproduce this on a dev build of your app?

**Comment by jaz-ah** [comment]
@tecknut I can't reproduce this locally

It looks like most crashes occur after executing this code to show the category list:

            provider.getCategoriesWithCallback { (categories, error) in
                self.activityIndicator.isHidden = true
                self.loadingData = false
                if error == nil {
                    self.categories = categories as! [ZDKHelpCenterCategory]
                    self.tableView.reloadData()
                } else {
                    Message.showFromViewController(self, message: ZendeskCSModule_LPVars.sharedInstance.helpCenterErrorMessage?.stringValue(), title: ZendeskCSModule_LPVars.sharedInstance.helpCenterErrorTitle?.stringValue())
                }
            }

where provider is:
    var provider:ZDKHelpCenterProvider

**Comment by jaz-ah** [comment]
Hi @tecknut any update? do you need any other info?

**Comment by tecknut** [comment]
We've been trying to reproduce this here We haven't been able to so far. 

If you have any more info please send it on. 

Thank you

**Comment by jaz-ah** [comment]
@tecknut one hint is that fabric says app is in focus only 15% of the time when this occurs - so possibly could be related to app getting backgrounded in middle of the zendesk call?

**Comment by tecknut** [comment]
Ok great, we'll try backgrounding a bunch of times and see if we can cause and break on the exception. It's out of office ours here in Ireland, so we wont have an update till at least tomorrow. Hopefully we can track this down.

**Comment by RonanMcH** [comment]
Hi @jaz-ah ,
We think we may have a route cause for the crashes you are experiencing but still cannot manage to replicate it exactly.  We would like you to open a ticket on [Zendesk Support](https://support.zendesk.com/hc/en-us/requests/new) so we can obtain more information about the crash from you on a less public channel (as some information may be sensitive).  Please link this issue in the ticket and paste the crash report and mention that you were talking to one of the Mobile SDK devs. We will keep an eye out for it and escalate it.
Thanks,
Ronan.

**Comment by jaz-ah** [comment]
@RonanMcH ok just did it thx.

**Comment by RonanMcH** [comment]
We have released version 1.10.1.1 of the SupportSDK with what we think will fix this issue. 
We are continuing this dialog in a ticket so I am going to close this issue.
