### ISSUE TITLE
Deprecation Error

### ISSUE THREAD

**Issue by aaronvegh** [zendesk/zendesk_sdk_ios#307]
- SDK version: 1.10.0.1
- Xcode version: 8.3.3
- iOS or Simulator: Both
- iOS Version: 10.3
- Swift version: 3

Steps to Reproduce:

1. Turn on deprecation warnings in Build Settings
2. Build.
3. Look at error:

```
/Pods/ZendeskSDK/ZendeskSDK.framework/Headers/ZDKRMADialogView.h:110:5: 'ZDKRMATableHeaderView' is deprecated: Deprecated as of 1.10.0.1, this will be removed.
```

**Comment by tecknut** [comment]
Hey @aaronvegh, you must have `treat warnings as errors` turned on. 

All of the `ZDKRMA**` namespace is now a deprecated API. We have a number of APIs which are currently marked as deprecated.

You may need to change your Xcode build settings so that deprecations are warnings only.

**Comment by aaronvegh** [comment]
With all due respect, you should use your position as a vendor-provided service to adopt best practices. Using your SDK should not require adoptees to weaken their own code. I'd suggest you either remove your deprecation warnings or clean up the code to remove the dependency. Thank you.

**Comment by tecknut** [comment]
On investigating this issue we found that the issue was only present for us on fresh pod installs in a project and only when running build. Building again after encountering the error succeeded.

It's possible to have `treat warnings as errors` affect only the pods target. Doing so will not weaken the code of an integrator. 

This post install hook resolves the issue: 

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name.start_with?('Pods-')
      puts "Updating #{target.name} SWIFT_TREAT_WARNINGS_AS_ERRORS to NO"
      target.build_configurations.each do |config|
        xcconfig_path = config.base_configuration_reference.real_path
        xcconfig = File.open(xcconfig_path, "a") { |file| file.write("SWIFT_TREAT_WARNINGS_AS_ERRORS = NO") }
      end
    end
  end
end
```
