### ISSUE TITLE
Possible to add custom UIBarButton items to help center nav bar?

### ISSUE THREAD

**Issue by bryanboyko** [zendesk/zendesk_sdk_ios#308]
- SDK version: 1.9.2.2
- Xcode version: 8.3.3
- iOS or Simulator: 
- iOS Version: 10.3.2
- Swift version:

Steps to Reproduce:

1. Add BarButtonItems to UINavigationController *navController before injecting to [ZDKHelpCenter pushHelpCenterOverview:navController withContentModel:helpCenterContentModel]; 
2. When help center is shown, default Zendesk navigation appearance shows instead of the buttons I added to the navController.navigationItem. 

Is it possible to add custom UIBarButtonItems to the help center navigation bar?
If not, is it possible to customize bar button fonts? (I was only able to change their color using [UINavigationBar appearance] as listed in Zendesk iOS SDK docs)

**Comment by baz8080** [comment]
Hi @bryanboyko 

We offer some limited control over the right button, which you can change to an image if you wish. You will need to implement the `ZDKHelpCenterConversationsUIDelegate` protocol, and then set it as the delegate of `ZDKHelpCenter `.  We have some [documentation here](https://developer.zendesk.com/embeddables/docs/ios/help_center#disable-requests).

We also allow changing [some font settings](https://developer.zendesk.com/embeddables/docs/ios/customize_the_look#change-the-fonts-of-the-ui), but not the ones that you are looking for.

If you wish to go for a completely custom UI, then we have an API layer that you can build upon.

https://developer.zendesk.com/embeddables/docs/ios/api_providers
https://developer.zendesk.com/embeddables/docs/ios/help_center#additional-methods-api-providers

Thanks!

**Comment by thewodros** [comment]
Hi, 
Question related to nav bar items. I am using the v2 iOS Zendesk SDK and I was able to configure help center, contact us (request), and my ticket (requestList) screens. The compose message button in the nav bar (right item) is not clickable i.e. cannot initiate the contact us screen when this button is pressed. How do you enable this right nav bar item?
