### ISSUE TITLE
Error updating to 1.10.0.1 from 1.9.2.2

### ISSUE THREAD

**Issue by bryanboyko** [zendesk/zendesk_sdk_ios#309]
- SDK version: 1.10.0.1
- Xcode version: 8.3
- iOS or Simulator: iOS
- iOS Version: 10.3
- Swift version: no

Steps to Reproduce:

1. Update from ZendeskSDK pod 1.9.2.2 to 1.10.0.1
2. Pod install and try to build project
3. Note error 'Could not build module 'ZendeskSDK -> ZDKRMATableHeaderView' is deprecated: Deprecated as of 1.10.0.1, this will be removed.'

4. Remove all code in project related to Zendesk except for single import of <ZendeskSDK/ZendeskSDK.h>
5. Delete Pods and remove derived data 
6. Pod install and run project
7. Note error 'Could not build module 'ZendeskSDK -> ZDKRMATableHeaderView' is deprecated: Deprecated as of 1.10.0.1, this will be removed.'

Is there something I can do to fix this?

**Comment by tecknut** [comment]
Hey @bryanboyko, there is a post install hook you can use. 

Detailed here https://github.com/zendesk/zendesk_sdk_ios/issues/307#issuecomment-314474539
