### ISSUE TITLE
Status bar of Image Picker is constantly using black color.

### ISSUE THREAD

**Issue by xareelee** [zendesk/zendesk_sdk_ios#31]
When using "contact us" (`-[ZDKRequests showRequestCreationWithNavController:]`) and using "attach files" button to pick an image for upload, the status bar in the image picker view will become black style and we have no idea how to change it to `UIStatusBarStyleLightContent`.

**Comment by xareelee** [comment]
I've tried to fix this issue by myself using aspect-oriented programming. This issue has been discussed in [here](http://stackoverflow.com/questions/18880364/uiimagepickercontroller-breaks-status-bar-appearance), but I think you can try fix this issue in Zendesk too. A **non-aspect-oriented** sample code is here (untested):

```
@implementation ZDKCreateRequestViewController (Fix)

- (void) navigationController:(UINavigationController *)navigationController willShowViewController:(UIViewController *)viewController animated:(BOOL)animated
{
  [super navigationController:navigationController willShowViewController:viewController animated:animated];
  // get info.plist
  NSDictionary *infoDictionary = [[NSBundle mainBundle] infoDictionary];
  
  
  // View controller-based status bar appearance
  NSNumber *viewControllerBasedStatusBarAppearance = infoDictionary[@"UIViewControllerBasedStatusBarAppearance"];
  BOOL useNonViewControllerBasedStatusBarAppearance = (viewControllerBasedStatusBarAppearance &&
                                                       [viewControllerBasedStatusBarAppearance isKindOfClass:[NSNumber class]] &&
                                                       ![viewControllerBasedStatusBarAppearance boolValue]);

  if (useNonViewControllerBasedStatusBarAppearance) {
    // Use status bar style in info.plist
    NSString *statusBarStyle = infoDictionary[@"UIStatusBarStyle"];
    BOOL useStatusBarStyleLightContent = (statusBarStyle &&
                                          [statusBarStyle isKindOfClass:[NSString class]] &&
                                          [statusBarStyle isEqualToString:@"UIStatusBarStyleLightContent"]);
    UIStatusBarStyle style = useStatusBarStyleLightContent? UIStatusBarStyleLightContent: UIStatusBarStyleDefault;
    [[UIApplication sharedApplication] setStatusBarStyle:style];
  }
}

@end
```

**Comment by venom889** [comment]
Was also having this issue. It seems to be fixed in iOS 9 beta 4. I couldn't get your example to compile though. I had to change:

```[super navigationController:navigationController willShowViewController:viewController animated:animated];```

to

```[super.navigationController.delegate navigationController:navigationController willShowViewController:viewController animated:animated];```

**Comment by tecknut** [comment]
Fixed in current version
