### ISSUE TITLE
Cannot attach to request with Support SDK

### ISSUE THREAD

**Issue by bryanboyko** [zendesk/zendesk_sdk_ios#311]
SDK version: 1.10.0.1
Xcode version: 8.3
iOS or Simulator: iOS
iOS Version: 10.3
Swift version: no

Steps to Reproduce:

ZDKRequestCreationConfig does not have a property with which attachments can be added

@interface ZDKRequestCreationConfig : NSObject {

    NSArray *tags;
    NSString *additionalRequestInfo;
    NSString *subject;

}

Is there another way to add an attachment to a request so that the request can be shown with 

[ZDKRequests presentRequestCreationWithViewController:viewController];

??

(ideally I won't have to dip into API providers to add an attachment)

**Comment by tecknut** [comment]
@bryanboyko currently 
```
[ZDKRequests presentRequestCreationWithViewController:viewController];
```
 will display an option add attachments if attachments are enabled in your Zendesk instance.

If you're certain that your instance is configured with attachments enabled and you're not able to attach anything, you may need to [open a request](https://support.zendesk.com/hc/en-us/requests/new) to check if there is an issue with the configuration of your instance.

Can you check if end users are allowed to attach files in your admin settings?

**Comment by bryanboyko** [comment]
Sorry I should have been more clear. 

Yes the little blue paperclip shows up when the request UI is presented, but I would like to programmatically attach some info that relates to my app. 

 Is that possible?

**Comment by tecknut** [comment]
No unfortunately there is no straight forward way to do this without creating your own workflow using the API providers. 

There may be ways to hack something together using [the NSNotification](https://github.com/zendesk/zendesk_sdk_ios/blob/master/ZendeskProviderSDK.framework/Headers/ZendeskSDKConstants.h#L93) which is posted after a request is submitted. The userInfo of this notification contains the requestId.

You could use this with the [upload provider](https://github.com/zendesk/zendesk_sdk_ios/blob/master/ZendeskProviderSDK.framework/Headers/ZDKUploadProvider.h#L59) to submit a [comment with attachments](https://github.com/zendesk/zendesk_sdk_ios/blob/master/ZendeskProviderSDK.framework/Headers/ZDKRequestProvider.h#L171) an behalf of the user. 

It may be possible to get this working, but it will involved a bit of experimentation. 

It sounds like a good use case. We welcome feature requests from customers. You can submit a [feature request to our community](https://support.zendesk.com/hc/en-us/community/topics/200488257-Zendesk-SDKs) page.

Thanks

**Comment by baz8080** [comment]
I'm going to close this one for now.
