### ISSUE TITLE
Unable to subclass ZDKHelpCenterOverviewController

### ISSUE THREAD

**Issue by mad102190** [zendesk/zendesk_sdk_ios#313]
- SDK version: 1.10.0.1
- Xcode version: 8.3.3
- iOS or Simulator: Either
- iOS Version: 10.3.1
- Swift version: 3

It's impossible to subclass `ZDKHelpCenterOverviewController` because the project uses the name of the class to load the Nib file. Therefore if I try to subclass I get a crash that states that the bundle could not load the nib `MyProject.FAQViewController` (when it should actually be trying to load `ZendeskSDK.ZDKHelpCenterOverviewController`)

I need to subclass in order to change some basic things, such as the navigation bar title, the status bar color, and add a custom UIBarButtonItem to the top right of the Help Center Overview. I've found some unsafe ways to do some of these things with extensions but I don't think this is the best solution.

Would it be possible to force the Nib to load via a hardcoded value or some sort of internal method that will not be affected by subclasses?

**Comment by tecknut** [comment]
Hey @mad102190, our stock UI is not intended to be subclassed. 

The indented interaction with the stock SDK UI is to call: 
```
ZDKHelpCenter.pushOverview(self.navigationController, with:helpCenterContentModel)
``` 

We have [some styling options](https://developer.zendesk.com/embeddables/docs/ios/customize_the_look), but the customisations you're after are not supported.

If you require a more customised UI, we have [API providers](https://developer.zendesk.com/embeddables/docs/ios/api_providers). These can be used to fetch articles.

If you would like to [make a feature request on our community](https://support.zendesk.com/hc/en-us/community/topics/200488257-Zendesk-SDKs) someone on the product team will get back to you.

Thanks

**Comment by mad102190** [comment]
Even changing the status bar style (i.e. `.lightContent`) isn't supported?

**Comment by tecknut** [comment]
For the stock UI we offer the styling mentioned above. Currently status bar style is not surfaced as a styling option.

It's something which can be added, a feature request to the link above will get the ball rolling.
