### ISSUE TITLE
ZDKHelpCenterOverviewController does not respect sorting or articles 

### ISSUE THREAD

**Issue by mad102190** [zendesk/zendesk_sdk_ios#314]
- SDK version: 1.10.0.1
- Xcode version: 8.3.3
- iOS or Simulator: Either
- iOS Version: Any
- Swift version: 3

There is no way to specify the sort order of the sections in the `ZDKHelpCenterOverviewController` class. It seems to always sort them by creation date, even though we've set the sort order manually on the Zendesk help center web portal. Upon further inspection, it seems that the API is in fact specifying to sort by `created_at` (which isn't what we want).

This is the call being made by the sdk: `https://{MY_ZENDESK}.zendesk.com/hc/api/mobile/en-us/articles.json?sort_by=created_at&sort_order=desc&include=categories,sections&limit=5&per_page=1000`

How can I specify to load the sections/articles with the `position` sort flag (or any sorting of our choosing) when using `ZDKHelpCenterOverviewContentModel.defaultContent()` and ensure the ViewController respects it?

**Comment by tecknut** [comment]
Hi @mad102190 this is a [known issue](https://developer.zendesk.com/embeddables/docs/ios/version_information#1.7.1.1) with the Help Center API. 

We are currently working on a solution to the problem. 

Thanks

**Comment by mad102190** [comment]
Oh ok thanks! Do you have any idea of when the fix will be implemented?

**Comment by tecknut** [comment]
We're currently coordinating with the back end API team responsible for this. As soon as we have something stable we will draft a release.
