### ISSUE TITLE
ZDKHelpCenterOverviewHeaderView gives off warnings in console

### ISSUE THREAD

**Issue by welshm** [zendesk/zendesk_sdk_ios#315]
- SDK version:
  1.10.0.1
- Xcode version:
  8.3.3
- iOS or Simulator:
  iOS Simulator
- iOS Version:
  10.3.1
- Swift version:
  Objective-C
Steps to Reproduce:

1. Integrate ZendeskSDK
2. Create a ZDKHelpCenterOverviewController and push it inside a navigation controller

ZDKHelpCenterOverviewContentModel *model = [ZDKHelpCenterOverviewContentModel defaultContent];
  ZDKHelpCenterOverviewController *controller =
      [[ZDKHelpCenterOverviewController alloc] initWithHelpCenterOverviewModel:model];
  controller.uiDelegate = self;

CONSOLE ISSUE
[LayoutConstraints] Custom views and layout for UITableViewHeaderFooterView should be contained within the content view. Offending view: <ZDKHelpCenterOverviewHeaderView: 0x7ff1aed69810; baseClass = UITableViewHeaderFooterView; frame = (0 0; 600 44); text = ''; opaque = NO; autoresize = W+H; layer = <CALayer: 0x60000022a440>>

**Comment by welshm** [comment]
I'm also seeing issues where instantiating the controller on a non-main thread (while not accessing UI components) causes animations to start breaking, which is often an indicator of UI access on a non-main thread. Is ZDKHelpCenterOverviewController doing UI modifications during initialization?

**Comment by tecknut** [comment]
Hi @welshm have you checked our [documentation](https://developer.zendesk.com/embeddables/docs/ios/help_center#help-center-in-the-support-sdk-ui) for how to show Help Center content?

**Comment by welshm** [comment]
I have, yes. We'd prefer to show the Zendesk content as a modal so we're not using pushHelpCenterOverview but presenting a navigation controller with the ZDKHelpCenterOverviewController inside.

**Comment by tecknut** [comment]
There is also have an API for presenting Help Center as a modal. 

We've been looking into the warning which is emitted. The reference points to a static sizing view which isn't presented on screen. 

We'll keep looking into it.

**Comment by baz8080** [comment]
I'm going to close this issue. We have released [version 2.0](https://developer.zendesk.com/embeddables/docs/ios_support_sdk/nutshell) and I'd advise you to check it out.
