### ISSUE TITLE
Implementing ZDKHelpCenterConversationsUIDelegate

### ISSUE THREAD

**Issue by lucianocn** [zendesk/zendesk_sdk_ios#317]
What's the properly way to implement`ZDKHelpCenterConversationsUIDelegate`?

```objective-c
//  MyViewController.m

@interface MyViewController () <ZDKHelpCenterConversationsUIDelegate>
@end

@implementation MyViewController

- (IBAction)btnFAQ:(id)sender
{
    ZDKHelpCenterOverviewContentModel *helpCenterContentModel = [ZDKHelpCenterOverviewContentModel defaultContent];
    helpCenterContentModel.uiDelegate = self;
    // ERROR: Property 'uiDelegate' not found on object of type 'ZDKHelpCenterOverviewContentModel *'
    [ZDKHelpCenter pushHelpCenterOverview:self.navigationController withContentModel:helpCenterContentModel];
}

- (ZDKNavBarConversationsUIType)navBarConversationsUIType
{
    return ZDKNavBarConversationsUITypeNone;
}

- (ZDKContactUsVisibility)active
{
    return ZDKContactUsVisibilityArticleListOnly;
}

- (UIImage *)conversationsBarButtonImage
{
    return [UIImage imageNamed:@"conversations_image"];
}

@end
```

**Comment by tecknut** [comment]
Hey @lucianocn the value you have chosen for [UI Type](https://github.com/zendesk/zendesk_sdk_ios/blob/master/ZendeskProviderSDK.framework/Headers/ZDKHelpCenterConversationsUIDelegate.h#L33) will result in no nav bar button. Enum is used to chose between a text bar button, an image bar button or no button. 

If you want a text bar button [add this](https://github.com/zendesk/zendesk_sdk_ios/blob/master/ZendeskProviderSDK.framework/Headers/ZDKHelpCenterConversationsUIDelegate.h#L85) method and return a string. 

If you want a localised string you can use the one we provide. 
```
- (NSString *)conversationsBarButtonLocalizedLabel {

    return [ZDKLocalization localizedStringWithKey:@"ios.ZDKRequests.rightBarButton.title.contact"];
}
```

`ZDKContactUsVisibilityArticleListOnly` means the bar button will only be on the initial list of articles, not on the articles themselves. 

Hope that helps.

**Comment by lucianocn** [comment]
@tecknut The problem is how to use the delegate presenting the modal with `ZDKHelpCenterOverviewContentModel` :

```objective-c
- (IBAction)btnFAQ:(id)sender
{
    ZDKHelpCenterOverviewContentModel *helpCenterContentModel = [ZDKHelpCenterOverviewContentModel defaultContent];
    helpCenterContentModel.uiDelegate = self;
    // ERROR: Property 'uiDelegate' not found on object of type 'ZDKHelpCenterOverviewContentModel *'
    [ZDKHelpCenter pushHelpCenterOverview:self.navigationController withContentModel:helpCenterContentModel];
}
```


Tks.

**Comment by tecknut** [comment]
There is a method on [ZDKHelpCenter](https://github.com/zendesk/zendesk_sdk_ios/blob/master/ZendeskSDK.framework/Headers/ZDKHelpCenter.h#L81).

**Comment by lucianocn** [comment]
@tecknut thanks, that's exactly what I was looking for!
