### ISSUE TITLE
Support SDK: Possible to tell if a request was submitted or cancelled?

### ISSUE THREAD

**Issue by bryanboyko** [zendesk/zendesk_sdk_ios#318]
SDK version: 1.10.0.1
Xcode version: 8.3
iOS or Simulator: iOS
iOS Version: 10.3
Swift version: no

Is there a way to determine if a request was submitted or cancelled after calling presentRequestCreationWithViewController: from the support SDK?

**Comment by tecknut** [comment]
Hey @bryanboyko there is a series of [notifications](https://github.com/zendesk/zendesk_sdk_ios/blob/master/ZendeskProviderSDK.framework/Headers/ZendeskSDKConstants.h#L93) posted.
