### ISSUE TITLE
[NF] ZDKHelpCenter.h implement hidesBottomBarWhenPushed

### ISSUE THREAD

**Issue by lucianocn** [zendesk/zendesk_sdk_ios#319]
It would be nice to `ZDKHelpCenter.h` has an option to set `hidesBottomBarWhenPushed = YES;` when pushing viewControllers.

```objective-c
nextViewController.hidesBottomBarWhenPushed = YES;
```

**Comment by nsomar** [comment]
Hello @lucianocn,

I have logged an issue in our internal backlog to track this issue. 
I will keep this issue open for future updates.

Thanks,

**Comment by baz8080** [comment]
I'm going to close this one for now. We have this tracked internally. We now take [feature requests in our forum](https://support.zendesk.com/hc/en-us/community/topics/200488257-Zendesk-SDKs) rather than on Github.
