### ISSUE TITLE
ZDKRequestProvider:createRequest:withCallback:

### ISSUE THREAD

**Issue by ehlersd** [zendesk/zendesk_sdk_ios#320]
- SDK version: Using ZendeskSDK (1.10.0.1)
- Xcode version: Using Xcode9b4
- iOS or Simulator: Both
- iOS Version: iOS10 & iOS11b4
- Swift version: Using ObjC

Steps to Reproduce:

When dealing with networking failures, the timeout seems a bit long with no feedback.  Is there a way to alter the timeout value used by the SDK?

**Comment by nsomar** [comment]
Hell @ehlersd,

At the moment there is no way to set the response timeout for network calls. I created an issue in our internal backlog to expose a way to change the request timeout.

I will keep this issue open for update porpuses.

**Comment by baz8080** [comment]
Hi @ehlersd 
I've discussed this with our PM and we are not going to expose this to integrators. If you'd like to talk more about it, then we have a [forum where both PMs and developers participate](https://support.zendesk.com/hc/en-us/community/topics/200488257-Zendesk-SDKs).
