### ISSUE TITLE
Crash w/ ZDKCommentsTableViewDelegate.m

### ISSUE THREAD

**Issue by jaz-ah** [zendesk/zendesk_sdk_ios#321]
- SDK version: 1.10.1.1
- Xcode version: 8.3.3
- iOS or Simulator: iOS
- iOS Version: 10.x (multiple versions of 10.0)
- Swift version: 3

Steps to Reproduce:

Getting this crash showing up in crashlytics;

Fatal Exception: NSRangeException*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array Raw Text
--
0 | CoreFoundation | __exceptionPreprocess
2 | CoreFoundation | -[__NSArrayM removeObjectAtIndex:]
3 | Activehours | ZDKCommentsTableViewDelegate.m line 93-[ZDKCommentsTableViewDelegate tableView:didSelectRowAtIndexPath:]
4 | UIKit | -[UITableView _selectRowAtIndexPath:animated:scrollPosition:notifyDelegate:]
14 | UIKit | UIApplicationMain

Interestingly enough, "app in focus" is showing 0% so this potentially happens when app is backgrounded and user is interacting with the zendesk tickets.. seems like an easy case to check for in that delegate method..

**Comment by baz8080** [comment]
Hi @jaz-ah I didn't have any luck in reproducing the issue, but you're right that it's a clear case that we can check for. How often is this crash happening?

**Comment by jaz-ah** [comment]
about 1-2/day.

**Comment by tecknut** [comment]
Hey @jaz-ah, thanks for the crash rate. 

I'm curious about this happening in the background when the crash happening in table view delegate methods which should only be called from user interaction. 

Is there any more detail you can provide us about the crash? 

If it's not possible to share here please [open a ticket with us](https://support.zendesk.com/hc/en-us/requests/new).

**Comment by jaz-ah** [comment]
unfortunately no more details -I'm just getting this from crashlytics - my guess from prior experience is a user is interacting with the zendesk support area and accidentally fat fingers the home button to background the app .. sometimes happens when people are taking pictures of the screen as well...

**Comment by baz8080** [comment]
@tecknut @jaz-ah I was trying my best to fat-finger and reproduce this. I think the timing might be quite tricky to reproduce.

**Comment by jaz-ah** [comment]
@baz8080 probably hard to repro - I've seen these before in many other apps i've developed and best thing is to just put a bounds check in there

**Comment by divo** [comment]
@jaz-ah We are unable to repo this. I've added it to our backlog to keep track of it.
If you come up with any steps to repo then please let us know.

**Comment by jaz-ah** [comment]
@divo probably will never get repro steps, just continued reports of the crash in crashlytics - since the backtrace is so obvious, any chance at adding a bounds check in there?

**Comment by mathewcropper** [comment]
Hey @jaz-ah. We're currently working on giving the UI a facelift, so we'll add this as one of the requirements/test cases. It's a longer term piece of work than a quick fix, though, so it'll be a little while before it's out. 

We won't be making updates to the existing UI in the meantime, so this is a _won't fix_ for this version of the SDK, I'm afraid. It is something you can look out for in a later feature release this year.

**Comment by tecknut** [comment]
Hi @jaz-ah we just released version 2 of the SDK which resolves this issue. The request UI has been completely reworked.

Thank you,
Alan
