### ISSUE TITLE
conversationsBarButtonImage on ZDKHelpCenterConversationsUIDelegate should be optional

### ISSUE THREAD

**Issue by chrismanderson** [zendesk/zendesk_sdk_ios#322]
- SDK version: 1.10.1.1
- Xcode version: 8.3.3
- iOS or Simulator: 10.3
- iOS Version: 10.3
- Swift version: 3

Steps to Reproduce:

I want to set the the `ZDKNavBarConversationsUIType` to `ZDKNavBarConversationsUITypeNone` via conforming to the `ZDKHelpCenterConversationsUIDelegate`. That should mean I don't need to provide a `conversationsBarButtonImage`, correct? But, that method is not only a required protocol method, it returns a `UIImage!` so I can't even return nil from it. This method should be an optional protocol method, or at the least, return an `UIImage?`.

**Comment by eepDev** [comment]
Hi @chrismanderson,

Thanks for pointing this out to us. I've created an issue for us to track this internally and will keep you posted on any updates.

**Comment by KillianSmith0** [comment]
@chrismanderson we've released a new version of our SDK (v2.0.4), this delegate method is now optional.
