### ISSUE TITLE
Infinite loop inside Zendesk SDK on iOS 11

### ISSUE THREAD

**Issue by mxcl** [zendesk/zendesk_sdk_ios#324]
- SDK version: 1.10.1.1
- Xcode version: 9b6
- iOS or Simulator: *hang* confirmed on both.
- iOS Version: Xcode 9b6 iOS 11 simulator
- Swift version: 3.2

Steps to Reproduce:

1. `guard let nc = navigationController else { return }`
2. `ZDKHelpCenter.pushOverview(nc, with: ZDKHelpCenterOverviewContentModel.defaultContent())`
3. Infinite loop

The Zendesk SDK infinitely loops on iOS 11 with the above code. A screenshot of the loop is attached below.

<img width="563" alt="screen shot 2017-09-07 at 12 09 44 pm" src="https://user-images.githubusercontent.com/58962/30173735-b808aeb6-93c6-11e7-9415-8875f69a6930.png">

The code works on iOS 10.

Our `ZDKConfig.instance()` is `.initialize`’d (per the documentation) in our `AppDelegate`.

Update: same with `.presentOverview`.
Update: Tried setting theme backgroundColors just in case it helps and it did not:

```
let theme = ZDKTheme.base()
theme.primaryBackgroundColor = .red
theme.emptyBackgroundColor = .red
theme.secondaryBackgroundColor = .red
theme.apply()
```

Update: this only occurs when compiling with Xcode 9, as our existing app on the store works on iOS 11 without this hang.

**Comment by tecknut** [comment]
Hey @mxcl thanks for reporting this. We've seen something like this occur previously when the [bundles are missing at run time](https://support.zendesk.com/hc/en-us/community/posts/115008714768-Crash-trying-to-present-Help-Center
).

Could you try two things for us?
- Can you enable logging and post the SDK logs up to the point of the crash?
- Can you check inside the contents of the `.app` after building to verify that the bundles are present when you build with Xcode 9? 

We're looking into this here on our end, but we're based in Ireland so most of the team are at home. We were planning to put out an iOS 11 patch release in the morning. We'll hold off on the release until this issue is resolved. 

Thanks, 
Alan

**Comment by tecknut** [comment]
Hey @mxcl have you had a chance to look at this again?

**Comment by RonanMcH** [comment]
Hi @mxcl ,
I am going to tentatively close this issue. Please feel free to reopen it if this is still an issue for you.
Thanks,
Ronan.

**Comment by mxcl** [comment]
I use CocoaPods to install Zendesk. Probably is the bundle issue, since it worked randomly once recently, but is not working again. Only started happening since Xcode 9.

**Comment by mxcl** [comment]
Strangely the framework nor bundles are embedded by CocoaPods.

<img width="1059" alt="screen shot 2017-09-29 at 6 34 26 pm" src="https://user-images.githubusercontent.com/58962/31038458-df231830-a544-11e7-881f-5a0ffce63014.png">

My Podfile is not complicated at least here:

```

target 'Poncho' do
  alamofire
  pod 'KVOController', '~> 1.2'
  pod 'MGSwipeTableCell', '~> 1.5'
  pod 'PhoneNumberKit', '~> 1.2'
  pod 'FBSDKCoreKit', '~> 4'
  mixpanel
  pop
  promisekit
  pod 'ReachabilitySwift', '~> 3.0'
  sentry
  pod 'Adjust', '~> 4.11.4'
  yyimage
  pod 'ZendeskSDK', '~> 1.10'
end
```

I'll keep investigating, but it seems odd that Zendesk is in the pods project (see screenshot) yet doesn't get explicitly embedded.

Also have no idea how it is even linking.

**Comment by divo** [comment]
@mxcl Are you still seeing this? Can you check/post the contents of your built app? The SDK bundles should be inside it.

![screen shot 2017-10-02 at 16 31 48](https://user-images.githubusercontent.com/9431616/31085510-454e9750-a78f-11e7-9907-51f25b3b96b6.png)

**Comment by mxcl** [comment]
> Everything worked as expected when I tried it.

Yes, well this is clearly a sporadic (it has worked sometimes), issue that only effects Xcode 9 (only started happening with Xcode 9) and is caused somehow by CocoaPods (possibly because we have 3 extensions, an iOS app and a watch app in this project).

So I don't think the bug is with you, though potentially how your `.podspec` works is a problem.

Really I am only continuing to advise so you are aware of it in case other people get it, will advise when I figure out the problem or more details though.

Possibly it is something wrong in my project. But I'm at a loss to say precisely what that would be.

I've read some material that suggests this sort of issue with CocoaPods is old in fact, but I've not narrowed it down yet.

**Comment by mxcl** [comment]
K I have had the preview build system on (makes 2.5 minute iterative debug cycles happen in seconds, so… it was hard to resist).

I turned it off and the archive I build works.

However, this is one data point, it may be a red-herring and building archives takes too long to run another test until I need to. Just keeping you informed.

**Comment by mu99el** [comment]
Hey guys have this issue, too. Started this week with Xcode 9 and iOS 11 and get an infinite loop when trying to present the Help Center with "ZDKHelpCenter.presentOverview()". Its the same loop like mxcl.

ZendeskSDK version: 1.11.1.1
Xcode version: 9.0 (9A235)
iOS Version: iOS 11.0
Swift version: 3.2

<img width="701" alt="screen shot 2017-10-11 at 11 30 39" src="https://user-images.githubusercontent.com/881762/31432763-aa32a4a6-ae77-11e7-8439-c1a1933b773b.png">

**Comment by mxcl** [comment]
I have archived the app twice now and turning off the preview build system before archiving fixed it both times.

**Comment by divo** [comment]
@mu99el are you using the new build system too?

**Comment by mu99el** [comment]
Yes I do. Did not read your messages correctly. Switching to "Standard Build System (Default)" helps. Thanks guys!

**Comment by divo** [comment]
@mxcl can you please check the contents of your built app. Please.

**Comment by mxcl** [comment]
@divo my computer died so I lost all my archives, next time I’m archiving I'll deliberately leave the preview setting on and report back.

**Comment by divo** [comment]
@mxcl Great, thanks!

**Comment by mxcl** [comment]
No longer happens with Xcode 9.1’s preview build system.

**Comment by baz8080** [comment]
@mxcl Great, thanks for letting us know. I'll close the issue.

**Comment by xGoPox** [comment]
Guys, I am using Xcode 9.2, iOS 11.2 and I am facing the exact same issue.
