### ISSUE TITLE
Carthage Support?

### ISSUE THREAD

**Issue by dmiluski** [zendesk/zendesk_sdk_ios#326]
- SDK version:
- Xcode version:
- iOS or Simulator:
- iOS Version:
- Swift version:

Steps to Reproduce:
I've found Carthage to be an overall cleaner integration method that CocoaPods which has been removed from our project completely. I would really appreciate it, if Zendesk offered a Carthage integration solution.

https://github.com/Carthage/Carthage

1. 
2.

**Comment by baz8080** [comment]
Hi @dmiluski 

It's on our radar, please see https://github.com/zendesk/zendesk_sdk_ios/issues/137 for more details. I'm going to close this now because we use Github issues for bugs only. Thanks!
