### ISSUE TITLE
StatusBar style

### ISSUE THREAD

**Issue by mrengine** [zendesk/zendesk_sdk_ios#327]
- SDK version: 1.11.0.1
- Xcode version: 9
- iOS or Simulator: Simulator / Device
- iOS Version: 11
- Swift version: 3

Hi,
How can i change status bar style? It's always .default (black). I need to change it to .light

```
let helpCenterContentModel = ZDKHelpCenterOverviewContentModel.defaultContent()
ZDKHelpCenter.presentOverview(controller, with: helpCenterContentModel)
```

controller has .light style, but when ZDK appears it become .default

**Comment by divo** [comment]
@mrengine The SDK shouldn't modify the status bar style. How are you styling it?

**Comment by RonanMcH** [comment]
HI @mrengine ,
Since we haven't heard from you in a while I am going to tentatively close this issue. Feel free to reopen it if this is still an issue for you.
Thanks,
Ronan.

**Comment by devedup** [comment]
I have the same issue. The issue is that the status bar will revert to .default style. You would normally provide:

`override var preferredStatusBarStyle: UIStatusBarStyle {
        return .lightContent
    }`

on your custom view controller. There seems to be no obvious way to do this with the Zendesk 1.11.2.1 SDK
