### ISSUE TITLE
iPhone X spacing issue

### ISSUE THREAD

**Issue by rhaining** [zendesk/zendesk_sdk_ios#328]
- SDK version: 1.11.0.1
- Xcode version: 9
- iOS or Simulator: iPhone X
- iOS Version: 11
- Swift version: 3.2

Steps to Reproduce:

1. View an existing support ticket. 
1. Tap the comment field to display the keyboard.

<img width="205" alt="iphonexuiissue" src="https://user-images.githubusercontent.com/462870/30919836-8c49ea06-a370-11e7-9227-0f9399c0c27b.png">

**Comment by rhaining** [comment]
@RonanMcH does the 1.11.11.1 release fix the iPhone X layout issues? thanks!

**Comment by divo** [comment]
@rhaining 1.11.11.1 does not fix these issues.

This is concerning. I have added it to our backlog. We will aim to get a fix out by the end of the month.

Thanks for reporting this issue.

**Comment by rhaining** [comment]
@divo thanks! for what it's worth, i've had success fixing issues like this by updating the view's top/bottom anchors to be relative to the `layoutMarginsGuide` (in this case, it'd be that view that encompasses the comment text view, etc)

**Comment by divo** [comment]
Thanks for the tip, I'll add it to the story.

**Comment by RonanMcH** [comment]
Hi @rhaining ,
We just released version 1.11.2.1 of the Zendesk SDK with iPhoneX spacing issues fixed. 
Thanks,
Ronan.

**Comment by rhaining** [comment]
awesome, thanks @RonanMcH! 

would it be possible to get some sort of release notes in the releases? or is there somewhere else outside of github y'all have those sorts of change logs? thanks!!

**Comment by RonanMcH** [comment]
Hi @rhaining ,
We post our release notes [here](https://developer.zendesk.com/embeddables/docs/ios/version_information)
