### ISSUE TITLE
Custom Chat bubble

### ISSUE THREAD

**Issue by hamzakhanfcb10** [zendesk/zendesk_sdk_ios#333]
How to change chat bubble color

**Comment by brendan-fahy** [comment]
Hi @hamzakhanfcb10, it sounds like you're talking about [our Chat SDK](https://github.com/zendesk/zendesk_sdk_chat_ios), though this is actually the Support SDK repo. Have you looked at our Chat SDK [UI customisation docs](https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/customization)?

**Comment by hamzakhanfcb10** [comment]
Hey Brendan,

Thanks for the reply. I went inside your library and found out chat bubbles property and that worked.
