### ISSUE TITLE
iPhone X Bottom Bar Spacing Issues: Articles & Tickets

### ISSUE THREAD

**Issue by rhaining** [zendesk/zendesk_sdk_ios#334]
- SDK version: 1.11.0.1
- Xcode version: 9.1
- iOS or Simulator: simulator
- iOS Version: 9.1
- Swift version: 3.2

Steps to Reproduce:

1. View article or view tickets
2. black area at bottom of teh X simulator

<img width="469" alt="zendeskbug-bottombar" src="https://user-images.githubusercontent.com/462870/32004964-15502bba-b971-11e7-842d-6ab66eeaf9b6.png">
<img width="470" alt="zendeskbug-bottombar2" src="https://user-images.githubusercontent.com/462870/32004965-16104076-b971-11e7-8f2b-388f305f175d.png">

**Comment by RonanMcH** [comment]
HI @rhaining ,
We just released version 1.11.2.1 of the Zendesk SDK today with fixes for iphoneX layout issues. This was included in the fixes. 
Thanks,
Ronan.

**Comment by tecknut** [comment]
@rhaining Has the release solved this issue for you?
Thanks

**Comment by rhaining** [comment]
@tecknut yes it looks good! thanks so much!
