### ISSUE TITLE
Crash when creating ticket with wrong authentication method

### ISSUE THREAD

**Issue by senatorsfc** [zendesk/zendesk_sdk_ios#336]
We are in the process of migrating from Anonymous authentication to JWT authentication on the iOS SDK, and we've run into this issue.

- SDK version: 1.11.2.1
- Xcode version: 9.1
- iOS or Simulator: Both
- iOS Version: 11

Steps to Reproduce:

1. Set SDK Authentication Configuration from Zendesk Web Backoffice to Anonymous
2. Client is setup with JWTAuthentication
3. Present Ticket Creation Request. Once "New" is pressed ,the app crashes with the following stacktrace 

> 	0   CoreFoundation                      0x000000011a2dc1ab __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000118d46f41 objc_exception_throw + 48
	2   CoreFoundation                      0x000000011a35ca34 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000011a25f0a8 ___forwarding___ + 1432
	4   CoreFoundation                      0x000000011a25ea88 _CF_forwarding_prep_0 + 120
	5   Hushed-Staging                      0x000000010dd15e2a +[ZDKRequestEmailUtils isEmailRequiredWithConversationEnabled:config:] + 122
	6   Hushed-Staging                      0x000000010dd24db0 -[ZDKCreateRequestViewController isEmailRequired] + 86
	7   Hushed-Staging                      0x000000010dd24ccd -[ZDKCreateRequestViewController updateSubmitButtonState] + 171
	8   Hushed-Staging                      0x000000010dd23c70 -[ZDKCreateRequestViewController initWithNibName:bundle:] + 688
	9   Hushed-Staging                      0x000000010dd1c315 -[ZDKRequestListViewController showContact] + 37

**Comment by RonanMcH** [comment]
Hi @senatorsfc ,
I think I have seen this issue before. Will you try delete your app from the simulator/device and reinstall it? Also delete your `build` folder and `derivedData`. I think this should fix it. This issue is with running an app that has been used with `ZDKAnonymousIdentity` and is now being used with `ZDKJwtIdentity`! Let me know if it works!
Thanks,
Ronan.

**Comment by baz8080** [comment]
Hi @senatorsfc We haven't heard back from you in a while, so I'm going to close the issue. Please reopen it if you still need help.
