### ISSUE TITLE
Help center searchBar.  Black text, but want white .. :(

### ISSUE THREAD

**Issue by MaximusMcCann** [zendesk/zendesk_sdk_ios#337]
- SDK version: 1.11.2.1
- Xcode version: 9.1
- iOS or Simulator: iPhone 5s 11.1 Simulator
- iOS Version: 11.1
- Swift version: 4

How can I change the UISearchBar text color/tint color?  It's not taking the tint colors I've set :(
-I've tried setting every color here: https://developer.zendesk.com/embeddables/docs/ios/customize_the_look#change-the-colors-of-the-ui , but with no luck.
-I've tried setting every `UIBarStyle`, but with no luck.
-I've tried changing the UINavigationController `backgroundColor`, `tintColor`, `barTintColor`, but with no luck.
-I've tried `UITextField.appearance(whenContainedInInstancesOf: [UISearchBar.self]).backgroundColor`, but with no luck.
I set everything I could find to red, but am not sure where the font color is coming from :/.  Please help.

![image](https://user-images.githubusercontent.com/1643285/32568377-ab13aa10-c483-11e7-8402-548fc3008af2.png)

Our tintColors are white:
![image](https://user-images.githubusercontent.com/1643285/32568370-a1bc2956-c483-11e7-8e98-83cb27f22446.png)

Setting in this fashion

```
        Router.navController.viewControllers.removeAll()
        let helpCenterContentModel = ZDKHelpCenterOverviewContentModel.defaultContent()
        ZDKHelpCenter.pushOverview(Router.navController, with: helpCenterContentModel)
```

**Comment by divo** [comment]
@MaximusMcCann we are looking into this but so far we think it is an issue with iOS
https://developer.zendesk.com/embeddables/docs/ios/version_information#1.11.2.1
https://openradar.appspot.com/34376509

**Comment by MaximusMcCann** [comment]
cheers

**Comment by mxcl** [comment]
Here's `UIAppearance` methods to change the text color.

```
        let proxy2 = UITextField.appearance(whenContainedInInstancesOf: [UISearchBar.self, UINavigationController.self])
        proxy2.attributedPlaceholder = NSAttributedString(string: "Search", attributes: [
            .foregroundColor: UIColor(white: 1, alpha: 0.5),
            .font: UIFont(.brandon(.medium), size: 17)
        ])
        proxy2.defaultTextAttributes = [
            NSAttributedStringKey.foregroundColor.rawValue: UIColor.white,
            NSAttributedStringKey.font.rawValue: UIFont(.brandon(.medium), size: 17)
        ]
        let proxy3 = UIBarButtonItem.appearance(whenContainedInInstancesOf: [UISearchBar.self, UINavigationController.self])
        proxy3.tintColor = .white
```

**Comment by MaximusMcCann** [comment]
@mxcl Cheers, did the trick!

**Comment by divo** [comment]
@mxcl thanks for the workaround, I have linked to it in our known issues.

**Comment by mstar0125** [comment]
Hello @MaximusMcCann @Thuran 
Could you please explain how to set search bar background same as navigation bar?
Here is what I got so far when changing the background color of navigation bar.


![img_0190](https://user-images.githubusercontent.com/5414823/43367531-1265ccc6-9381-11e8-9915-b36b8a78b40e.png)

**Comment by BharatAgarSoftTech** [comment]
@mstar0125 set barTint with pattern image like this

UIImage *navImg = [_globalGDXData imageWithGradient:kColorAppPurple endColor:kColorAppOrange];
[[UINavigationBar appearance] setBarTintColor:[UIColor colorWithPatternImage: navImg]];

**Comment by newfotune** [comment]
This worked for me.
`let helpCenterContentModel = ZDKHelpCenterOverviewContentModel.defaultContent()
        let attrs = [NSForegroundColorAttributeName: UIColor.white, NSFontAttributeName: UIFont.systemFont(ofSize: 15.0)]
        let appearance = UITextField.appearance(whenContainedInInstancesOf: [UISearchBar.self])
        
        appearance.defaultTextAttributes =  attrs
        ZDKHelpCenter.pushOverview(self.navigationController, with:helpCenterContentModel)`

**Comment by Thuran** [comment]
> > I am open Helper using this code
> > `let viewController = ZDKHelpCenterUi.buildHelpCenterOverview() self.navigationController?.pushViewController(viewController, animated: true)`
> > How am I going to pass this proxys to Zendesk?
> > I'm putting the navigationbar orange and the bottom search is turning red.
> > ![screen shot 2018-06-07 at 11 00 43 am](https://user-images.githubusercontent.com/19709285/41104559-0c1eed4c-6a42-11e8-85e2-1b06d2060ed0.png)
> 
> I'm facing the same issue. Have you find the solution?

I could not figure it out. I ended up using the white color for the navigation bar and the orange color for the title. 😞
