### ISSUE TITLE
Ability to set UIStatusBarStyle.

### ISSUE THREAD

**Issue by MaximusMcCann** [zendesk/zendesk_sdk_ios#338]
- SDK version: 1.11.2.1
- Xcode version: 9.1
- iOS or Simulator: iPhone 5s 
- iOS Version: 11.1
- Swift version: 4

Would like to change the `UIStatusBarStyle`.  Our `UINavigationController` is set to:
```
  override var preferredStatusBarStyle: UIStatusBarStyle {
    return  UIStatusBarStyle.lightContent
  }
```
but still shows black text.

![image](https://user-images.githubusercontent.com/1643285/32569986-689b2082-c488-11e7-9a39-a3e6291757f5.png)

Code snippet:
```
        Router.navController.viewControllers.removeAll()
        let helpCenterContentModel = ZDKHelpCenterOverviewContentModel.defaultContent()
        ZDKHelpCenter.pushOverview(Router.navController, with: helpCenterContentModel)
```

**Comment by tecknut** [comment]
Hi @MaximusMcCann thanks for reaching out to us. 

Can you clarify a few things for me?

- Do you have "View controller-based status bar" set to YES in your info.plist
- Do you need to remove all view controllers from swift router before pushing the SDK?
- Does this black status bar display when push a blanch view controller as follows: 
```
Router.navController.viewControllers.removeAll()
// a basic blank controller 
let controller = UIViewController()
Router.navController.pushViewController(controller, animated: true)
```

Thanks,
Alan

**Comment by MaximusMcCann** [comment]
- [x] Do you have "View controller-based status bar" set to YES in your info.plist. Yes
- [x] Do you need to remove all view controllers from swift router before pushing the SDK? Yes
- [x] Does this black status bar display when push a blanch view controller as follows. Yes

Normally our VCs extend this to make the status bar text white:
```
// Note: depends on custom extensions
class BaseVC: UIViewController {
  override var preferredStatusBarStyle: UIStatusBarStyle {
    return UIStatusBarStyle.whiteTextStyle
  }
... more code
}
```

**Comment by tecknut** [comment]
@MaximusMcCann have you tried setting "View controller-based status bar" set to NO? 
Do you need to switch the status bar style in your app outside of the Zendesk SDK?

**Comment by MaximusMcCann** [comment]
Yes, we need to switch the status bar style.
So we must have "View controller-based status bar" set to YES in the info.plist

**Comment by eepDev** [comment]
Hi @MaximusMcCann,

Unfortunately, we don't provide an option to change UIStatusBarStyle . Our UI was designed with minimal customisation options in mind and changing the status bar style is out of the scope.

If this is important to you, please consider posting a feature request on [our forum](https://support.zendesk.com/hc/en-us/community/topics/200488257-Zendesk-SDKs) where our PM can address it.

Thanks,
Elvis
