### ISSUE TITLE
Underlying views visible when transitioning to Zendesk Articles

### ISSUE THREAD

**Issue by rhaining** [zendesk/zendesk_sdk_ios#339]
- SDK version: 1.11.2.1
- Xcode version: 9.1
- iOS or Simulator: simulator
- iOS Version: 11.1
- Swift version: 3.2

Steps to Reproduce:

1. View zendesk articles
2. it looks like the view might have a clear background, so our content underneath is showing through?

screen capture:
[zendesk-articles.mov.zip](https://github.com/zendesk/zendesk_sdk_ios/files/1458833/zendesk-articles.mov.zip)

**Comment by tecknut** [comment]
Hey @rhaining, can you provide us with the code snippets you're using to present the SDK please?

Thank you,
Alan

**Comment by rhaining** [comment]
@tecknut we use:
```swift
ZDKHelpCenter.pushOverview(navigationController, with: .defaultContent())
```

**Comment by divo** [comment]
@rhaining I am unable to replicate this as far as I can see we are setting the view background color. 
![screen shot 2017-11-15 at 15 29 07](https://user-images.githubusercontent.com/9431616/32844284-e97da206-ca19-11e7-8324-60a34cb6ebc9.png)

Are you modifying / styling the navbar in anyway or setting any appearance properties in your app, particularly on UISearchBar?

Can you also try applying a [template theme](https://developer.zendesk.com/embeddables/docs/ios/customize_the_look#use-a-template-light-theme) and see if the issue persists?

**Comment by RonanMcH** [comment]
Hi @rhaining ,
Have you had any luck with @divo 's suggestion?
Ronan.

**Comment by rhaining** [comment]
Hey @divo & @RonanMcH,

We are using a theme already:
```swift
        let theme = ZDKTheme.base()
        theme.primaryTextColor = Color.invertedBase
        theme.primaryBackgroundColor = .white
        theme.secondaryBackgroundColor = Color.backgroundColor
        theme.emptyBackgroundColor = Color.subtleChrome
        theme.metaTextColor = Color.secondaryContent
        theme.separatorColor = Color.articulatedChrome
        theme.inputFieldTextColor = Color.invertedBase
        theme.inputFieldBackgroundColor = .white
        theme.apply()
```

We are not setting appearance properties on `UISearchBar`. 

We are using a custom `UINavigationBar` subclass in this navigation controller, but its styling shouldn't affect this I wouldn't think?
```swift
    override init(frame: CGRect) {
        super.init(frame: frame)

        let image = UIImage()
        isTranslucent = false
        setBackgroundImage(image, for: .default)
        shadowImage = image
        barTintColor = Color.brand
        tintColor = UIColor(white: 1, alpha: 0.85)
        titleTextAttributes = [
            .foregroundColor: UIColor.white
        ]
    }
```

Looking at my exploded view, I noticed that the `ZDKHelpCenterOverviewController` isn't beneath the navigation bar, but is rather situated below it:
![screen shot 2017-11-29 at 3 26 30 pm](https://user-images.githubusercontent.com/462870/33397524-d5a98e2e-d519-11e7-860a-a08cb5347274.png)

If I then comment out `isTranslucent = false` from that navigation bar, everything works okay! But it screws up some other parts of our app.

Is there a way for y'all to handle this state gracefully?

thanks

**Comment by tecknut** [comment]
Hey @rhaining, 

This has been sitting here for some time without an update, apologies for that.

Would it be possible for you to share the navigation bar subclass? It may go a ways to helping us reproduce the issue here.

Thanks,
Alan

**Comment by divo** [comment]
@rhaining It looks like this was introduced when the SDK was patched for the iPhone X. Setting `isTranslucent = true` on the navigation bar results in an error in our layout. We hope to patch this in the next month or two.

**Comment by rhaining** [comment]
thanks @divo

**Comment by divo** [comment]
@rhaining Thanks for reporting this issue. We have just released 2.0.4. which should fix it.

**Comment by rhaining** [comment]
thanks @divo!

**Comment by KillianSmith0** [comment]
@rhaining we’ve had to rollback our v2.0.4 as it introduced an issue with scrolling in articles in iOS 9 and 10. v2.0.5 will be out in the next day or two with the fix for this issue. Will put a comment out when we release

**Comment by KillianSmith0** [comment]
@rhaining v2.0.5 has just been released 👍

**Comment by rhaining** [comment]
thanks @KillianSmith0 !
