### ISSUE TITLE
Tapping on a link to a section in FAQ opens in Safari instead of in app

### ISSUE THREAD

**Issue by dangochi** [zendesk/zendesk_sdk_ios#340]
- SDK version: 1.9.2.2, 1.11.2.1
- Xcode version: 9.1
- iOS or Simulator: both
- iOS Version: 9.0, 10.3.1, and 11.1
- Swift version: N/A

Steps to Reproduce:
* push/present FAQ and go to an article (URL pattern: https://mydomain.zendesk.com/hc/en-us/articles/12345-Random-Article-Title-)
* tap on a link in the article that points to a section (URL pattern: https://mydomain.zendesk.com/hc/en-us/sections/67890-Section-Title)

Expected: FAQ would push to a view controller for the section
Actual: app opens link in Safari instead

In version 1.9.2.2, you can navigate to sections within the SDK, so I would've expected that tapping on a link to a section wouldn't open in Safari.

In 1.11.2.1, I can't tell if you can actually navigate to sections anymore, so perhaps this is no longer valid. I'm still logging this though as maybe this should be (is?) supported, but I'm missing something that would allow this to be handled.

**Comment by eepDev** [comment]
Hi @dangochi,

Thanks for reporting this. 
I'm afraid our Support SDK never supported in-app navigation into sections and currently we don't have any plans on changing that. 

However if this is something that would be of interest to you, please create a feature request on [our forum](https://support.zendesk.com/hc/en-us/community/topics/200488257-Zendesk-SDKs) where our PM can see and address it.

Elvis
