### ISSUE TITLE
 'Contact Us' not showing

### ISSUE THREAD

**Issue by Ze-ro-G** [zendesk/zendesk_sdk_ios#342]
- SDK version:
- Xcode version: Version 9.1 (
- iOS or Simulator: iPhone 8 Plus
- iOS Version: iOS11
- Swift version: 3

Steps to Reproduce:

1 : Embed a ZDKHelpCenterOverviewController like this 

```
        let helpCenterContentModel = ZDKHelpCenterOverviewContentModel.defaultContent()

        let center : ZDKHelpCenterOverviewController = ZDKHelpCenterOverviewController(helpCenterOverviewModel:helpCenterContentModel!)        
        self.addChildViewController(center)
        self.view.addSubview(center.view)
```

2 : Then  I try  to get the right button of the Help Center like this but it doesn't works.

```
        self.navigationItem.rightBarButtonItem = center.navigationItem.rightBarButtonItem
```

Question : Is there any way to get the ViewController pushed when I trigger the 'Contact Us' button of the The Help Center ?

I can't push it normally with ZDKHelpCenter.pushOverview because my View is in a sideMenu.

![simulator screen shot - iphone 8 plus - 2017-11-23 at 15 31 07](https://user-images.githubusercontent.com/3285421/33177669-c06ddfc0-d063-11e7-8492-d3970ee88966.png)

**Comment by patrick-doyle** [comment]
Can you use a modal presentation method instead? The ZDKHelpCenterOverviewController does not support being in a child view.

**Comment by divo** [comment]
@Ze-ro-G As Patrick said ZDKHelpCenterOverviewController does not support being a child view.

To present Help Center please see https://developer.zendesk.com/embeddables/docs/ios/help_center#help-center-in-the-support-sdk-ui

**Comment by baz8080** [comment]
Going to close this issue as working as designed
