### ISSUE TITLE
Getting a 404 when search for article by ID

### ISSUE THREAD

**Issue by matcartmill** [zendesk/zendesk_sdk_ios#344]
- SDK version: 1.11.2.1
- Xcode version: 9.1
- iOS or Simulator: Simulator
- iOS Version: 11.1
- Swift version: 4

The following works and shows us the correct ZenDesk page:

```
let model = ZDKHelpCenterOverviewContentModel.defaultContent()
model?.labels = labels?.map { $0.rawValue }
ZDKHelpCenter.setUIDelegate(self)
ZDKHelpCenter.pushOverview(navigationController, with: model)
```

The following does not work and instead returns an error:

```
let localeStore = Registry.application!.resolve(LocaleStoreProtocol.self)!
let provider = ZDKHelpCenterProvider(locale: localeStore.currentLocale.identifier)
        
provider?.getArticleById(id, withCallback: { (article, error) in
     if let article = article?.first as? ZDKHelpCenterArticle, let vc = ZDKArticleViewController(article: article) {
        viewController.present(vc, animated: true)
    } 
})
```

A screenshot of the error attached for detail:

<img width="365" alt="screen shot 2017-11-25 at 1 08 48 pm" src="https://user-images.githubusercontent.com/1612537/33233301-d741f6ee-d1e1-11e7-8371-1a7fba3eb601.png">

We are configuring the ZenDesk client with `ZDConfig`, etc.

Any thoughts?

**Comment by divo** [comment]
@matcartmill Help Center articles are unique per local. You can have the same article for different locals but this must be done manually for each article. Can you check the article you are searching for contains content for the local you are setting?

**Comment by matcartmill** [comment]
Hey @divo, thanks for the response. I will follow up with our support team and see what locales they've specified for the articles.

Are the locales in Zendesk strict on how they need to be formatted? For instance I believe the Zendesk client takes something like `en-us`, however the iOS `Locale` system returns something like `en_US`. Would those be equal, or do we need to format in a specific way?

Thanks!

**Comment by matcartmill** [comment]
Did some experimenting and it does seem like ZenDesk is strict on the `Locale` front. `en-gb` isn't the same as `en-GB` or `en_GB` or `en_gb`. That said, I was able to load the article once the correct locale with the correct format was passed in.

**Comment by baz8080** [comment]
@matcartmill the APIs expect it in the `en` or `en-us` formats. When you use our UI we do some settling of the locale, but the provider APIs don't do this. Glad you got it fixed!
