### ISSUE TITLE
New Request Screen Blank (using Fabric)

### ISSUE THREAD

**Issue by bdittmer** [zendesk/zendesk_sdk_ios#345]
- SDK version: 1.11.2.1
- Xcode version: 9.1
- iOS or Simulator: Both
- iOS Version: 11.1
- Swift version: 4

Steps to Reproduce:

1. Follow the Fabric Installation instructions
2. Attempt to present a Request Creation view
3. Result:
<img width="490" alt="screenshot 2017-11-30 10 12 28" src="https://user-images.githubusercontent.com/275917/33450669-66ad041c-d5c1-11e7-9966-400912bc7ac2.png">

I am not doing anything clever or different. The API keys are correctly set in Info.plist. Code below.

In AppDelegate.swift:

```
Fabric.with([Crashlytics.self, Branch.self, Twitter.self, Zendesk.self])

let identity = ZDKAnonymousIdentity()
if Model.shared.currentUser.isValid() {
   identity.name = Model.shared.currentUser.fullName
   identity.email = Model.shared.currentUser.email
} else {
   identity.name = "Not Logged In"
   identity.email = "unknown@asdf.com"
}

ZDKConfig.instance().userIdentity = identity
```

And in a UIViewController subclass: 
```
ZDKRequests.presentRequestCreation(with: self)
```

The debug logs:
```
2017-11-30 11:30:30.775577-0800 [4163:294084] [DEBUG]: About to execute [0x60000020d7b0]: https://<recacted>/api/mobile/sdk/settings/499b7243198dd406d79e525770aa58e025af19da4ce19054.json
with headers
{
    Accept = "application/json";
    "Accept-Language" = en;
    "Client-Identifier" = "<redacted>";
    "Content-Type" = "application/json";
    "Mobile-Sdk-Identity" = "<redacted>";
    "User-Agent" = "Zendesk-SDK/1.11.2.1 iOS/11.1 Env/Development";
}
2017-11-30 11:30:31.407408-0800 [4163:294084] [DEBUG]: Response code [0x60400020ada0]: 200
2017-11-30 11:30:31.407808-0800 [4163:294084] [DEBUG]: Request success: [0x60400020ada0]: https://<redacted>/api/mobile/sdk/settings/<redacted>.json
2017-11-30 11:30:31.410541-0800 [4163:294084] [DEBUG]: No support for en, Help Center is enabled in your application settings
2017-11-30 11:30:31.410769-0800 [4163:294084] [DEBUG]: Successfully updated SDK settings
```

**Comment by MaximusMcCann** [comment]
Can second this :/

**Comment by tecknut** [comment]
Hey @bdittmer and @MaximusMcCann can you verify that the `.bundle`'s have been added to your projects and are copied to your app on building?

From the screen shot above the the localization key at the top of the screen generally happens because the strings bundle is missing.

Thanks,
Alan

**Comment by MaximusMcCann** [comment]
@tecknut Opening up the product and showing package contents, I do not see it there.  We import ZendeskSDK using cocoapods, fwiw.

**Comment by MaximusMcCann** [comment]
This all appears correct
![image](https://user-images.githubusercontent.com/1643285/33616896-e5ae7f12-d9a3-11e7-9839-38a4dddde9bb.png)

**Comment by MaximusMcCann** [comment]
@bdittmer My issue was using the "New Build System (Preview)".  Switching back to the "Standard Build System (Default)" fixed the copy issue.
![image](https://user-images.githubusercontent.com/1643285/33618115-46ffc66a-d9a7-11e7-939c-bdc0018357bf.png)

**Comment by bdittmer** [comment]
@tecknut @MaximusMcCann It looks like the download link on Fabric's site does not include the strings bundle: https://fabric.io/kits/ios/zendesk/manual-install

**Comment by bdittmer** [comment]
I just pulled them down from the repo. Adding them to the bundle fixed the issue!

**Comment by tecknut** [comment]
Glad things are working for you guys. 

@bdittmer Thanks for bringing this to our attention! We'll look into why the bundle is missing from the download page on fabric.
