### ISSUE TITLE
How to add custom attachment to Request from user By default supportSDK UI

### ISSUE THREAD

**Issue by zoxin** [zendesk/zendesk_sdk_ios#346]
- SDK version:1.11.2.1
- Xcode version:9.1
- iOS or Simulator:iOS
- iOS Version:
- Swift version:

I don't want to Custom the Request UI. Is there any way to add custom attachment to Request

sorry for my English

**Comment by zoxin** [comment]
I want to add some log file when the user contact us

**Comment by brendan-fahy** [comment]
Hi @zoxin, there's currently no way to add some log file when the user creates a request through the SDK. Thanks for your input, this is something we're already planning on adding for the next version of the SDK.

**Comment by tecknut** [comment]
Hey @zoxin we just released version 2 of the SDK. 

This feature has been added. The request ui can be configured with a `RequestUiConfiguration` which has a `fileAttachments` property. 

https://developer.zendesk.com/embeddables/docs/ios_support_sdk/configure

Thank you,
Alan
