### ISSUE TITLE
Missing images 

### ISSUE THREAD

**Issue by floriangbh** [zendesk/zendesk_sdk_ios#347]
Hello, 

When I open an article from zendesk some images are missing (but working great on web version).

![screen shot 2017-12-01 at 12 27 32](https://user-images.githubusercontent.com/14054997/33481344-5c6be6f2-d694-11e7-9a03-fd5c396a3367.png)

- SDK version: Using ZendeskSDK (1.11.2.1)
- Xcode version: Xcode 9.3
- iOS or Simulator: iOS 
- iOS Version: 11.1.2
- Swift version: 4.0.2

Steps to Reproduce:
1. Open Article from zendesk controller, which contains some images.

Any ideas ?

Thank you
Florian

**Comment by RonanMcH** [comment]
Hi Florian,
Is it possible you are hosting this Help Center content externally? You may need to add the [AppTransportSecturityKey](https://developer.zendesk.com/embeddables/docs/ios/version_information#app-transport-security) to your app's `info.plist`. Let us know if this solves your issue.
Thanks,
Ronan.

**Comment by floriangbh** [comment]
Hello Ronan,

I already have this key in my `info.plist` : 

```xml
<key>NSAppTransportSecurity</key>
<dict>
	<key>NSAllowsArbitraryLoads</key>
	<true/>
</dict>
```

Some image loading well (1/20)...

Thanks

**Comment by tecknut** [comment]
@floriangbh do you need to log in to Help Center in the browser to view the articles for which the images are not being shown? 

You may need to register [this url protocol](https://developer.zendesk.com/embeddables/docs/ios/help_center#access-a-restricted-help-center) to see these articles if you're Help Center requires a log in on the web. 

Let us know if this works.

Thanks, 
Alan

**Comment by divo** [comment]
@floriangbh When you say it doesn't work do you mean you get an error or you still cannot see the images?

Where are you seeing these URLs? In the logs or the articles themselves?

**Comment by floriangbh** [comment]
> @floriangbh When you say it doesn't work do you mean you get an error or you still cannot see the images?

I cannot see the image, like in the precedent screenshot. 

> Where are you seeing these URLs? In the logs or the articles themselves?

There URLs coming from the web. 

Thank for your responses

**Comment by RonanMcH** [comment]
Hey @floriangbh ,
I am going to proactively open a ticket for you with us and we can debug this issue further there.
Thanks,
Ronan.

**Comment by floriangbh** [comment]
Hello, where I can find this ticket ?

**Comment by RonanMcH** [comment]
HI @floriangbh , 
I sent it to the email on your website. I change the email associated with the ticket if you would like?
Thanks,
Ronan.

**Comment by floriangbh** [comment]
Hi Ronan,
Oups; I changed the email on my website recently but I made a mistake with `.fr` instead of `.com`... Can you change with .com instead of .fr ? 

Thanks

**Comment by RonanMcH** [comment]
Hi @floriangbh , 
No problem. I will resend the ticket now.
Thanks.

**Comment by floriangbh** [comment]
Finally the solution was with : https://developer.zendesk.com/embeddables/docs/ios/help_center#access-a-restricted-help-center ... 

Thank you !
