### ISSUE TITLE
Attachments not displayed in ticket responses

### ISSUE THREAD

**Issue by gransell** [zendesk/zendesk_sdk_ios#349]
- SDK version: 1.11.2.1
- Xcode version: 9.2
- iOS or Simulator: Simulator and device
- iOS Version: 11.2
- Swift version: 4

Steps to Reproduce:

1. Send a ticket from an agent to an end user with an attachment
2. When the end user opens the ticket in the app all they see is the text and not the attachments.

Not sure if this is related to #347

**Comment by RonanMcH** [comment]
Hi @gransell ,
Currently the Support SDK only supports opening image attachments on device. Anything else will not be accessible or even appear on device. Viewing a host of different attachment types on device in the SDK is something we are working on and are hoping to get into the next version of the SDK.  We will let you know once we have released.
Thanks,
Ronan.

**Comment by gransell** [comment]
Thanks for the quick response @RonanMcH! Looking forward to the update
