### ISSUE TITLE
Getting a 403 error when uploading attachments, submitting tickets or viewing helpcenter

### ISSUE THREAD

**Issue by platedbay** [zendesk/zendesk_sdk_ios#350]
- SDK version:
1.11.2.1
- Xcode version:
9.1
- iOS or Simulator:
Simulator & Devices
- iOS Version:
iOS 11
- Swift version:
4.0

We've had this integration within our application for about a year now and we just discovered it's stopped working in production. Went to go debug it locally and we're getting the following error response when both uploading attachments (`ZDKUploadProvider`), creating requests (`ZDKRequestProvider`) or viewing our FAQs (`ZDKHelpCenterProvider`).

```
Error Domain=ZDDispatcher Code=3 "(null)" UserInfo={zd_dispatcher_err=HTTP Error: 403}
```

I know we have an active internet connection, I know that we've properly set the `ZDKConfig.instance().userIdentity` to our `ZDKAnonymousIdentity` with user information before making these provider requests. I've also verified we're initializing with the correct `appId`, `zendeskUrl` and `clientId` (none of this has changed). The only thing I can think of that's changed recently is us updating to the latest version of the iOS SDK.

We'd appreciate any and all help regarding this. Thank you!

**Comment by tecknut** [comment]
Hi @platedbay I see you've opened up a ticket on our Zendesk instance. I'm going to follow up there.

**Comment by platedbay** [comment]
Hey folks,

Just wanted to follow up with some visibility on this. After going through every possible avenue, it turns out the issue lies with the email address used on the `ZDKAnonymousIdentity`. I was using my email which is the same that's used for my internal admin/agent on our account. There was a recent fix (server side) that does not allow agents accounts to be used via the SDK.

This obviously shouldn't be an issue for your actual users, but can definitely be a problem when developing or testing your integration. Hopefully this saves folks some time in the future if they run into this 👍

**Comment by ce98118mir** [comment]
This is a horrible problem for those who it affects. We wasted a few hours trying to trouble shoot this.  First of all thanks a lot platedbay for this update. 

However why in the world would you do this zendesk?

1  Why would you do something like this?  The only people affected are testers.
2  Assuming good reason for you, if you do it, then why would  you not put a meaningful server side error message ?

Thanks
Pras

**Comment by divo** [comment]
@ce98118mir @platedbay This was a mistake on our part. Confusion on where to document this change resulted in it not being documented at all. Our sincere apologies for letting this slip through the cracks.

We have added a note to the [integration documention](https://developer.zendesk.com/embeddables/docs/ios/set_an_identity)

**Comment by welshm** [comment]
What does this mean for end users who are agents or administrators for other Zendesk accounts? Or does it only affect agents/admins of the target support account?

**Comment by divo** [comment]
@welshm Its per account so agents will still be able to create tickets in other Zendesk instances.

**Comment by tecknut** [comment]
@viccarre 
> BTW I was testing on an iPhone 5s with iOS 10.3 and seems to be working correctly. But this issue appears when I'm trying to attach a file to iPhone 8 with iOS 11.
Error Domain=ZDDispatcher Code=3 "(null)" UserInfo={zd_dispatcher_err=HTTP Error: 413}

Is it possible that the image file size on an iPhone 5s is less than the attachment file size max and the iPhone 8 file sizes for an image is larger? (assuming that the attachments you are uploading are photos)

**Comment by baz8080** [comment]
I'm going to close this issue. We needed to prevent agents from using the SDK to mitigate a security issue.

**Comment by parth51** [comment]
Do we have any solution for this issue? We are using v1 ZENDESK SDK. We have almost 20+ testers account with agent email address. Can't we use that for Zendesk?
