### ISSUE TITLE
Infinite loop inside Zendesk SDK on iOS 11

### ISSUE THREAD

**Issue by xGoPox** [zendesk/zendesk_sdk_ios#351]
SDK version: 1.10.1.1
Xcode version: Version 9.2 (9C40b)
iOS or Simulator: hang confirmed on both.
iOS Version: Version 9.2 (9C40b) iOS 11.2 simulator
Swift version: 4
Steps to Reproduce:

1 - guard let nc = navigationController else { return }
2 - ZDKHelpCenter.pushOverview(nc, with: ZDKHelpCenterOverviewContentModel.defaultContent())
3 - Infinite loop

exact same issue as : https://github.com/zendesk/zendesk_sdk_ios/issues/324

**Comment by divo** [comment]
@xGoPox Are you using the preview build system?

**Comment by Bashta** [comment]
@divo Happens on both.

**Comment by tecknut** [comment]
Hey @Bashta can you verify that the SDK bundle files are in your app bundle after you build?

**Comment by RonanMcH** [comment]
Hi @Bashta ,
just wanted to follow up again and see if this issue still persists for you?
Thanks,
Ronan.

**Comment by Bashta** [comment]
We have updated the SDK and it is not happening anymore.

**Comment by divo** [comment]
@xGoPox are you still seeing this issue?

**Comment by charles-packer** [comment]
I have the latest SDK and I'm seeing this issue.

**Comment by baz8080** [comment]
@charles-packer 

1. Are you using the standard or preview build system?
2. Can you verify that all of the SDK bundles are in your app bundle?

**Comment by tecknut** [comment]
Hey @charles-packer are you still experiencing this?

**Comment by iDevo** [comment]
Hi there! I've the same issue. In my case it depends between simulator (which is working just fine) and testing the App / SupportCenter on any iPhone, example iPhone X with 11.2.5 installed.
I'm also using the latest version of the SDK installed via CocoaPods and set up with anonymous login using Swift 4:

```
let url = "URL"
let appID = "APP_ID"
let clientID = "CLIENT_ID"

var valuesToSave = [String: Any]()
valuesToSave["url"] = url
valuesToSave["appId"] = appID
valuesToSave["clientId"] = clientID

valuesToSave["userId"] = ""
valuesToSave["name"] = ""
valuesToSave["email"] = ""
valuesToSave["authType"] = 1

let identity = ZDKAnonymousIdentity()
identity.name = ""
identity.email = ""
ZDKConfig.instance().userIdentity = identity
ZDKConfig.instance().initialize(withAppId: appID, zendeskUrl: url, clientId: clientID)

UserDefaults.standard.set(NSKeyedArchiver.archivedData(withRootObject: valuesToSave), forKey: "ZDSDKSampleAppDefaultsKey")
UserDefaults.standard.synchronize()

let contentModel = ZDKHelpCenterOverviewContentModel.defaultContent()
contentModel?.hideContactSupport = true

if ZDKUIUtil.isPad() {
    self.modalPresentationStyle = .formSheet
    ZDKHelpCenter.presentOverview(self, with: contentModel)
}
else {
    ZDKHelpCenter.presentOverview(self, with: contentModel)
}
```

**Comment by divo** [comment]
@iDevo 
Are you using XCode 9.3 beta? Are you using the preview build system too?

**Comment by iDevo** [comment]
@divo I‘m using the standard xCode 9.2 from the AppStore (build: 9C40b)

**Comment by RonanMcH** [comment]
@iDevo , this loop can also happen when the `xib`s we ship for Help Center aren't included in your app correctly. We ship these in `ZendeskSDK.bundle`.  Can you check the contents of your built app to ensure this bundle is in there and let us know?

**Comment by iDevo** [comment]
Hi @RonanMcH thank you for your answer. Yes I can confirm, that the `ZendeskSDK.bundle` and `ZendeskSDKStrings.bundle` is located in the archive. The path is: 
`MyApp.xcodearchive  >  Products  >  Applications  >  MyApp.app  >  ZendeskSDK.bundle`

**Comment by baz8080** [comment]
@iDevo Thanks for the additional information. We can only reproduce this locally when the nibs or xibs are not present. For us it doesn't make a difference if we're deploying to a device or a simulator. I'll leave the issue open so others can get some ideas, and so we can try to get more data on the issue.

**Comment by divo** [comment]
@iDevo In your copy files build phase do you have "Copy only when installing" checked?

**Comment by tecknut** [comment]
Hi @iDevo, we're closing this issue. We have just released version 2 of the SDK. This versions is a dynamic framework which is itself a bundle and contains all resources required. This issues should no longer occur.

FYI, It is currently still necessary to include the strings bundle.

Thanks,
Alan

**Comment by iDevo** [comment]
Sorry for not getting back to you so long (busy time), I really appreciate your work guys! Thanks! 👌🏽
