### ISSUE TITLE
Max attachment size is different every time.

### ISSUE THREAD

**Issue by ioskunal** [zendesk/zendesk_sdk_ios#352]
- SDK version: 1.11.2.1
- Xcode version: 9.0
- iOS or Simulator: Simulator
- iOS Version: 9.0
- Swift version: 3

Steps to Reproduce:

1. Click on Add attachment
2.Select a photo
3. Pops up comes up as `Max attachment size is 1.7 MB`
 The max limit keeps on changing every time I select another photo.

**Comment by baz8080** [comment]
Hi @ioskunal 

Thanks for reporting this. It's a bug. We use that string in two places, and in one it uses the actual image size and in the other it uses the maximum attachment size. I've created an issue to track this internally.

**Comment by ioskunal** [comment]
Thanks @baz8080 , Please update and close it. This is very very critical.Thanks for your quick response. Its appreciated.

**Comment by baz8080** [comment]
@ioskunal We'll look at fixing it in the next release. We're currently working on a major update, and it's unlikely we'll release a patch for this before that because it's not a crash.

**Comment by ioskunal** [comment]
Do you have any estimate by when you would be able close this issue?

**Comment by baz8080** [comment]
Hi @ioskunal We'll look at it in a patch when we GA version 2 of the SDK. It is expected soon, but I can't give an ETA now.

**Comment by tecknut** [comment]
Hey @ioskunal we have just released version 2 of the SDK which has resolved this issue. 

Thank you,
Alan
