### ISSUE TITLE
There is a "Contact us" still exist with ZDKContactUsVisibilityOff

### ISSUE THREAD

**Issue by zoxin** [zendesk/zendesk_sdk_ios#354]
- SDK version:1.11.2.1
- Xcode version:9.1
- iOS or Simulator:IOS
- iOS Version:
- Swift version:

Steps to Reproduce:

1. disable ContactUs function, we don't need this
-(ZDKContactUsVisibility)active {
    return ZDKContactUsVisibilityOff;
}
2.search something that does not exist in help center. There is a "Contact us" in the result page. It's should not exist.

**Comment by RonanMcH** [comment]
Hi @zoxin ,
To hide the the "contact us" in the empty search you set a bool on the `ZDKHelpCenterOverviewContentModel` like so: 
```
ZDKHelpCenterOverviewContentModel *contentModel = [ZDKHelpCenterOverviewContentModel defaultContent];
contentModel.hideContactSupport = YES;
[ZDKHelpCenter pushHelpCenterOverview:self.navigationController withContentModel:contentModel];
```
Hope this helps,
Ronan

**Comment by zoxin** [comment]
@RonanMcH Thanks 👍
