### ISSUE TITLE
Does not compile when being included in a mm file

### ISSUE THREAD

**Issue by moleki** [zendesk/zendesk_sdk_ios#36]
I am getting the following error just by including ZendeskSDK/ZendeskSDK.h inside an .mm file

/Zendesk/ZendeskSDK.framework/Headers/ZDKUIUtil.h:42:34: Expected ';' after method prototype

**Comment by baz8080** [comment]
Hi Moleki,

Sorry for the late reply on this one. Can you give me more details about how you encounter this issue?

**Comment by baz8080** [comment]
Hi Moleki,

I'm going to close this issue but please feel free to reopen it if you need help.

Thanks,
Barry,
