### ISSUE TITLE
Module compiled with Swift 4.0.3 cannot be imported in Swift 4.1

### ISSUE THREAD

**Issue by harrygt** [zendesk/zendesk_sdk_ios#360]
- SDK version: 2.0.0
- Xcode version: 9.3 (9E145)
- iOS or Simulator: iOS
- iOS Version: 11.3
- Swift version: 4.1

Steps to Reproduce:

1. Manually add latest SDK to project
2. Build
3. Receive error in the title

When will support for Swift 4.1 be added or is there a way to get around this for the time being?

**Comment by JakubMazur** [comment]
I'm having the same issue, cannot really build project anymore because of this issue.

**Comment by patrick-doyle** [comment]
Thanks for raising issue. We are currently working on it. We will update here when its available.

**Comment by JakubMazur** [comment]
Thanks, @patrick-doyle in the meantime, I've created walkaround for this issue, so if @harrygt you want to use it: https://github.com/JakubMazur/zendesk_sdk_ios/tree/swift_4.1

**Comment by divo** [comment]
@harrygt @JakubMazur We just released 2.0.1 with Swift 4.1 support.
