### ISSUE TITLE
I can't update to version 2.0.0

### ISSUE THREAD

**Issue by Sethmr** [zendesk/zendesk_sdk_ios#364]
Version 2.0.0 isn't available in the pod repo. Follow these steps to see issue.

1. In terminal type 'pod repo update'.
2. In terminal type 'pod search ZendeskSDK'
3. The RESULTS:

-> ZendeskSDK (1.11.2.1)
   Zendesk SDK 1.11.2.1
   pod 'ZendeskSDK', '~> 1.11.2.1'
   - Homepage: https://github.com/zendesk/zendesk_sdk_ios
   - Source:   https://github.com/zendesk/zendesk_sdk_ios.git
   - Versions: 1.11.2.1, 1.11.1.1, 1.11.0.1, 1.10.1.1, 1.10.0.1, 1.9.2.2,
   1.9.2.1, 1.9.1.1, 1.9.0.1, 1.8.0.1, 1.7.6.1, 1.7.5.1, 1.7.4.1, 1.7.3.1,
   1.7.2.1, 1.7.1.1, 1.7.0.1, 1.6.2.1, 1.6.1.1, 1.6.0.1, 1.5.4.1, 1.5.3.1,
   1.5.2.1, 1.5.1.1, 1.5.0.1, 1.4.1.4, 1.4.1.3, 1.4.1.2, 1.4.1.1, 1.4.0.2,
   1.4.0.1, 1.3.4.1, 1.3.3.1, 1.3.2.1, 1.3.1.2, 1.3.1.1, 1.3.0.1, 1.2.0.1,
   1.1.1.2, 1.1.1.1, 1.1.0.1, 1.0.0.1, 0.9.2, 0.9.1 [master repo]
   - Subspecs:
     - ZendeskSDK/UI (1.11.2.1)
     - ZendeskSDK/Providers (1.11.2.1)

**Comment by divo** [comment]
@sethmr we have not yet published the release to Cocoapods. There are still some questions we need to answer surrounding the release of a Swift framework on Cocoapods.

**Comment by satindar** [comment]
@divo Glad to hear you're working on the Cocoapods release! I was trying to build with Cococpods 1.5.0 and I'm seeing a few of these errors when trying to build static libraries:

`Include of non-modular header inside framework module 'ZendeskSDK.ZDKArticleViewController'`

That one is from `ZDKArticleViewController.h` on the import for `<ZendeskProviderSDK/ZDKHelpCenterConversationsUIDelegate.h>`

Is this something that you've already encountered and are working on? If not, I can file an issue with more detail. Or maybe you already know how to solve this issue?

**Comment by divo** [comment]
We have just released SDK 2.0 to Cocoapods
