### ISSUE TITLE
Crash when opening RequestUIViewController in v2.0.0

### ISSUE THREAD

**Issue by datamaru** [zendesk/zendesk_sdk_ios#366]
- SDK version: 2.0.0
- Xcode version: 9.3
- iOS or Simulator: iOS
- iOS Version: 11.1.2
- Swift version: 4.1

Steps to Reproduce:

1. Push RequestUI View Controller
`let requestScreen = RequestUi.buildRequestUi()
self.navigationController?.pushViewController(requestScreen, animated: true)` 

It only happen with RequestUi.buildRequestUi(). I tried to use RequestUi.buildRequestList() and it opened just fine. It also crash if i try to open requestUi view from requestList view.

Zendesk Log is not debugging any error. Xcode crash code is `Thread 1: EXC_BAD_ACCESS (code=1, address=0x1)`

**Comment by datamaru** [comment]
Zendesk log using `CoreLogger.logLevel = .debug`:
`"ios.ZDKRequests.createRequest.title" = "Contact us";`

There' nothing displayed when using `CoreLogger.logLevel = .error`

How to see the stack trace? Because there's nothing regarding the crash in the debugging console.

**Comment by divo** [comment]
You need to enable logging as well as set the level.
https://developer.zendesk.com/embeddables/docs/ios_support_sdk/debug

**Comment by datamaru** [comment]
Sorry for the late reply. This is the full stack trace leading to the crash https://pastebin.com/H5aK4bS3

**Comment by tecknut** [comment]
Thanks for the update @datamaru, we're looking into this now. We'll update as we find out more information.

**Comment by bolshedvorsky** [comment]
I've got the same issue on iOS 11.3. RequestUIViewController crashes the app from both RequestUi.buildRequestUi() and RequestListViewController.

**Comment by divo** [comment]
@datamaru @bolshedvorsky Can you confirm you followed [the integration instructions?](https://developer.zendesk.com/embeddables/docs/ios_support_sdk/sdk_add)

There are a good few steps now, especially if your app is not already using Swift.

**Comment by Alak** [comment]
Same problem here. iOS 11.3, xcode 9.3 swift 4.1.

Happening on `RequestUi.buildRequestUi(requestId: "id")`

**Comment by bolshedvorsky** [comment]
Yes, I followed the instructions. Our app is written in Swift 4.1, there were no issues with 1.x version of Zendesk SDK. 

The RequestListViewController can be opened using ZendeskSDK 2.0.1, but the RequestViewController crashes.

I've got the same stack trace as https://pastebin.com/H5aK4bS3. As you can see from the stack trace it crashes inside of the ZendeskSDK: ZendeskSDK.RequestContainerReducer.reduce(state: ZendeskSDK.RequestContainerState, action: ZendeskSDK.Action)

**Comment by bolshedvorsky** [comment]
This happens with Swift 4.1 as I'm not able to use Swift 4.0.2 or Swift 4.0 due to my project being compiled with Swift 4.1.

![screen shot 2018-04-17 at 16 57 19](https://user-images.githubusercontent.com/16137590/38881752-7851a77a-4260-11e8-9734-3e2d94c8967f.png)

**Comment by bolshedvorsky** [comment]
I'm using an anonymous identity initialised with the name / email.

**Comment by bolshedvorsky** [comment]
This request happens when I present the 'RequestUi.buildRequestList()' and tap on Start A Conversation button. 

![screen shot 2018-04-17 at 17 00 41](https://user-images.githubusercontent.com/16137590/38881984-07de745e-4261-11e8-82b3-6ba6b80cfb3f.png)

**Comment by divo** [comment]
@bolshedvorsky Can you enable Suas logging,  `SuasDebugLogger.enabled = true`,  and post the results please?

**Comment by bolshedvorsky** [comment]
This was enabled, no logs, except for the line '[INFO]: Localization key and value : "ios.ZDKRequests.createRequest.title" = "Contact us";'

**Comment by divo** [comment]
Suas logging should produce a torrent. Are you doing a debug build?

**Comment by divo** [comment]
[be downloaded here ](url)

**Comment by divo** [comment]
[be downloaded here ](url)

**Comment by divo** [comment]
I have pulled 2.0.1 until we have a fix or a workaround

**Comment by Alak** [comment]
any news about xcode 9.3 support ? @divo

**Comment by divo** [comment]
We are working on it now. All going well it should be out next week. _All going well_

**Comment by divo** [comment]
We have release 2.0.2 with Swift 4.1 support

**Comment by RonanMcH** [comment]
Hi @Alak , @bolshedvorsky and @datamaru,
We just released version 2.0.2 of the SupportSDK with Swift 4.1 (xcode 9.3) . This crash should not be present any more. 
Thanks for your patience,
Ronan.
