### ISSUE TITLE
Custom help_center_article_style.css not working

### ISSUE THREAD

**Issue by dcooper87** [zendesk/zendesk_sdk_ios#367]
- SDK version: 2.0.1
- Xcode version: 9.3 (9E145)
- iOS or Simulator: Both
- iOS Version: 11.3 (Simulator) 10.0.2 (Device)
- Swift version: 4.1

Steps to Reproduce:

1. Add custom `help_center_article_style.css` per https://developer.zendesk.com/embeddables/docs/ios_support_sdk/customize_the_look#change-the-style-of-help-center-articles
2. Run app and select article. The article styling is ignoring any changes I make to the new css file.

I've tried adding the file to the root folder and the main project folder but neither seem to work. It worked prior to upgrading to SDK 2.0.

Any help appreciated.

**Comment by tecknut** [comment]
Can you confirm that the css file is being copied to your app bundle in your projects build phases?

**Comment by dcooper87** [comment]
Yeh - just double checked and it's definitely being copied.

**Comment by divo** [comment]
We have a fix for this and plan to release a patch for this and other small issues in the coming weeks.

**Comment by harrygt** [comment]
Any news on when this fix will be released?

**Comment by KillianSmith0** [comment]
@harrygt - we should have a patch released by the end of next week. If not, the week after. This patch will include a fix for this. Will update this issue when the patch is in 👍

**Comment by harrygt** [comment]
That's perfect timing for us! Well done! 👍

**Comment by divo** [comment]
@harrygt @dcooper87 we have just released 2.0.4. It addresses this issue

**Comment by jeffremer** [comment]
Thanks @divo, just updated to 2.0.5 and verified it fixes this 👍

**Comment by AndreyLunevich** [comment]
2.0.5 not work for me. Can anyone help with this @divo @jeffremer  ?

**Comment by KillianSmith0** [comment]
@AndreyLunevich - Can you make sure you follow the setup correctly, ensure your css file name is exactly `help_center_article_style .css`, it's in the root directory of your project folder, and then import the project into your directory
Ref: https://developer.zendesk.com/embeddables/docs/ios_support_sdk/customize_the_look#change-the-style-of-help-center-articles

**Comment by AndreyLunevich** [comment]
@KillianSmith0 I sure that everything is configured right, because at 1.x version everything worked.
