### ISSUE TITLE
Update to V2 using PODS

### ISSUE THREAD

**Issue by EugeneGordin2303** [zendesk/zendesk_sdk_ios#368]
Hi guys, is it possible to update to v2 of the SDK using PODS? 

I tried running pod update ZendeskSDK and it didn't work. It listed my current version as ZendeskSDK (1.11.2.1). 

Are you planning on adding v2 update to PODS any time soon? Thank you

**Comment by divo** [comment]
@EugeneGordin2303 please see https://github.com/zendesk/zendesk_sdk_ios/issues/364
