### ISSUE TITLE
Crashing when calling a search API from provider using an agent's email address

### ISSUE THREAD

**Issue by capecrawler** [zendesk/zendesk_sdk_ios#369]
- SDK version: 2.0
- Xcode version: 9.2
- iOS or Simulator: Simulator
- iOS Version: 11.2
- Swift version: 4.0

Steps to Reproduce:

1. Authenticate using an agent email address
2. Use provider to search for an article
3. Crash

**Comment by divo** [comment]
@capecrawler Thanks for reporting this. We do not allow users with agent emails in the SDK, please see [setting an identity](https://developer.zendesk.com/embeddables/docs/ios/set_an_identity#must-do-set-an-identity-authentication).

I am unable to replicate the crash, but I do get a stack trace. Can you post the stack trace you are seeing please?

**Comment by tecknut** [comment]
Hi @capecrawler, 

We haven't heard back from you in a while. Just checking in with you to see if you have had a chance to capture a stack trace?

Thanks,
Alan

**Comment by KillianSmith0** [comment]
Hi @capecrawler,

I'm going to close this issue due to inactivity, feel free to reopen when you can bring back a stack trace 👍
