### ISSUE TITLE
ZDKCustomField is not filled in created issue if field type is dropdown and field value contains spaces

### ISSUE THREAD

**Issue by DrBreen** [zendesk/zendesk_sdk_ios#370]
- SDK version: 2.0.0
- Xcode version: 9.3
- iOS or Simulator: Reproducible on both.
- iOS Version: 11.3
- Swift version: 3.0

Steps to Reproduce:

1. In Zendesk agen console, create field with type "Drop-down"
2. Create two values, one without space in it, like "Complaint" and one with space, like "Technical Support"
3. Write minimum code needed to create ticket that contains the following: subject, anonymous identity, description and custom field with "drop-down" type. Custom field value must be "Technical Support".
4. Send request to Zendesk
5. Dropdown field is not filled when viewing ticket

Changing "Technical Support" to "Complaint" fixes it, and field is filled as expected.

Sample code for reproducing the issue:
```
let appId = your app_id here
let clientId = your client_id here
let zendeskUrl = your zendesk_url here
let dropdownFieldId = your dropdown field id here
let userEmail = your user email here
let userName = your username here

Zendesk.initialize(appId: appId, clientId: clientId, zendeskUrl: zendeskUrl)
        
let identity = Identity.createAnonymous(name: userName, email: userEmail)
Zendesk.instance?.setIdentity(identity)
    
let createRequest = ZDKCreateRequest()
        
createRequest.subject = "Test Subject"
createRequest.requestDescription = "Test description"
        
let dropdownField = ZDKCustomField(fieldId: dropdownFieldId as NSNumber, andValue: "Technical Support")!
createRequest.customTicketFields = [dropdownField]
        
requestProvider.createRequest(createRequest) { (_, error) in
    print("Finished request, success = \(error == nil)")
}
```

**Comment by divo** [comment]
@DrBreen  Thanks for reporting this, I have added it to our backlog. We are currently working on a patch to the fix should be out in the coming weeks.

**Comment by KillianSmith0** [comment]
Hi @DrBreen,
As you can see where you design your custom dropdown field, there is a checkbox to see the `tags` that belong to the values of your custom dropdown. The tags are what needed to be passed in to `andValue`. A tag is the snake case of the value. Eg.  value = `Technical Support`, tag = `technical_support`. 

It seems the method param is misleading. Thanks for bringing this to our attention, we will need to update our documentation. Going to close this for now, feel free to open if any other issues.
