### ISSUE TITLE
incompatible versions of Swift

### ISSUE THREAD

**Issue by ahmetalsan** [zendesk/zendesk_sdk_ios#373]
- SDK version: 2.0.0
- Xcode version: Version 9.3 (9E145)
- iOS or Simulator:
- iOS Version:
- Swift version: Using Objective-C

Steps to Reproduce:

1. Add frameworks
2. Build
3. Xcode gives error:
Zendesk/ZendeskProviderSDK.framework/ZendeskSDKStrings.bundle/_CodeSignature/CodeSignature: Failed to parse Mach-O: Reached end of file while looking for: uint32_t.
error: The following binaries use incompatible versions of Swift:

**Comment by dannyhertz** [comment]
@ronan-mch hey Ronan, curious if you had a soft ETA on Swift 4.1 compatibility? Thanks!

**Comment by pkhbdb** [comment]
@RonanMcH Hi Ronan! I'll be rehiterating Danny's question here, but do you have an approximate ETA for Swift 4.1 compatibility ? Thank you !

**Comment by RonanMcH** [comment]
Hi @dannyhertz and @pkhbdb ,
we are hoping to have a release out by end of next with Swift 4.1 compatibility.
Thanks,
Ronan.

**Comment by pkhbdb** [comment]
Alright, thank you for your reply!
Alexandre

**Comment by RonanMcH** [comment]
Hi @dannyhertz and @pkhbdb ,
We just released version 2.0.2 of the Support SDK with Swift 4.1 compatibility. 
Thanks,
Ronan.
