### ISSUE TITLE
Selecting "Contact us" button (from any screen) causes enclosing NavController to dismiss itself

### ISSUE THREAD

**Issue by dannyhertz** [zendesk/zendesk_sdk_ios#375]
- SDK version: 2.0.2
- Xcode version: 9.3
- iOS or Simulator: Sim
- iOS Version: 11.3
- Swift version: 4.1

Steps to Reproduce:

1.  Create overview VC
```
        let vc = ZDKHelpCenterUi.buildHelpCenterOverview()
        let navWrapper = UINavigationController(rootViewController: vc)
        navController.present(navWrapper, animated: true, completion: nil)
```

2. Click "compose" icon in top right nav bar

3. Click "start a conversation"

4. Enclosing Nav controller dismisses

**Comment by divo** [comment]
@dannyhertz can you [enable logging](https://developer.zendesk.com/embeddables/docs/ios_support_sdk/debug) and post the output please?

**Comment by dannyhertz** [comment]
@divo Ah intersting. It keeps complaining about no identity being set

```
2018-04-27 10:59:42.584216-0400 HQ[68584:31941850] [ERROR]: Couldn't retrieve identity from storage.
2018-04-27 10:59:42.585398-0400 HQ[68584:31941850] [DEBUG]: Returning cached settings for SupportSettings.Type
2018-04-27 10:59:42.585503-0400 HQ[68584:31941850] [ERROR]: No identity set. Dismissing Request creation
```

However I am 100% setting an identity in the correct order like so

`        Zendesk.instance?.setIdentity(Identity.createAnonymous(name: "danny", email: "test@test.com"))
`

**Comment by dannyhertz** [comment]
Looks like enabling the articles section in the zendesk dashboard made the error go away. A little strange but glad its working now.

**Comment by brendan-fahy** [comment]
Hey @dannyhertz, the lack of an identity would definitely explain why the screen was dismissing itself, as the SDK can't really function without one. Are you still seeing those logs regarding no identity being set? The fix here is more likely to be related to the identity than to toggling Help Center in the dashboard, but it would be good to be sure.

**Comment by tecknut** [comment]
Hey @dannyhertz 

Haven't heard back from you in a while. We're going to close this issue for now. If you need any further assistance please get back in touch.
