### ISSUE TITLE
RequestUi crashes when trying to attach media from photo library

### ISSUE THREAD

**Issue by jgavris** [zendesk/zendesk_sdk_ios#376]
- SDK version: 2.0.2
- Xcode version: 9.3
- iOS or Simulator: iOS 11.3.1
- iOS Version: iOS 11.3.1
- Swift version: 4.1

Steps to Reproduce:

1. Build a RequestUi and run on a device. Tap the 'attach' paperclip, then the '...' button. The app will crash with an unexpected nil value in an optional.

![img_49fa919f8c89-1](https://user-images.githubusercontent.com/178749/39443560-fcfe50f0-4c82-11e8-8590-6a5e3eb803c2.jpeg)

@divo Any ideas ?

**Comment by divo** [comment]
@jgavris Have you [enabled iCloud permissions?](https://developer.zendesk.com/embeddables/docs/ios_support_sdk/sdk_add#add-icloud-permissions). We attempt to detect them and show the button only if they are enabled but there is no way to explicitly do this. An app will crash if the iCloud APIs are used without the proper permissions.

**Comment by jgavris** [comment]
@divo Yes, this bundle identifier has all 3 iCloud services enabled (key-value storage, icloud documents, and cloudkit).

**Comment by jgavris** [comment]
Also, what if we don't want / need CloudKit? Can we configure the request ui to just allow camera / photo roll?

**Comment by divo** [comment]
We don't offer a way to disable iCloud sharing in the SDK. The idea is if the capability is available we display the button, if not we don't. 

Can you post the logs you get from the crash? Please see [here to enable logging](https://developer.zendesk.com/embeddables/docs/ios_support_sdk/debug), although I'm more interested in the system logs, not the SDK logs.

Can you also take a look at `FileManager.default.ubiquityIdentityToken` when your app is running and let us know if it is nil? The presence of this value is how we determine if iCloud is available.

**Comment by divo** [comment]
@jgavris Sorry for the delay, we do support duty on a rotating basis.

I was able to recreate the crash. The fix is to set to set `UINavigationBar.appearance().tintColor`. This is because we are attempting to fix an issue in `UIDocumentPickerViewController`. Unfortunately `tintColor` is implicitly forced unwrapped for us so if it's not set we crash when we access it.

Thank you for bringing this to our attention. I'll add it to know issues and try and get a patch out for it soon.

**Comment by divo** [comment]
@jgavris we have just released 2.0.3 to fix this issue.

**Comment by jgavris** [comment]
Thanks! Will try it out. When will it hit cocoapods? I would recommend adding your framework binaries as git LFS files. I noticed this repo is quite large as we've added it as a submodule since it's not available on cocoapods.

**Comment by divo** [comment]
We haven't released 2.0 on Cocoapods yet because of a few things we were unsure of. I'm looking at it now. Let us know how you get on with 2.0.3 anyway.

**Comment by divo** [comment]
Ok, it's on CocoaPods

**Comment by jgavris** [comment]
Perfect thanks!

**Comment by nguyenquocdathcmus** [comment]
hi. @divo  . I also have a problem with UINavigationBar.appearance().tintColor. Can you tell me how to fix it?
