### ISSUE TITLE
Close button is present in the Help center which does nothing

### ISSUE THREAD

**Issue by sheff1422** [zendesk/zendesk_sdk_ios#377]
- SDK version: 2.02
- Xcode version: 9.3
- iOS or Simulator: Simulator
- iOS Version: 11.3
- Swift version: 4.1

Close button is present in the Help center which does nothing. http://prntscr.com/jce6ip 
Is there a chance to have a config which removes it?

Steps to Reproduce:

1. TabBar based application
2. One of tabBarItem leads directly to help center
3. UINavigationController in viewDidAppear add HelpCenterUiConfiguration()
let helpCenter = HelpCenterUi.buildHelpCenterOverview(withConfigs: [hcConfig])
self.pushViewController(helpCenter, animated: true)

**Comment by divo** [comment]
@sheff1422 Can you try embedding HelpCenter in another ViewController. Just nest it inside a controller inside your tabBarItem.

**Comment by sheff1422** [comment]
@divo Thanks for the hint but create ticket button is missing now http://prntscr.com/jcehhd

**Comment by brendan-fahy** [comment]
Hey @sheff1422, this looks like a feature gap on our side. We're looking into it to see if we can find a workaround for you, or whether it'll require a code change from us.

**Comment by sheff1422** [comment]
@brendan-fahy  Thank you. Will be looking forward for some further info from you

**Comment by tecknut** [comment]
Hey @sheff1422, 

We have a workaround which might work for you.

```
import UIKit
import ZendeskSDK

class NavigationController: UINavigationController {
    
    var observer: NSKeyValueObservation?
    
    override func viewDidLoad() {
        super.viewDidLoad()

        let helpCenterViewController: UIViewController = HelpCenterUi.buildHelpCenterOverview()
        self.pushViewController(helpCenterViewController, animated: true)
        
        observer = helpCenterViewController.observe(\UIViewController.navigationItem.leftBarButtonItem) { (viewController, change) in
            
            if viewController.navigationItem.leftBarButtonItem != nil {
                viewController.navigationItem.leftBarButtonItem = nil
            }
        }
    }
}
```

Can you try this and let us know if your happy with it? 

Thank you,
Alan

**Comment by sheff1422** [comment]
@tecknut  Thanks for this hint. I created smth similar but without observer and button returns back each time when i am returning back from some article in help center.  I will try this one and give you the feedback !

**Comment by sheff1422** [comment]
@tecknut Works like a charm. Thank you!

**Comment by eepDev** [comment]
Glad to hear it worked! 
We created a JIRA story to track this issue internally and address it. Please keep an eye out on our release notes for further updates!
I'm going to close this issue for now.

Thanks,
Elvis

**Comment by Lawati97** [comment]
@tecknut unfortunately that didn't work for me since i have 
 let helpCenterViewController: UIViewController = HelpCenterUi.buildHelpCenterOverview(with config [helpCenter, articleView])
        self.navigationController.setViewController([helpCenterViewController], true)

as the code you gave me didn't help me to remove the 'x' button

**Comment by Lawati97** [comment]
@tecknut  after using your i keep on getting a tool bar but for some reason i cannot remove it?
Thank you for your code!!

**Comment by Lawati97** [comment]
![screen shot 2018-12-04 at 5 58 14 pm](https://user-images.githubusercontent.com/37277245/49480960-5c713400-f7ee-11e8-8b69-d62f49a2df1b.png)

**Comment by Lawati97** [comment]
![screen shot 2018-12-04 at 5 58 14 pm](https://user-images.githubusercontent.com/37277245/49481036-af4aeb80-f7ee-11e8-9d1c-3eb0ef1ac6f2.png)

**Comment by Lawati97** [comment]
![screen shot 2018-12-04 at 5 58 14 pm](https://user-images.githubusercontent.com/37277245/49481116-fc2ec200-f7ee-11e8-8329-a95a16a5732c.png)

As you can see the lower shaded area.
I tried to hide it using viewController or self but yet it didn't worked

**Comment by Lawati97** [comment]
@tecknut thank you for helping us with the code, i currently have on more issue is that for some reason there is a navigation controller showed up and no matter what i did it kept on showing up, ill attach a picture regarding about my issue.
![screen shot 2018-12-06 at 1 52 26 pm](https://user-images.githubusercontent.com/37277245/49608529-7893e300-f95e-11e8-8598-14759dfcfdcb.png)
![screen shot 2018-12-06 at 1 52 34 pm](https://user-images.githubusercontent.com/37277245/49608533-7b8ed380-f95e-11e8-8a6b-9b3efe9fd9ac.png)
