### ISSUE TITLE
Presenting ZDKHelpCenter on iPhone lacks "Cancel" button

### ISSUE THREAD

**Issue by lickel** [zendesk/zendesk_sdk_ios#38]
ZDKHelpCenter's `+presentHelpCenterWithNavController:` methods should still be allowed on iPhone.

**Comment by tecknut** [comment]
@lickel Thanks for pointing this out. We've created an issue for this and will address it in an upcoming release.

**Comment by Prince2k3** [comment]
This is a pretty important issue. I'm going to bump +1 in hope that this is resolved soon

**Comment by tecknut** [comment]
This is fixed in 1.4.1.1
