### ISSUE TITLE
RequestUI crash on bad audio attachment

### ISSUE THREAD

**Issue by arshiacont** [zendesk/zendesk_sdk_ios#383]
- SDK version: 2.0.3
- Xcode version: 9.3
- iOS or Simulator: Simulator iPhone 6
- iOS Version: 11.3
- Swift version: 4

Steps to Reproduce:

Using API Provider to (successfully) submit a Support Ticket with 3 attachments (2 audio files and 1 txt file). Agent responds to the message. Attempting to go Zendesk UI with RequestList. Openning this specific conversation thread results to systematic crash with "Fatal error: cannot increment beyond endIndex" with the attached stack on the crashed
![zendeskv2-requestlist-crash](https://user-images.githubusercontent.com/3298204/39926399-632b2376-552f-11e8-8daf-1662b5b1eab2.png)

This crash does _not_ happen on other threads containing images. I had similar issue with a conversation having an MP4 video attachment.

**Comment by patrick-doyle** [comment]
HI,

Taking a look at this and we cant reproduce it in our UI. Can you add the code that uses the provider to create ticket and attachments? Also can you link a file that causes the crash?

Thanks

**Comment by arshiacont** [comment]
@patrick-doyle I just found the cause of the error: It is caused (on the iOS UI) if an [audio] attachment has "bad" content such as the corrupted audio file. If as an agent I attach this to a response, it'll cause the UI to crash (whether the corrupted file comes from Agent or User it's the same result).

(I compressed the .wav file here to pass)
[solo_687_2018-05-11-13-21-57.wav.zip](https://github.com/zendesk/zendesk_sdk_ios/files/1995644/solo_687_2018-05-11-13-21-57.wav.zip)

**Comment by divo** [comment]
@arshiacont I can replicate the bug and have a fix on master. The bug isn't specifically for corrupted files and has a very low probability of happening, you just happened to be unlucky. Thank you for reporting it. 

We will patch it in the coming weeks.

**Comment by arshiacont** [comment]
Thank you @divo ! We will put 2.0.3 in production on our side and looking forward to the next Pod update.

**Comment by divo** [comment]
@arshiacont we have just released 2.0.4. It addresses this issue. Thanks for reporting it.
