### ISSUE TITLE
Hiding contact button from article view controllers

### ISSUE THREAD

**Issue by fenroar** [zendesk/zendesk_sdk_ios#387]
- SDK version:
2.0.3

When presenting a view controller instantiated by a ZDKHelpCenterArticle, is there a way to hide the contact button on the navigation bar?

<img width="375" alt="screen shot 2018-05-22 at 12 20 57" src="https://user-images.githubusercontent.com/1408640/40359433-a0f77356-5dba-11e8-9855-ee37ba50cd0a.png">

**Comment by KillianSmith0** [comment]
Hi @fenroar, thanks for reaching out.
We have come across this issue before, and have it in our backlog. Here is a [suggested workaround](https://github.com/zendesk/zendesk_sdk_ios/issues/377#issuecomment-386244051), that might help you for now. Although you will need to replace `leftBarButtonItem` with `rightBarButtonItem`, to remove the contact button.

Don't hesitate to follow up with questions!

**Comment by fenroar** [comment]
Thanks, it works 👍
