### ISSUE TITLE
Pod not found for 2.0.0

### ISSUE THREAD

**Issue by hamdshah** [zendesk/zendesk_sdk_ios#389]
I wanted to import version 2.0.0 because currently we are on swift version 4.0 but the latest version is compiled using 4.1. But cocoapod can't find the version 2.0.0.
Any workaround to import it in swift 4.0 ?

- SDK version: 2.0.0
- Xcode version: 9.2
- iOS or Simulator:
- iOS Version: 10.0
- Swift version: 4.0

Steps to Reproduce:

1. Add the pod to pod file for version 2.0.0

PS

Seems like the tag 2.0.0 don't have `podspec` file.
https://github.com/zendesk/zendesk_sdk_ios/tree/2.0.0

**Comment by hamdshah** [comment]
@KillianSmith0 
Oh okay, thanks for the instance response. 👍

**Comment by KillianSmith0** [comment]
👍🏼
