### ISSUE TITLE
ZDKHelpCenter's present method uses UIModalPresentationStyle wrong

### ISSUE THREAD

**Issue by lickel** [zendesk/zendesk_sdk_ios#39]
In an ideal world, I could just present a view controller myself.
This would let me use custom presentation code as I see fit.

That being said, this property is _not_ meant to be used by the presenter:

    Defines the transition style that will be used for this view controller when it is presented modally. 
    Set this property on the view controller to be presented, not the presenter.

There's a couple solutions that could help resolve this:
* Change the method signature to take common parameters like `modalTransitionStyle` and `modalPresentationStyle`
* Provide a block to configure the view controller, e.g. 

        [ZDKHelpCenter presentHelpCenterWithNavController:nav configuration:^(UIViewController *vc) {
            // allow customization
        }];

* Allow creating ZDKHelpCenterViewControllers directly

**Comment by lickel** [comment]
This is also true of ZDKRequests' presentation methods (and possibly others)

**Comment by tecknut** [comment]
@lickel we are aware this is not a standard use of modal presentation style. You can currently create your own instances of `ZDKSupportViewController`, however it is not properly documented. We have a how to guide which covers doing this which will be available soon.

**Comment by lickel** [comment]
Thanks. I was able to use it directly to handle a number of issues.
It still suffers from https://github.com/zendesk/zendesk_sdk_ios/issues/38 though I can work around it.
