### ISSUE TITLE
[HelpCenter Modal Localization] How to set localization as 'Cancel', 'Contact us' in HelpCenter Modal?[Resolved]

### ISSUE THREAD

**Issue by TranLuongTuanAnh** [zendesk/zendesk_sdk_ios#391]
- SDK version: 1.11.2.1
- Xcode version: 9.1
- iOS or Simulator: Simulator
- iOS Version: 11.0

Steps to Reproduce:

I change iphone language and location to Japanese, but title of Navigation Bar Items of Help Center Modal not show as expected.
How to set this title to japanese?

![simulator screen shot - iphone 8 - 2018-05-25 at 14 04 31](https://user-images.githubusercontent.com/6303302/40528343-afbcc49a-602b-11e8-9d3d-de8af3727e02.png)

**Comment by maxbrunner** [comment]
Hi @TranLuongTuanAnh 

There are a couple of things that maybe going on. Can you try to to configure your XCode development language to Japanese, as here:

![e4abdb83-b2e2-4d68-9081-30aa32e51e0e-20471-0000130663ae59d6](https://user-images.githubusercontent.com/1657704/40550984-a59f5e52-6033-11e8-82ae-36f9124b9744.JPG)

If this don't solve the problem, we will need some more information and then it would be better to open a ticket so we can follow up with the resolution.

**Comment by TranLuongTuanAnh** [comment]
@maxbrunner Thanks your reply! I sloved it by add Japanese to Localizations in Project Info
![localization](https://user-images.githubusercontent.com/6303302/40633588-8a10c176-632b-11e8-8ee8-23799f8920c2.png)
