### ISSUE TITLE
Issue with Zendesk sdk V2.0

### ISSUE THREAD

**Issue by surjeetsg** [zendesk/zendesk_sdk_ios#392]
- SDK version: 2.0.3
- Xcode version: 9.3.1
- iOS or Simulator: Any
- iOS Version: 11.3
- Swift version: 4.0

I upgrade sdk version from 1.x to 2.x, and tested app. App was working as expected. Now after few days, When I try to raise a Ticket on Zendesk, IT doesn't Work. 

Then I test zendesk sample app, and sample app for support also not working.   

Steps to Reproduce:
Attached Video for steps.
[zendesk.zip](https://github.com/zendesk/zendesk_sdk_ios/files/2044669/zendesk.zip)

**Comment by maxbrunner** [comment]
Hi surjeetsg. Which user are you using as an identity? The Zendesk Support SDK is intended for end-users only. Authenticating with an agent/admin/owner email address will cause a 403 authentication error (which may be the cause of the problem you're facing).
