### ISSUE TITLE
Empty ticket list in the iOS app

### ISSUE THREAD

**Issue by EugeneGordin2303** [zendesk/zendesk_sdk_ios#393]
- SDK version: ZendeskSDK 2.0.3
- Xcode version: 9.3.1
- iOS or Simulator: 11.2.6
- iOS Version: 11.2.6
- Swift version: 4
Steps to Reproduce:

1. I submit a ticket from my app
2. I'm getting ticket properly created in the Zendesk portal
3. I see the ticket in the iOS tickets list
4. close the iOS app
5. open the iOS app
6. go to tickets list

Observed: no tickets

Is this a bug or a feature? I thought the Zendesk SDK would fetch the tickets for this user? It appears to me that the tickets are cached as long as the app is "alive" and then the cache is getting cleared.

Can you please clarify this one for me, thank you!

**Comment by KillianSmith0** [comment]
Hi @EugeneGordin2303, this is not expected behaviour of the app. It's possible that you might be setting the identity of the Zendesk instance, in a place that is called every time the app is opened. Try setting it one of the AppDelegate methods.

**Comment by EugeneGordin2303** [comment]
Hi @KillianSmith0 are you saying that identity should be set only once per launch? We set it whenever we get response for getUser...so we actually can set this identity per user basis

**Comment by EugeneGordin2303** [comment]
OK, I followed your suggestion and removed calls that do the identity initialization from everywhere besides my getUser callback and it started to work properly. Thank you, @KillianSmith0 !

**Comment by KillianSmith0** [comment]
@EugeneGordin2303 - yes well the device should be sent once, per device. The tickets are cached to the device per instance of an identity, if the identity is reset the cache will clear. So you should set the identity, only on the initial response for getUser. 

If you want a user's tickets to always be linked to a certain user, you'll have to set up for JWT auth.
For more info give [Setting an Identity](https://developer.zendesk.com/embeddables/docs/ios_support_sdk/sdk_set_identity) a read. Here is a bit more on deciding your [authentication approach](https://develop.zendesk.com/hc/en-us/articles/360001069567#toc_1)
