### ISSUE TITLE
ZDKRequestProvider().getUpdatesForDevice inconsistent

### ISSUE THREAD

**Issue by ShotJP** [zendesk/zendesk_sdk_ios#394]
- SDK version: 1.11.1.1
- Xcode version: 9.3.1
- iOS or Simulator: iPhone 8 Plus
- iOS Version: 11.3

In our application we have a couple places where we use `ZDKRequestProvider().getUpdatesForDevice` to apply badging in various places. When I open the app this will be 0 (specifically `requestUpdates!.requestsWithUpdates.count`). If I navigate to the request list (`ZDKRequests.pushRequestList`) this callback will now return the correct number. If I then stop the app and start again I'm back to getting 0 from `ZDKRequestProvider().getUpdatesForDevice`

Am I getting the badge number incorrectly here?

**Comment by KillianSmith0** [comment]
Hi @ShotJP,
It sounds like you're using it right however, you might want to make a call to `getUpdatesForDevice` when you start the view up, maybe in the viewDidLoad?

Here is a sample app of the Support SDK V2 using [request updates](https://github.com/zendesk/ios_sdk_demo_apps/blob/master/SupportSDKSamples/support_request_updates_sample/RequestUpdatesVC.swift), same rules apply for v1!

**Comment by ShotJP** [comment]
It is indeed being called in `viewWillAppear` in a couple different places. Once the user has seen the request list it properly returns the value but not on a new session start (when the user would need to know if they received a response)

**Comment by KillianSmith0** [comment]
@ShotJP Ah ok now I understand the issue, sorry. 
The Support SDK only caches new tickets to device when the ticket list is refreshed and pulled from the network again. So a user must reload their ticket list. 
For a user to seamlessly find out if they have received a response, you would have to set up [Push Notifications](https://developer.zendesk.com/embeddables/docs/ios_support_sdk/handle_push_notifications_ua)  for request updates.

Reference on ticket updates: https://developer.zendesk.com/embeddables/docs/ios_support_sdk/requests#check-for-ticket-updates

**Comment by ShotJP** [comment]
Push notifications aren't in the cards for us right now, wrapping this in a `getAllRequestsWithCallback` seems to solve the problem though. Still confusing to me to have to do this step but it'll work for our purposes

**Comment by KillianSmith0** [comment]
@ShotJP - that's good news that you found a workaround. After further looking into this issue though the getUpdatesForDevice method should work. If you are storing the the value of `requestWithUpdates.count`, somewhere can you make sure you're not setting it to 0 when you are entering that screen? 

If not the case, and you are unhappy with you're workaround could you try and replicate the issue 
in the [sample app](https://github.com/zendesk/ios_sdk_demo_apps/tree/master/SupportSDKSamples)? As it works for me
