### ISSUE TITLE
Disable ticket creation not working

### ISSUE THREAD

**Issue by iDevo** [zendesk/zendesk_sdk_ios#395]
Hey there!
I'm currently implementing my Help Center into my App using your new SDK 2. 
I followed your required instructions and setup up everything in the AppDelegate and in my custom view controller, in order to show the Help Center and it worked fine so far! (Great work btw, it's way easier than in SDK 1 now!)

In the final step, I'd like to disable the the opportunity to create a ticket inside the App so I followed [your documentation](https://developer.zendesk.com/embeddables/docs/ios_support_sdk/help_center#disable-ticket-creation) but unfortunately, Xcode is complaining that it (obviously) can not find the delegate property in the standard UIViewController class. In my optioning there is just something missing in the documentation like `as! HelpCenterArticleViewController` but I wasn't able to figure out the right subclass.

Here is my exact code inside my custom ViewController subclass, which follows the `ZDKHelpCenterConversationsUIDelegate` delegate:

```
@IBAction func buttonPressedSupport(_ sender: Any) {
        let hcConfig = HelpCenterUiConfiguration()
        hcConfig.groupType = .section
        hcConfig.groupIds = [123456789]
        let helpCenter = HelpCenterUi.buildHelpCenterOverview(withConfigs: [hcConfig])
        helpCenter.uiDelegate = self
        self.navigationController?.pushViewController(helpCenter, animated: true)       
}
```

I may missed any step but of course I double-checked my steps and I think it's pretty straight forward so far.
Thanks in advance! 

- SDK version: 2.0.3
- Xcode version: 9.3.1
- iOS or Simulator: Simulator
- iOS Version: 11.3
- Swift version: 4.0

Steps to Reproduce:
1.  Follow the instructions on the official Zendesk page
2. Look at the error saying: `Value of type 'UIViewController' has no member 'uiDelegate'`

**Comment by tecknut** [comment]
Hey @iDevo, 

Can you option click your `let helpCenter` declaration? It should reveal whether it's type is correct:
```
let helpCenter: UIViewController & ZDKHelpCenterDelegate
```

Above is what should show. The [definition of that builder method](https://github.com/zendesk/zendesk_sdk_ios/blob/5dd0d5976be7ad00b34b7055777f9ba777d33110/ZendeskSDK/4.0.2/ZendeskSDK.framework/Headers/ZDKHelpCenterUi.h#L44) returns such a value. 

```
+ (UIViewController <ZDKHelpCenterDelegate>*) buildHelpCenterOverviewWithConfigs:(NSArray<ZDKUiConfiguration> *)configs;
```
I've tried out the snippet above and unfortunately had no compile errors. I'm on Xcode 9.2 though, and I can't update Xcode at the moment.

If the view controller assignment isn't resolving to the correct type we'll have to look into to this further. 

Alan

**Comment by iDevo** [comment]
Hey @tecknut,
thank you for your quick answer at a Sunday - It's working now thanks to you!

The option click says it's a common ViewController: 
`let helpCenter: UIViewController`

The printing description is:
`<ZDKHelpCenterOverviewController: 0x7fb2d5570310>`

I've no idea, why xCode it's saying that because when I cast the variable `helpCenter` to your type, xCode is doing fine with setting the delegate and also while running the App:
`let helpCenter = HelpCenterUi.buildHelpCenterOverview(withConfigs: [hcConfig]) as! UIViewController & ZDKHelpCenterDelegate`

So maybe it's a xCode related problem too. 
Anyway, it's working perfectly using the cast, thank you very much!!!

Enjoy your weekend!
