### ISSUE TITLE
Debugging ZDKHelpCenterUi view controller

### ISSUE THREAD

**Issue by egfojas** [zendesk/zendesk_sdk_ios#397]
- SDK version: 2.0
- Xcode version: 9.2
- iOS or Simulator: 8+ Simulator
- iOS Version: 11.2
- Swift version: 3.2

Steps to Reproduce:

1.  Open Article using [ZDKHelpCenterUi buildHelpCenterArticleWithArticleId:andConfigs:]
2. Open any redirection link within the loaded article
3. Zendesk View Controller failed to load redirected article.

Is there any way to see the actual URLRequests/httpurl/articleid loaded by the default viewcontroller of zendesk? The redirection works when accessing the webpage on web browsers

Here's the Article Content when called via ZDKProvider getArticleById method
"article_details" = "Happy from Happiness at Circles.Life \U2022 June 2, 2017";
    "author_id" = 6331186108;
    "author_name" = "Happy from Happiness at Circles.Life";
    body = "<p>Bills are only applicable if you're on the $28 /mo Base Plan.</p>\n<p>On an average month (not your <a href=\"https://circlesasiasupport.zendesk.com/hc/en-us/articles/115000491334\">first month</a>), your bill contains:</p>\n<ol>\n<li>Your Base Plan and Pluses for next month, paid in advance.</li>\n<li>Your <a href=\"https://circlesasiasupport.zendesk.com/hc/en-us/articles/115000730054-What-are-the-different-charges-\">additional usage</a> for last month,\U00a0if any.</li>\n</ol>\n<p class=\"wysiwyg-text-align-center\"><iframe src=\"//www.youtube-nocookie.com/embed/a6KjKqDM3ZY\" width=\"560\" height=\"315\" frameborder=\"0\" allowfullscreen=\"\"></iframe></p>\n<p class=\"wysiwyg-text-align-center\">\U00a0<img src=\"https://circlesasiasupport.zendesk.com/hc/article_attachments/115001836494/Capture2.PNG\" alt=\"Capture2.PNG\" width=\"371\" height=\"427\">\U00a0</p>\n<p class=\"wysiwyg-text-align-center\">Now, still unclear? Click below to learn more!\U00a0</p>\n<p class=\"wysiwyg-text-align-center\">**<a href=\"https://circlesasiasupport.zendesk.com/hc/en-us/articles/115000491334\" target=\"_blank\" rel=\"noopener noreferrer\">**<img src=\"https://circlesasiasupport.zendesk.com/hc/article_attachments/115001168294/FAQ_your_first_bill_button.png\" alt=\"FAQ_your_first_bill_button.png\" width=\"156\" height=\"156\">\U00a0</a>\U00a0**<a href=\"https://circlesasiasupport.zendesk.com/hc/en-us/articles/115000730054\" target=\"_blank\" rel=\"noopener noreferrer\">**<img src=\"https://circlesasiasupport.zendesk.com/hc/article_attachments/115001168354/FAQ_mysterious_charges_button.png\" alt=\"FAQ_mysterious_charges_button.png\" width=\"156\" height=\"156\">\U00a0</a>\U00a0</p>\n<p>\U00a0</p>";
    "created_at" = "2017-06-02 08:22:15 +0000";
    htmlUrl = "https://circlesasiasupport.zendesk.com/hc/en-us/articles/115000194254-Reading-my-bill";
    identifier = 115000194254;
    labelNames =     (
        circlesone
    );
    locale = "en-us";
    outdated = 0;
    position = 0;
    "section_id" = 115000024953;
    title = "Reading my bill";
    voteCount = 149;
    voteSum = 7;

![simulator screen shot - iphone 8 plus - 2018-06-07 at 10 30 52](https://user-images.githubusercontent.com/8390560/41075143-e35f96d0-6a3d-11e8-9c57-c931051175b6.png)

![simulator screen shot - iphone 8 plus - 2018-06-07 at 10 29 59](https://user-images.githubusercontent.com/8390560/41075124-c5bbcebe-6a3d-11e8-8c0a-35f45b810d4b.png)

**Comment by KillianSmith0** [comment]
Hi @egfojas, This was a known issue in Zendesk 2.0, can you update to 2.0.3 and see if the issue still occurs?

**Comment by egfojas** [comment]
Hi @KillianSmith0!  Yes, both the links are HC articles as well. Updating to 2.0.3 fixed the problem. Thank you very much!

**Comment by KillianSmith0** [comment]
@egfojas - no problem , gonna close the issue 👍🏼
