### ISSUE TITLE
Crash in RequestListViewController when operator replied. 

### ISSUE THREAD

**Issue by aravika08** [zendesk/zendesk_sdk_ios#398]
- SDK version:
SDK v2 ZendeskSDK 4.1
- Xcode version: 
9.4
- iOS or Simulator:
iOS and Simulator
- iOS Version:
iOS 11
- Swift version:
4.1

Steps to Reproduce:
Hi!
I added SDK in my project, get the crash:
1. Go to empty RequestListViewController:
let viewController = RequestUi.buildRequestList()
self.navigationController?.pushViewController(viewController, animated: true)
2. Empty list. Create new dialog. Write to operator.
3. Wait until the operator answered. Operator answered.
4. Back to ticket list.
Crash

Stack trace:
[Crash ZENDESK.txt](https://github.com/zendesk/zendesk_sdk_ios/files/2080115/Crash.ZENDESK.txt)

**Comment by KillianSmith0** [comment]
Hi @aravika08, thanks for reaching out,

Currently working on replicating this issue, it only appears to not work in certain languages (eg. Russian), can you confirm for me if it works in a different language like english? I wasn't able to replicate a crash but the button doesn't work. Does the crash occur every time the button is pressed?

**Comment by KillianSmith0** [comment]
Hi @aravika08,

I'm currently working on replicating the issue. I was unable to replicate the problem, can you first clean build and delete derived data and see if the issue persists? And also looking through your crash logs, can you confirm the state of your operator/agent's avatar? Did they upload their own profile image, or are they using the dafault avatar?

**Comment by KillianSmith0** [comment]
@aravika08 - We have a fix for this and will be included in one of our upcoming patches. Closing this for now, feel free to reopen
