### ISSUE TITLE
Article View - Don't open links in Safari

### ISSUE THREAD

**Issue by chaseacton** [zendesk/zendesk_sdk_ios#399]
When viewing a single support article, it would be great if URLs opened in an internal web view rather than taking the user to Safari. Can we get this added as a config option?

**Comment by baz8080** [comment]
@chaseacton Are you talking about links that go outside of your Help Center articles?

**Comment by chaseacton** [comment]
In our case, these are links to other articles on our Zendesk site.

**Comment by KillianSmith0** [comment]
Hi @chaseacton, we already have a deeplinking feature as part of the SDK, which seems to be not working for you for some reason.. Can you confirm that the url of the articles matches the URL belonging to your apps configs? 
For example: 
URL: `https://z3ntestkillian.zendesk.com`
Article: `https://z3ntestkillian.zendesk.com/hc/en-us/articles/xxxarticleIDxxx-article-name`

**Comment by chaseacton** [comment]
Thank you, that solved it. I was initializing the SDK with our Zendesk subdomain URL, but the articles linked to our custom domain. Updating the config fixed the problem.
