### ISSUE TITLE
Previous Tickets doesn't appear in Help Center for Anon user

### ISSUE THREAD

**Issue by osrufung** [zendesk/zendesk_sdk_ios#40]
I can create new tickets, view them in the Ticket list in current "session", but... when i restart my App and link the same previous user identity by mean of '[ZDKConfig instance].userIdentity' it appears in blank. Any idea?

**Comment by tecknut** [comment]
Hey @osrufung, can you provide some code snippets ? Preferably the identity setting and it would also be great if you could say when the code is called in your apps lifecycle. 

Thanks

**Comment by osrufung** [comment]
This code is called on viewDidLoad method of "Preferences View Controller" each time user opens this Modal ViewController.
 
- (void)setupZendesk
{
  ZDKAnonymousIdentity *identity = [ZDKAnonymousIdentity new];
  identity.email = self.userSession.userEmail;
  [ZDKConfig instance].userIdentity = identity;
  
  
  [[ZDKConfig instance] initializeWithAppId:@"493de192b1bc857e54b....." zendeskUrl:@"https://mobincube.zendesk.com" ClientId:@"mobile_sdk_client_89....." onSuccess:^() {
    NSLog(@"Config found, SDK is ready");
  } onError:^(NSError *error) {
    NSLog(@"Config could not be fetched.");
  }];
}

After this, the user opens the Helps Desk by means of: 
  [ZDKHelpCenter showHelpCenterWithNavController:self.navigationController];

Thanks!

**Comment by tecknut** [comment]
As a quick fix can you try this ?

```
- (void)setupZendesk
{

 if ( ! [ZDKConfig instance].userIdentity ) {
    identity = [ZDKAnonymousIdentity new]
    identity.email = self.userSession.userEmail;
    [ZDKConfig instance].userIdentity = identity;
 }


  [[ZDKConfig instance] initializeWithAppId:@"493de192b1bc857e54b....." zendeskUrl:@"https://mobincube.zendesk.com" ClientId:@"mobile_sdk_client_89....." onSuccess:^() {
    NSLog(@"Config found, SDK is ready");
  } onError:^(NSError *error) {
    NSLog(@"Config could not be fetched.");
  }];
}
```

Does `self.userSession.userEmail;` change at all when you experience this issue? If it changes at all, it would cause any data associated with the previous identity to be cleared.

**Comment by osrufung** [comment]
Ok! That was the problem. 👍

No, the email doesn't change for the same user.  Thank you!

**Comment by tecknut** [comment]
No problem @osrufung. 

Just a heads up though. If you need to change the identity for some reason in the future this will need to be changed. 

Let us know about any future issues you experience. 

Thanks
