### ISSUE TITLE
Wrong type in header

### ISSUE THREAD

**Issue by abekert** [zendesk/zendesk_sdk_ios#401]
- SDK version: 2.0.3
- Xcode version: 9.4
- iOS or Simulator: Both
- iOS Version: 11
- Swift version: 4

Steps to Reproduce:

1. Open **ZDKHelpCenterUi.h**
2. Look at methods:
`+ (UIViewController <ZDKHelpCenterDelegate>*) buildHelpCenterOverviewWithConfigs:(NSArray<ZDKUiConfiguration> *)configs;`
`+ (UIViewController<ZDKHelpCenterDelegate>*) buildHelpCenterArticle:(ZDKHelpCenterArticle *)article andConfigs:(NSArray<ZDKUiConfiguration> *)configs;`
`+ (UIViewController<ZDKHelpCenterDelegate>*) buildHelpCenterArticleWithArticleId:(NSString *)articleId andConfigs:(NSArray<ZDKUiConfiguration> *)configs;`

There you assume to receive an array **of** configs, nor array that **is** a config instead.
So `configs` type should be `NSArray<id<ZDKUiConfiguration>> *`, not `NSArray<ZDKUiConfiguration> *`

**Comment by KillianSmith0** [comment]
Hi @abekert, 

I'm not sure I follow, the ZDKHelpCenter method `buildHelpCenterOverviewWithConfigs`, will only ever take in a list of `ZDKUiConfigurations`. Do you have an example of why you would need an array of `<id<ZDKUiConfiguration>>`?

**Comment by abekert** [comment]
Sure. Here is an example. I want to build and present help center view controller. So I write something like:
`            __auto_type configurations = @[/* my configurations or empty */];`
`            __auto_type helpCenter = [ZDKHelpCenterUi buildHelpCenterOverviewWithConfigs:configurations];`

And I got an error: 
`Incompatible pointer types sending 'NSArray *' to parameter of type 'NSArray<ZDKUiConfiguration> * _Nonnull'`

Currently the method is assuming **not** the list of configurations, but an array that **is** already a configuration. `NSArray` shouldn't adopt such a protocol. But its members could.

**Comment by KillianSmith0** [comment]
`__auto_type` is only inferring that the object your assigning to `configurations` is an `NSArray *`, this might be because ZDKUiConfiguration isn't an object/class, but only a protocol. 
Here is a set of documentation that shows different ways to set up [configs for the SDK](https://developer.zendesk.com/embeddables/docs/ios_support_sdk/help_center#filter-articles-by-category), I would suggest following these guidelines for setting up configs.

**Comment by abekert** [comment]
You are right about `__auto_type`.

But have you ever try the code from the documentation?
`UIViewController *helpCenter = [ZDKHelpCenterUi buildHelpCenterOverviewWithConfigs:@[]];` 
gives an error, as I said before
`Incompatible pointer types sending 'NSArray *' to parameter of type 'NSArray<ZDKUiConfiguration> * _Nonnull'`

**Comment by abekert** [comment]
Please, look thoughtfully one more time on methods. What do you expect to receive here? What should adopt the protocol? A container? Or the members of that container?

**Comment by KillianSmith0** [comment]
@abekert, these aren't breaking errors, they are only warnings, and won't crash code.
The method takes in `NSArray<ZDKUiConfiguration>`, which is an array of different types of configs used for building the help centre i.e. `ZDKHelpCenterUiConfig` / `ZDKRequestUiConfig`.. `ZDKUiConfiguration` allows an integrator to have different configs set up to style their HC to their needs.

The issue raised with: with article id takes in a String, so it would actually be @"123"

**Comment by abekert** [comment]
As you said, you want **an array of different types of configs used for building the help centre**, then you need an array of elements, where every element is a config — `NSArray<id<ZDKUiConfiguration>>`.

But currently you have an array of what-ever-things-possible, but array itself should be a config — `NSArray<ZDKUiConfiguration>`. That's wrong.

These aren't breaking errors, you are true, but I'm using `Treat Warnings as Errors` flag set to `yes`, so I have to do a strange looking type casting to escape the error.

**Comment by KillianSmith0** [comment]
@abekert unfortunately we are not in the position to change our API's as they aren't broken. As you're treating warnings as errors, you are going to have to apply the cast you initially had, in order to suppress them. Sorry for the inconvenience

**Comment by abekert** [comment]
What do you mean saying **our API's as they aren't broken**?
**It is broken.**
Your header is assuming another type of variable and it's a mistake. I don't understand why you can't accept it.

**Comment by KillianSmith0** [comment]
Thanks for your time on this discussion. Our development repo is actually a private repo, and therefore we can't merge your PR. We will take these changes into account, for an upcoming release.
