### ISSUE TITLE
Have a build for Xcode 10/Swift 4.1.5

### ISSUE THREAD

**Issue by yellowgmk** [zendesk/zendesk_sdk_ios#403]
- SDK version: 2.0.3
- Xcode version: 10.0 beta
- Swift version: 4.1.5

Could you please make a build of the SDK that could be integrated in Xcode 10 beta, which uses Swift 4.1.5 ?

**Comment by NickNko** [comment]
I am also looking for a Build which I can use with Xcode 10 and iOS 12

**Comment by HamstringAssassin** [comment]
Thanks, @NickNko & @yellowgmk. We're looking into this. I'm afraid I can't give any timelines at the moment though. Thanks for your patience. 

I'll keep this issue open so anyone else looking can see any updates.

**Comment by ZWXAllen** [comment]
xcode 10.0 beta 
dyld: Symbol not found: __T0BOWV
  Referenced from: /private/var/containers/Bundle/Application/39416F76-6076-4659-8DB6-E3821E8BD217/EcovacsHome.app/Frameworks/ZendeskCoreSDK.framework/ZendeskCoreSDK
  Expected in: /private/var/containers/Bundle/Application/39416F76-6076-4659-8DB6-E3821E8BD217/EcovacsHome.app/Frameworks/libswiftCore.dylib
 in /private/var/containers/Bundle/Application/39416F76-6076-4659-8DB6-E3821E8BD217/EcovacsHome.app/Frameworks/ZendeskCoreSDK.framework/ZendeskCoreSDK

**Comment by harrygt** [comment]
We are also having this issue. 

Anyway for you guys to build this so that it doesn't break projects when a new swift version is released? Zendesk is our only dependancy that has this problem (we have 9 others).

**Comment by brendan-fahy** [comment]
Hi all, our normal release build process has some issues when building with Xcode 10 (problems with test apps linking with fat binaries created during release). The only thing we've been able to do successfully so far is build for the active architecture only. If that's any good to you, we can share that. In the meantime it's something we'll have to keep looking into.

**Comment by harrygt** [comment]
I think that would be useful for the time being. That should allow us to at least build our products and then make sure there are no other problems. I know its still early beta stages for iOS 12 but being able to run the apps is definitely something we want to do earlier rather than later 👍

**Comment by Abdul-Hannan** [comment]
@brendan-fahy at least we could build that way. I would suggest publishing a branch with that temporary fix and in our podfile, we can use your branch instead of master

**Comment by tecknut** [comment]
@inso- That is indeed our usual release process. This is where the issue lies for us. 

When testing our release builds the linker is complaining about missing symbols for architectures. We've used `nm` to look for the symbols which the linker says are missing. `nm` reports the symbols in the fat framework. 

At the moment we are trying to figure out why the linker is not picking up on these symbols. 

Thank you
Alan

**Comment by KillianSmith0** [comment]
Apologies for the delay, we are having issues with the release build for the SDK on Xcode10-beta, as mentioned above. However I was able to throw together a debug build of the SDK, which is a temporary solution, so you can integrate the SDK into your apps on beta. This will only work on Simulator.

Here is the steps to get them working: 
1. Download the zip and add it to your frameworks folder
2. Delete/Comment out the line in step 4 of [adding the SDK](https://developer.zendesk.com/embeddables/docs/ios_support_sdk/sdk_add#adding-the-sdk-with-cocoapods). 
3. Run on *Simulator*.

[Xcode10Build.zip](https://github.com/zendesk/zendesk_sdk_ios/files/2145185/Xcode10Build.zip)

**Comment by reallyseth** [comment]
@KillianSmith0 I just tried this, and am still seeing build errors. When adding the frameworks from the zip into my frameworks folder, is that the folder underneath the Pods folder? Or do you mean the frameworks folder in the workspace browser?

**Comment by KillianSmith0** [comment]
Here you go 
[Xcode10-3.zip](https://github.com/zendesk/zendesk_sdk_ios/files/2165746/Xcode10-3.zip)

**Comment by yellowgmk** [comment]
@reallyseth There should not be incompatibility problems between the same Swift version... With other libraries, we've been using the same binaries with Xcode 10 beta 1, beta 2, and beta 3 without the need of recompiling.

@KillianSmith0 @HamstringAssassin @tecknut Any progress on having a framework that works both on devices and simulator?

**Comment by welshm** [comment]
Any timeline on when this might get into the main branch? We're looking at developing iOS 12 features, but are blocked by this.

**Comment by tecknut** [comment]
@welshm iOS 12 is still in beta. We won't release a version of the SDK targeted at iOS 12 until the build tools for iOS are out of beta.

**Comment by tecknut** [comment]
@yellowgmk We are having issues with the beta build tools in Xcode 10. When we build for both device and simulator and combine the binaries into a fat framework the linker complains about missing symbols. 
So far we've been able to validate that the symbols the linker is complaining about are actually present in the fat binary. 
We're still looking into this with each new beta version that's released. 
We will update here if any progress is made.

**Comment by KillianSmith0** [comment]
@welshm if you are using CocoaPods, you can put the contents of the `Xcode10-3.zip` in your `Pods>ZendeskSDK>ZendeskSDK` folder, it should work in Xcode10-beta. Make sure not to run `pod update` though.

**Comment by welshm** [comment]
@KillianSmith0 Thanks! That will work for a dev branch with simulator, hopefully something for device later...

**Comment by KillianSmith0** [comment]
Here is a build for [Xcode10-beta4](https://github.com/zendesk/zendesk_sdk_ios/files/2214223/Xcode10-4SDKv2.1.zip). It also includes the most recent version update, so would recommend everyone else to use this one. 

Unfortunately it is still for simulator-only as our SDK continues to disagree with the beta build process.There is still some issues with the build-system according to the Xcode beta-release notes, so hopefully as it matures with the betas, it will become available. 

I will put it into a branch for now also

**Comment by CraigSiemens** [comment]
Would you be able to put that build into a branch? That would allow dependency managers like CocoaPods and Carthage to be pointed at that branch without large project changes to change how Zendesk is included.

**Comment by KillianSmith0** [comment]
@CraigSiemens
Just did it there, branch name `xcode10-beta` 👍  let me know if there's any issues.. There's only a build for the Swift 4.1 artefacts

**Comment by benguild** [comment]
Can we get an update on the release schedule here? The GM will be out soon.

**Comment by divo** [comment]
The issues with our build seems to be resolved in XCode 10 beta 5. I have pushed artifacts to `xcode10-beta` branch, you can find them in the 4.2 folder.

We will do an official release when XCode 10 drops.

**Comment by NickNko** [comment]
I am having an issue integrating the SDK into my AppDelegate. I updated my Podfile to use the xcode10-beta branch. `Support.initialize(withZendesk:` Zendesk.instance)` in my AppDelegate gives me the error shown in the screenshot. 
<img width="512" alt="grafik" src="https://user-images.githubusercontent.com/40205185/43839491-7f61e2ca-9b1e-11e8-8057-6aceb77c9812.png">

I am currently using Swift 4.1, as I am not able to migrate to Swift 4.2, because my project is not compiling due to this error. 
Do you have any suggestions?

**Comment by KillianSmith0** [comment]
@NickNko - if you are using CocoaPods, you can manually put the contents of the 4.2 folder from the `xcode10-beta` branch, into your `Pods>ZendeskSDK>ZendeskSDK` folder, it should work in Xcode10-beta. Make sure **not** to run pod update/install, as it will overwrite it.

Let me know if you have further issues

**Comment by NickNko** [comment]
I resolved my issue by building for the Simulator. Previously I was trying to build onto a physical device, which seems to be unsopported in the beta. @KillianSmith0 when do you plan on supporting physical devices, as the release of iOS 12 is coming closer?

**Comment by jeffremer** [comment]
When building with Xcode 10 Beta 6 (available as of today) I can get the app to execute to the dynamic library loading stage, but then it fails to find a symbol in libswiftDispatch.dylib:

```
dyld: Symbol not found: _$S8Dispatch0A3QoSV0B6SClassO7defaultyA2EmFWC
  Referenced from: /Users/jeff/Library/Developer/CoreSimulator/Devices/50D50194-35E3-4D6C-A679-B3A01B470B05/data/Containers/Bundle/Application/858F47E1-5CFC-4D4E-B5A1-76A28D0EFDE1/Strava.app/Frameworks/ZendeskCoreSDK.framework/ZendeskCoreSDK
  Expected in: /Users/jeff/Library/Developer/CoreSimulator/Devices/50D50194-35E3-4D6C-A679-B3A01B470B05/data/Containers/Bundle/Application/858F47E1-5CFC-4D4E-B5A1-76A28D0EFDE1/Strava.app/Frameworks/libswiftDispatch.dylib
 in /Users/jeff/Library/Developer/CoreSimulator/Devices/50D50194-35E3-4D6C-A679-B3A01B470B05/data/Containers/Bundle/Application/858F47E1-5CFC-4D4E-B5A1-76A28D0EFDE1/Strava.app/Frameworks/ZendeskCoreSDK.framework/ZendeskCoreSDK
```

I'm integrating the SDK manually, not using Cocoapods - does this error indicate that I'm missing something or should I expect this to be resolved in another SDK update?

**Comment by NickNko** [comment]
I am getting the same error

**Comment by hertanu** [comment]
Same issue

**Comment by divo** [comment]
Thanks for letting us know. It's still a beta after all so it's pretty understandable the artifacts produced by different versions are not compatible. 

I will try and get a build up soon.

**Comment by hertanu** [comment]
Would be great to get a new version so we can work with the most updated xCode. Thanks!

**Comment by KillianSmith0** [comment]
@here the Xcode10 beta 6 artefacts are now available on `xcode10-beta` branch, for all interested

**Comment by hertanu** [comment]
Thanks. Can you please add a zip file to with them?

**Comment by jeffremer** [comment]
> Thanks. Can you please add a zip file to with them?

You can download the repository at that particular ref as a [zip file](
https://github.com/zendesk/zendesk_sdk_ios/archive/xcode10-beta.zip).

**Comment by johnny77221** [comment]
Tried set pod file to specified git url and branch to xcode10-beta does not work.
instead, the following works for me on device and simulator:
1. specify pod 'ZendeskSDK', '2.1.0'  and pod install
2. on GitHub page, switch branch Xcode10-beta and download zip
3. open the Zendesk dir in project's pod dir, replace 4.1 folder with the 4.2 folder in the zip file
4. search project and replace pod build scripts to use 4.2 folder

hope it works for you as well

**Comment by boazFrenkel** [comment]
I'm using CocoaPods
- I set the pod file to:
pod 'ZendeskSDK', :git => 'https://github.com/zendesk/zendesk_sdk_ios.git', :branch => 'xcode10-beta'  
- I run pod install
- I deleted the strip-frameworks.sh script

When building with Xcode 10 Beta 6 I can Build the project but then I get an crash as @jeffremer:

dyld: Symbol not found: _$S8Dispatch0A3QoSV0B6SClassO7defaultyA2EmFWC
  Referenced from: /Users..../Frameworks/ZendeskCoreSDK.framework/ZendeskCoreSDK
  Expected in:....

does this error indicate that I'm missing something or should I expect this to be resolved in another SDK update?

**Comment by KillianSmith0** [comment]
@boazFrenkel First can you just try to run pod update, and see if the issue persists? Also what folder is the Core artefact 'Expected in:..' is it your Pods folder.?

Second attempt: can you download the artefacts and try to manually put them into you're `Pods/ZendesKSDK/` folder, and see if the issue persists?

**Comment by boazFrenkel** [comment]
Thanks for the instant reply!
Can I reply here?

**Comment by boazFrenkel** [comment]
@KillianSmith0 

1) I set the pod file to:
pod 'ZendeskSDK', :git => 'https://github.com/zendesk/zendesk_sdk_ios.git', :branch => 'xcode10-beta'
I run pod update ZendeskSDK.  *(successfully)
I deleted the strip-frameworks.sh script

The issue persists here is a full description:

dyld: Symbol not found: _$S8Dispatch0A3QoSV0B6SClassO7defaultyA2EmFWC
  Referenced from: /Users/boaz/Library/Developer/CoreSimulator/Devices/920DDE6C-31B4-4ED4-8A42-8E6A006820F7/data/Containers/Bundle/Application/468491F5-50D9-4616-88E3-C0E173B409A6/Cheetah Staging.app/Frameworks/ZendeskCoreSDK.framework/ZendeskCoreSDK
  Expected in: /Users/boaz/Library/Developer/CoreSimulator/Devices/920DDE6C-31B4-4ED4-8A42-8E6A006820F7/data/Containers/Bundle/Application/468491F5-50D9-4616-88E3-C0E173B409A6/Cheetah Staging.app/Frameworks/libswiftDispatch.dylib
 in /Users/boaz/Library/Developer/CoreSimulator/Devices/920DDE6C-31B4-4ED4-8A42-8E6A006820F7/data/Containers/Bundle/Application/468491F5-50D9-4616-88E3-C0E173B409A6/Cheetah Staging.app/Frameworks/ZendeskCoreSDK.framework/ZendeskCoreSDK

**Comment by RonanMcH** [comment]
Hi @boazFrenkel,
The podspec is actually pointing at the beta4. This was a mistake that we updated the artefacts but didn't point the podspec at the correct folder with the correct artefacts. I'll update the podspec on that branch now and let you know.
Thanks,
Ronan.

**Comment by RonanMcH** [comment]
HI @boazFrenkel ,
I fixed that. Try run `pod update` again and let us know if it works.
Thanks,
Ronan.

**Comment by boazFrenkel** [comment]
Hi @RonanMcH 
It works after running pod update.
Thanks for the quick response!

**Comment by JoaqStar** [comment]
I just installed Xcode 10 Beta 6 and added this to my Podfile:

pod 'ZendeskSDK', :git => 'https://github.com/zendesk/zendesk_sdk_ios.git', :branch => 'xcode10-beta'

I ran pod update and this is what I got:

[!] Failed to load 'ZendeskSDK' podspec: 
[!] Invalid `ZendeskSDK.podspec` file: undefined method `swift_version=' for #<Pod::Specification name="ZendeskSDK">.

 #  from /var/folders/t3/y9q3m9jx3cn1l5wyvsp6sxth0000gn/T/d20180911-3117-bs251/ZendeskSDK.podspec:23
 #  -------------------------------------------
 #    s.frameworks = 'MobileCoreServices', 'SystemConfiguration', 'Security', 'MessageUI'
 >    s.swift_version = '4.2'
 #    s.xcconfig = { 'FRAMEWORK_SEARCH_PATHS' => '$(inherited)', 'CLANG_ENABLE_MODULES' => 'YES', 'ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES' => 'YES' }
 #  -------------------------------------------

My pod file beings with:

platform :ios, '10.0'
use_frameworks!

Do you see something obviously wrong with that configuration?

**Comment by Stunba** [comment]
When you guys gonna release a build with Xcode 10 GM?

**Comment by SoFx00** [comment]
Hi! When will you build your library with XCode 10 GM? 
It is very important for us because it is the only one release blocker.

**Comment by benguild** [comment]
It's been an internal release blocker here for over a month

**Comment by RonanMcH** [comment]
Hey guys,
We are working on a release for Xcode 10 GM today so watch this space. @benguild , we had builds for the some xcode betas up with cocoapods support so this shouldn't have blocked you from an internal release. Could you provide some feedback as to why this was the case?
Thanks,
Ronan.

**Comment by benguild** [comment]
@RonanMcH We couldn't convince everyone to switch to the Xcode beta because of the headaches

**Comment by Stunba** [comment]
Hey @ronan-mch,
Beta release from branch xcode10-beta doesn't work for me. Could you specify what it was build for? which swift version?
I have my project build with external libraries targeting swift 4.1 version but zendesk sdk doesn't compile.(using both current stable version and xcode10-beta branch version).
Thanks.

**Comment by andreyberillo** [comment]
Hi @Stunba 
https://github.com/zendesk/zendesk_sdk_ios/tree/xcode10-beta/ZendeskSDK/4.2
You could use frameworks from "4.2" folder, cause only them currently supports xcode 10.
Try to replace content of <your_project_name>/Pods/ZendeskSDK/ZendeskSDK/4.1/

**Comment by harrygt** [comment]
I've just tried that @andreyberillo but I get this:

```
ld: warning: ignoring file Pods/ZendeskSDK/ZendeskSDK/4.1/ZendeskProviderSDK.framework/ZendeskProviderSDK, file was built for x86_64 which is not the architecture being linked (arm64): Pods/ZendeskSDK/ZendeskSDK/4.1/ZendeskProviderSDK.framework/ZendeskProviderSDK
ld: warning: ignoring file Pods/ZendeskSDK/ZendeskSDK/4.1/ZendeskSDK.framework/ZendeskSDK, file was built for x86_64 which is not the architecture being linked (arm64): Pods/ZendeskSDK/ZendeskSDK/4.1/ZendeskSDK.framework/ZendeskSDK
```

**Comment by Stunba** [comment]
> Hi @Stunba
> https://github.com/zendesk/zendesk_sdk_ios/tree/xcode10-beta/ZendeskSDK/4.2
> You could use frameworks from "4.2" folder, cause only them currently supports xcode 10.
> Try to replace content of <your_project_name>/Pods/ZendeskSDK/ZendeskSDK/4.1/

Thanks @andreyberillo 
It works

**Comment by harrygt** [comment]
Will doing this support Testflight betas? 

Not sure why Zendesk is the only cocoapod we have that is causing problems here. All the others just seem to work fine.

**Comment by hertanu** [comment]
When today do you expect to have the release ready?

**Comment by RonanMcH** [comment]
Hi guys,
We just released version 2.1.1 of the Support SDK with swift 4.2 support.
Thanks,
Ronan.

**Comment by yahalawa** [comment]
Hi so I just started using ZendeskSDK v2.1.1 and it has the fix for Xcode 10 which is great, but it does not work on Xcode 9 (regardless of which build system I choose). I get the following error on first launch of app:
dyld: Symbol not found: _$SBOWV
  Referenced from: /private/var/containers/Bundle/Application/...Frameworks/ZendeskCoreSDK.framework/ZendeskCoreSDK
  Expected in: /private/var/containers/Bundle/Application/.../Frameworks/libswiftCore.dylib
 in /private/var/containers/Bundle/Application/.../Frameworks/ZendeskCoreSDK.framework/ZendeskCoreSDK

**Comment by RonanMcH** [comment]
Hi @yahalawa ,
The release 2.1.1 is just a new build for only xcode 10. Version 2.1.0 is the same code, just built for xcode 9.4 so you should use that!
Thanks,
Ronan.

**Comment by gvsharma** [comment]
I am facing this issue with logic junction sdk as well.

**Comment by dylancopeland** [comment]
Going forward, are fixes going to be back-ported into an Xcode 9 compatible version or is support for Xcode 9 being dropped immediately?
