### ISSUE TITLE
Ticket view doesnt dismiss on successful submission

### ISSUE THREAD

**Issue by jackjpark** [zendesk/zendesk_sdk_ios#404]
- SDK version: 2.0.3
- Xcode version: 9
- iOS or Simulator: Sim / iOS
- iOS Version: 11
- Swift version: Latest

Steps to Reproduce:

1. Create ticket via `RequestUi.buildRequestUi(with: [config])`
2. Display with `navController.pushViewController(viewController, animated: true)`
3. User enters name, email, content and clicks send
4. Confirm message comes up at bottom of view and ticket submits fine
5. Controller stays on screen, if user presses back it tells them message not sent and will be deleted

Expected:

View dismisses to previous view when submitted successfully

Setup Code:

```
    private func createZendeskTicket(title: String, tags: [String], _ navController: UINavigationController) {
        Theme.applyJPTheme()

        let config = RequestUiConfiguration()
        config.subject = title
        config.tags = tags

        let viewController = RequestUi.buildRequestUi(with: [config])
        navController.pushViewController(viewController, animated: true)
    } 
```

**Comment by RonanMcH** [comment]
Hi @jackjpark ,
this issue has been fixed in our latest release. Sorry for the delay in getting back to you.
Thanks,
Ronan.
