### ISSUE TITLE
Article languages do not update

### ISSUE THREAD

**Issue by fenroar** [zendesk/zendesk_sdk_ios#405]
- SDK version: 2.0.3
- iOS or Simulator: iOS

I have an article published in both English and German. If I install my app and the device language is set to German, when viewing the article, it is in German. However, when I then change the language and go back to view the article, the article does not change to English. 

I assume there is some caching mechanism in place as if I uninstall the app and reinstall after the language change, the article then displays the correct language. If so, is there a way to clear this?

**Comment by brendan-fahy** [comment]
Hey @fenroar, this sounds to me like it's our SDK settings being cached that's causing this issue. The settings cache expires after 1 hour, at which point the new locale would be used. Does that solve the issue for you or do need something more immediate?

**Comment by fenroar** [comment]
If there is a way to clear the cache immediately, that would be most ideal in our situation.

**Comment by divo** [comment]
@fenroar, unfortunately, we don't offer this to protect against abuse. 

The next release of the SDK will include an API to override the local we use to fetch Help Center content. It should be released in the coming weeks.

**Comment by KillianSmith0** [comment]
@fenroar - We have released the patch which includes the API mentioned above. Follow these steps to [override the device locale](https://developer.zendesk.com/embeddables/docs/ios_support_sdk/help_center#overriding-device-locale). Just update the SDK to the newest version

**Comment by AndreyLunevich** [comment]
@KillianSmith0 no possibility to change language
![screen shot 2018-07-17 at 4 53 04 pm](https://user-images.githubusercontent.com/1756686/42821802-0f6da4f6-89e2-11e8-83f8-ad25ab261a1c.png)

Zendesk: 2.0.5
