### ISSUE TITLE
Localizable doesn't work

### ISSUE THREAD

**Issue by aravika08** [zendesk/zendesk_sdk_ios#413]
- SDK version:
4.1
- Xcode version:
9.4.1

Steps to Reproduce:

1. Installl SDK, added in project ZendeskSDKStrings.bundle
2. Change language in device
3. Open chat application
_____
Result: Change language from en to ru docent work

Path strings:
zendesk_sdk_ios/ZendeskSDK/4.1/ZendeskSDKStrings.bundle/ru.lproj/Localizable.strings

**Comment by tecknut** [comment]
Hi @aravika08, 

Have you any update for us?

Thanks

**Comment by aravika08** [comment]
>>Can you add more details on where the exact issue is?

Yeah, sorry. I was on vacation.
Localization in our application is not implemented by standard means, so as it turned out it was necessary to simply adjust the project settings.

Thank you for your time!
