### ISSUE TITLE
UI element is not hittable after integrated Zendesk SDK 2.1.0

### ISSUE THREAD

**Issue by ngoclt** [zendesk/zendesk_sdk_ios#422]
- SDK version: 2.1.0
- Xcode version: 9.4.1
- iOS or Simulator: Simulator
- iOS Version: 11.4.1
- Swift version: 3.3

Steps to Reproduce:

1. Previously we were using Zendesk SDK 1.6, all of the UI tests works well.
2. However, after update to ZendeskSDK 2.1.0 via Cocoapods.
3. All of the UI tests are failed. 

Issue: The element is not hittable. ( `tap()` function doesn't work at all).

Our UI test was working perfectly until I integrate with Zendesk SDK. All of UI element is not hittable when we run the UI test (both with Xcode or with command line). **If I remove Zendesk SDK from Cocoapods, it works well again**.

**Comment by divo** [comment]
@ngoclt this sounds like it will be very tough to track down. 

I did find a few places [talking about adding a delay](https://stackoverflow.com/questions/37276597/xcuielement-tap-not-working) after your tests start. It's possible initializing the ZendeskSDK has added enough of a startup delay to break your tests.

Failing that, can you make a sample project that recreates the issue? We need something to start with.

**Comment by ngoclt** [comment]
Hi, 

Thank you very much for your response. Our temporary solution is reverting the SDK back to v1. It works well for our UI test. For the moment, we don't have time for creating a sample. But will do it during this weekend. 

Btw, since Cocoapods supports for static framework now, could you please add this clarification `s.static_framework = true` into your Podspec file?

**Comment by divo** [comment]
@ngoclt 2.0 is now a dynamic framework so we can't add this to our podfile

**Comment by ngoclt** [comment]
Yes, I meant adding to version v1.11.2.2 
But it's fine anyway. 

I will update this ticket by the end of this week. 

Thanks,

**Comment by RonanMcH** [comment]
Hi @ngoclt ,
Is this issue still persisting for you? 
Thanks,
Ronan.

**Comment by RonanMcH** [comment]
Hi @ngoclt ,
I am going to tentatively close this issue since we haven't heard from you in a while. Please feel free to reopen it if you are still having problems.
Thanks,
Ronan
