### ISSUE TITLE
Help Center SearchBar background color

### ISSUE THREAD

**Issue by mstar0125** [zendesk/zendesk_sdk_ios#423]
Hello, 
I am adding Help Center in my app. I customized navigation bar with custom color, but couldn't update SearchBar background, so it looks weird.

Could you please help me how to do this?

![img_0190](https://user-images.githubusercontent.com/5414823/43349188-c39e8160-9230-11e8-8fb7-4d6d027c7118.png)

**Comment by divo** [comment]
@mstar0125 What iOS versions are you seeing this on? How are you styling your navigation bar? Can you try `UINavigationBar.appearance.barTintColor` ?

**Comment by SandissM** [comment]
@divo Hey, I've same exact result as @mstar0125 and I'm setting custom color exactly as you suggested with .barTintColor

**Comment by KillianSmith0** [comment]
@SandissM - can you confirm what version of iOS you are testing on? Is it 10/below? Thanks

**Comment by SandissM** [comment]
I'm using iOS 11

**Comment by KillianSmith0** [comment]
@SandissM can you also try and set the color of `UISearchBar.appearance().barTintColor`, and see if this solves the issue?

**Comment by SandissM** [comment]
Sadly, it didn't.
![screen shot 2018-08-08 at 11 49 01](https://user-images.githubusercontent.com/33860247/43826898-23f6001e-9b01-11e8-8b76-ec1ef8772632.png)

Well everything would be fine if it would be possible to at least add padding to that search bar it looks kinda weird being so close.

**Comment by KillianSmith0** [comment]
@SandissM I'm having difficulties replicating the issue, can you provide an insight as to how you're presenting the HelpCenter?

**Comment by SandissM** [comment]
@KillianSmith0 Sure, 

So for presenting(modally):

`
let identity = Identity.createAnonymous()
  Zendesk.instance?.setIdentity(identity)

  let hcConfig = HelpCenterUiConfiguration()
  hcConfig.hideContactSupport = true

 let vc = ZDKHelpCenterUi.buildHelpCenterOverview(withConfigs: [hcConfig])
 vc.uiDelegate = self

let nc = UINavigationController(rootViewController: vc)
nc.addStyle(style: .zendesk)
(self.navigationController ?? self).present(nc, animated: true, completion: nil)
`

And implementation of addStyle() in case of zendesk:
`
navigationBar.tintColor = .white
navigationBar.barTintColor = .red
navigationBar.titleTextAttributes = [NSAttributedStringKey.font: UIFont.boldSystemFont(ofSize: 16)]
navigationBar.isTranslucent = false
UIApplication.shared.statusBarStyle = .lightContent
`

**Comment by divo** [comment]
@SandissM I'm following what you are doing exactly and I still can't replicate this.
However, I see you are styling an instance of UINavigationController and then presenting it with another. 
Can you try styling it, in the same way, but using UIAppearance?
So `navigationBar.tintColor = .white` -> `UINavigationBar.appearance.tintColor` etc

**Comment by SandissM** [comment]
@divo Tried replacing ```navigationBar``` with ```UINavigationBar.appearance()```, but unfortunately with no luck. 

_However, I see you are styling an instance of UINavigationControllers UINavigationBar and then presenting it with another._
```(self.navigationController ?? self).present(nc, animated: true, completion: nil)```
Well not exactly im presenting it **onto** another, not with another.

**Comment by divo** [comment]
@SandissM I still can't replicate this with the code you have provided. I have no idea how `UIAppearance` wouldn't work.

Can you replicate the issue in a sample project and send it to us?

**Comment by SandissM** [comment]
I found the place which where breaking it, set from another place where these parameters which broke the visual look of it.

Code which broke behaviour:

```
navigationBar.setBackgroundImage(UIImage(), for: UIBarMetrics.default)
navigationBar.shadowImage = UIImage()
```

![Uploading Screen Shot 2018-08-15 at 10.07.19.png…]()

**Comment by divo** [comment]
@SandissM  I'm glad you found the issue.

The second screen shot you posted looks correct to me, what exactly is the issue?

**Comment by SandissM** [comment]
@divo Ideally search bar should be in the middle of yellow box I guess. Basically simulate zendesk v1 default UI but its aligned to top

**Comment by divo** [comment]
@SandissM afaik we aren't modifying the layout of the search bar. This is the system default. I would guess it's supposed to be the same color as the nav bar as it copies its appearance by default.

**Comment by tecknut** [comment]
Hey @SandissM, 

We've looked back through the code which adds the search bar. Nothing has changed since v1 in terms of how the search bar is added on screen. If there is a change in layout this was not intended. 

Have you confirmed that the search bar is in the middle of the yellow box in v1? 

Thanks,
Alan

**Comment by RonanMcH** [comment]
Hey @SandissM ,
this seems to a bug in iOS 11 with Apple's appearance selector for the searchBar when the `navigationItem`s `searchController` is set to be a `UISearchController`. Here is a simple [sample app](https://drive.google.com/file/d/1MKSBDk9iO_xIuzxIKHdsmo8Xc7q67Pr7/view) showing the issue.
Thanks,
Ronan.
