### ISSUE TITLE
RequestProvider has no initWithZendesk method on Objective C

### ISSUE THREAD

**Issue by EfeAcikgoz** [zendesk/zendesk_sdk_ios#427]
- SDK version:
4.1
- Xcode version:
9.4.1 
- iOS or Simulator:
iPhone X
- iOS Version:
11.4.1
- Swift version:
Using Objective-C

Following the guide Support SDK v2 iOS to implement the Check for ticket updates.
The guide initializes the RequestProvider using initWithZendesk:[ZDKZendesk instance], but if I try to initialize it like that, I get the error "No visible @interface for 'ZDKRequestProvider' declares the selector 'initWithZendesk:'"

Steps to Reproduce:

1. Just try to type 
ZDKRequestProvider * provider = [[ZDKRequestProvider alloc] initWithZendesk:[ZDKZendesk instance]];

**Comment by EfeAcikgoz** [comment]
Adding 
- (instancetype)initWithZendesk:(ZDKZendesk *)zendesk; to ZDKRequestProvider.h under ZDKRequestProvider interface fixes the issue, and I can can get the updates again

**Comment by divo** [comment]
@EfeAcikgoz you can just use `init`. There is no need to pass it the Zendesk instance. This was a bit confused when we launched 2.0, it is explained [in our documentation.](https://developer.zendesk.com/embeddables/docs/ios_support_sdk/migration_guide#update-the-provider-references)

**Comment by EfeAcikgoz** [comment]
Rechecked it, now it's working with just init too.
When I first implemented it with init, I was always getting 0 totalUpdates from the method.
I'm not sure what changed, but it seems to be working fine right now with just init, so I'm closing the issue.
