### ISSUE TITLE
Text cursor moves to the end automatically in a request view in Japanese

### ISSUE THREAD

**Issue by pixyzehn** [zendesk/zendesk_sdk_ios#428]
- SDK version 2.1.0:
- Xcode version 9.4.1:
- iOS or Simulator iOS:
- iOS Version 11.4.1:
- Swift version 4.1:

Steps to Reproduce:

1. Open a request view composed by `RequestUi.buildRequestUi`.
2. Type a message in Japanese.
3. Move the cursor between words and type a message in Japanese.
4. After finishing a conversion mode, the cursor ends up moving in the end.

Result: The cursor shouldn't move to the end.

1 | 2
---- | ---- 
<img src="https://user-images.githubusercontent.com/2482478/44261871-ee8a0800-a210-11e8-89f2-035ac4835ff7.PNG" width="320"/> | <img src="https://user-images.githubusercontent.com/2482478/44261869-edf17180-a210-11e8-8967-56b16c6e12a4.jpeg" width="320"/>

**Comment by tecknut** [comment]
Hey @pixyzehn, thanks for raising this. We'll look into this and update you here.

**Comment by tecknut** [comment]
Hi @pixyzehn we've been trying to replicate this, and for us the cursor stays in the middle after typing. 

Can you give us some more specific reproduction steps please?

Thank you,
Alan

**Comment by pixyzehn** [comment]
@tecknut Yes, I can.

Steps to Reproduce:

1. Type `てすと` in Japanese.
2. Move the cursor from end to the betwee `て` and `す`.
3. Type a character and tap the enter which is `確定` in Japanese.

The result: The cursor end up moving to the end.

Also, you can reproduce similar issues if you delete `て` from `てすと`. The cursor will move to the end as well. Hope you can figure out the problem.

**Comment by tecknut** [comment]
I've tried the steps above and It's not happening here for me. 

![keyboard-issue](https://user-images.githubusercontent.com/2079547/45623883-9ef16300-ba80-11e8-9720-340714ee9c9c.gif)

Am I missing something?

**Comment by pixyzehn** [comment]
@tecknut As far as I can see, we use this text field part in Contact us. Please let me know if you need something.

<img src="https://user-images.githubusercontent.com/2482478/45624266-6732ed00-ba79-11e8-975f-d0691519e63a.jpg" width="320">

**Comment by tecknut** [comment]
Ah yes great! I can replicate this now. I'll have a deeper look at this and get back to you.

**Comment by KillianSmith0** [comment]
Hi @pixyzehn,

We released a new version of our SDK. If you update to v2.3.0 your issue should be resolved.

I'll close this issue, feel free to open a new one if any other problems arise.
Killian

**Comment by pixyzehn** [comment]
@KillianSmith0 Thank you for letting me know that. Will update the version.
