### ISSUE TITLE
Module compiled with Swift 4.1 cannot be imported by the Swift 4.2 compiler

### ISSUE THREAD

**Issue by Blockwallet** [zendesk/zendesk_sdk_ios#429]
- SDK version: 2.1.0
- Xcode version: 10.0 beta 6
- iOS or Simulator:
- iOS Version: 10.13.6
- Swift version: 4.2

Steps to Reproduce:

1. Build or Run
2. Get error "Module compiled with Swift 4.1 cannot be imported by the Swift 4.2 compiler" by "import ZendeskSDK"

Is there a workaround?

**Comment by tecknut** [comment]
Hi @Blockwallet there is an [issue tracking the beta versions of Xcode](https://github.com/zendesk/zendesk_sdk_ios/issues/403).

Thank you
