### ISSUE TITLE
Help Center searchBar background color transition animation 

### ISSUE THREAD

**Issue by jamfly** [zendesk/zendesk_sdk_ios#430]
- SDK version: 2.1.0
- Xcode version: 9.4.1
- iOS or Simulator: ios and simulator
- iOS Version: 11.4.1
- Swift version: 4.1

Steps to Reproduce:

1. open a help center view composed by `ZDKHelpCenterUi.buildHelpCenterOverview()`
2. tap random question 
3. tap back button

Result: 
search bar background color supposed to be as same as navigation bar, but it turn out that it is black.

![bug0](https://user-images.githubusercontent.com/32366307/44394037-cc71ec00-a568-11e8-91d4-28a870cd8552.gif)

Steps to Reproduce:

1. open a request view composed by `ZDKHelpCenterUi.buildHelpCenterOverview()`
2. tap textField

Result:
status bar will be black, not the same color of navigation bar 
![bug1](https://user-images.githubusercontent.com/32366307/44394277-646fd580-a569-11e8-8582-921273ae09d9.gif)

**Comment by RonanMcH** [comment]
HI @jamfly ,
I have not been able to reproduce this issue. Are you on the latest version of the SDK?
Thanks,
Ronan.

**Comment by jamfly** [comment]
Hi @RonanMcH 
I am using 2.1.0

**Comment by RonanMcH** [comment]
Great,
I'm still struggling to reproduce this. Are you setting any properties on your navBar globally or in the navController? 
Thanks,
Ronan.

**Comment by jamfly** [comment]
@RonanMcH 

    [[UIBarButtonItem appearanceWhenContainedInInstancesOfClasses:@[[UISearchBar class], [UINavigationController class]]] setTintColor:[UIColor whiteColor]];

    [[UITextField appearanceWhenContainedInInstancesOfClasses:@[[UISearchBar class], [UINavigationController class]]] setBackgroundColor:[UIColor ic_darkRed]];

    [[UISearchBar appearanceWhenContainedInInstancesOfClasses:
      @[[UINavigationController class]]] setBackgroundColor:[UIColor ic_red]];

    [[UISearchBar appearanceWhenContainedInInstancesOfClasses:
      @[[UINavigationController class]]] setImage:[UIImage imageNamed:@"iphone-input-search"] forSearchBarIcon:UISearchBarIconSearch state:UIControlStateNormal];

    [[UIBarButtonItem appearanceWhenContainedInInstancesOfClasses:@[[UISearchBar class], [UINavigationController class]]] setTintColor:[UIColor whiteColor]];

above is my implementation of set navigation bar and search bar, i am not sure if these did influence animation, and I put these code inside 
`- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions`

just after `[self.window makeKeyAndVisible]`

**Comment by RonanMcH** [comment]
Hi @jamfly ,
I still haven't reproduced this issue. I made a sample project with this code in it and still could not see the black bars appearing in your app. Could you possibly send us a sample project with the problem replicated? 
Thanks,
Ronan.

**Comment by jamfly** [comment]
HI @RonanMcH 
Thank you for your respond

But, I am afraid I can't give you sample project. If possibly that property or method in somewhere causes it?  And I changed it without even notice. And could you tell me what's the best move to customize help center's ui. cause i also had tried `[ZDKTheme currentTheme].primaryColor = [UIColor orangeColor]` but it didn't work. Also I want to ask if possibly some animation settings may cause it?

Thanks, 
Jamfly

**Comment by divo** [comment]
@jamfly `primaryColor` only sets a few accent colors within our UI.

Can I suggest you create a sample integration and apply your apps styling until the bug manifests? That should help you figure out what exactly is going wrong. We are still not able to replicate this with the information you have provided.

**Comment by tecknut** [comment]
Hi @jamfly, 

The `preferredStatusBarStyle` property on view controllers can only be overridden internally. Unfortunately.  

I've been trying to find the source of the black search bar with no luck so far. I'm not sure how this is occurring in the gif above. We have no code which alters appearance during view will appear. 

Out of curiosity, do you require view controller based status bar style?

**Comment by jamfly** [comment]
Hi @tecknut 
If I just use default theme, the whole white one, and I set `preferredStatusBarStyle` to be `UIBarStyleBlack` It would simply be whole black, that's fair enough, but it will also produce that black bar animation.  Can I just turn the animation off, or set StatusBar color by navigation bar's color. 

Thanks,
Jamfly

**Comment by tecknut** [comment]
The animation is a system one. We're not actually animating anything during the transition.

**Comment by jamfly** [comment]
@tecknut so, that black bar just cannot solve, right? cause if you don't wanna your status bar be white, that would appear.

**Comment by RonanMcH** [comment]
HI @jamfly , 
this seems to be an Apple bug in iOS 11 when you set the `navigationItem`s `searchController` to be a `UISearchController` the appearance seems to get set to the `searchBar` after it has finished animating on to the screen when navigating back on the nav stack, which is why the color appears to pop on. 
The reason it doesn't happen on other versions of iOS is because our code sets the `searchBar` as a property on the `tableView` instead in this case because of other bugs we encountered. This [sample app](https://drive.google.com/file/d/1MKSBDk9iO_xIuzxIKHdsmo8Xc7q67Pr7/view?usp=sharing) shows the issue in a project with a very simple set up.
Thanks,
Ronan.

**Comment by jamfly** [comment]
Hi @RonanMcH 
sorry for the lately respond, and thank you for your help
so I just change my style to whole white. 
And no more ugly black bar show up again.

**Comment by RonanMcH** [comment]
Hi @jamfly ,
that's great.
Thanks,
Ronan.
