### ISSUE TITLE
Can't install Zendesk through Cocoapods

### ISSUE THREAD

**Issue by nyeu** [zendesk/zendesk_sdk_ios#432]
- SDK version: Trying to install 2.0.4
- Xcode version: 9.4
- iOS or Simulator: Both
- iOS Version: 11.3
- Swift version: 4.1

Steps to Reproduce:

1. Add `pod 'ZendeskSDK'` to my Podfile as said in the installing tutorial.
2. Run `pod install`
3. This message appears 
```[!] Error installing ZendeskSDK
[!] /usr/bin/git clone https://github.com/zendesk/zendesk_sdk_ios.git /var/folders/v0/qmjt9h111dxf164x9l__d_dh0000gn/T/d20180831-19106-1199pp6 --template= --single-branch --depth 1 --branch 2.0.4

Cloning into '/var/folders/v0/qmjt9h111dxf164x9l__d_dh0000gn/T/d20180831-19106-1199pp6'...
warning: Could not find remote branch 2.0.4 to clone.
fatal: Remote branch 2.0.4 not found in upstream origin
```

<img width="1067" alt="screen shot 2018-08-31 at 19 32 04" src="https://user-images.githubusercontent.com/7888779/44927379-a280ac80-ad54-11e8-92aa-fbbde23008be.png">

All other pods have run good, the issue only happens with Zendesk pod.

**Comment by KillianSmith0** [comment]
Or try running `pod update`

**Comment by nyeu** [comment]
The combination of both worked, thank you.

**Comment by KillianSmith0** [comment]
@nyeu I would recommend removing the `, '~> 2.1'` as it will point you to the 2.1 version only.. When there is a new version of the SDK, you won't be pointed towards the new version when you run `pod update` next
