### ISSUE TITLE
Swift 4.2 Support

### ISSUE THREAD

**Issue by rhysforyou** [zendesk/zendesk_sdk_ios#433]
With the Xcode 10 GM Seed now available, and Apple accepting submissions compiled against the iOS 12 SDK, it'd be helpful to have a version of the Zendesk SDK which works with Swift 4.2

- SDK version: 2.1.0
- Xcode version: Version 10.0 (10A254a)
- iOS or Simulator: Simulator and Device
- iOS Version: 12.0
- Swift version: 4.2

Steps to Reproduce:

1. Install the SDK
2. Build the app

**Comment by RonanMcH** [comment]
Hi guys,
We just released version 2.1.1 of the Support SDK with swift 4.2 support.
Thanks,
Ronan.

**Comment by wrags** [comment]
🙌Thanks!
