### ISSUE TITLE
HelpCenterCategoryViewModel' is unavailable: cannot find Swift declaration for this class

### ISSUE THREAD

**Issue by egfojas** [zendesk/zendesk_sdk_ios#435]
- SDK version:  2.0.2
- Xcode version: 9.4.1
- iOS or Simulator: Simulator
- iOS Version: 11.1
- Swift version:  4.1

Steps to Reproduce:

1. Use HelpCenterCategoryViewModel, HelpCenterSectionViewModel, or HelpCenterArticleViewModel in swift class

Error seen: HelpCenterCategoryViewModel' is unavailable: cannot find Swift declaration for this class
App successfully builds but still showing said error

**Comment by KillianSmith0** [comment]
@egfojas Can you confirm whether clean-building your project fixed this?

**Comment by RonanMcH** [comment]
Hi @ngoclt ,
I am going to tentatively close this issue since we haven't heard from you in a while. Please feel free to reopen it if you are still having problems.
Thanks,
Ronan.
