### ISSUE TITLE
`Theme` Swift class name is too generic

### ISSUE THREAD

**Issue by chrismanderson** [zendesk/zendesk_sdk_ios#436]
- SDK version: 2.1.1
- Xcode version: 10
- Swift version: 4.2

The Swift class name `Theme` for the `ZDKTheme` Objective C class is too generic. I already have a `Theme` class in my app, and I would assume many other developers do as well as it's a pretty common and well-defined term. It's also not listed under a module, as something like `ZDK.Theme` doesn't work.

While `Theme` is a Swiftier-name for sure, in this case, I think it should remain `ZDKTheme` to minimize any code conflicts. It could also be namespaces under a module, but that feels like a larger task, so the rename itself is much simpler.

https://github.com/zendesk/zendesk_sdk_ios/blob/ff67eaddcab874305d7a22da710819b51898c0f1/ZendeskSDK/4.2/ZendeskSDK.framework/Headers/ZendeskSDK-Swift.h#L401

**Comment by tecknut** [comment]
Hi @chrismanderson, 

`Theme` is infact namespaced in Objective C to `ZDKTheme`. Additionally, in Swift, it is namespaced under the SDK module `ZendeskSDK.Theme`.

It's possible to typealias this to something shorter if required. 

`
