### ISSUE TITLE
issue with MODULES_DISABLED macro

### ISSUE THREAD

**Issue by hfutrell** [zendesk/zendesk_sdk_ios#437]
- SDK version: 2.1.1 
- Xcode version: Version 10.0 (10A255)

ZendeskSDK.framework/Headers/ZendeskSDK.h includes the following macro usage:

```
#if MODULES_DISABLED
#import <ZendeskProviderSDK/ZendeskProviderSDK.h>
#else
@import ZendeskProviderSDK;
#endif
```

This looks like it'd be handy if Zendesk is inadvertently included from a context where Objective-C modules (i.e `@import`) do not work such as Objective-C++. Unfortunately slightly higher up in `ZendeskSDK.h` we have:

```
#import "ZDKHelpCenterUi.h"
```

and then in `ZDKHelpCenterUi.h` we have

```
@import UIKit;
```

The `@import` in `ZDKHelpCenterUi.h` seems to make the `MODULES_DISABLED` macro pointless, because it will still be used even if the macro is enabled. This can break compilation if you rely on `MODULES_DISABLED` to disable usage of `@import`. Is this an oversight or am I misunderstanding the purpose of the `MODULES_DISABLED` macro?

**Comment by tecknut** [comment]
Hey @hfutrell, 

Apologies for the late reply to your issue. This is indeed an oversight. Thank you for bringing it to our attention. 

It will be fixed in our release. 

Thank you,
Alan

**Comment by KillianSmith0** [comment]
Hi @hfutrell 

We released a new update of our SDK. Updating to 2.3.0 will fix your issue. 
Going to close this issue, feel free to open a new one if any other issues occur. 

Killian
