### ISSUE TITLE
Set language for Help Center

### ISSUE THREAD

**Issue by rusdariusalex** [zendesk/zendesk_sdk_ios#439]
- SDK version: 4.2
- Xcode version: 10.0
- iOS or Simulator: 12.0
- iOS Version: 12.0
- Swift version: Objective-C

Is there any way to change the language of the Help Center? For example the phone language is English but you want to change the app language to French. I would like to force the Help Center content language to French. (something like [ZDKHelpCenterUi buildHelpCenterOverviewWithLanguage:@"fr"])

**Comment by KillianSmith0** [comment]
You weren't too far off: [Overriding device locale](https://developer.zendesk.com/embeddables/docs/ios_support_sdk/help_center#overriding-device-locale)

`Support.instance().helpCenterLocaleOverride = "fr"`

**Comment by rusdariusalex** [comment]
Thank you.

Just one more question:

First time when I call [ZDKRequestUi buildRequestUi], it uses the strings from Localizable.strings. But if I call the same method again after I changed the language of the app the strings have the value of the previous language and localizedStringForKey method is not called any more
