### ISSUE TITLE
Why does it take over my UINavigationBar customization?

### ISSUE THREAD

**Issue by hawflakes** [zendesk/zendesk_sdk_ios#444]
I lost my custom back indicator and the little hairline I put in my navigationBar. How do I customize those?

- SDK version: 2.1.1
- Xcode version: 10
- iOS or Simulator: both
- iOS Version: 12
- Swift version: 4.2

Steps to Reproduce:

1.  Have a custom NavigationBar in your NavigationController
2. Push a Zendesk Controller
this one kinda works:
```
            let helpCenter = HelpCenterUi.buildHelpCenterOverview(withConfigs: [config])
```

this one breaks:
```
            let requestScreen = RequestUi.buildRequestUi(with: [config])
```

separately, there is mention of customizing the way help center works, but I can't figure out how to disable the right bar button item ( the compose button)

**Comment by hawflakes** [comment]
Before I open up a new ticket I have a nice hairline. Afterwards it's gone.

![simulator screen shot - iphone 8 - 2018-09-28 at 01 28 10](https://user-images.githubusercontent.com/232777/46197285-34c99100-c2be-11e8-9da7-1d0bef5c505b.png)
![simulator screen shot - iphone 8 - 2018-09-28 at 01 28 12](https://user-images.githubusercontent.com/232777/46197286-34c99100-c2be-11e8-88a7-6948c4506641.png)
![simulator screen shot - iphone 8 - 2018-09-28 at 01 28 02](https://user-images.githubusercontent.com/232777/46197287-34c99100-c2be-11e8-9b8d-8bf55d11d447.png)

**Comment by KillianSmith0** [comment]
I was able to replicate this issue.. I will create a bug in our backlog to track this.

We are aware of the the issue of hiding the compose button in the HC view, and are planning on releasing a fix for this soon. 

However, to do this, you would normally use on of our `HelpCenterUiConfigs`
```swift
let config = HelpCenterUiConfiguration()
config.hideContactSupport = true
```
This line should work as planned in one of our upcoming releases. Will keep you posted on this post, in relation to both issues.

Thanks,
Killian

**Comment by KillianSmith0** [comment]
Hi @hawflakes 

We release a new version of Support last Friday. Updating to v2.3 should solve the navbar issue.
As for disabling ticket creation, take a look at our [updated docs](https://developer.zendesk.com/embeddables/docs/ios_support_sdk/help_center#disable-ticket-creation).

I'm going to close this issue, feel free to open a new one if other issues occur
