### ISSUE TITLE
ZendeskCoreSDK requires libswiftAVFoundation

### ISSUE THREAD

**Issue by adamtait** [zendesk/zendesk_sdk_ios#446]
- SDK version: 2.2 (or 4.2?)
- Xcode version: 10.0
- iOS or Simulator: Simulator
- iOS Version: 10.13 (but shouldn't matter)
- Swift version: 4.0

Steps to Reproduce:

1. Create new single view Obj-C iOS app
2. Integrate Zendesk SDK into iOS app codebase [according to docs](https://developer.zendesk.com/embeddables/docs/ios/integrate_sdk)
3. Run project; See runtime error

```
dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib
  Referenced from: /Users/adamtait/Library/Developer/CoreSimulator/Devices/54E7817C-5613-4145-8AE3-00DF43B8ECEF/data/Containers/Bundle/Application/E29E231A-98FD-4ED9-81E9-DB1971447A38/myapp.app/Frameworks/ZendeskSDK.framework/ZendeskSDK
  Reason: image not found
```

This problem will always occur in projects where `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO`. Changing `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=YES` fixes the problem.

Including the Swift standard libs bloats an Obj-C app which doesn't otherwise use them. Can we remove the ZendeskCoreSDK upon them?

**Comment by KillianSmith0** [comment]
Hi @adamtait,
We use Swift to develop our SDK's.. If `AWAYS_EMBED_SWIFT_LIBRARIES=NO` then it won't work.. Our SDK is a dynamic swift library.. Although it bloats the build of the application, it will only be a small fraction of your app's footprint, when the .ipa reaches the app store, as their is a number of optimisations that happen beforehand. Here's a good read on [dynamic libraries](https://www.ca.com/en/blog-developers/dynamic-versus-static-framework-in-ios.html)

**Comment by tecknut** [comment]
Hey @adamtait we're going to close this.

If you need any further help please get in touch. 

Thanks, 
Alan

**Comment by adamtait** [comment]
Nothing further. Clearly, it's unreasonable to ask you to re-write your SDK in another language so we have reached an impasse and you were right to close the ticket.

If you're curious, I won't be using the SDK and instead will leverage Zendesk's HTTP/REST API from all my iOS & Android apps.
