### ISSUE TITLE
`additionalRequestInfo` in ZendeskSDK 2.X

### ISSUE THREAD

**Issue by ManueGE** [zendesk/zendesk_sdk_ios#452]
- SDK version: 2.2
- Xcode version: 10.1 beta2
- iOS or Simulator: iOS
- iOS Version: 12
- Swift version: 4.2

Steps to Reproduce:

1. With ZendeskSDK 1.X we were able to add some additional info to the requests using this method:
```
[ZDKRequests configure:^(ZDKAccount *account, additionalRequestInfo *requestCreationConfig) {
    NSString *txt = [NSString stringWithFormat:@"%@%@", [requestCreationConfig contentSeperator], @"whatever"];
    requestCreationConfig.additionalRequestInfo = txt;
}];
```
2. Is this possible to do the same thing in version 2.X ?

**Comment by tecknut** [comment]
Hey @ManueGE, this is no longer a feature in v2. 

`ZDKRequestUiConfiguration` is used for configuring ticketing in v2. 

Thank you, 
Alan

**Comment by ManueGE** [comment]
Yep, I know it, but not equivalent for `additionalRequestInfo`, right? we'd need to use custom fields, isn't it?

**Comment by baz8080** [comment]
@ManueGE that is correct.  I don't know if it'll ever come back, but we have some discussions on our [forums](https://develop.zendesk.com/hc/en-us/community/topics/360000018828-Mobile-SDKs) about `additionalRequestInfo`, and our PM is aware of it.
