### ISSUE TITLE
First send message doesn't show in chat

### ISSUE THREAD

**Issue by aravika08** [zendesk/zendesk_sdk_ios#454]
- SDK version: 2.2.0
- Xcode version: 10.0
- iOS or Simulator: iPhone X
- iOS Version: 12.1
- Swift version: 4.2

Steps to Reproduce:

1. Start ZDCChat:
`ZDCChat.start(in: self.navigationController) { config in
                config?.emailTranscriptAction = .neverSend
                self.navigationController?.navigationBar.isHidden = false
            }
            ZDCChat.updateVisitor { user in
                user?.addNote("chat-not-autorization")
            }
            ZDCChat.instance().overlay.setEnabled(false)`
2. First send message doesn't show in chat

**Comment by RonanMcH** [comment]
@aravika08 , moving this open issue to the correct repo [here](https://github.com/zendesk/zendesk_sdk_ios/issues/454) and closing this issue.
