### ISSUE TITLE
Missing required key: CFBundleVersion

### ISSUE THREAD

**Issue by sschizas** [zendesk/zendesk_sdk_ios#459]
- SDK version: 2.3.0
- Xcode version: 10.1
- iOS or Simulator: -
- iOS Version: 12
- Swift version: 4.2

I have added the SDK via Cocoapods.

Steps to Reproduce:

1. Archive project for App Store submission
2. Go to Organizer and validate application archive

If you perform the steps above you get an error from iTunes stating the following:

<img width="656" alt="screen shot 2018-11-05 at 21 34 55" src="https://user-images.githubusercontent.com/1173551/48022011-a9f07780-e142-11e8-984f-3a6d199b7046.png">

Any ideas why this happens? I believe this issue was introduced with SDK version 2.3.0

**Comment by sschizas** [comment]
Hi @bielikb,

I rolled back to 2.2.0 version of the SDK and I was able to archive and submit version to App Store without any issue. I have tried to completely remove the SDK and re-install it without any luck. I will give it another try and I would let you know with my findings.

Cheers,
Stavros

**Comment by bielikb** [comment]
Thanks a lot @sschizas!

Looking forward to hearing from you.

Best,
Boris

**Comment by bielikb** [comment]
Hi @sschizas,
could you please update, whether the issue is gone & you can freely update to our latest version of SDK?

Thanks,
Boris

**Comment by sschizas** [comment]
@bielikb After upgrading to latest version (2.3.0) the issue doesn't exists. I had to reintegrate the cocoa pods in general so may that was the trick to correctly upgrade the Zendesk SDK.
