### ISSUE TITLE
Support fetching categories & sections by ID

### ISSUE THREAD

**Issue by lickel** [zendesk/zendesk_sdk_ios#46]
It's great that you now support fetching an article by ID.
It would be awesome if you also supported fetching categories and sections as well.

**Comment by tecknut** [comment]
@lickel Can you expand on that please? What is it that you are looking to achieve? We're more than happy to take it on board and add it to our road map.

**Comment by lickel** [comment]
There are places in my app where I'd like to show a specific category or section, rather than the whole support page. 

I can show a support VC with a category or section, so if I can fetch them from a provider by ID, I'd be all set.

**Comment by tecknut** [comment]
Ok, I'll bring this up with the rest of the team and we'll see when we can add this.

Thanks for the suggestion.

**Comment by tecknut** [comment]
We've created tasks for this, so you can expect it in an upcoming release. However I can't give you an exact date for this.

I'm gonna close this issue. 

Thanks again.
