### ISSUE TITLE
Can't seem to get Help Center when upgrading from 2.1.0 to 2.3.0

### ISSUE THREAD

**Issue by hawflakes** [zendesk/zendesk_sdk_ios#460]
- SDK version: 2.3.0
- Xcode version: 10.1
- iOS or Simulator: Simulator
- iOS Version: 12.1
- Swift version: 4.2

Steps to Reproduce:

1. Updated my SDK to 2.3.0 and using a standard help center:
```
            let helpCenterViewController = HelpCenterUi.buildHelpCenterOverviewUi(withConfigs: [])
            self.navigationController?.pushViewController(helpCenterViewController, animated: true)
```

What shows up: "My Tickets"
![simulator screen shot - iphone x - 2018-11-10 at 22 25 36](https://user-images.githubusercontent.com/232777/48309885-beb07f00-e537-11e8-8acd-f24e676c8716.png)

What was expected: Standard Help Center
When using 2.1.0 we have what we expect:
![img_5106](https://user-images.githubusercontent.com/232777/48309891-dee03e00-e537-11e8-94f3-2aa6b9d833a8.png)

Help. I don't know why this is breaking when it looks like a straightforward update.

**Comment by KillianSmith0** [comment]
Hi @hawflakes,

Can you make sure Guide/Help Center is enabled in the settings on your Zendesk instance? Go to Settings/Mobile SDK and the app you are using..

**Comment by hawflakes** [comment]
@KillianSmith0 it was switched off. Now that I've switched it on & saved it, it's still breaking for me. Is there anything else I'm missing? Do I need to wait a certain amount of time?

**Comment by hawflakes** [comment]
Thanks!
