### ISSUE TITLE
Clicking on a link in a help center article to another article should stay in the app.

### ISSUE THREAD

**Issue by CraigSiemens** [zendesk/zendesk_sdk_ios#463]
- SDK version: 2.3.0
- Xcode version: 10.1
- iOS or Simulator: Both
- iOS Version: 12.1
- Swift version: 4.1

Currently any links tapped will open in safari. If your help center requires authentication, the browser will then ask the user to sign in when they're already authenticated within the mobile app. 

Steps to Reproduce:
1. Use a mobile app with a help center with articles that require authentication.
1. Open a help center article
1. Tap on a link to another help center article.
1. It will open safari and require the user to sign in to access.

**Comment by KillianSmith0** [comment]
@CraigSiemens Can you confirm the domain linked to your sdk app instance is the same domain as the help center articles you are deeplinking?

**Comment by CraigSiemens** [comment]
Ahh, that might be it. Our production help center recently change to using a custom subdomain.
