### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by heroic** [zendesk/zendesk_sdk_ios#466]
- SDK version: 2.3.0
- Xcode version: 10.1
- iOS or Simulator: iPhone
- iOS Version: 12.1
- Swift version: 4.0

Steps to Reproduce:

1. Create a project
2. Add SDK
3. Include project into app
4. Launch app
5. Crash

The app crashes with the error:

dyld: Library not loaded: @rpath/ZendeskCoreSDK.framework/ZendeskCoreSDK
  Referenced from: /var/containers/Bundle/Application/F67C5FD4-9C86-4CFD-8AA0-D5366C906089/App.app/App
  Reason: image not found
(lldb) 

I have set the Always embed standard swift libraries to yes everywhere.

**Comment by bielikb** [comment]
Hi @heroic,

SDK v2.3.0 is available only for Swift version 4.2 and 4.2.1.

Please also make sure you're embedding the `ZendeskCoreSDK`, ZendeskProviderSDK` and ZendeskSDK framework respectively. 
You can link & embed the frameworks within your project's build phases.

If you're in doubt, feel free to ask. Im attaching the image to show, how you can embed the aforementioned frameworks.

Best,
Boris

<img width="1258" alt="screen shot 2018-11-16 at 17 05 49" src="https://user-images.githubusercontent.com/4924709/48636138-f600af00-e9c1-11e8-8fb6-782b745f6616.png">

**Comment by RonanMcH** [comment]
Hi @heroic ,
Can you let us know if Boris' advice this solved your issue?
Thanks,
Ronan.

**Comment by HamstringAssassin** [comment]
Hi @heroic, 

Unless you've any objection, I'm going to close this issue. Feel free to contact us again and advise if this didn't fix your issue and we can start looking into it some more. 

Thanks a mil, 
Al
