### ISSUE TITLE
Can I hide the back button on a request view controller returned by RequestUi.buildRequestUi(requestId:)?

### ISSUE THREAD

**Issue by Bubcho** [zendesk/zendesk_sdk_ios#470]
Hi,
I'm using Zendesk iOS SDK 2.2.0 in a Swift 4.2 project. I'm showing a request by:
`
let vc = RequestUi.buildRequestUi(requestId: "requestID")
navigationController.pushViewController(viewController: vc, animated: true, completion: {})
`
Is there a way to hide the back button in the navigation bar of the request view controller that the SDK is giving me? I've tried setting in the previous vc:
`
navigationController?.navigationItem.backBarButtonItem = nil
`
and also modifying the vc that the SDK gives me:
`
vc.navigationItem.leftBarButtonItem = nil
vc.navigationItem.leftBarButtonItems = nil
vc.navigationItem.hidesBackButton = true
`
but to no avail. Would appreciate to know if this is even possible? Thanks guys!

**Comment by Lawati97** [comment]
where you able to fix it @Bubcho ? as i am facing through the same issue
