### ISSUE TITLE
How can I customize ZDKRequestUi buildRequestList ticket creation

### ISSUE THREAD

**Issue by SamuraiCoder** [zendesk/zendesk_sdk_ios#474]
- SDK version: 2
- Xcode version: 10
- iOS or Simulator: iOS
- iOS Version: 12
- Swift version:

Hi, I'm integrating zendesk in one of our games. It wasn't as simple as I expected but now is there. 

I'm using 

UIViewController *requestScreen = [ZDKRequestUi buildRequestList];

To show the viewController with all the tickets created. As long as something is responded it appears in the viewcontroller with a bullet. That's ok.

But if I add a new ticket, how can I customize this ticket with custom parameters? 

For now, this is my method (still testing stuff)

	utf8string userID = "blabla";
	
	ZDKCustomField *customFieldOne = [[ZDKCustomField alloc] initWithFieldId:@1234567 andValue:@"some_value"];
	ZDKRequestUiConfiguration *config = [ZDKRequestUiConfiguration new];
	config.subject = @"iOS Ticket with userId: %s ", [NSString stringWithUTF8String:globalId.c_str()];
	config.tags = @[@"ios", @"mobile"];
	config.fields = @[customFieldOne];

	UIViewController *requestScreen = [ZDKRequestUi buildRequestList];

Cheers.

**Comment by RonanMcH** [comment]
Hi @SamuraiCoder ,
You can pass `UIConfiguration`s to the Request List to customize the tickets created from here using the following code:
```
 ZDKRequestUiConfiguration * config = [[ZDKRequestUiConfiguration alloc] init];
 config.subject = @"Test from request list";
 config.tags = @[@"RequestList"];
        
 UIViewController *requestList = [ZDKRequestUi buildRequestListWith:@[config]];
 [self.navigationController pushViewController:requestList animated:YES];
```
Let us know if this answers your question.

Sorry to hear it wasn't as simple as you expected, please let us know where and what we can improve on our [product feedback form](https://develop.zendesk.com/hc/en-us/community/topics/360000018828-Mobile-SDKs).

Thanks,
Ronan.

**Comment by SamuraiCoder** [comment]
Cool, that apparently works. Thanks. 

And what about if I want to send info like OS/Device info/App name? basically all the tags available on the default form? 

Regards.

**Comment by RonanMcH** [comment]
Hi @SamuraiCoder ,
You can just add these details as tags to the `uiConfig` you started the request list UI with. We do have a Zendesk marketplace app that will gather some of the information you mentioned there. Have a look. [Here](https://www.zendesk.com/apps/support/support-sdk-metadata/) it is.
I'm gonna close this issue as your problem seems to be solved. Feel free to reopen or open more issues.
Thanks,
Ronan.
