### ISSUE TITLE
How can we customize buildRequestUI navigation title?

### ISSUE THREAD

**Issue by kuoliangkwong** [zendesk/zendesk_sdk_ios#475]
- SDK version: 2.3.0
- Xcode version: 10.1
- iOS or Simulator: Simulator
- iOS Version: 12.1.2
- Swift version: 4.2

How can we customize the default "Contact Us" in buildRequestUI navigation title? I tried using RequestUiConfiguration.subject but it seems like not working.

**Comment by RonanMcH** [comment]
Hi @kuoliangkwong ,
You cannot customise the `RequestUI` title using the `RequestUiConfiguration` I'm afraid. You will need to edit our localisation files and provide a translation for all the languages you support. [Here](https://developer.zendesk.com/embeddables/docs/ios_support_sdk/localize_text) is our documentation on adding and changing localisations in the Support SDK. If you want to change just one translation, it is probably not necessary to create a new strings bundle but just to edit the existing one.

You can go to the `ZendeskSDKStrings.bundle` in your project and navigate to each locale, you want to have your localised text. You will need to open each `Localizable.strings` file as a `ASCII Property List` and then edit the string you want to translate. The translation key for the `RequestUI` title is `ios.ZDKRequests.createRequest.title`.
Let us know if this has helped you.

Thanks,
Ronan.

**Comment by kuoliangkwong** [comment]
It works~ Thanks alot @RonanMcH. Btw, if i change ZendeskSDKStrings.bundle, when I pod update, it will get replaced by original version, right?
