### ISSUE TITLE
Crash on calling the method unregisterForPush

### ISSUE THREAD

**Issue by pechn** [zendesk/zendesk_sdk_ios#484]
- SDK version: 2.3.0
- Xcode version: 10.1
- iOS or Simulator: iOS
- iOS Version: 12.x
- Swift version:

Steps to Reproduce:

1.App will crash on calling the function 

> `[[[ZDKPushProvider alloc] initWithZendesk:[ZDKZendesk instance]] unregisterForPush];`

2.Also crash on setting a new jwt identifier:

> `NSString *jwtUserIdentifier = @"My JWT Identifier";`
>  `id<ZDKObjCIdentity> userIdentity = [[ZDKObjCJwt alloc] initWithToken:jwtUserIdentifier];`
>  `[[ZDKZendesk instance] setIdentity:userIdentity];`

The crash log:

> #0	in PushRegistrationResources.url.getter ()
> #1	in PushRegistrationResources.url.getter ()
> #2	in specialized PushRegistrationProvider.unregisterForPush(withDeviceIdentifier:) ()
> #3	in Zendesk.setIdentity(_:) ()
> #4	in Zendesk.setIdentity(_:) ()
> #5	in @objc Zendesk.setIdentity(_:) ()
> #6	0x0000000102fcd948 in -[HomeViewController configZendeskIdentity]

**Comment by KillianSmith0** [comment]
Hi @pechn 
Could you [enable logging](https://developer.zendesk.com/embeddables/docs/ios_support_sdk/debug) in your AppDelegate and update this issue with more detailed logs please.

Thanks,
Killian

**Comment by pechn** [comment]
> Hi @pechn
> Could you [enable logging](https://developer.zendesk.com/embeddables/docs/ios_support_sdk/debug) in your AppDelegate and update this issue with more detailed logs please.
> 
> Thanks,
> Killian

I have enabled logging but it showed nothing relative to the crash issue. BTW, I integrates Firebase Cloud Messaging SDK at the mean time

**Comment by KillianSmith0** [comment]
Can you do the following:
1. Set the debug level to `ZDKLogLevelVerbose`
2. Remove the call for unregisterForPush..
3. Replicate the crash for jwt identifier
4. Redact any sensitive information from logs and send them
5. Do the same for the unregisterForPush crash..

Can you ensure that you don't clear the ZDKZendesk instance anywhere before calling this? 

Also make sure your jwt identifiers are **unique**

Do you use firebase for Zendesk push notifications?

Thanks,
Killian

**Comment by pechn** [comment]
Hi Kilian,

I think I have found the root cause of the crash issue - the symbol '>' in the registered device identifier makes the calling of unregisterForPush crash. There is nothing relative to the Firebase SDK.
Hope you solve the bug in the next release.

**Comment by RonanMcH** [comment]
Hi @pechn,
Your device identifier should not contain any spaces or the characters < and >. You should strip them out before making the call to register for push notifications with Zendesk. I will update our documentation to detail this. 
Thanks for letting us know,
Ronan.
