### ISSUE TITLE
A blank screen is displayed if the ZDKHelpCenterUi is loaded for the first time

### ISSUE THREAD

**Issue by vdvsibedge** [zendesk/zendesk_sdk_ios#485]
- SDK version: 2.3.0
- Xcode version:
- iOS or Simulator: Both
- iOS Version: 10.1 (10B61)
- Swift version: 4.2

Steps to Reproduce:

1. Install a host app and launch it for the first time.
2. Disable your internet connection
3. Navigate to the Zendesk help UI using HelpCenterUi.buildHelpCenterOverviewUi(withConfigs:)

**Result:** A blank screen is displayed.
**Expected result:** An error message is displayed and/or the host application is notified somehow that data weren't loaded due to connection issues.

**Comment by KillianSmith0** [comment]
Hi @vdvsibedge 

We have a task in our backlog to improve the offline experience of this sdk. Unfortunately I don't have a timeline, when this might be updated. We'll notify this issue once we have an update!

Regards,
Killian

**Comment by KillianSmith0** [comment]
Duplicated issue so I will close this. Refer to #486 for more info
