### ISSUE TITLE
iOS 10 Navigation Bar covering UI

### ISSUE THREAD

**Issue by colealanroberts** [zendesk/zendesk_sdk_ios#487]
- SDK version: 2.3.0
- Xcode version: 10.1
- iOS or Simulator: Simulator
- iOS Version: 10.3.1
- Swift version: Objective-C

Steps to Reproduce:

1. File a support ticket (Conversations on) and note the recent tickets tableview underneath the navigation bar. This only happens on iOS 10.

![image](https://user-images.githubusercontent.com/3952713/52874779-2dddd680-3118-11e9-9906-11e3f1b0bc62.png)

**Comment by pechn** [comment]
I had met the same issue and have found a workaround to solve it. 

> `UIViewController *requestListController = [ZDKRequestUi buildRequestList];
    requestListController.edgesForExtendedLayout = UIRectEdgeNone; // To avoid navigation bar covering the content in iOS <= 10
    [self.navigationController pushViewController:requestListController animated:YES];`

**Comment by colealanroberts** [comment]
@pechn Excellent, I'll give this a shot.

**Comment by KillianSmith0** [comment]
Hi @colealanroberts  
I wasn't able to replicate this, can you send a snippet showing how you set up and present the view controller? 

Thanks ,
Killian

**Comment by colealanroberts** [comment]
@KillianSmith0 here's a shortened snippet. I chose to create and present a new UINavigationController because the need to display this article in a modally presented controller with navigation was a requirement.

# ZendeskManager.m
 
Method used in ZendeskManager singleton to create and show the Zendesk Help Center
```
- (void)showHelpCenter:(UINavigationController *)navigationController articleId:(NSString *)articleId presentationStyle:(ZDKHelpCenterPresentationStyle)presentationStyle {
 
    ZDKRequestUiConfiguration *requestConfig = [self buildRequestConfig];
    requestConfig.ticketFormID = self.zendeskConfig.formId;
   
    UIViewController *articleController = [ZDKHelpCenterUi buildHelpCenterArticleUiWithArticleId:articleId andConfigs:@[requestConfig]];
   
    if (presentationStyle == ZDKHelpCenterPresentationStylePresent) {
        UINavigationController *presentedNavigationController = [[UINavigationController new] initWithRootViewController:articleController];
        [navigationController presentViewController:presentedNavigationController animated:YES completion:nil];
    } else {
        [navigationController pushViewController:articleController animated:YES];
    }
}
```
 
# Some VC
 ```
- (void)showHelpCenter {
    NSString *someArticleId = @"123";
    [[ZendeskManager shared] showHelpCenter: self.navigationController articleId: someArticleId presentationStyle: ZDKHelpCenterPresentationStylePresent];
}
```
_ZDKHelpCenterPresentationStyle_ is an enum I created with a similar nomenclature as the official SDK.

**Comment by KillianSmith0** [comment]
@colealanroberts This code refers to the article screen, could you send the snippet related to the request list? This really shouldn't be an issue, and you shouldn't need to use a workaround for this, just trying to help debug this.

Thanks,
Killian

**Comment by colealanroberts** [comment]
I appreciate your help! Here's a very condensed look at the buildRequestConfig method. The removed code sets up a number of extra ZDKCustomFields.

```
- (ZDKRequestUiConfiguration *)buildRequestConfig {
    ZDKRequestUiConfiguration *config = [ZDKRequestUiConfiguration new];
        
    ZDKCustomField *appName = [[ZDKCustomField alloc] initWithFieldId:self.zendeskConfig.fieldAppPrettyName andValue:self.zendeskConfig.appPrettyName];

    config.fields = @[appName];
    config.subject = @"Feedback";
    
    return config;
}
```

**Comment by RonanMcH** [comment]
Hi @colealanroberts ,
I have been able to reproduce this. It seems to be a bug on iOS 10 when modally presenting a `navController` with the `HelpCenterArticleViewController`. I have a made an internal ticket to track this issue. We will update this issue when it is fixed.
Thanks,
Ronan.

**Comment by colealanroberts** [comment]
@ronan-mch Thanks for the update!
