### ISSUE TITLE
Orientation issue

### ISSUE THREAD

**Issue by sarahjstacey15** [zendesk/zendesk_sdk_ios#488]
- SDK version:2.3.0
- Xcode version: 10.1
- iOS or Simulator: Both
- iOS Version: iOS 9, 10, 11 & 12
- Swift version: 4.2

Steps to Reproduce:

Using the following code to show the request UI there is no way to control the supported orientations. 

let requestListController = RequestUi.buildRequestList(with: [requestConfig])
let navHelp = UINavigationController(rootViewController: requestListController)
self.navigationController?.present(navHelp, animated: true, completion: nil)

Is there any way around this to lock it to just portrait? When I create the request ui the supportedInterfaceOrientations return as "allButUpsideDown" 

S

**Comment by KillianSmith0** [comment]
Hi @sarahjstacey15 

Unfortunately there isn't a way to force the view controller. I found this snippet online it might help you. 

```swift

        let value = UIInterfaceOrientation.portrait.rawValue
        UIDevice.current.setValue(value, forKey: "orientation")


        UIDevice.current.setNilValueForKey("orientation") // for removal
```
You could call this before you present the VC, and use the nil to reset if you want? Hope this helps!

Killian

**Comment by sarahjstacey15** [comment]
Got a version working now, basically in my navigation controller I'm checking the navigation controller against my own controller and then forcing it to portrait. It's a bit of a messy hack but it seems to work. 

S

**Comment by KillianSmith0** [comment]
You could also just disable landscape in your project settings, but I assume you may need landscape for other use cases.. At least you got something working! I will close this issue for now, feel free to open another if any other issues arise! 

Thanks,
Killian
