### ISSUE TITLE
Color of top panel for "Contact us" screens

### ISSUE THREAD

**Issue by NoliNik** [zendesk/zendesk_sdk_ios#489]
- SDK version: 2.3.0
- Xcode version:10.1
- iOS or Simulator: any
- iOS Version: any 
- Swift version: 4.0

Steps to Reproduce:

1. set custom color for navigation bar in your app
2. push ReqestsList screen (navigation bar will have correct color)
3. press create new article button (will modal present Contact us screen with incorrect color)

![screen shot 2019-02-22 at 18 38 34](https://user-images.githubusercontent.com/7544933/53252942-277bcb80-36d1-11e9-9e10-6d78f0b3359a.png)

**Comment by KillianSmith0** [comment]
Hi @NoliNik,

This is an issue on our end.. I will create an issue in our backlog. In the mean time here is a workaround for you: 
```swift
UINavigationBar.appearance().barTintColor = yourColour
```
If you have different navbar colors on different screens, you will have to set this value appropriately 

Kind regards,
Killian

**Comment by KillianSmith0** [comment]
@NoliNik I will close this issue for now, feel free to open another one with any other issues that might arise!
