### ISSUE TITLE
Conflict With Other SDK

### ISSUE THREAD

**Issue by SuYungCheng** [zendesk/zendesk_sdk_ios#490]
- SDK version: 2.3.0
- Xcode version: 10.1
- Swift version: 4.2

Steps to Reproduce:

1.  I use RxSwift and Action Framework before
2. After I add the Zendesk SDK it shows error: 'Action' is ambiguous for type lookup in this context
3. Conflict with Action SDK
4. mark the import Zendesk , it work fine.

the error image:
![image](https://user-images.githubusercontent.com/17446246/53281761-f058f900-3768-11e9-8330-48063d267a5c.png)

error code:
![image](https://user-images.githubusercontent.com/17446246/53281770-02d33280-3769-11e9-842d-0ba6fc85d1ee.png)

**Comment by KillianSmith0** [comment]
Hi @SuYungCheng,

Unfortunately it seems we share a common API with the Action framework, here's a good read on [API pollution](https://nshipster.com/swift-api-pollution/#strategies-for-api-consumers) which has some tips that might help as a workaround. 

The Action you're using in the code looks more like the Action framework's Action, so you would probably be marking this one `Action.Action`.. If you have a lot of use cases of this you could add a typealias for this maybe?

```swift
typealias MyAction = Action.Action
```

**Or** you can try implicitly import the Action.Action class like so:
```swift
import class Action.Action
``` 
Take a look at [this article](https://nshipster.com/import/#importing-individual-declarations) for reference!

Hope one of these help, I will close this for now, feel free to open another issue if any other issues arise

Thanks,
Killian
