### ISSUE TITLE
Bitcode support

### ISSUE THREAD

**Issue by jay18001** [zendesk/zendesk_sdk_ios#50]
Can you please create a version of your framework with bitcode enabled.

**Comment by tecknut** [comment]
@jay18001 We can add support for this when Xcode 7 comes out of beta.

**Comment by thediary** [comment]
I think it's probably close enough to iOS 9 launch where support should be added. Our app requires bit code to be turned on and unless ZenDesk has support (or a workaround) it will be a problem

**Comment by tecknut** [comment]
@thediary Unfortunately we can't build and release a version of our SDK with a beta version of Xcode. When Xcode 7 is out of beta we will release a new build of what ever version we are on that will be specifically built with that flag enabled.

**Comment by thediary** [comment]
Most other third part sdk vendors create a separate branch (publicly available on Github) for people to use at least until Xcode comes out of beta. Then when it comes out of beta, they merge it into the master branch. Otherwise, how are we supposed to update our apps with bitcode support on launch day?

Will you at least be able to provide a new version when it hits GM?

**Comment by baz8080** [comment]
@thediary We're currently awaiting final QA on a 1.4.0.1 build of the SDK. When that checks out we can do a 1.4.0.2 build supporting it.  The timeline for this is likely to be late this week or early next week.

**Comment by thediary** [comment]
Ok thank you for the update!

**Comment by tecknut** [comment]
@thediary We just released a new version with bitecode support.

**Comment by hankbao** [comment]
Great :+1:

**Comment by jameshays** [comment]
Using 10.4.0.2 I'm getting this: ```full bitcode bundle could not be generated because '/Pods/ZendeskSDK/ZendeskSDK.framework/ZendeskSDK(ZDKBundleUtils.o)' was built only with bitcode marker. The library must be generated from Xcode archive build with bitcode enabled (Xcode setting ENABLE_BITCODE)```

**Comment by jrahaim** [comment]
I am getting the same error on 1.4.1.2
ZendeskSDK.framework/ZendeskSDK(ZDKHelpCenterCategory.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

**Comment by StevenDiviney** [comment]
We have just done another release to address the latest bit code issue.
