### ISSUE TITLE
SDK 2.3.1 doesn't work with Xcode 10.1 

### ISSUE THREAD

**Issue by georgescumihai** [zendesk/zendesk_sdk_ios#502]
- SDK version: 2.3.1
- Xcode version: 10.1
- iOS or Simulator: Both
- iOS Version: 12.2
- Swift version: 4.2 

Steps to Reproduce:

1. Install SDK version 2.3.1 with cocoapods
2. Try to build with Xcode 10.1
3. ZendeskCoreSDK is build with swift 5.0 
```
Module compiled with Swift 5.0 cannot be imported by the Swift 4.2.1 compiler: /Pods/ZendeskSDK/ZendeskSDK/5.0/ZendeskCoreSDK.framework/Modules/ZendeskCoreSDK.swiftmodule/x86_64.swiftmodule
```

So you can't use 2.3.1 for both Xccode 10.1 and 10.2.
This limits the adoption of Xcode10.2, and we can't upgrade from 2.3.0 until this is fixed.
What is the solution to use different version depending on the installed Xcode ?

I searched for a workaround if we can specify in the Podfile what version to use depending on the Swift version, but I had no luck.

**Comment by KillianSmith0** [comment]
The Cocoapods release for Xcode 10.2/Swift 5 points to the latest Swift5 artefacts, Cocoapods doesn't allow us to point to multiple modules in one Cocoapod update. You can download the artefacts manually and replace the ones in your current pods folder. We can create a new branch that point to 4.2 artefacts, we can try get this done by End of Day but there is limited developer resources this week

Regards,
Killian

**Comment by georgescumihai** [comment]
Ok, that will fix the issue with different Podfile and Podfile.lock.

**Comment by RonanMcH** [comment]
HI @georgescumihai ,
The feature set for 2.3.0 and 2.3.1 is the same. 2.3.1 is the same code recompiled for Swift 5.0 so we won't be rebuilding it for swift 4.2. You should continue to point your podfile at 2.3.0 till you have upgraded xcode. 
Thanks,
Ronan.

**Comment by georgescumihai** [comment]
That is the workaround at this point, the issue comes when the CI is not updated to Xcode10.2 or not everybody in the team has updated to Xcode10.2.

I will close the issue as there is not nice solution.
