### ISSUE TITLE
ZDCChat.start(nil) not starting modal view

### ISSUE THREAD

**Issue by Sroka** [zendesk/zendesk_sdk_ios#504]
- SDK version: 1.4.0
- Xcode version: 10.1
- iOS or Simulator: iPhone 7
- iOS Version: 11.4
- Swift version: 4.2

Steps to Reproduce:

1. Call ZDCChat.start(nil)

ER: Chat window is shown
AR: Nothing is happening

Might I add that this is ReactNative app and I'm doing this in a native bridge. I would use ZDCChat.start(in: <UINavigationController>, config: <config>) overload otherwise but unfortunately React Native does not yet support Navigation controllers. I would really appreciate some quick help with this

**Comment by danthedrummer** [comment]
Hi,

This repository is for the Zendesk Support SDK. Can you go through [this channel](https://github.com/zendesk/zendesk_sdk_chat_ios/blob/master/CONTRIBUTING.md#issues) to submit issues for Zendesk Chat SDK.
