### ISSUE TITLE
Unable to load Help center for JWT authenticated users

### ISSUE THREAD

**Issue by chillin0531** [zendesk/zendesk_sdk_ios#505]
- SDK version: 2.3.1
- Xcode version:10.1
- iOS or Simulator: iPhone
- iOS Version: 12

In the Objective C app, I have initialised the SDK as follows
`[ZDKZendesk initializeWithAppId:"appId" clientId:"clientId" zendeskUrl:"url"];
[ZDKSupport initializeWithZendesk:[ZDKZendesk instance]];`

and set the identity as follows
`id<ZDKObjCIdentity> userIdentity = [[ZDKObjCJwt alloc] initWithToken:"unique_id"];
[[ZDKZendesk instance] setIdentity:userIdentity];`

Which was working fine but suddenly got a login error. **But its working good for anonymous users**.
I have tested the JWT endpoint using curl command and there was no errors and JWT token was generated successfully and verified too.

 I have added the complete log as follows.

> [DEBUG]: The details provided during intialization were not previously stored. If this device was previously registered for push notficiations using different Zendesk SDK application details it is not possible to unregister automatically.
> [DEBUG]: Initialized with a different SDK configuration. Clearing storage.
> [DEBUG]: clearing storage suite: com.zendesk.core.session with app id: 25073a7f51e7796b432e8fcdfcbaec961b2f3bc074611f27.
> [DEBUG]: clearing storage suite: com.zendesk.core.identity with app id: 25073a7f51e7796b432e8fcdfcbaec961b2f3bc074611f27.
> [DEBUG]: clearing storage suite: com.zendesk.core.settings with app id: 25073a7f51e7796b432e8fcdfcbaec961b2f3bc074611f27.
> [DEBUG]: No UUID found. Have you set an identity?
> [DEBUG]: Returning default settings for BlipsSettings.Type. No data in cache.
> INFO]: Initializing Support SDK.
> [ERROR]: Couldn't retrieve identity from storage.
> [DEBUG]: clearing storage suite: com.zendesk.core.identity with app id: 25073a7f51e7796b432e8fcdfcbaec961b2f3bc074611f27.
> [DEBUG]: clearing storage suite: com.zendesk.core.session with app id: 25073a7f51e7796b432e8fcdfcbaec961b2f3bc074611f27.
> [DEBUG]: stored identity with app id: 25073a7f51e7796b432e8fcdfcbaec961b2f3bc074611f27.
> [INFO]: Localization key and value : "ios.ZDKRequests.createRequest.cancel.button" = "Cancel";
> [VERBOSE]: No settings in cache.
> [VERBOSE]: Calling interceptor ClientIdentifierInterceptor(accountDetails: ZendeskCoreSDK.ApplicationConfiguration(applicationId: "25073a7f51e7796b432e8fcdfcbaec961b2f3bc074611f27", clientId: "mobile_sdk_client_2a9e66f5354900e8f147", accountUrl: "https://company.zendesk.com"))
> [DEBUG]: storing settings with app id: 25073a7f51e7796b432e8fcdfcbaec961b2f3bc074611f27.
> [DEBUG]: successfully stored settings with app id: 25073a7f51e7796b432e8fcdfcbaec961b2f3bc074611f27.
> [DEBUG]: Settings cached.
> [DEBUG]: Returning settings for HelpCenterSettings.Type from network.
> [INFO]: Localization key and value : "ios.ZDKHelpCenter.helpCenterOverview.title" = "Help";
> [DEBUG]: Reachability Flag Status: -R ------- networkStatusForFlags
> 
> [DEBUG]: Returning cached settings for ConversationsSettings.Type
> [DEBUG]: Returning cached settings for HelpCenterSettings.Type
> [INFO]: Localization key and value : "ios.ZDKHelpCenter.support.contactSupport" = "Contact us";
> [INFO]: Localization key and value : "ios.ZDKHelpCenter.support.contactSupport" = "Contact us";
> [DEBUG]: Returning cached settings for HelpCenterSettings.Type
> [DEBUG]: Returning cached settings for HelpCenterSettings.Type
> 
> [VERBOSE]: Calling interceptor SettingsRequestInterceptor(settingsStore: ZendeskCoreSDK.SettingsStore(key: "settings", appId: "25073a7f51e7796b432e8fcdfcbaec961b2f3bc074611f27"), settingsProvider: ZendeskCoreSDK.SettingsProvider(environment: ZendeskCoreSDK.ApplicationConfiguration(applicationId: "25073a7f51e7796b432e8fcdfcbaec961b2f3bc074611f27", clientId: "mobile_sdk_client_2a9e66f5354900e8f147", accountUrl: "https://company.zendesk.com"), settingsCache: ZendeskCoreSDK.SettingsStore(key: "settings", appId: "25073a7f51e7796b432e8fcdfcbaec961b2f3bc074611f27"), cachingLogic: ZendeskCoreSDK.IntervalValidator(validityPeriod: 3600.0, startDate: 2019-04-23 05:43:58 +0000)), validator: ZendeskCoreSDK.IntervalValidator(validityPeriod: 3600.0, startDate: 2019-04-23 05:43:58 +0000))
> 
> [DEBUG]: Returning cached settings for CoreSettings.Type
> 
> [VERBOSE]: Settings interceptor retrived settings: CoreSettings(brandId: 360002351191, updatedAt: 2019-04-16 12:13:51 +0000, applicationId: Optional("25073a7f51e7796b432e8fcdfcbaec961b2f3bc074611f27"), authentication: Optional(ZendeskCoreSDK.CoreSettings.AuthenticationType.jwt))
> 
> [VERBOSE]: Calling interceptor LoginRequestInterceptor(identityStore: ZendeskCoreSDK.IdentityStore(appId: "25073a7f51e7796b432e8fcdfcbaec961b2f3bc074611f27"), accessProvider: ZendeskCoreSDK.AccessProvider(environment: ZendeskCoreSDK.ApplicationConfiguration(applicationId: "25073a7f51e7796b432e8fcdfcbaec961b2f3bc074611f27", clientId: "mobile_sdk_client_2a9e66f5354900e8f147", accountUrl: "https://company.zendesk.com"), identityStore: ZendeskCoreSDK.IdentityStore(appId: "25073a7f51e7796b432e8fcdfcbaec961b2f3bc074611f27"), settingsStore: ZendeskCoreSDK.SettingsStore(key: "settings", appId: "25073a7f51e7796b432e8fcdfcbaec961b2f3bc074611f27")))
> 
> [VERBOSE]: Calling interceptor ClientIdentifierInterceptor(accountDetails: ZendeskCoreSDK.ApplicationConfiguration(applicationId: "25073a7f51e7796b432e8fcdfcbaec961b2f3bc074611f27", clientId: "mobile_sdk_client_2a9e66f5354900e8f147", accountUrl: "https://company.zendesk.com"))
> 
> CredStore - performQuery - Error copying matching creds.  Error=-25300, query={
>     class = inet;
>     "m_Limit" = "m_LimitAll";
>     ptcl = htps;
>     "r_Attributes" = 1;
>     sdmn = "Web Password";
>     srvr = "company.zendesk.com";
>     sync = syna;
> }
> 
> [ERROR]: Login error : keyNotFound(CodingKeys(stringValue: "authentication", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"authentication\", intValue: nil) (\"authentication\").", underlyingError: nil))
> 
> [VERBOSE]: Halting on AuthRequestInterceptor(identityStore: ZendeskCoreSDK.IdentityStore(appId: "25073a7f51e7796b432e8fcdfcbaec961b2f3bc074611f27")) with error: error(Swift.DecodingError.keyNotFound(CodingKeys(stringValue: "authentication", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"authentication\", intValue: nil) (\"authentication\").", underlyingError: nil)))
> 
> [INFO]: Localization key and value : "ios.ZDKHelpCenter.support.contactError" = "Unable to connect";
> [INFO]: Localization key and value : "ios.ZDKHelpCenter.toastRetryButton" = "Retry";

**Comment by danthedrummer** [comment]
Hi,

Please open a ticket with us through support@zendesk.com and **delete** this issue. You've posted credentials that should not be shared publicly.

**Comment by chillin0531** [comment]
Hi @danthedrummer,
Thanks for your reply.
I have fixed this issue by just removing all the users. As I am in initial state of development, it helps.
