### ISSUE TITLE
Help Center cell items don't wrap text.

### ISSUE THREAD

**Issue by Prince2k3** [zendesk/zendesk_sdk_ios#52]
When viewing FAQ for instance. I notice the text in the table view don't wrap. This is a big issue for people looking to use FAQ or any other section where the text doesn't wrap.

**Comment by tecknut** [comment]
Hey @Prince2k3 this has been requested by someone previously on our [product feedback page](https://support.zendesk.com/hc/en-us/community/posts/204281048-iOS-SDK-Option-to-not-truncate-titles-of-entries) and our product team have taken this feedback on board. 

The truncation is what our designers decided on when we first added Help Center. In the short term, if you wish to have more control over how Help Center content is present you can use our providers to build custom UI. 

Thanks
