### ISSUE TITLE
More customization

### ISSUE THREAD

**Issue by kmiloaguilar** [zendesk/zendesk_sdk_ios#54]
I will like to customise the title of the contact us to have a different title, the bar tint color for that controller.

**Comment by StevenDiviney** [comment]
He @kmiloaguilar , this is currently possible. Here is a link to the relevant docs: https://developer.zendesk.com/embeddables/docs/ios/customization

Thanks

**Comment by tecknut** [comment]
@kmiloaguilar did this solve your issue?

**Comment by kmiloaguilar** [comment]
I think I did it in a different way. I will let you know
