### ISSUE TITLE
Can't open up Reviews tab in AppStore to rate my app

### ISSUE THREAD

**Issue by jaanushansen** [zendesk/zendesk_sdk_ios#55]
Currently it is only possible to use for rating in App Store links in this format:

itms-apps://itunes.apple.com/app/id%APP_ID%?mt=8

This opens app AppStore Details tab, but I would like to open up Reviews tab. Reviews tab can not be opened in iOS7, but in lower and higher versions it is possible to use the following url:

itms-apps://itunes.apple.com/WebObjects/MZStore.woa/wa/viewContentsUserReviews?pageNumber=0&sortOrdering=1&type=Purple+Software&mt=8&id=%APP_ID%

So I decided to use Zendesk RMA only for iOS 7.1+ and set to use this url in Zendesk admin, but unfortunately it do not work, it results in ZDKRMAConfigObject itunesAppId to be "itms-apps://itunes.apple.com/app/id(null)"

Maybe you could support also the long url in config? Or even build a smart system so that depending on iOS version the system returns the url which is supported on client iOS.

**Comment by tecknut** [comment]
@jaanushansen Since iOS 7 you can no longer direct users to the review tab of the app store. If you set the format in the admin config to be `itms-apps://itunes.apple.com/app/id<your-id-here>` we will use the old url format for pre iOS 7 and the new format for iOS 7 +.

**Comment by jaanushansen** [comment]
@tecknut Yes, review tab cannot be opened in iOS 7, but it appears, that the mentioned URL works again since iOS 7.1, as is mentioned here:

http://stackoverflow.com/questions/18905686/itunes-review-url-and-ios-7-ask-user-to-rate-our-app-appstore-show-a-blank-pag#23037620

I myself just tested, that itms-apps://itunes.apple.com/WebObjects/MZStore.woa/wa/viewContentsUserReviews?pageNumber=0&sortOrdering=1&type=Purple+Software&mt=8&id=%APP_ID% works on iOS 7.1.2, 8.4.1 and 9.0-beta.

**Comment by tecknut** [comment]
@jaanushansen Thanks for pointing out the updates on this issue. We have PR up for this and it will be out with our next release.
