### ISSUE TITLE
-[ZDKRequests showRequestCreationWithNavController:] crash

### ISSUE THREAD

**Issue by bulusoy** [zendesk/zendesk_sdk_ios#56]
[ZDKRequests showRequestCreationWithNavController:] causes the app to crash when the "send" button has been tapped (of course, with some text inside the textview).

Steps to reproduce:
1. Create a ZDKConfig instance with AppID, zendesk URL & clientID
2. Create a ZDKAnonymousIdentity, assign an e-Mail and set it as the identity for the current `[ZDKConfig instance]`
3. Open the RequestCreation View using `-[ZDKRequests showRequestCreationWithNavController:]`
4. Enter some text and then tap send.

See back trace below:
```
-[ZDKAnonymousIdentity hasIdentifer]: unrecognized selector sent to instance 0x7f855e221d40
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ZDKAnonymousIdentity hasIdentifer]: unrecognized selector sent to instance 0x7f855e221d40'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000109203c65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000108ddcbb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010920b0ad -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x000000010916113c ___forwarding___ + 988
	4   CoreFoundation                      0x0000000109160cd8 _CF_forwarding_prep_0 + 120
	5   REDACTED                  0x0000000104b85eee -[ZDKDispatcher loginFromRequestQueue:onError:] + 348
	6   REDACTED                0x0000000104b85760 -[ZDKDispatcher loginThenExecute:onError:] + 416
	7   REDACTED                 0x0000000104b87d00 __63-[ZDKDispatcher executeRequest:onSuccess:onError:requiresAuth:]_block_invoke177 + 191
	8   libdispatch.dylib                   0x0000000109b72186 _dispatch_call_block_and_release + 12
	9   libdispatch.dylib                   0x0000000109b91614 _dispatch_client_callout + 8
	10  libdispatch.dylib                   0x0000000109b786a7 _dispatch_queue_drain + 2176
	11  libdispatch.dylib                   0x0000000109b77cc0 _dispatch_queue_invoke + 235
	12  libdispatch.dylib                   0x0000000109b7b3b9 _dispatch_root_queue_drain + 1359
	13  libdispatch.dylib                   0x0000000109b7cb17 _dispatch_worker_thread3 + 111
	14  libsystem_pthread.dylib             0x0000000109efea9d _pthread_wqthread + 729
	15  libsystem_pthread.dylib             0x0000000109efc3dd start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by tecknut** [comment]
@bulusoy Can you put your SDK init code snippet in a comment here please? Make sure you remove any sensitive information like the app id and client id.

**Comment by bulusoy** [comment]
```
	[[ZDKConfig instance] initializeWithAppId:@"<APP ID HERE>"
								   zendeskUrl:@"<URL HERE>"
							         ClientId:@"<ID HERE>" onSuccess:^{
											 ZDKAnonymousIdentity *identity = [ZDKAnonymousIdentity new];
											 identity.name = @"Test Name";
											 identity.email = @"hans@blabla.com";

											 [ZDKConfig instance].userIdentity = identity;
											 
											 [ZDKRequests showRequestCreationWithNavController:self.navigationController];

```

**Comment by tecknut** [comment]
@bulusoy We haven't been able to replicate this. Can you open a ticket with support.zendesk.com and give this github issue as a reference? If you state that you were discussing this with one of the devs it should get escalated to us quickly and we can go from there. 

We will need to take a look at you Zendesk instance and inspect your SDK admin config to debug this further. 

Are you OK to do this ?

**Comment by bulusoy** [comment]
Allright, will do. Thanks.

**Comment by tecknut** [comment]
@bulusoy Are you still experiencing this crash ?

**Comment by akozlik** [comment]
I've been running into this same issue when using Swift. It was working fine the other day but suddenly started crashing.

Our init code is:

`ZDKConfig.instance().initializeWithAppId({app_id}, zendeskUrl: {url}, andClientId:{client_id})`

Our user setup is:

`var anonymousIdentity = ZDKAnonymousIdentity()`
`anonymousIdentity.name = "Test Name"`
`anonymousIdentity.email = "test@email.com"`
`ZDKConfig.instance().userIdentity = anonymousIdentity`

**Comment by akozlik** [comment]
I figured out the issue. We had JWT authentication turned on in our Agent portal so the application would crash when attempting to use an Anonymous user. Is there a better way to handle the error here rather than just crashing the app?

@bulusoy You may want to check to see if you have JWT authentication turned on in your mobile SDK settings. Switching back to Anonymous resolved the issue for me.

**Comment by tecknut** [comment]
@akozlik We have a build patch going out tomorrow. This is just a rebuild of our last release to remove some warnings in Xcode 7. There will be a point release which will be out in a week or so which will have a fix for the crash when the incorrect identity type is set.

**Comment by akozlik** [comment]
Excellent, thanks for the quick response. Hope the above can help @bulusoy out as well.
