### ISSUE TITLE
App crashes for [__NSPlaceholderDictionary initWithObjects:forKeys:count:] 

### ISSUE THREAD

**Issue by cristinasitaa** [zendesk/zendesk_sdk_ios#58]
My code snippet is 

    [[ZDKConfig instance] initializeWithAppId:@"###" zendeskUrl:@"###" ClientId:@"###" onSuccess:^() {
        [ZDKRMA configure:^(ZDKAccount *account, ZDKRMAConfigObject *config) {
            
        //     configure additional info
            NSString *versionString = [NSString stringWithFormat:@"%@ (%@)",
                                       [[[NSBundle mainBundle] infoDictionary] objectForKey:@"CFBundleShortVersionString"],
                                       [[[NSBundle mainBundle] infoDictionary] objectForKey:@"CFBundleVersion"]];
            
            NSString *appVersion = [NSString stringWithFormat:@"App version: %@", versionString];
            
            
            NSString *additionalText = [NSString stringWithFormat:@"%@\n\n%@",
                                        appVersion,
                                        [ZDKDeviceInfo deviceInfoString]];
            
            
            config.additionalRequestInfo = [NSString stringWithFormat:@"\n\n\n\n%@", additionalText];
        }];
        
        ZDKAnonymousIdentity *anonymousUser = [ZDKAnonymousIdentity new];
        anonymousUser.email = email;
        anonymousUser.name = firstName;
        anonymousUser.externalId = userId;
        [ZDKConfig instance].userIdentity = anonymousUser;
        
    } onError:^(NSError *error) {
        NSLog(@"%@", error.description);
    }];

When I press send (for support tickets or for feedback), I receive this message before the app crashes

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010f092c65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010ed2bbb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010ef9c84f -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 383
	3   CoreFoundation                      0x000000010efaf59b +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
	4   BabyBundle                          0x000000010bb6bc70 +[ZDKDeviceInfo deviceInfoDictionary] + 380
	5   BabyBundle                          0x000000010bb1f6d4 __88-[ZDKRequestProvider createRequestWithSubject:description:tags:attachments:andCallback:]_block_invoke + 1075
	6   BabyBundle                          0x000000010bb67d78 __63-[ZDKDispatcher executeRequest:onSuccess:onError:requiresAuth:]_block_invoke153 + 30
	7   BabyBundle                          0x000000010bb65fcd __42-[ZDKDispatcher loginThenExecute:onError:]_block_invoke + 98
	8   BabyBundle                          0x000000010bb66cb1 __47-[ZDKDispatcher loginFromRequestQueue:onError:]_block_invoke + 213
	9   BabyBundle                          0x000000010bb68956 __50-[ZDKDispatcher executeRequest:onSuccess:onError:]_block_invoke + 645
	10  CFNetwork                           0x000000011112c8c5 __67+[NSURLConnection sendAsynchronousRequest:queue:completionHandler:]_block_invoke_2 + 155
	11  Foundation                          0x000000010c9e157f __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	12  Foundation                          0x000000010c9220b2 -[NSBlockOperation main] + 98
	13  Foundation                          0x000000010c904774 -[__NSOperationInternal _start:] + 645
	14  Foundation                          0x000000010c904383 __NSOQSchedule_f + 184
	15  libdispatch.dylib                   0x000000010f5a9614 _dispatch_client_callout + 8
	16  libdispatch.dylib                   0x000000010f5906a7 _dispatch_queue_drain + 2176
	17  libdispatch.dylib                   0x000000010f58fcc0 _dispatch_queue_invoke + 235
	18  libdispatch.dylib                   0x000000010f5933b9 _dispatch_root_queue_drain + 1359
	19  libdispatch.dylib                   0x000000010f594b17 _dispatch_worker_thread3 + 111
	20  libsystem_pthread.dylib             0x000000010f916637 _pthread_wqthread + 729
	21  libsystem_pthread.dylib             0x000000010f91440d start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by tecknut** [comment]
@cristinasitaa Can you supply more of your code please? Any other Zendesk SDK code you have would help. 

Also, can you be more specific on how to replicate this issue please?

**Comment by cristinasitaa** [comment]
I fixed it by removing Zendesk from Pods and add it manually. I haven't change any line of code and now it's working fine. I'm still not sure what's happening.

**Comment by tecknut** [comment]
@cristinasitaa we haven't seen this crash before with cocoapods, we can try find a solution if you'd prefer to use cocoapods. 

Are you happy with how it's working now?
