### ISSUE TITLE
Push versions to CocoaPods

### ISSUE THREAD

**Issue by billinghamj** [zendesk/zendesk_sdk_ios#61]
We'd much prefer to attach to a version number of Zendesk, i.e.:

`pod 'zendesk', '~> 1.3'`

Rather than the current:

`pod 'ZendeskSDK', git: 'https://github.com/zendesk/zendesk_sdk_ios.git'`

This is primarily because we run `pod update` as a part of our build process. Every other library follows semantic versioning, so this means we won't receive breaking changes but will always receive the latest fixes.

The way it currently works for Zendesk means the moment you commit a breaking change to master, our app breaks immediately.

**Comment by tecknut** [comment]
@billinghamj We just added support for this. 

Add `source 'https://github.com/zendesk/Specs.git` to the top of your Podfile and you should be able to specify the release tag you want to use.

Thank you for pointing this out, it was an oversight on our behalf. One which we were happy to put right.

Please let us know of any other improvements you may think of.

**Comment by billinghamj** [comment]
@tecknut This is appreciated, but why not push to the Cocoapods Trunk like *every* other library...?

**Comment by billinghamj** [comment]
They're now on Cocoapods Trunk - https://github.com/CocoaPods/Specs/tree/master/Specs/ZendeskSDK

If you let me know what email address you have registered with Cocoapods Trunk, I'll set you as the owner of the pod.
