### ISSUE TITLE
ZDKSupportView appearance option for nav buttons

### ISSUE THREAD

**Issue by jimmaye** [zendesk/zendesk_sdk_ios#62]
Will it be possible to disable/remove the "contact us" button, aka. the right nav button item, from the support view anytime soon? 
We want our users to be able to use the supportview(Help center), but not create and view tickets yet. We can of create this ourselves by hand of course, but since you already did the convenience viewcontrollers, it's seems like a hassle to do all that work just to be able to remove a single button here and there.

**Comment by tecknut** [comment]
@jimmaye This has been brought up before by other integrators, and it's something which we are addressing. We have a solution that will go out with our next release, but we can't give a specific date as to when it will be released.

**Comment by jimmaye** [comment]
Sounds awesome, thank you!

**Comment by tecknut** [comment]
@jimmaye I'll keep this issue open till we release the fix, and update you on it when the release is out.

**Comment by tecknut** [comment]
@jimmaye We just released a new version of the SDK which added another value to an [enum so you can have no nav bar.](https://github.com/zendesk/zendesk_sdk_ios/blob/53d2d9fc88c09f1c3a717ba2879fa52dc8bbe5ee/SampleApp/SampleApp/Frameworks/ZendeskSDK.framework/Headers/ZDKHelpCenterConversationsUIDelegate.h#L35)

Setting this value [here](https://github.com/zendesk/zendesk_sdk_ios/blob/53d2d9fc88c09f1c3a717ba2879fa52dc8bbe5ee/SampleApp/SampleApp/Frameworks/ZendeskSDK.framework/Headers/ZDKHelpCenter.h#L115) will remove this button. 

Hope this allows you to achieve what you want.

**Comment by jimmaye** [comment]
@tecknut Thank you very much - this should do the trick!

**Comment by tecknut** [comment]
Good to hear. Closing this now
