### ISSUE TITLE
"Failed to get categories" in HelpCenter

### ISSUE THREAD

**Issue by andres-ciano** [zendesk/zendesk_sdk_ios#65]
As indicated in the documentation, I initialize the SDK using the provided snippet:
```
[[ZDKConfig instance] initializeWithAppId:@"MY_APP_ID" zendeskUrl:@"MY_INSTANCE_URL" ClientId:@"MY_CLIENT_ID" onSuccess:^() {} } onError:^(NSError *error) {}];
```
Once I know the request has returned `success` I proceed to open the HelpCenter using:
```
[ZDKHelpCenter showHelpCenterWithNavController:self.navigationController];
```
Then a banner appears with the error: *"Failed to get categories"*, and the screen remains empty.

Worth to note we have tried with a sandbox setup and with a production enabled application. All server-side configuration seems to be fine.

Probably related, though not helpful (for me at least, yet):
https://github.com/zendesk/zendesk_sdk_ios/issues/49
https://github.com/zendesk/zendesk_sdk_ios/issues/23

Any info or guidance you can provide will be greatly appreciated; in any case, thanks in advance!

Here is the **console output for the initialization**:
```
2015-08-25 11:36:31.916 [DEBUG]: No SDK configuration file found in local storage, sending request to fetch configuration file.
2015-08-25 11:36:31.920 [DEBUG]: About to execute [0x7fe40672f0c0]: https://<INSTANCE>.zendesk.com/api/mobile/sdk/settings/<UNIQUE_ID>.json
with headers
{
    Accept = "application/json";
    "Accept-Language" = en;
    "Client-Identifier" = "mobile_sdk_client_<SOME_CLIENT_ID>";
    "Content-Type" = "application/json";
    "User-Agent" = "Zendesk-SDK/1.3.4.1 iOS/8.4";
}
2015-08-25 11:36:33.520 [DEBUG]: Response code [0x7fe40672f0c0]: 200
2015-08-25 11:36:33.521 [DEBUG]: Request success: [0x7fe40672f0c0]: https://<INSTANCE>.zendesk.com/api/mobile/sdk/settings/<UNIQUE_ID>.json
2015-08-25 11:36:33.533 [DEBUG]: No support for en
2015-08-25 11:36:33.533 [DEBUG]: Successfully updated SDK settings
2015-08-25 11:36:33.536 [LOG] ZDK INITIALIZE SUCCESS
```

And here is the **debug output when opening the HelpCenter**:
```
2015-08-25 11:42:19.873 [DEBUG]: sdkSettings: <ZDKAppSettings: 0x7fe405dbbd40>
2015-08-25 11:42:19.892 [DEBUG]: About to execute login request [0x7fe405d5cfc0]: https://<INSTANCE>.zendesk.com/access/sdk/anonymous
with headers
{
    Accept = "application/json";
    "Client-Identifier" = "mobile_sdk_client_< SOME_CLIENT_ID >";
    "Content-Type" = "application/json";
    "Mobile-Sdk-Identity" = "<SOME_HASH>";
    "User-Agent" = "Zendesk-SDK/1.3.4.1 iOS/8.4";
}
2015-08-25 11:42:20.940 [DEBUG]: Response code [0x7fe405d5cfc0]: 0
2015-08-25 11:42:20.940 [ERROR]: Login request error [0x7fe405d5cfc0]: https://<INSTANCE>.zendesk.com/access/sdk/anonymous
2015-08-25 11:42:20.941 [ERROR]: Request error: [{
    "zd_dispatcher_err" = "Error Domain=NSURLErrorDomain Code=-1012 \"The operation couldn\U2019t be completed. (NSURLErrorDomain error -1012.)\" UserInfo=0x7fe40655c7d0 {NSErrorFailingURLStringKey=https://<INSTANCE>.zendesk.com/access/sdk/anonymous, NSUnderlyingError=0x7fe405c97d80 \"The operation couldn\U2019t be completed. (kCFErrorDomainCFNetwork error -1012.)\", NSErrorFailingURLKey=https://<INSTANCE>.zendesk.com/access/sdk/anonymous}";
}]
2015-08-25 11:42:20.944 [DEBUG]: Request Error: displaying toast
```

**Comment by andres-ciano** [comment]
Moved a bit forward (or backward, depending on how you see it)...
I got it working for the sandbox adding:
```
ZDKAnonymousIdentity *identity = [ZDKAnonymousIdentity new];
[ZDKConfig instance].userIdentity = identity;
```
But somehow, it is not working in our production site.

The weird thing is that, while logged in, the SDK tries to fetch categories using:
```
https://*****.zendesk.com/api/v2/help_center/en-us/categories.json?per_page=1000
```
which fails. But when `curl`ing that url *without the /en-us* the json responds as expected.

**Comment by tecknut** [comment]
@andres-ciano Can you create a ticket on support.zendesk.com please? We're probably gonna need to replicate this ourselves with your account details which shouldn't be shared here.

**Comment by andres-ciano** [comment]
Thanks @tecknut. We've already referenced this issue from the ticket below.

https://support.zendesk.com/hc/en-us/community/posts/204978678--Failed-to-get-categories-in-HelpCenter-for-iOS-SDK-integration

**Comment by tecknut** [comment]
@andres-ciano Ok I'll open an actual ticket. That link goes to a community page which is public. We will need to get some information to continue. 

Do you have an email so I can open a ticket on your behalf?

**Comment by andres-ciano** [comment]
You are right @tecknut. Sorry about that.
This is the proper ticket: https://support.zendesk.com/hc/en-us/requests/1216836

**Comment by tecknut** [comment]
Closing this, issue was solved. Bad memcache.

**Comment by ccombes** [comment]
I just encountered this issue starting new with ZenDesk.  Can you elaborate more on what the solution is?

I added the "identity" code above and forum categories display.  I don't know what would happen in the production app.

```
ZDKAnonymousIdentity *identity = [ZDKAnonymousIdentity new];
[ZDKConfig instance].userIdentity = identity;
```
Please advise.

**Comment by andres-ciano** [comment]
@ccombes, you should contact them on their own support plattform... We got it fixed it (on their side) over there.

CC @guillermo-olx

**Comment by baz8080** [comment]
@ccombes you can create a new issue here or open a ticket by emailing support@zendesk.com. Please [enable logging](https://developer.zendesk.com/embeddables/docs/ios/advancedtopics#logging) and give us as much detail as you can, including code snippets.

**Comment by blakeperdue** [comment]
We were having the same issue and identifying the user like @ccombes suggested solved it:

```
ZDKAnonymousIdentity *identity = [ZDKAnonymousIdentity new];
[ZDKConfig instance].userIdentity = identity;
```

**Comment by ccombes** [comment]
Here is how we are using it by setting the email address as well:
`ZDKAnonymousIdentity *identity = [ZDKAnonymousIdentity new];
identity.email = @"someone@example.com";
[ZDKConfig instance].userIdentity = identity;
`

**Comment by chipp** [comment]
Our team also got this error, but it was solved after we connected the credit card to our Zendesk account.
Maybe it will help someone.
