### ISSUE TITLE
Installing via CocoaPods gives import non-modular framework header error

### ISSUE THREAD

**Issue by jasperblues** [zendesk/zendesk_sdk_ios#67]
I had to add the following install hook in CocoaPods: 

```
post_install do |installer|
  installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
    configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
  end
end
```

. . . would be better if the PodSpec included this, so that its not necessary to add that install hook.

**Comment by tecknut** [comment]
Thanks for pointing this out @jasperblues. We just updated the podspec. Would you be able to tell us if this solved your issue?

**Comment by jasperblues** [comment]
sure, giving it a try. . .

**Comment by jasperblues** [comment]
Did you update the podspec in the CocoaPods mater repo? I didn't see a new version or anything. But after pod update seems ok.

**Comment by tecknut** [comment]
Depending on how you have our pod included in your Podfile you could be getting our pod from this repo or our Specs repo. I pushed the update to this repo and our specs repo.

See our README.md :

> You can also reference this repository as a cocoapod:

````
source 'https://github.com/zendesk/Specs.git'

pod 'ZendeskSDK'
````

>To choose a specific version: 

```
source 'https://github.com/zendesk/Specs.git'

pod 'ZendeskSDK', '~> RELEASE_VERSION_TAG'
```

**Comment by jasperblues** [comment]
I'm using the podspec in the CocoaPods mater repo `http://cocoapods.org/pods/?q=Zendesk`

**Comment by tecknut** [comment]
Our official Podspec is located at https://github.com/zendesk/Specs.git and this is the spec which we push updates to.

A third party has put our spec on http://cocoapods.org/pods/?q=Zendesk but this is not the official source for our SDK.

**Comment by jasperblues** [comment]
Ah, ok, thanks for that info. I'd strongly recommend adding a specific note to that effect in the getting started docs as its not unreasonable to assume that the CocoaPods master repo is the official source - this is a very common occurrence.

In that case if you didn't update the master repo/spec, then I was unable to reproduce the issue again by cleaning build products and pod updating a second time. I'm not sure why. 

But anyway - works for me now. You may close the issue or wait for someone to verify it more thoroughly.

**Comment by tecknut** [comment]
@jasperblues Thanks, we had reasons for having our own Specs repo. We're reviewing things at the moment and will update readme with what ever gets decided. 


I'm going to leave this open for a while and close it if it goes stale. 

Thanks again.

**Comment by tecknut** [comment]
Closing this.
