### ISSUE TITLE
Does not present view controller

### ISSUE THREAD

**Issue by jasperblues** [zendesk/zendesk_sdk_ios#69]
I've wired up the following delegate methods: 

```objc
- (void)onRateApp
{
    DDLogDebug(@"onRateApp");
    [ZDKRMA showInView:self.view];
}

- (void)onVisitKnowledgeBase
{
    DDLogDebug(@"onVisitKnowledgeBase!");
    [ZDKHelpCenter showHelpCenterWithNavController:self.navigationController];
}
```

* These methods are invoked on the main thread.
* self.navigationController is an instance of APNavigationController,  a subclass of UINavigationController (tried using also vanila UINavigationController)

Neither rate my app nor knowledgebase VCs are presented. Need help.

**Comment by tecknut** [comment]
Hey @jasperblues, the ZDKRMA works in conjunction with your admin config settings in Zendesk. There are a few conditions which are set there. You need to call `+logVisit` on `ZDKRMA` to increment a counter which is used to track the amount of times a user has landed on the view in which you want to present RMA. This and a timestamp measured in days need to reach a threshold before RMA is shown. 

You can set these values to 0 in the admin config panel and then delete the app from your device or simulator to force an update of the SDK settings. This should set things up for RMA to show for you as a test, and then you can set the values back to something which you think works in your app.

For the issue with `ZDKHelpCenter`, can you nil check `self.navigationController` please to ensure it's not nil?

**Comment by jasperblues** [comment]
Hello @tecknut Thanks for the response. 

Yes, I nil checked the `UINavigationController` . Also as I said above, I tried using an instance of a vanila UINavigationController rather than the sub-class (which has trivial customizations).

**Comment by tecknut** [comment]
@jasperblues OK, can you give us more information about your integration please? 

At what point do you initialise the SDK ?
Have you turned on logging? ( if so can you post some logs here in your next response, make sure you remove any sensitive information like client id and sdk_guid from the request headers in the logs)
Do any other features of the SDK work for you? (create request?)

**Comment by jasperblues** [comment]
@tecknut I'll get back to you. We've managed to get rate my app showing with some drawbacks: https://github.com/zendesk/zendesk_sdk_ios/issues/70

Now working on Knowledge Base.

**Comment by tecknut** [comment]
What are your drawbacks? It might be possible to do what you want.

**Comment by jasperblues** [comment]
The linked #70 describes them - delay while showing.

**Comment by baz8080** [comment]
@jasperblues I'm going to close this issue based on 
https://github.com/zendesk/zendesk_sdk_ios/issues/70 which added a read/write shouldShowBlock

**Comment by jasperblues** [comment]
:+1:
