### ISSUE TITLE
Unable to override shouldShowBlock in ZDKRMAConfigObject

### ISSUE THREAD

**Issue by alexgarbarev** [zendesk/zendesk_sdk_ios#70]
Documentation says 
> To override the default settings of ZDKRMA, call the configure method and set new values as desired.

But `shouldShowBlock` property definition look like this:

```
@property (nonatomic, copy, readonly) ShouldShow shouldShowBlock;
```
Documentation says 
> Can be overridden for custom behaviour.

 but it's READONLY property hence cannot be overridden.
Am I miss something?

**Comment by tecknut** [comment]
@alexgarbarev Thanks for pointing this out. This was meant to be made read write, but it obviously slipped through the cracks. We have a jira opened up for this. We are preparing a release and are in code freeze, so this will be out in a patch release soon. 

In the mean time lets see if we can get something working for you, what custom behaviour are you looking for?

**Comment by alexgarbarev** [comment]
I get something working with that:
```
    [ZDKRMA configure:^(ZDKAccount *account, ZDKRMAConfigObject *config) {
        ShouldShow block = ^BOOL(NSNumber *visitCount, NSDate *initialCheckDate, NSDate *lastDisplayDate, ZDKRMAAction lastOptionSelected, NSString *appVersionAtLastInteraction) {
            return YES;
        };
        [config setValue:block forKey:@"shouldShowBlock"];
    }];
```
because KVC can be used with readonly properties as well. 

I want to show "Rate My App" by tapping on custom button. I tried block above, but it doesn't work (block isn't called). Weird..

**Comment by alexgarbarev** [comment]
So I don't want any "visit count", "duration" checking etc. I want just opening "Rate My App" manually by user. Is that possible?

**Comment by tecknut** [comment]
You can use show always. It's another method which will just show RMA. 

I'll add the fact that KVC didn't work to the jira we have, it would be nice to know why that is.

Thanks again for pointing this out. Hopefully show always is what you want.

**Comment by alexgarbarev** [comment]
Thanks @tecknut. ShowAlways works fine. 
KVC works for settings block. After KVC call, `shouldShowBlock` property points to right value. But for some strange reason block wasn't called.

**Comment by alexgarbarev** [comment]
@tecknut Is it possible to show "Rate My App" instantly? I can't set Delay to 0 on admin panel. It forces value to 1..

**Comment by tecknut** [comment]
@alexgarbarev this is news to me, I've been able to set the delay value to 0 in the past. I'll open an issue with our server side devs.

**Comment by tecknut** [comment]
Release just out with a read write should show block. Hope that helps.
