### ISSUE TITLE
Can't set background color for Navbar in issue creation VC

### ISSUE THREAD

**Issue by jasperblues** [zendesk/zendesk_sdk_ios#71]
When presenting the issue creation VC the navbar is white, not matter what is set via appearance proxy etc. Firing up the Reveal tool shows that the UINavigationBar backing view gets set to white, and editing this property (via Reveal) fixes things. . . but the navbar is not obeying appearance proxy settings. 

Saw another issue logged about this earlier in the month, on August 5th.

**Comment by tecknut** [comment]
@jasperblues Tested this in our sample and have been able to change the navbar colour. 

`[[UINavigationBar appearance] setBarTintColor: [UIColor redColor]];`

in the app delegate.

**Comment by tecknut** [comment]
As that issue states, here is the link to the docs which describe how to do this. https://developer.zendesk.com/embeddables/docs/ios/customization

**Comment by jasperblues** [comment]
Yes also tested in your sample app when the error first encountered. works there. doesn't work in our app, not sure what the root cause is yet, but appearance proxies work everywhere except that issue creation vc.

**Comment by tecknut** [comment]
@jasperblues Tested in another App with our SDK. https://github.com/zendesk/sdk_demo_app_ios

Working there too.

**Comment by jasperblues** [comment]
Same issue reported by another user: https://support.zendesk.com/hc/en-us/community/posts/204607658-Change-navigation-bar-color-in-iOS-SDK

**Comment by tecknut** [comment]
@jasperblues Here is a link another sample app with this working. I've not been able to replicate this issue. 

https://www.dropbox.com/s/3iel5dk9lyu69s2/NavBarTest.zip?dl=0

**Comment by jasperblues** [comment]
I'll see if we can strip it down to a sample project for you.

**Comment by luky1984** [comment]
i had same problem how to tint the navbar color, since the default color was light gray and button was white, that means not readable.

only [[UINavigationBar appearance] setBarTintColor: [UIColor redColor]];

worked for me too, that means nothing from customization page

**Comment by tecknut** [comment]
@jasperblues is this issue persisting?

**Comment by jasperblues** [comment]
Yes, it wasn't solved. But we've moved on.

**Comment by tecknut** [comment]
Do you think you will to strip it down to a sample project? We have not been able to replicate this and as such can't debug anything.

**Comment by jasperblues** [comment]
I would like to, but unfortunately it is not a priority any more and on this particular project there is very little time for side tasks. I can do it after our store release perhaps.

**Comment by tecknut** [comment]
Ok, I'm going to close this for now then. Please reopen it, or create a new issue, if you get the chance to replicate it in a sample app which we can debug.
