### ISSUE TITLE
Linker error "Symbols not found for architecture arm64"

### ISSUE THREAD

**Issue by luky1984** [zendesk/zendesk_sdk_ios#72]
Hi, i followed getting started tutorial https://developer.zendesk.com/embeddables/docs/ios/gettingstarted that means, i downloaded zendesk, then i copied those three files to xcode/frameworks etc, but when i try build the projecti see 20 linker errors and on bottom message "Symbols not found for architecture arm64"

I tried hard to manage the problem but i was not successfull. I tried for example change archicture in settings from standard architectures (armv7, arm64) to armv7 only, but the error persists.

I also tried Product / Clean.

As i said, i copied the zendesk sdk in project manually not via cocoapods.
I dont know if it matters but i have in linker flags "-lc++" that should not be problem i guess.
I tried different versions from your github, but i have problems with all of them.

I have Xcode 6.4.

I also tried Archive action (because somewhere i found that the debug/release thing could be problem) but same results.

Btw, yes i have ZendeskSDK in Build phases / Link binary with libraries, and two bundle files in Build phases / Copy Bundle resources section.

I am attaching screen of errors.

![screen shot 2015-09-09 at 11 38 11](https://cloud.githubusercontent.com/assets/10039829/9758523/830982da-56e7-11e5-9fa7-afda18b403d2.png)

![screen shot 2015-09-09 at 11 41 31](https://cloud.githubusercontent.com/assets/10039829/9758577/cd40f52c-56e7-11e5-99f2-c9d6a31b4dc8.png)

Please help, thx

**Comment by RonanMcH** [comment]
Hey @luky1984 ,
can you try add the Security framework to your project and see if it compiles.

**Comment by luky1984** [comment]
Hey Ronan, thanks for fast reply, i will try it right away.

L.

**Comment by luky1984** [comment]
So i tried add Security framework to Build Phases / Link Binary with libraries, but it didn't help. I also tried Product / Clean and then Build, but nothing.

**Comment by RonanMcH** [comment]
Hey @luky1984 ,
Could you please open a ticket with https://support.zendesk.com/ and link this github issue in the ticket.

**Comment by luky1984** [comment]
Pff, i don't know what happened but now it works... Meanwhile i removed the ZendeskSDK from project to be able to work on it, made some changes in code, then i added it again because i realized that i have opened another scheme (i have normal and beta - i noticed my mistake that i have opened normal scheme, while i am using beta for deploying) but then it worked, even if the Security framework was not included etc.

Strange. It must have reason why, but i dont know now which is it.

If i will be able to reproduce the problem i will say what was the reason.

Thanks and regards

**Comment by luky1984** [comment]
Ok, now i added Security framework and it works, so the reason of problem was this.

It didn't work when i was trying this before because i was probably working with "normal" scheme, while building "debug" scheme.

Many thanks.

Please include this information about Security framework also on your Getting started page, to help also others :).

Have a nice day
