### ISSUE TITLE
Identity change of name is reflected only if made together with identity email change

### ISSUE THREAD

**Issue by luky1984** [zendesk/zendesk_sdk_ios#73]
Hi,

i am using the anonymous type of identity like:

ZDKAnonymousIdentity *identity = [ZDKAnonymousIdentity new];

identity.name = @"Anonymous";
identity.email = @"anonym@anonym.com";

And then i have the website backend x.zendesk.com where i see the submited tickets.

I noticed, that if i change in ObjC code the name to something else, the new name will not appear in zendesk ticket list, there will be still the old name (which was sent in first submitted ticket)

The new name will only appear if i also change the identity email in the ObjC (as shown above).

So it seems that either the iOS SDK or the Zendesk Website links the name of identity to identity email and displays this name for every future tickets of this identinty email, no matter if the future tickets were send with another name in identity.

Let me show example:

1) i send first ticket as: 

identity.name = @"Anonymous";
identity.email = @"anonym@anonym.com";

in admin i see ticket from Anonymous / anonym@anonym.com

2) i send second ticket as:

identity.name = @"Bear";
identity.email = @"anonym@anonym.com";

in admin i see ticket from Anonymous / anonym@anonym.com

Change of name was not reflected !

3) i send ticket as:

identity.name = @"Bear";
identity.email = @"bear@anonym.com";

in admin i see ticket from Bear / bear@anonym.com

Change of name was reflected, because i also changed the email.

====

Btw, i am checking in console the identity.name variable after i made the change, and i see there the new value.

So may be it is more problem of Zendesk website.

Btw: doesnt help if i delete the app from device and will try the step 2. (still in admin will be displaed the old name, unless i make the change as shown in step 3)

Problem of this is, that if i will have more users using same email (some "foo" email because i dont know their real email) but i know their name, i will not see their real names in Zendesk website, because all tickets with the common email will show name of the first ticket.

Or dont know if this is problem of, that ZendeskSDK saves the first identity somewhere deeply on the phone, so from other phone the other name would be reflected. I will try it from simulator, if possible.

**Comment by StevenDiviney** [comment]
Hi @lucky1984,

This is expected behavior. More information can be found here https://developer.zendesk.com/embeddables/docs/ios/authentication#authentication-process

You may be able to use external id to identify the user in your system.

**Comment by luky1984** [comment]
Thank you for pointing me out.
