### ISSUE TITLE
Custom fields are not send in request. 

### ISSUE THREAD

**Issue by luky1984** [zendesk/zendesk_sdk_ios#74]
Hi, i am setting custom fields like:

    NSLog(@"Custom data %@",  @[identity.name, identity.email, vOS, vIp, vDevice, vApp]);

    ZDKCustomField *fOS =     [[ZDKCustomField alloc] initWithFieldId:@(22451972) andValue:vOS];
    ZDKCustomField *fIp =     [[ZDKCustomField alloc] initWithFieldId:@(22474078) andValue:vIp];
    ZDKCustomField *fDevice = [[ZDKCustomField alloc] initWithFieldId:@(22451982) andValue:vDevice];
    ZDKCustomField *fApp =    [[ZDKCustomField alloc] initWithFieldId:@(22461961) andValue:vApp];
    
    [ZDKConfig instance].customTicketFields = @[fOS, fIp, fDevice, fApp];

But in Zendesk administration, the custom fields are not filled in the ticket. They are empty. 

- the ids of custom ticket fields are correct and they do exists in zendesk / custom fields
- i check the values of custom fields with NSLog as show above and they are set correctly
- i am setting them in success block of [[ZDKConfig instance] initializeWithAppId ... before i call
  [ZDKRequests showRequestCreationWithNavController:self.navigationController];

Btw custom tags are send correctly, but they are set other way than custom fields.

Thx,

L.

**Comment by StevenDiviney** [comment]
Hi @luky1984,

To debug this issue further could you open please a ticket at [support.zendesk.com](https://support.zendesk.com/)

If you link this github issue in the ticket it would be very helpful.

Thanks,

Steven

**Comment by luky1984** [comment]
Hi i found the reason. In ticket fields administration the fields must be set as visible and editable to end user. Without it, it doesn't work.
