### ISSUE TITLE
Unexpected CFBundleExectuable Key

### ISSUE THREAD

**Issue by joshbillions** [zendesk/zendesk_sdk_ios#76]
SDK builds and runs just fine with Xcode 7 GM, but fails with the following error when submitting to the app store:

![screen shot 2015-09-10 at 11 29 36 am](https://cloud.githubusercontent.com/assets/2422443/9793390/3b66de56-57b3-11e5-8046-04948d6548e1.png)

![screen shot 2015-09-10 at 11 29 43 am](https://cloud.githubusercontent.com/assets/2422443/9793394/3e49d16e-57b3-11e5-9a9a-cccbc51c7615.png)

**Comment by baz8080** [comment]
Hi Josh,

We will be releasing a 1.4.0.x of the SDK soon and we're going to address this issue in that.

Thanks,
Barry.

**Comment by joshbillions** [comment]
Issue resolved with 1.4.0.1, thanks Zendesk team!

**Comment by billinghamj** [comment]
You guys should probably update your spec repo... @baz8080 I've updated the unofficial one on Cocoapods trunk.

**Comment by tecknut** [comment]
It has been updated.
