### ISSUE TITLE
Derived Data references in the exported framework

### ISSUE THREAD

**Issue by lickel** [zendesk/zendesk_sdk_ios#79]
The latest version spits out over 200 warnings.

```
while processing /Users/lickea/Documents/Software/Threadflip/iOS/Pods/ZendeskSDK/ZendeskSDK.framework/ZendeskSDK(ZDKHelpCenterCategory.o):
warning: /Users/rmchugh/Library/Developer/Xcode/DerivedData/ModuleCache/2H9WKLUJCLOE7/Foundation-1YMZJBNB8N25F.pcm: No such file or directory
...
while processing /Users/lickea/Documents/Software/Threadflip/iOS/Pods/ZendeskSDK/ZendeskSDK.framework/ZendeskSDK(ZDKHelpCenterCategory.o):
warning: Could not resolve external type c:objc(cs)NSObject
```

**Comment by tecknut** [comment]
@lickel Can you give us more information. We test deployed the SDK in our sample app and our Remember The Date app, including an app store submission, and didn't encounter this. 

Some reproduction steps would help us track down this issue. Including Xcode version. 

All our SDK development is in Ireland, which means it will be Monday morning local time before we get a chance to look at this. 

Thanks

**Comment by lickel** [comment]
I'm not sure why it's happening, other than to say that I don't have a `/Users/rmchugh` folder.
It only seems to be an issue when I make simulator builds.

The simulator builds do seem to work locally, but it's definitely difficult to see legitimate (local) warnings when there's a wall of them from a third-party library.
In the past, I've seen similar linker warnings from binary dependencies, so it's presumably a flag in the build settings that's been set incorrectly.

**Comment by billinghamj** [comment]
+1 to this issue. We're running on OS X 10.10.5. Xcode 7 GM.

In our case, 8333 lines of errors come out relating to this during the GenerateDSYMFile phase. It's quite hard to provide a copy of the full error log as it's 22MB in size.

We also see /Users/rmchugh/ in the output, which would indicate the issues are coming from within the compiled file provided in the SDK.

**Comment by tecknut** [comment]
@lickel We tracked down the source of this issue. A build option, CLANG_ENABLE_MODULES which is set to YES by default, caused these errors when built with Xcode 7. As we were keen to get an Xcode 7 build out to support early adopters this issue slipped passed us. 

We've done some testing around this and will have a new build release out by tomorrow which has this build option disabled.

**Comment by tecknut** [comment]
We have just released an updated build which fixes this issue.
