### ISSUE TITLE
Is it "license" or "licence"?

### ISSUE THREAD

**Issue by jtihon** [zendesk/zendesk_sdk_ios#81]
Greetings. I noticed that you have a "LICENCE.md" file but you refer users to look at the "license" in "README.md". Which spelling is it supposed to be? "Licence" is the British spelling, but the majority of the project uses "license"

  - https://github.com/zendesk/zendesk_sdk_ios/blob/master/README.md
  - https://github.com/zendesk/zendesk_sdk_ios/blob/master/LICENCE.md
  - https://github.com/zendesk/zendesk_sdk_ios/blob/master/ZendeskSDK.podspec

**Comment by baz8080** [comment]
Hi Jack,

Firstly, thanks for pointing that out and sweet avatar btw. We are not fans of inconsistency so we'll get it sorted out

![blankmap-world6 svg](https://cloud.githubusercontent.com/assets/1534413/9898907/27346058-5c4e-11e5-8d6f-87c9ddc03cc8.png)

You have certainly exposed us on this one.  We're an American company that came from Copenhagen and the SDK is made in Ireland by people who inherited the English language from our friends in London.   On top of that we have quite the diverse team here with people from all over the world.  To make it even more confusing Licence is only the noun in British English and license is the verb. The next version of the license is going to be written in [lojban](https://en.wikipedia.org/wiki/Lojban) though so we should be good.

Thanks!
Barry.

**Comment by jtihon** [comment]
Thanks for the reply, it made my day. Also, I thanks to `-getFlatArticlesWithCallback:`, I'm unstuck!

**Comment by jtihon** [comment]
Also, long cat is long.
![Image of long cat walking]
(http://media.indiedb.com/images/games/1/10/9018/61708.gif)

**Comment by baz8080** [comment]
:+1: :grinning:

**Comment by Jarred-Sumner** [comment]
:laughing:

**Comment by apanzerj** [comment]
Just came here to say meoooooooooooooooooooooow

**Comment by baz8080** [comment]
@jtihon The public facing bit of LICENSE vs LICENCE is merged. The rest of it will come when we do our next release. I'm going to close the issue :)

**Comment by jtihon** [comment]
Yay!
