### ISSUE TITLE
s/invokation/invocation/g

### ISSUE THREAD

**Issue by jtihon** [zendesk/zendesk_sdk_ios#83]
Sorry to be finding these typos, but I've been reading your headers a lot recently.
Looks like "invokation" is only in `ZDKRequestProvider.h`

**Comment by baz8080** [comment]
Thanks Jack, we'll get it sorted. I know some of our iOS devs will be delighted that the headers are being read :)

![](http://img.memecdn.com/long-cat_o_147841.jpg)

**Comment by baz8080** [comment]
Starting a sweep of the typos today.

**Comment by baz8080** [comment]
@jtihon These spelling mistakes (and a host of others) have been fixed and will be here when we do our next release.

**Comment by jtihon** [comment]
(=^-ω-^=)
