### ISSUE TITLE
`ZDKAPISuccess` documentation

### ISSUE THREAD

**Issue by jtihon** [zendesk/zendesk_sdk_ios#84]
Greetings, I'm using the following class method with callback to handle feedback requests:

```
+ (void) showRequestCreationWithNavController:(UINavigationController*)navController
                                  withSuccess:(ZDKAPISuccess)success
                                     andError:(ZDKAPIError)error;
```

from looking at `ZDKAPISuccess`, which is defined as:

```
typedef void (^ZDKAPISuccess) (id result);
```

I am perfectly happy with `lldb` and figuring out what is going on, but it'd be nice if the __ego__ would assert it's organizational power over the __id__'s uncoordinated instinctual trends and get clearer documentation on what it sends back.

Also, it'd be good to have actual usage examples for this particular API in the sample projects. :-D

Thanks for all the help so far,

—longcat

**Comment by tecknut** [comment]
@jtihon The history of `ZDKAPISuccess` is as long as longcat is long. 

It's defined in [ZDKAPIDispatcher](https://github.com/zendesk/zendesk_sdk_ios/blob/master/ZendeskSDK.framework/Headers/ZDKDispatcher.h) as follows: 
```objective-c
/**
 *  API success block.
 *
 *  @since 0.9.3.1
 */
typedef void (^ZDKAPISuccess) (id result);
```

It's been around since the beginning. Create request controller has also been around a long time, and predates the providers.
```objective-c
+ (void) showRequestCreationWithNavController:(UINavigationController*)navController
                                  withSuccess:(ZDKAPISuccess)success
                                     andError:(ZDKAPIError)error;
```
Basically, show request chains the callback from the dispatcher, which passes a [ZDKDispatcherResponse](https://github.com/zendesk/zendesk_sdk_ios/blob/master/ZendeskSDK.framework/Headers/ZDKDispatcherResponse.h) as `result`. 

Hopefully the helps to clear things up.

**Comment by jtihon** [comment]
Cool. I know how it works and have managed to pull out the data as JSON in `result.data`, but I was hoping for something a bit more structured. Ideally, I'd get a success block with not only regular success/fail status, but also some metadata like the ticket's id on return.

Granted this probably isn't what people normally want, but I'm trying to enable a pretty useful feature on our developer builds.

In a nutshell, I am implementing a pretty standard shake to send feedback. The reason I'm looking at the callback is to attach a screenshot as an attachment to make those reports just a bit clearer.

It took a bit of reading of headers to get to the point here. Originally I was thinking I could bundle the attachment on submitting feedback, but it looks like that was a non-starter. I've since come upon this method where I'll attach after I've successfully generated the ticket.

**Comment by tecknut** [comment]
Depending on how much UI work you want to do you can achieve this with the [ZDKRequestProvider](https://github.com/zendesk/zendesk_sdk_ios/blob/master/ZendeskSDK.framework/Headers/ZDKRequestProvider.h#L105) and the [ZDKUploadProvider](https://github.com/zendesk/zendesk_sdk_ios/blob/master/ZendeskSDK.framework/Headers/ZDKUploadProvider.h#L58). 

Or you could use the [ZDKRequestWithAttachmentsUtil](https://github.com/zendesk/zendesk_sdk_ios/blob/master/ZendeskSDK.framework/Headers/ZDKRequestWithAttachmentsUtil.h). It kind of wraps using the request provider and upload provider. 

Either approach will work for adding attachments while creating requests. I'm not sure how much time you have to work on this, but all the peaces are there to make a shake to send feedback.

**Comment by jtihon** [comment]
@tecknut, thanks, I got it working basically using those things. Thanks for the heads up on `ZDKRequestWithAttachmentsUtil`, it'll save me a few lines of code.

It'd still be nice to get a structured response from the callback so that I don't have to jump through the `NSJSONSerialization` hoops.

I'm basically done now, but I will be hosed until I test it if the response format changes... Orz

**Comment by tecknut** [comment]
Thanks for the feedback. We're always looking to improve the SDK.

**Comment by jtihon** [comment]
Just wondering. Is it possible to add an attachment while creating a ticket like how you do it in the UI? I have a couple triggers in place to auto-close the tickets so that internal feedback doesn't mess with Support's reports, but it looks like adding the attachment in a separate step re-opens it.

As I alluded to before, I initially wanted to do that, but from from my piecing together the headers came up with the solution you suggested. 

Any ideas?

**Comment by tecknut** [comment]
It's late here at the moment, but tomorrow I'll try knock up a quick and dirty sample app.

**Comment by jtihon** [comment]
@tecknut  That'd be great. Thanks! I need to roll onto some other things, but I would happily squeeze in some time to get it working smoothly.

**Comment by baz8080** [comment]
Hi Jack, while tecknut is sleeping I can give you a general gist of how we do it.  We: 

* Upload the attachment first with [the upload provider](https://github.com/zendesk/zendesk_sdk_ios/blob/master/ZendeskSDK.framework/Headers/ZDKUploadProvider.h#L58-L61).  
* Get the [upload token](https://github.com/zendesk/zendesk_sdk_ios/blob/master/ZendeskSDK.framework/Headers/ZDKUploadResponse.h#L33) from the response
* Create a request and add the token to the [attachments array](https://github.com/zendesk/zendesk_sdk_ios/blob/master/ZendeskSDK.framework/Headers/ZDKCreateRequest.h#L56)
* Call the [create request](https://github.com/zendesk/zendesk_sdk_ios/blob/master/ZendeskSDK.framework/Headers/ZDKRequestProvider.h#L105-L106) provider.

I hope that helps somewhat. I'm a jetlagged Android guy so it might not ;)

**Comment by jtihon** [comment]
@baz8080 yeah, that was what I was hoping for. I started down that route but then got stuck when using the helper class method to present the the controller. It unfortunately doesn't take in any parameters aside from the `UINavigationController` you want to push onto and the success and error callbacks.

I do have it mostly working (and it worked the first time, surprisingly!)

**Comment by tecknut** [comment]
@jtihon what @baz8080 said is exactly how it should be done. Did this work out for you?

**Comment by jtihon** [comment]
Looks like that will do what I want. If I get a chance I'll build out a VC to generate the fields. For now I'm using your built-in handler so I don't need to do `JSON` decoding.

From looking at the callback, the documentation is a bit fuzzy.
```
/**
 *  Block defined for a callback to be used for handling async server response for creating a request
 *
 *  @param result id object as a result of the API request sent to a Zendesk instance, can be nil on error
 *  @param error  NSError returned as a result of any errors taking place when the request is executed, can be nil on success
 */
```

What's the specific success/error check? `error != nil`?
`result` might not be `nil` on error?

Can I get a `result` and a non-`nil` `error`?

**Comment by baz8080** [comment]
Hi Jack,

error != nil is the general check. You will get a result or an error. If you ever find this not to be the case then that is a bug and we'll fix it.
