### ISSUE TITLE
ZDKDeviceInfo crashes on iPhone 6S

### ISSUE THREAD

**Issue by JustSid** [zendesk/zendesk_sdk_ios#85]
As the title says, it crashes on the iPhone 6s. Backtrace:

	Thread : Fatal Exception: NSInvalidArgumentException
	0  CoreFoundation                 0x0000000183740f5c __exceptionPreprocess + 124
	1  libobjc.A.dylib                0x0000000198c2bf80 objc_exception_throw + 56
	2  CoreFoundation                 0x000000018362f8e8 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 324
	3  CoreFoundation                 0x000000018362f780 +[NSDictionary dictionaryWithObjects:forKeys:count:] + 64
	4  app                            0x0000000100524728 +[ZDKDeviceInfo deviceInfoDictionary] (ZDKDeviceInfo.m:151)
	5  app                            0x00000001004d87a0 __88-[ZDKRequestProvider createRequestWithSubject:description:tags:attachments:andCallback:]_block_invoke (ZDKRequestProvider.m:145)
	6  app                            0x0000000100520398 __63-[ZDKDispatcher executeRequest:onSuccess:onError:requiresAuth:]_block_invoke153 (ZDKDispatcher.m:362)
	7  app                            0x0000000100520ae8 __63-[ZDKDispatcher executeRequest:onSuccess:onError:requiresAuth:]_block_invoke177 (ZDKDispatcher.m:421)
	8  libdispatch.dylib              0x00000001994197b0 _dispatch_call_block_and_release + 24
	9  libdispatch.dylib              0x0000000199419770 _dispatch_client_callout + 16
	10 libdispatch.dylib              0x000000019942575c _dispatch_queue_drain + 864
	11 libdispatch.dylib              0x000000019941d274 _dispatch_queue_invoke + 464
	12 libdispatch.dylib              0x0000000199419770 _dispatch_client_callout + 16
	13 libdispatch.dylib              0x0000000199427bb0 _dispatch_root_queue_drain + 2140
	14 libdispatch.dylib              0x000000019942734c _dispatch_worker_thread3 + 112
	15 libsystem_pthread.dylib        0x000000019962d478 _pthread_wqthread + 1092
	16 libsystem_pthread.dylib        0x000000019962d028 start_wqthread + 4

The exception:

	Fatal Exception: NSInvalidArgumentException
	*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]

**Comment by StevenDiviney** [comment]
@JustSid Thanks for bringing this to our attention. Can you try this bundle and see if it fixes your issue?

https://www.dropbox.com/s/5328y5n976wemgn/ZendeskSDK.bundle.zip?dl=0

**Comment by JustSid** [comment]
That worked indeed! Is it okay to submit an AppStore update with that bundle?

**Comment by StevenDiviney** [comment]
@JustSid We have just done a release of the SDK that updates this bundle and fixes the underlying issue.

**Comment by JustSid** [comment]
Awesome, thank you so much for the quick response :)

**Comment by StevenDiviney** [comment]
@JustSid We just did another release concerning this. We use system information to identify what type of device the request is made from, then use a plist in that bundle to convert it to a more readable string. Turns out the new devices report differently to what the Apple documentation states (they are swapped).

Anyway the overall effect is tickets from a 6s will look like they came from a 6s plus and vica versa, the new release fixes this. It's not a big deal but just letting you know.

**Comment by jaanushansen** [comment]
Hi!

I wonder, if the issue is now solved this way that when in the future Apple introduces new device models Zendesk SDK won't be crashing?

**Comment by baz8080** [comment]
@jaanushansen It is. If we don't find a mapping now we will default to 'Unknown device'

**Comment by jaanushansen** [comment]
Good to know, thank you for your response!

**Comment by nonnname** [comment]
This issue actual for latest unity plugin! What's about unity plugin support? When you planned update it?

**Comment by StevenDiviney** [comment]
@nonnname We are putting the finishing touches on a release of the unity plugin this week. We will let you know when it goes live.

**Comment by StevenDiviney** [comment]
@nonnname we have released version 1.4 of the unity plugin which fixes this and many other issues
https://developer.zendesk.com/embeddables/docs/ios/Unity3D_plugin#download
