### ISSUE TITLE
UI language

### ISSUE THREAD

**Issue by dogo** [zendesk/zendesk_sdk_ios#87]
Currently Zendesk sdk loads the device locale and set the UI strings to match the device locale. There is a way to ignore this step or force other locale 

eg:
1) My app supports en-US and es-ES and have an setting to change the app language.
2) My device is currently using en-US locale
3) User change app language to es-ES 
4) User press "Support" (Zendesk :P) the zendesk interface is loaded using en-US strings 

Expected result:

4) User press "Support" (Zendesk :P) the zendesk interface is loaded using es-ES strings

**Comment by tecknut** [comment]
@dogo This is something we don't support. We use apples localised string macros which return translations for the device local. 

We have no plans to change this behaviour.

**Comment by dogo** [comment]
Okay, thanks
