### ISSUE TITLE
Potential Circular reference imports causing build error

### ISSUE THREAD

**Issue by linktoming** [zendesk/zendesk_sdk_ios#91]
When I use 1.4.1.1 with cocoapods, the project got build error. Something like duplicated definition for some classes. Manually adding the framework worked fine somehow.

After I remove the circular reference (ref: https://github.com/zendesk/zendesk_sdk_ios/pull/88 ), it can be built successfully with cocoapods.

It would be better if you can do this change in the source code level.

**Comment by baz8080** [comment]
@linktoming We've fixed the circular references internally. They'll be in the next release. We don't have a date for that right now but we'll leave this issue open and let you know when it's released.

**Comment by RonanMcH** [comment]
Hi @linktoming ,
We have fixed the potential circular references and the fix is in our latest release (1.5.0.1).
Thanks again for bringing this to our attention,
Ronan.
