### ISSUE TITLE
Bitcode support missing from 1.4.1.2

### ISSUE THREAD

**Issue by jrahaim** [zendesk/zendesk_sdk_ios#92]
I am getting the bitcode error on 1.4.1.2
ZendeskSDK.framework/ZendeskSDK(ZDKHelpCenterCategory.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

**Comment by ssavic** [comment]
I'm having the same exact issue, with the latest 1.4.1.2

**Comment by StevenDiviney** [comment]
@jrahaim @ssavic We have just done another release to fix this.
