### ISSUE TITLE
Crash on iPhone 6s

### ISSUE THREAD

**Issue by rentbitswill** [zendesk/zendesk_sdk_ios#94]
Crashing when attempting to create a ticket from iPhone 6s (actual device not simulator).

It appears that ZDKDeviceInfo.deviceType is returning nil

**Comment by StevenDiviney** [comment]
@rentbitswill what version of the SDK are you using? We have just done a release to address this.

**Comment by rentbitswill** [comment]
Just grabbed the latest version. Thanks!
