### ISSUE TITLE
Link to release notes?

### ISSUE THREAD

**Issue by jtihon** [zendesk/zendesk_sdk_ios#95]
Minor nit. I had to a dig around a bit to find the release notes for the sdk.
There are a bunch of changes, and being a diligent developer, I'm loathe to upgrade unless there is some issue fixed. I don't need the `s/licence/license/g' change, but I did have a google a bit to find the release notes instead of looking around for them.

How about a link in the `README.md`?

https://developer.zendesk.com/embeddables/docs/ios/release_notes

**Comment by baz8080** [comment]
Will do. I could have sworn I replied to this yesterday, sorry about that.

**Comment by tecknut** [comment]
We have a link to docs and release notes in the README now.
