### ISSUE TITLE
1.4.1.3 Does not compile on Xcode 6.4 (Perhaps any Xcode < 7)

### ISSUE THREAD

**Issue by nicholas** [zendesk/zendesk_sdk_ios#97]
I'm guessing the latest release was built using Xcode 7.0+? That's causing older Xcodes to produce the following:

![Screenshot](https://photos-3.dropbox.com/t/2/AADGSU8VDexh5IyAfJC4aiha8QqQ6Bprz4pdta0tD5zKBA/12/19179734/png/32x32/1/1444755600/0/2/Screenshot%202015-10-13%2010.55.27.png/CNbRkgkgASACIAMgBSAHKAEoAigH/T4O-Ej4ajfOqWgKpnYJ6xD4RGjGQxS8Erlf5Hyh1at8?size=1024x768&size_mode=2)

Reverted back to 1.4.1.2 and all is well.

**Comment by RonanMcH** [comment]
Hi Nicholas,
Thanks for raising this issue with us. We had a similar issue with Xcode 7 and cocoapods. We patched that issue on our end and there was a patch for it on cocoa pods (which should be in an update soon, but I’m not sure when). Our patch for Xcode 7 and cocoapods seems to be causing this issue with Xcode 6 and cocoapods.

For us to fix the issue for Xcode 6 we would have to re-introduce the previous issue back into Xcode 7. This is something we can’t do. What we can do is suggest upgrading cocoapods to the latest version (and possibly the latest beta version if the problem presists). If upgrading cocoapods doesn’t fix the issue, upgrading to Xcode 7 will solve the issue.

**Comment by RonanMcH** [comment]
Hi again Nicholas,
we have investigated this on our side and have discovered that cocoapods have fixed this issue since release 1.4.1.3.  The fix will come in our next release as the build setting will need to be changed on our end.  This should allow SDK integration on Xcode 6.4 with no duplicate symbol errors.

Thanks again for bringing it to our attention.

**Comment by nicholas** [comment]
Awesome, thanks for the quick turnaround!

**Comment by tecknut** [comment]
@nicholas Is this working fine now? Just checking in before we close this of.

**Comment by nicholas** [comment]
Afraid not. I just tried with Cocoapods 0.39.0 and Zendesk 1.4.1.4 and still get the error. If there's anything I can provide you with to help, just let me know. I was able to reproduce this in a new, clean test project too.

**Comment by RonanMcH** [comment]
Hi @nicholas, 
this should be fixed as of our latest release. (1.5.0.1)

**Comment by RonanMcH** [comment]
This issue has been fixed so I am going to close it.
Thanks again for bringing it to our attention,
Ronan.
